### ISSUE TITLE
CheCluster.status.CheURL is blank when running on K8s with che-gateway

### ISSUE THREAD

**Issue by sleshchenko** [eclipse/che#20467]
### Describe the bug

CheCluster.status.CheURL is blank when running on K8s with che-gateway:
```
  status:
    cheClusterRunning: ""
    cheURL: ""
    cheVersion: ""
    dbProvisioned: true
    devfileRegistryURL: https://192.168.39.132.nip.io/devfile-registry
    devworkspaceStatus:
      gatewayHost: 192.168.39.132.nip.io
      gatewayPhase: Established
      phase: Active
      workspaceBaseDomain: 192.168.39.132.nip.io
    gitHubOAuthProvisioned: false
    keycloakProvisioned: true
    keycloakURL: https://192.168.39.132.nip.io/auth
    openShiftoAuthProvisioned: false
    pluginRegistryURL: https://192.168.39.132.nip.io/plugin-registry/v3
```

### Che version

next (development version)

### Steps to reproduce

1. Deploy Che on minikube:
```
chectl server:deploy --installer=operator --platform=minikube --che-operator-cr-patch-yaml=/home/sleshche/che-custom-che-server.yaml --workspace-engine=dev-workspace
```
where patch file is 
```
spec:
  k8s:
    singleHostExposureType: gateway
  server:
    customCheProperties:
      CHE_INFRA_KUBERNETES_ENABLE__UNSUPPORTED__K8S: "true"
```
2. Once it's deployed, check CheCluster's status.

### Expected behavior

CheURL is correctly reported

### Runtime

minikube

### Installation method

chectl/next

### Environment

Linux

**Comment by sleshchenko** [comment]
it's how Che URL is evaluated for internal needs https://github.com/eclipse-che/che-operator/blob/8b1dd1527a8e950872e4b4d35cda4758464eac02/pkg/util/util.go#L621

**Comment by sleshchenko** [comment]
Sorry, my fault. I made a typo in configuration and after I fixed it:
```yaml
status:
  cheClusterRunning: Available
  cheURL: https://192.168.39.132.nip.io
  cheVersion: next
  dbProvisioned: true
  devfileRegistryURL: https://192.168.39.132.nip.io/devfile-registry
  devworkspaceStatus:
    gatewayHost: 192.168.39.132.nip.io
    gatewayPhase: Established
    phase: Active
    workspaceBaseDomain: 192.168.39.132.nip.io
  gitHubOAuthProvisioned: false
  keycloakProvisioned: true
  keycloakURL: https://192.168.39.132.nip.io/auth
  openShiftoAuthProvisioned: false
  pluginRegistryURL: https://192.168.39.132.nip.io/plugin-registry/v3
```
