### ISSUE TITLE
why there are eamodio/vscode-gitlens and eamodio/gitlens in che-plugin-registry

### ISSUE THREAD

**Issue by zWingz** [eclipse/che#20475]
### Summary

There are [vscode-gitlens](https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/eamodio/vscode-gitlens/) and [gitlens](https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/eamodio/gitlens/) in che-theia plugins

![image](https://user-images.githubusercontent.com/13031838/133601951-01ee9e05-3da4-4e9f-b067-84de5064c6d2.png)

but the `che-theia-plugins.yaml` declare `vscode-gitlens` once
```yaml
  - repository:
      url: 'https://github.com/eamodio/vscode-gitlens'
      revision: v10.2.1
    aliases:
      - eamodio/vscode-gitlens
    extension: https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-gitlens/gitlens-10.2.1.vsix
```
