### ISSUE TITLE
[che-operator] Enhancements in the way how OAuth2 providers can be configured

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse/che#20496]
### Is your task related to a problem? Please describe

- Github, Gitlab, Bitbucket should be configured in a similar way.
- Factory OAuth flow without Keycloak.

### Describe the solution you'd like

 - Should be possible to configure Gitlab from secret. In the same way, like it's made for Github and Bitbucket.https://github.com/eclipse/che/issues/18932
 - Github and Gitlab OAuth configs should be mounted as a file to che-server in the same way like it's made for Bitbucket
 - Environemnt variables for clientid and secret. CHE_OAUTH2_GITHUB_CLIENTID__FILEPATH CHE_OAUTH2_GITHUB_CLIENTSECRET__FILEPATH
 - Change path `/home/user/eclipse-che/conf/oauth1/bitbucket/` - > `/config/oauth1/bitbucket/`  and `/config/oauth2/github/` and `/config/oauth2/gitlab/` see more   https://github.com/eclipse/che/issues/19061#issuecomment-915169002
 - Add CHE_INTEGRATION_GITLAB_SERVER__ENDPOINTS. Like https://github.com/eclipse-che/che-operator/blob/8e0966bed3c682f81bba2c2454ace33cb1e9c761/pkg/deploy/server/server_configmap.go#L314-L334

### Release Notes Text

The way to configure GitHub, Bitbucket and Gitlab as Git service providers for Che workspaces has been made consistent and simpler.

**Comment by l0rd** [comment]
👍

**Comment by tolusha** [comment]
1. 

GitHub configuration secret:
```
kind: Secret
apiVersion: v1
metadata:
  name: github-oaut-config
  namespace: <...> 
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: github
type: Opaque
data:
  id: <...> 
  secret: <...> 
```

Mount env to che-server deployment:
* `CHE_OAUTH2_GITHUB_CLIENTID__FILEPATH` with content of `id` key to location `/che-conf/oauth/github/client-id`
* `CHE_OAUTH2_GITHUB_CLIENTSECRET__FILEPATH` with content of `secret` key to location `/che-conf/oauth/github/client-secret`
