### ISSUE TITLE
Commands are not displayed in the sidecar component 

### ISSUE THREAD

**Issue by svor** [eclipse/che#20498]
### Describe the bug

The Workspace view displays commands only for dev component, but they are not displayed for sidecar plugins.
For example if a devfile contains a component like: 
```
  - id: ms-python/python/latest
    type: chePlugin
    alias: python-plugin
```
and a command:
```
  - name: Second command
    actions:
      - type: exec
        command: echo 'Command was finished'
        component: python-plugin
```
This command won't be displayed in the Workspace view.

### Che version

7.36@latest

### Steps to reproduce

1. Create a workspace by using
```yaml
apiVersion: 1.0.0
metadata:
  name: test-workspace
components:
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    alias: maven
    image: 'quay.io/eclipse/che-java11-maven:next'
  - id: ms-python/python/latest
    type: chePlugin
    alias: python-plugin
commands:
  - name: First command
    actions:
      - type: exec
        command: echo 'Command was finished'
        component: maven
  - name: Second command
    actions:
      - type: exec
        command: echo 'Command was finished'
        component: python-plugin
```
2. Take a look at the Workspace view where python sidecar is displayed.

### Expected behavior

Python sidecar's command **Second command** should be displayed in the Workspace view

### Runtime

minikube

### Screenshots

![screenshot-nimbus-capture-2021 09 21-13_07_36](https://user-images.githubusercontent.com/1271546/134152763-327348fb-699d-442b-9d28-a9bc5e506306.png)

### Installation method

chectl/latest

### Environment

Linux
