### ISSUE TITLE
An admin should be able to specify Secrets, ConfigMaps and PersistentVolumesClaims that need to be provisioned on each user's namespace

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse/che#20501]
### Is your task related to a problem? Please describe

There are multiple usecases.
 - Share some application environment variables. JAVA_OPTS, MAVEN_OPTS
 - Share password and login for some database in all workspaces
 - Etc. 

### Describe the solution you'd like

Secrets and configmaps with predefined set of labels can be propaged to the user's namespace

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: <secret-name>

  annotations:
    .....
  labels:
    .....
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-config
type: <type>
data:
  ....
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: <configmap-name>
  annotations:
    .....
  labels:
    .....
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-config
type: <type>
data:
```

Original labels and annotations should be preserved.

### Additional context

https://issues.redhat.com/browse/CRW-2120

**Comment by metlos** [comment]
As for the instructions on how to map those secrets/configmaps to the workspaces, we should make sure that the DWO labels/annos are used. E.g. https://github.com/devfile/devworkspace-operator/pull/417 and https://github.com/devfile/devworkspace-operator/pull/564

**Comment by metlos** [comment]
We need to somehow guarantee the order in which the configmaps/secrets would be applied to the workspace.

Imagine an admin would define a "global" configmap with `JAVA_OPTS` env variable for all workspaces of all users. It is conceivable that some users might want to redefine that env var to something else. They would do that by defining their own configmap in their namespace and labeling it accordingly.

We need to be able to tell DWO in what order it should apply the configmaps such that the "user settings" can override  the "global settings".

What do you think about this, @sleshchenko , @l0rd ?

**Comment by l0rd** [comment]
@metlos good point. We definitely need to label the target secrets/configmaps as `app.kubernetes.io/managed-by: che` and `app.kubernetes.io/created-by: che-server` or something like that. 

However I think we can leave the how to merge multiple overlapping secrets/cm out of the scope of this issue.

**Comment by l0rd** [comment]
@tolusha this is the issue you are currently working on right?

**Comment by tolusha** [comment]
This one https://github.com/eclipse/che/issues/21605

**Comment by ibuziuk** [comment]
@tolusha @l0rd please consider taking this issue to the next sprint for Team A

**Comment by l0rd** [comment]
che-operator should watch for Secrets/ConfigMaps/PersistentVolumeClaims, with the following labels, in the Che namespace:

```yaml
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-config
```

For example if, a ConfigMap like the following one is in the Che namespace:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: dev-env-variables
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-config
  annotations:
    (...)
data:
  (...)
```

then the following ConfigMap should be created in every user namespace:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: dev-env-variables
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-config
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/watch-secret: "true"
  annotations:
    (...)
data:
  (...)
```
