### ISSUE TITLE
[DevWorkspace] Preferences from the plugin are not applied for the workspace

### ISSUE THREAD

**Issue by svor** [eclipse/che#20559]
### Describe the bug

Some plugins can provide preferences like vscode-java: https://github.com/eclipse-che/che-plugin-registry/blob/main/che-theia-plugins.yaml#L256.
In the dasboard we can see that the preferences was recognized:

[DevWorkspace] Preferences from the plugin are not applied for the workspace

```yaml
components:
  - attributes:
      app.kubernetes.io/name: tools
      che-theia.eclipse.org/vscode-extensions:
        - 'https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.75.0-60.vsix'
        - 'https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-java-debug/vscode-java-debug-0.26.0.vsix'
        - 'https://open-vsx.org/api/vscjava/vscode-java-test/0.28.1/file/vscjava.vscode-java-test-0.28.1.vsix'
      che-theia.eclipse.org/vscode-preferences:
        java.server.launchMode: Standard
```
But **/projects/che.theia-workspace** file doesn't contain these preferences.

### Che version

7.37@latest

### Steps to reproduce

1. Create a worksapce by Java Spring Bot devfile version 2 https://github.com/che-samples/java-spring-petclinic/tree/devfilev2
2. Check /projects/che.theia-workspace file, it doesn't contain `java.server.launchMode: Standard` which should be provided by vscode-java plugin.

### Expected behavior

`java.server.launchMode: Standard` preference should be added

### Runtime

minikube

### Screenshots

![screenshot-192 168 49 2 nip io-2021 09 30-17_43_51](https://user-images.githubusercontent.com/1271546/135477405-25ec69a8-0161-4931-9a7f-4088bdc7c1d9.png)

![screenshot-192 168 49 2 nip io-2021 09 30-17_47_30](https://user-images.githubusercontent.com/1271546/135478088-eeeeca6c-9e48-4bee-b89f-7ecb7f869ebb.png)

### Installation method

chectl/next

### Environment

Linux
