### ISSUE TITLE
Support overriding Che Theia plugins preferences and sidecar through .che/che-theia-plugins.yaml

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20596]
### Is your enhancement related to a problem? Please describe

There is [an issue](https://github.com/eclipse/che/issues/20559) to apply vs code extension preferences specified in the plugin registry (for che-theia plugins).

This issue is about overriding vs code extensions preferences using the file `.che/che-theia-plugin.yaml` in the git repository.

### Describe the solution you'd like

If the file `.che/che-theia-plugin.yaml` in the git repository exists we should use it to override the spec of the plugins.

For example if the file `.che/che-theia-plugin.yaml` exist at the root of the repository:

```
- id: redhat/java8/latest
  override:
    preferences:
      java.server.launchMode: LightWeight
    sidecar:
      memoryLimit: 1280Mi 
```

the che-theia plugin should be included in the workspace and its default preferences and sidecar specification should be merged with the one in the file.
