### ISSUE TITLE
Che-theia is not showing the preview urls that are defined in the devfile.

### ISSUE THREAD

**Issue by sunix** [eclipse/che#20621]
### Describe the bug

Che-theia is not showing the preview urls that are defined in the devfile.
The command
```
  - name: watch documentation
    previewUrl:
      port: 8080
      path: /
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/jkube/kubernetes-maven-plugin/doc'
        type: exec
        command: mvn clean -Pwatch package -DoutputHtmlDirectory='/var/www/html'
        component: maven
```
is supposed to suggest the user to open the URL when he runs the task.

### Che version

7.37@latest

### Steps to reproduce

1. Start a workspace with the following devfile
  ```yaml

    apiVersion: 1.0.0
    metadata:
      generateName: jkube-
    projects:
      - name: jkube
        source:
          startPoint: master
          location: 'https://github.com/eclipse/jkube'
          type: git
    components:
      - type: chePlugin
        id: redhat/java/latest
        preferences:
          java.server.launchMode: Standard
    
      - id: eamodio/gitlens/latest
        type: chePlugin
        registryUrl: 'https://che-plugin-registry-main.surge.sh/v3'
    
      - id: github/vscode-pull-request-github/latest
        type: chePlugin
    
      - id: donjayamanne/githistory/latest
        type: chePlugin
        registryUrl: 'https://che-plugin-registry-main.surge.sh/v3'
    
      - id: asciidoctor/asciidoctor-vscode/latest
        type: chePlugin
        registryUrl: 'https://che-plugin-registry-main.surge.sh/v3'
    
      - mountSources: true
        args: ['sleep', 'infinity']
        memoryLimit: 64M
        type: dockerimage
        alias: git
        image: quay.io/sunix/git-devtools
    
      - type: dockerimage
        alias: maven
        image: 'quay.io/eclipse/che-java11-maven@sha256:5c8c8ab286f7cdde19f2e990f69e265b9dc8ac6d314e68de46daf6cb0441c366'
        env:
          - name: MAVEN_CONFIG
            value: ''
          - name: MAVEN_OPTS
            value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user'
          - name: JAVA_OPTS
            value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
          - name: JAVA_TOOL_OPTIONS
            value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        memoryLimit: 2Gi
        mountSources: true
        volumes:
          - name: m2
            containerPath: /home/user/.m2
          - name: www
            containerPath: /var/www/html
        endpoints:
          - attributes:
              public: 'false'
            name: debug
            port: 8000
    
      - mountSources: true
        endpoints:
          - name: httpd
            attributes:
              public: 'true'
            port: 8080
        memoryLimit: 1Gi
        type: dockerimage
        image: 'quay.io/centos7/httpd-24-centos7:latest'
        alias: jkube-doc-httpd
        volumes:
          - name: www
            containerPath: /var/www/html
    
    commands:
      - name: build all
        actions:
          - type: exec
            component: maven
            command: mvn clean install
            workdir: '${CHE_PROJECTS_ROOT}/jkube'
    
      - name: build documentation
        previewUrl:
          port: 8080
          path: /
        actions:
          - type: exec
            component: maven
            command: mvn clean -Phtml package -DoutputHtmlDirectory='/var/www/html'
            workdir: '${CHE_PROJECTS_ROOT}/jkube/kubernetes-maven-plugin/doc'
    
      - name: watch documentation
        previewUrl:
          port: 8080
          path: /
        actions:
          - type: exec
            component: maven
            command: mvn clean -Pdoc-watch package -DoutputHtmlDirectory='/var/www/html'
            workdir: '${CHE_PROJECTS_ROOT}/jkube/kubernetes-maven-plugin/doc'
    
  ```
2. Run the command/task `build documentation`

### Expected behavior

When running the task, che-theia is supposed to suggest the user to open in Preview.

### Runtime

Kubernetes (vanilla), OpenShift

### Installation method

chectl/latest

### Environment

GCE, Dev Sandbox (workspaces.openshift.com)
