### ISSUE TITLE
Adding git lfs support

### ISSUE THREAD

**Issue by ffalkenberg** [eclipse/che#20642]
### Summary

Hi,

using the devfile below I am setting up my WS. 
The repo gets cloned but the git-lfs stored files only contain references (theia-editor only contains git, not git lfs)
How could I install git lfs into the theia-editor and would that fix it? (It seems to be a javascript image)
Or would I have to install it into a different image?

Thanks in advance.

### Relevant information

```
apiVersion: 1.0.0
metadata:
  name: example
projects:
  - name: example
    source:
      location: 'git@github<>.net:example.git'
      type: github
components:
    reference: https://<example-plugin-registry>/7.31.0/v3/plugins/ms-python/python/latest/meta.yaml
    type: chePlugin
  - alias: theia-editor
    type: cheEditor
    reference: https://<example-plugin-registry>/7.31.0/v3/plugins/eclipse/che-theia/latest/meta.yaml
```

### Release Notes Text

Che workspaces are now supporting Git Large File Storage extension https://git-lfs.github.com/
