### ISSUE TITLE
Factory flow from devfile link should pass whole factory flow with editor/plugins resolving

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20680]
### Describe the bug

Let's try to use this following devfile.yaml

with content

```
schemaVersion: 2.1.0
metadata:
  name: my-dummy-project
projects:
  - name: invalid-project
    git:
      remotes:
        origin: "https://github.com/does/not/exist"
```

I expect to not be able to start my Workspace or to see that it was unable to clone projects

### Che version

next (development version)

### Steps to reproduce

Click on a factory workflow by using the following devfile

https://gist.githubusercontent.com/benoitf/e4fa7d0b602e9a4972f27d96bb7334f3/raw/c236cd7a40a91c70f636c2a858041000e174b0f7/devfile-invalid-project-location.yaml 

The IDE is displayed but I have no project

### Expected behavior

Failed to get my workspace running, error message, etc.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

other (please specify in additional context)

### Additional context

It's only by going to the project-clone container logs that I can see
![image](https://user-images.githubusercontent.com/436777/138313779-17b9d760-6a3f-4426-8b6c-c1e2c03b81ac.png)
