### ISSUE TITLE
When DevWorkspace is enabled zip projects download fail because the devfile regitry certificate is untrusted

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20709]
### Is your enhancement related to a problem? Please describe

I am using a devfile that has a zip project:

```
projects:
  - name: spring-petclinic
    zip:
      location: https://192.168.64.10.nip.io/devfile-registry/resources/java-web-spring-java-web-spring-4953f87917b449a404a7f1f4e2457836b9eafbbc.zip
```

But when I start the workspace the project doesn't appear in Theia. 

![image](https://user-images.githubusercontent.com/606959/139426797-42cc7ad1-75ff-4daa-ac2d-dd834d006b08.png)

I can see a file `/projects/project-clone-errors.log` that contains a certificate error:

```log
2021/10/29 10:02:08 Read DevWorkspace at /devworkspace-metadata/flattened.devworkspace.yaml
2021/10/29 10:02:08 Processing project spring-petclinic
2021/10/29 10:02:08 Downloading project archive from https://192.168.64.10.nip.io/devfile-registry/resources/java-web-spring-java-web-spring-4953f87917b449a404a7f1f4e2457836b9eafbbc.zip
2021/10/29 10:02:08 Encountered error while setting up project spring-petclinic: failed to download archive: Get "https://192.168.64.10.nip.io/devfile-registry/resources/java-web-spring-java-web-spring-4953f87917b449a404a7f1f4e2457836b9eafbbc.zip": x509: certificate signed by unknown authority
```

In the workpace namespace there is a secret with the `tls.crt` and `tls.key` for `192.168.64.10.nip.io` that is named `workspace763675abe4674548-endpoints`. But this secret is not mounted in the workspace (it hasn't the annotations to be automounted by the devworkspce controller):

```json
{
  "creationTimestamp": "2021-10-29T10:02:00Z",
  "name": "workspace763675abe4674548-endpoints",
  "namespace": "admin-che",
  "ownerReferences": [
    {
      "apiVersion": "controller.devfile.io/v1alpha1",
      "blockOwnerDeletion": true,
      "controller": true,
      "kind": "DevWorkspaceRouting",
      "name": "routing-workspace763675abe4674548",
      "uid": "3c845aa3-7193-4266-ae74-ce86172cd42d"
    }
  ],
  "resourceVersion": "14318",
  "uid": "6108ac05-b712-44d5-868d-67269469dc27"
}
```

### Describe the solution you'd like

The secret should contain the right annotations and labels to be mounted in containers and used by curl and theia.

### Additional context

I have tried to edit the secret to have it automounted

```yaml
  annotations:
    controller.devfile.io/mount-as: file
    controller.devfile.io/mount-path: /public-certs
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
```

As a result the secret get mounted and:
- curl still fails to download the zip file (I have the same error as above)
- if I refresh Theia downloads the zip and load the project successfully

![image](https://user-images.githubusercontent.com/606959/139431634-cc72c97b-201e-473d-a678-83d7a52c3537.png)
