### ISSUE TITLE
handle all fields of repository che-editor.yaml file

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20715]
### Is your task related to a problem? Please describe

For now, we can have a .che/che-editor.yaml file but it's not following the expected syntax

We should have override capabilities and allow to specify `id`, `registryUrl` etc

This is defined by issue https://github.com/eclipse/che/issues/18668
##### che-editor.yaml

```yaml
# Contains the spec of just ONE editor. 
# Here I am providing 3 examples separted with ---
---
# EXAMPLE 1 - registry reference
id: eclipse/che-theia/nigthly         # mandatory
registryUrl: https://my-registry.com  # optional
override:                             # optional
  containers:
    - name: theia-ide
      memoryLimit: 1280Mi
---
# EXAMPLE 2 - web reference
reference: https://gist.github.com/.../che-editor.yaml # mandatory
override:                                              # optional
  containers:
      - name: theia-ide
        memoryLimit: 1280Mi 
---
# EXAMPLE 3 - inline
inline:        # <--- that's current syntax of https://github.com/eclipse/che-plugin-registry/blob/master/che-editors.yaml
               #      but we should use devfile v2 instead 
  endpoints:
    - name: "theia"
      public: true
      targetPort: 3100
      attributes:
        protocol: http
        type: ide
        secure: true
        cookiesAuthEnabled: true
        discoverable: false
    (...)
  containers:
    - name: theia-ide
      image: "quay.io/eclipse/che-theia:next"
      env:
        - name: THEIA_PLUGINS
          value: local-dir:///plugins
      volumeMounts:
        - name: plugins
          path: "/plugins"
        - name: theia-local
          path: "/home/theia/.theia"
      mountSources: true
      ports:
        - exposedPort: 3100
      memoryLimit: "512M"
      cpuLimit: 1000m
      cpuRequest: 100m
  initContainers:
    - name: remote-runtime-injector
      image: "quay.io/eclipse/che-theia-endpoint-runtime-binary:next"
      volumeMounts:
        - name: remote-endpoint
          path: "/remote-endpoint"
          ephemeral: true
      env:
        - name: PLUGIN_REMOTE_ENDPOINT_EXECUTABLE
          value: /remote-endpoint/plugin-remote-endpoint
        - name: REMOTE_ENDPOINT_VOLUME_NAME
          value: remote-endpoint
```

### Describe the solution you'd like

Override capabilities, `id` or `reference` support
