### ISSUE TITLE
Simplify Eclipse Che configuration format (CheCluster API v2)

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#20758]
### Is your task related to a problem? Please describe

After switching to DevWorkspace engine we might need to drop some fields.
Some fields are deprecated already, other are required to be renamed.

### Describe the solution you'd like

Collect all possible changes in CheCluster CR

### Additional context

This is how the new configuration sections looks like

```
> devEnvironments
    > defaultPlugins
    > defaultNamespace
    > storage
    > nodeSelector
    > tolerations
    > trustedCerts
        > gitTrustedCertsConfigMapName
> components
    > devWorkspace
    > dashboard
    > cheServer
        > clusterRoles
        > deployment
        > loglevel
        > debug
        > proxy
        > extraProperties
    > database
    > pluginRegistry
    > devfileRegistry
    > imagePuller
    > metrics
> networking
    > labels
    > annotations
    > domain
    > hostname
    > tlsSecretName
    > auth
> containerRegistry
```

## Release Notes Text

`CheCluster` custom resource definition has been updated to reflect that changes introduced with the switch to the DevWorkspaces. The result is a shorter and simpler configuration file to maintain for Eclipse Che administrators.

**Comment by tolusha** [comment]
Rename:
- `server.devfileRegistryUrl` -> `devfileRegistryURL`
- `server.pluginRegistryUrl` -> `pluginRegistryURL`

**Comment by mmorhun** [comment]
@tolusha great work!

> move server.CheHostTLSSecret into server.CheServerRoute

I'd move into `CheDashboardEndpointTLSSecret` as `Route` is Openshift specific.

> move k8s.TlsSecretName into server.CheServerIngress

The name is not clear. From a first shight it might be percepted as ingress name to use for Che server. What about `server.EndpointTLSSecret`? (than we might have it for both Kubernetes and Openshift)

> move k8s.IngressDomain into server.CheServerIngress

Not clear. I'd like to keep `domain` word, and even old name, but moved to server section maybe.

> server.ExternalDevfileRegistry -> devfileregistry.enable

if I set `devfileregistry.enable` to `false` will it disable it at all :smile:  ?
The same for plugin registry. I think word `external` is mandatory in the name.

> Single-host strategy will be the only one supported. We can remove fields related to multi-host strategy.

If we delete multi host, so does it makes sense to keep both `CheTLSSecret` and `CheHostTLSSecret`?

**Comment by AndrienkoAleksandr** [comment]
> auth.UpdateAdminPassword

Do we have the same feature for Dex?

**Comment by mmorhun** [comment]
Also, it's time to get rid of `self-signed-certificate` secret, isn't it?

**Comment by AndrienkoAleksandr** [comment]
> server.ExternalDevfileRegistry -> devfileregistry.enable
> server.ExternalPluginRegistry -> pluginregistry.enable

Looks not clear for me

**Comment by tolusha** [comment]
@AndrienkoAleksandr 

```
// Instructs the Operator on whether to deploy a dedicated devfile registry server.
// By default, a dedicated devfile registry server is started. When `externalDevfileRegistry` is `true`,
// no such dedicated server will be started by the Operator and configure at least one
// devfile registry with `externalDevfileRegistries` field.
// +optional
ExternalDevfileRegistry bool `json:"externalDevfileRegistry"`
```

Basically this field as well as `spec.server.ExternalPluginRegistry` indicates if dedicated devfile/plugin registry is started. 
It is logical to turn this field into `spec.pluginregistry.enable`  with converting algorithm `spec.pluginregistry.enable = !spec.server.ExternalPluginRegistry`

**Comment by tolusha** [comment]
@mmorhun 

> server.ExternalDevfileRegistry -> devfileregistry.enable

see explanation above.

> self-signed-certificate

Sorry, out of scope.

**Comment by tolusha** [comment]
```
- make`server.CheHost` as a part of `server.CheServerRoute` and `server.CheServerIngress`
- make `server.CheHostTLSSecret` as part of `server.CheServerRoute`
- make `k8s.TlsSecretName` as part of `server.CheServerIngress`
- make `k8s.IngressDomain` as part of `server.CheServerIngress`
```
Hostname, secret and domain basically is part of of route(ingress). So, it is logically to move them into that structure.


> auth.UpdateAdminPassword

Only works for Keycloak

> server.ExternalDevfileRegistry -> devfileregistry.enable
> server.ExternalPluginRegistry -> pluginregistry.enable

`ExternalDevfileRegistry` controls whether or not deploy dedicated registry despite the fact that it contains `external` in its name. Beside this there is `ExternalDevfileRegistries` fields which is responsible for configuring external devfile registries.
So, my suggestion is the following:
1. Remove `server.ExternalDevfileRegistry` field
2. Add `devfileregistry.enable` to control deploying dedicated registry.
3. Keep `devfileregsitry.ExternalDevfileRegistries` to configure external devfile registries regardless dedicated one.

**Comment by mmorhun** [comment]
> `ExternalDevfileRegistry` controls whether or not deploy dedicated registry despite the fact that it contains `external` in its name. Beside this there is `ExternalDevfileRegistries` fields which is responsible for configuring external devfile registries.
So, my suggestion is the following:

To which registries will the value of, for example, `DevfileRegistryCpuLimit` be applied? It is not clear.

> 2. Add devfileregistry.enable to control deploying dedicated registry.

Maybe name it `devfileregistry.InternalRegistryEnabled` ?

**Comment by AndrienkoAleksandr** [comment]
> server.useInternalClusterSVCNames

I think this feature can be still usefull for plugin and devfile registry links and maybe for dashboard deployment.

**Comment by tolusha** [comment]
It is deprecated in favor of `DisableInternalClusterSVCNames`

**Comment by tolusha** [comment]
Related issue https://github.com/eclipse/che/issues/20759

**Comment by tolusha** [comment]
IN_PROGRESS:

```yaml
spec:
	server:
		deployment:
		route:
		ingress:
		logLevel:
		debug:
		clusterRoles:
		workspaceClusterRole:
		workspaceNamespaceDefault:
		gitSelfSignedCert:
		airGapContainerRegistryHostname:
		airGapContainerRegistryOrganization:
		proxySecret:
	storage:
		pvc:
		pvcStrategy:
		preCreateSubPaths:
	dashboard:
		deployment:
	pluginRegistry:
		deployment:
	devfileRegistry:
		deployment:
	auth:
		oAuthClientName:
		oAuthSecret:
		gatewayAuthenticationSidecarImage:
		gatewayAuthorizationSidecarImage:
	database:
		deployment:
		pvc:
		hostName:
		port:

deployment:
	container:
		image:
		imagePullPolicy:
		resources:
			limits:
				cpu:
				memory:
			requests:
				cpu:
				memory:
	securityContext:
		runAsUser:
		fsGroup:

route:
	labels:
	annotations:
	domain:
	host:
	tlsSecretName:

ingress:
	class:
	labels:
	annotations:
	domain:
	host:
	tlsSecretName:

pvc:
	claimSize:
	storageClass:
```

**Comment by l0rd** [comment]
A few comments:

1. Wouldn't it better to move server.route and server.ingress to auth.gateway?

2. Shouldn't we rename `server.workspaceClusterRole` as `server.workspaceServiceAccountClusterRole`?

3. Shouldn't we rename `server.workspaceNamespaceDefault` as `server.workspaceNamespaceName`? Calling it `Default` means that it can be customized but that's not possible anymore.

4. Do we need `enable` for the registries?  If I specify:

```
spec:
  pluginRegistry:
    externalPluginRegistries: <externalPluginRegistries>
```
I would expect to be disabled by default. I should not need to set the extra field `enabled=false`.

5. In general we should make sure that for booleans the default is `false`. So if the default is `enabled=true` we should replace that with `disabled=false`. 

```yaml
spec:
  pluginRegistry:
    disabled: <boolean>
    externalPluginRegistries: <externalPluginRegistries>
```

6. Do we support multiple external plugin registries?
