### ISSUE TITLE
alias not working when type: kubernetes

### ISSUE THREAD

**Issue by amoldeshpande05** [eclipse/che#20767]
### Alias not working for type kubernetes.

My devfile has the following component

```
- mountSources: true
  type: kubernetes
  reference: '--url--/test.yaml'
  alias: appContainer
```
  
  Where test.yaml has following content
     
```
apiVersion: v1
kind: Pod
metadata:
 name: podman
spec:
 containers:
   - image: amoldeshpande/custom-podman-root
     name: container
     args:
       - sleep
       - "infinity"
     securityContext:
       privileged: true
```
  

I am getting as
podman/container
![image](https://user-images.githubusercontent.com/33426696/141492830-e372affc-30b2-40fd-b77e-eedd3028fd1f.png)

I am expecting alias: appContainer
appContainer.

### Che version

7.37

### Steps to reproduce

Use this devfile

```
apiVersion: 1.0.0
metadata:
  name:podmanWorkspace
attributes:
  persistVolumes: 'false'
components:
  - mountSources: true
    type: kubernetes
    reference: 'https://raw.githubusercontent.com/amoldeshpande05/loan-approval-system/main/test4.yaml'
    alias: myApp
```
Start the container.

### Expected behavior

I should get the name of the developer container as myApp

### Runtime

Docker Desktop

### Screenshots

![image](https://user-images.githubusercontent.com/33426696/141493717-d7d3fd32-ed69-45da-bf59-b093379cc99e.png)
I am getting the name which is present in the yaml file

### Installation method

chectl/latest

### Environment

macOS
