### ISSUE TITLE
Used CPU of a plugin is higher than limit on Developer Sandbox

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20768]
### Describe the bug

On developer sandbox the memory used by a plugin goes above the limit:

![image](https://user-images.githubusercontent.com/606959/141751777-08c8219b-44c0-42e9-8c15-44c2e2a3d429.png)

That should not happen. A container cannot use more CPU than its limit. Is the limit not applied? Is the used CPU mis-calculated?

### Che version

7.36

### Steps to reproduce

Use a devfile that includes the openshift connector and specify a low CPU limit for it. Start the workspace on developer sandbox. 

### Expected behavior

The used CPU should never go above the limit.

### Runtime

OpenShift

### Installation method

other (please specify in additional context)

### Environment

Dev Sandbox (workspaces.openshift.com)

**Comment by l0rd** [comment]
I have reproduced that for the Java extension too https://github.com/eclipse/che/issues/20769

**Comment by vinokurig** [comment]
Could not reach the limit on dog-fooding with che-code editor:
![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2022 08 18-16_41_44](https://user-images.githubusercontent.com/7668752/185409832-60bdca93-4180-4262-85d4-b5f8eb02539c.png)

**Comment by svor** [comment]
@vinokurig try to reproduce it on developer sandbox as it is described in the description

**Comment by l0rd** [comment]
Note that this issue was reproduced in Theia, not VS Code.

**Comment by vinokurig** [comment]
Could not reproduce it on devspaces 3.0 with che-theia neither:
![screenshot-nimbusweb me-2022 08 19-10_59_39](https://user-images.githubusercontent.com/7668752/185572699-41f08769-26a4-4cfe-85ce-1ef9fb10bfd4.png)

**Comment by ibuziuk** [comment]
> Could not overdraw the limit on dog-fooding with che-code editor:

On dogfooding we do apply neither limits nor quotas, it should be verified on the Developer Sandbox staging enviroment

**Comment by vinokurig** [comment]
I've tried it on the Developer Sandbox with this devfile:
```YAML
apiVersion: 1.0.0
metadata:
  name: bash-psfc
projects:
  - name: bash
    source:
      location: 'https://github.com/che-samples/bash'
      type: git
      branch: main
components:
  - mountSources: true
    command:
      - tail
    args:
      - '-f'
      - /dev/null
    memoryLimit: 64Mi
    type: dockerimage
    alias: dev
    image: 'registry.access.redhat.com/ubi8-minimal:8.3'
  - id: mads-hartmann/bash-ide-vscode/latest
    type: chePlugin
    registryUrl: 'https://eclipse-che.github.io/che-plugin-registry/7.42.0/v3/'
  - id: rogalmic/bash-debug/latest
    type: chePlugin
    registryUrl: 'https://eclipse-che.github.io/che-plugin-registry/7.42.0/v3/'
  - id: timonwong/shellcheck/latest
    preferences:
      shellcheck.executablePath: /bin/shellcheck
    type: chePlugin
    registryUrl: 'https://eclipse-che.github.io/che-plugin-registry/7.42.0/v3/'
  - id: redhat/vscode-openshift-connector/latest
    memoryLimit: 500Mi
    type: chePlugin
```
The workspcae failed to start because of the `Pod crash loop back-off` error see the video:
![ezgif-3-a6208c33c8](https://user-images.githubusercontent.com/7668752/185911378-d4ac66b1-62d8-442a-9ce8-1c18347b13a0.gif)
