### ISSUE TITLE
Since 7.38.x, can't connect on workspace. 502 Bad Gateway 

### ISSUE THREAD

**Issue by disaster37** [eclipse/che#20781]
### Describe the bug

When I launch new or existing workspace, I get error `502 Bad Gateway`. The workspace pod is successfully running and green badge is displayed on the workspace name.

It seems to have problem with URL and keykloak. It failed on request (return code 502):
```
https://che-test.rancher-hpd.hm.dm.ad/auth/realms/che/protocol/openid-connect/auth?client_id=che-public&redirect_uri=https%3A%2F%2Fche-test.rancher-hpd.hm.dm.ad%2F_app%2Floader.html%3FredirectUrl%3Dhttps%3A%2F%2Fche-test.rancher-hpd.hm.dm.ad%2Fserver03gf2m93-jwtproxy%2Fserver-4402%2F%26workspaceId%3Dworkspacegdtysto4k1xg016y&state=acbab698-5108-42a5-a7c1-86b8a7e05bb5&response_mode=fragment&response_type=code&scope=openid&nonce=1f30bc23-31f1-427c-ba51-e2f18a0822b1
```

I can successfully access on `https://che-test.rancher-hpd.hm.dm.ad/auth/realms/che/protocol/openid-connect/auth`, so it seems there are some problem on redirect...

### Che version

7.38@latest

### Steps to reproduce

1.Deploy Eclipse che from chectl with the following options:
```
chectl server:deploy --installer=operator --domain=che-test.rancher-hpd.hm.dm.ad --multiuser --chenamespace=che-test --cheboottimeout=600000 --platform=k8s --che-operator-cr-patch-yaml=che-operator-cr-patch.yaml --postgres-pvc-storage-class-name=nfs-client --workspace-pvc-storage-class-name=nfs-client --skip-kubernetes-health-check
```

The contend of che-operator-cr-patch.yaml:
```yaml
spec:
  k8s:
    singleHostExposureType: 'gateway'
    tlsSecretName: 'che-tls-certificates'
  metrics:
    enable: true
  server:
    serverExposureStrategy: 'single-host'
    proxyPort: "8080"
    proxyURL: 'http://squid.squid.svc.cluster.local'
    nonProxyHosts: 'localhost|10.0.0.0/8|.hm.dm.ad|.rancher-hpd.hm.dm.ad|.svc.cluster.local'
    useInternalClusterSVCNames: true
    workspaceNamespaceDefault: 'che-<username>'
    customCheProperties:
      CHE_LIMITS_USER_WORKSPACES_COUNT: "-1"
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "3"
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "43200000"
      CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATIONS: 'che.eclipse.org/username=<username>,field.cattle.io/projectId=c-57d7n:p-8j45h'
      CHE_INFRA_KUBERNETES_NAMESPACE_LABELS: 'app.kubernetes.io/part-of=che.eclipse.org,app.kubernetes.io/component=workspaces-namespace,field.cattle.io/projectId=p-8j45h'
      CHE_WORKSPACE_DEFAULT__CPU__LIMIT__CORES: '1'
      CHE_WORKSPACE_DEFAULT__CPU__REQUEST__CORES: '500m'
      CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__LIMIT__CORES: '300m'
      CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__REQUEST__CORES: '50m'
  storage:
    pvcClaimSize: 4Gi
    pvcStrategy: per-workspace
```

2. Run bash workspace
3. You get message `502 Bad Gateway` instead to access on theia UI.

### Expected behavior

Access on Theia UI

### Runtime

Kubernetes (vanilla), other (please specify in additional context)

### Installation method

chectl/latest

### Environment

Linux

### Eclipse Che Logs

```shell
There are no error logs from workspace, che server or keykloack pods.
```

### Additional context

Kubernetes is deployed with Rancher 2.6.2
