### ISSUE TITLE
Gitlab/OAuth2 cloning private projects fails with autopopulated tokens - Access denied

### ISSUE THREAD

**Issue by nils-mosbach** [eclipse/che#20790]
### Describe the bug

We're currently have issues setting up a proper OAuth flow for cloning private GitLab projects. My intention was to allow cloning private projects for all of our developers using GitLab OAuth without the need of defining SSH-Tokens or Kubernetes secrets on user side. So basically add a button to all GitLab Project-Pages (like "Open in Che") which will does the trick (Login, clone, etc.) without user interaction.

GitLab-OAuth Login to Che and reading the devfile from a private GitLab-Repository (using a factory link) works great, but project sources can't be cloned in theia.

It throws "Permission denied" while cloning sources. 

Git clone in the terminal (theia or dev-container) outputs the following.

```
Cloning into 'playground'...
fatal: unable to get credential storage lock: Permission denied
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://git.company.dev/MosbachN/playground.git/'
```

Are we missing something?

### Che version

7.39@latest

### Steps to reproduce

We've setup GitLab/Keycloak/Che as described in the documentation. 

* Custom Che properties in Operator-Config: 
  * CHE_INTEGRATION_GITLAB_SERVER__ENDPOINTS: "https://git.company.dev/" 
  * CHE_INTEGRATION_GITLAB_OAUTH__ENDPOINT: "https://git.company.dev/" 
* Keycloak realm and client configured as described in the documentation
  * Created a realm "git-dev"
  * Added a identity provider "GitLab"
    - Authorization URL: https://git.company.dev/oauth/authorize
    - Token URL: https://git.company.dev/oauth/token
    - Default scopes: api read_user read_api write_repository openid profile email

### Expected behavior

Login to Che using GitLab Credentials (OAuth) works great. 
What also works great is reading devfile.yamls from private repositories using (https://che-dev.company.dev/dashboard/f?url=http://git.company.dev/...). 
So that's all good and theia pops up using all plugins and extensions defined by the devfile.

The Problem we have is that project sources cannot be cloned. See error above.

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Linux

### Additional context

Git config seems to get injected properly by Che.

```
$ cat /etc/gitconfig 
[user]
        name = mosbachn
        email = nm@company.com

[credential]
        helper = store --file /home/theia/.git-credentials/credentials
```

Even credentials get mounted by a secred `git-credentials-secret-6xk49` to `/home/theia/.git-credentials/credentials`.

```
$ cat /home/theia/.git-credentials/credentials
https://MosbachN:8f************e7@git.company.dev
```

**Comment by l0rd** [comment]
cc @skabashnyuk @xbaran4

**Comment by skabashnyuk** [comment]
@nils-mosbach Thank you for this report. Could you please share the way you've installed che and the devfile you've used?

**Comment by mshaposhnik** [comment]
For me it looks like git is unable to create `.git-credentials.lock` in the home folder

**Comment by nils-mosbach** [comment]
**Permission denied - Get credential storage lock**

I double checked that by copying the files (credential-store and git-config) as deployed by che to a fresh ubuntu container locally with git installed. Cloning still fails (Authentication failed), lock file error is gone. So, I'm not sure if the error message that belongs to the lock file will cause the authentication issue.

**Installation of Che**

I installed Che using chectl. Deployment: Operator.

``` yaml
spec:
  devWorkspace:
    enable: false
  server:
    tlsSupport: true
    customCheProperties:
      CHE_SYSTEM_SUPER__PRIVILEGED__MODE: "true"
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "-1"
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "9000000" 
      CHE_SYSTEM_ADMIN__NAME: mosbachn
      CHE_INTEGRATION_GITLAB_SERVER__ENDPOINTS: "https://git.company.dev/"
      CHE_INTEGRATION_GITLAB_OAUTH__ENDPOINT: "https://git.company.dev/"
    cheImagePullPolicy: Always
    devfileRegistryPullPolicy: Always
    pluginRegistryPullPolicy: Always
    
  database:
    externalDb: false
    postgresImagePullPolicy: Always

  storage:
    pvcStrategy: per-workspace
    pvcClaimSize: '5Gi'

  auth:
      externalIdentityProvider: true
      identityProviderURL: 'https://auth.company.dev/auth'
      identityProviderRealm: 'git-dev'
      identityProviderClientId: 'che'
      openShiftoAuth: false

  k8s:
      ingressDomain: 'company.dev'
      ingressStrategy: 'multi-host'
      tlsSecretName: 'tls-company-dev'
```

We're running a custom plugin and devfile registry, but the issue also exists, if I use the java/gradle image provided by the che-registry [devfile.yaml](https://github.com/eclipse-che/che-devfile-registry/blob/main/devfiles/java-gradle/devfile.yaml). I tried cloning the private repository in the gradle container provided by the devfile using `git clone https://git.company.dev/MosbachN/playground.git/`. Still the same error.

It seems that the credential-store injected by che isn't able to authenticate.

@skabashnyuk I'm happy to dig a little deeper if you need additional information like logs, etc.

Just in case: Tested against GitLab Community Edition. I'm not sure if that's a limitation since reading the devfile from the project works.
