### ISSUE TITLE
Che-server isn't reconfigured after adding OAuth Config secret

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse/che#20841]
### Describe the bug

After adding OAuth secret to the eclipse-che namespace che-operator isn't reconfigure che-server with OAuth settings.

### Che version

7.39@latest

### Steps to reproduce

1. deploy che `chectl server:deploy --platform=openshift --installer=operator --workspace-engine=dev-workspace` and add secret 
```
kubectl apply -f - <<EOF
kind: Secret
apiVersion: v1
metadata:
  name: github-oauth-config
  namespace: eclipse-che
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: github
type: Opaque
data:
  id: ?? 
  secret: ??
EOF
```
2. che-server didn't reconfigured.

### Expected behavior

At step 2 che-operator should mount secret as a file and provide environment variables that point to this file.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

### Eclipse Che Logs

```shell
n/a
```

### Additional context

https://github.com/eclipse-che/che-operator/blob/main/pkg/deploy/server/server_deployment.go#L492-L500
CHE_OAUTH_GITHUB_CLIENTID__FILEPATH: /che-conf/oauth/github/id
CHE_OAUTH_GITHUB_CLIENTSECRET__FILEPATH: /che-conf/oauth/github/secret
