### ISSUE TITLE
[theia-devworkspace handler] store projects section when generating templates

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20877]
### Is your enhancement related to a problem? Please describe

For now the projects section is empty
It should generate the projects section in the devfile.yaml

### Describe the solution you'd like

Option to include or not the `projects` section
When using the CLI it should include the projects section while when running inside dashboard it shouldn't

```
projects:
  - name: scala-sbt
    source:
      location: 'https://github.com/che-samples/scala-sbt'
      type: git
      branch: devfile2
```

if we add flag like npx devworkspace-handler ...... --project.${name}={{DEVFILE_REGISTRY_URL}}/${name}.zip

it should be like
```
projects:
  - name: scala-sbt
    source:
      location: '{{DEVFILE_REGISTRY_URL}}/resources/v2/scala-sbt.zip'
      type: zip
```
