### ISSUE TITLE
Support for namespace-level configuration of pod tolerations and node selector

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse/che#20884]
### Is your task related to a problem? Please describe

As a Eclipse Che admin, I want to be able to set up the configuration of pod tolerations and node selector. Devworkspace operator expected them as k8s namespace annotations:
```yaml
    metadata:
      annotations:
        controller.devfile.io/node-selector: |
          {
            "test-node-selector": "test"
          }
        controller.devfile.io/pod-tolerations: |
          [
            {
              "key": "key1",
              "operator": "Equal",
              "value": "value1",
              "effect": "NoSchedule"
            }
          ]
```

see more https://github.com/devfile/devworkspace-operator/pull/696

### Describe the solution you'd like

Che-operator should grab existing configuration from  che-server's  env var configuration `CHE_WORKSPACE_POD_NODE__SELECTOR` and `CHE_WORKSPACE_POD_TOLERATIONS__JSON` and put them in a format expected by devworkspace operator.

### Describe alternatives you've considered

n/a

### Release Notes Text

It is now possible to specify pod tolerations and node selector for workspaces of a Che instance setting a CustomCheProperty in CheCluster CR. It's not possible to specify that for just one workspace or for one user: it's a global config.

**Comment by ibuziuk** [comment]
@skabashnyuk we probably need to add the issue to https://github.com/eclipse/che/issues/20830

**Comment by skabashnyuk** [comment]
The source of configuration now is che-server configuration: `CHE_WORKSPACE_POD_NODE__SELECTOR` and `CHE_WORKSPACE_POD_TOLERATIONS__JSON`.  @l0rd  do you think we should keep this source or it should be configured somehow differently?

**Comment by l0rd** [comment]
If I look at the [new CheCluster draft](https://github.com/eclipse/che/issues/20758#issuecomment-984664253) I would say:

```yaml
spec:
  server:
    workspacePodNodeSelector:
    workspacePodTolerationsJson:
```

@amisevsk @tolusha what's your take on that?

**Comment by tolusha** [comment]
What about moving workspace related configuration to a dedicated section?

```yaml
spec:
   server:
     workspace:
       podNodeSelector:
       podTolerationsJson:
```   

or:

```yaml
spec:
   workspace:
     podNodeSelector:
     podTolerationsJson:
```
