### ISSUE TITLE
Use next channel of DevWorkspaceOperator when using next channel of Che

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#20899]
### Is your enhancement related to a problem? Please describe

When using chectl, I can apply for chectl `next` channel.

I expect to have DevWorkspaceOperator next channel and not a tagged version

### Describe the solution you'd like

For example Che-operator is publishing nightlies of che-operator OLM bundle.
DevWorkspace operator could publish nightlies as well.

Also chectl could use devworkspace operator next tag when we're using next channel.

### Describe alternatives you've considered

Any other solution that allows to use next development channel of DevWorkspace Operator when using chectl/next

**Comment by tolusha** [comment]
Some questions: 
1. Do we have next channel for DevWorkspace operator?
2. Should che-operator depends on next version of DWO rather than stable version ?

**Comment by benoitf** [comment]
cc @amisevsk 

I think DevWorkspace Operator currently doesn't have olm 'next' channel or a nightly job like https://github.com/eclipse-che/che-operator/blob/main/.github/workflows/build-catalog-and-bundle-images.yaml

**Comment by amisevsk** [comment]
> I think DevWorkspace Operator currently doesn't have olm 'next' channel or a nightly job like https://github.com/eclipse-che/che-operator/blob/main/.github/workflows/build-catalog-and-bundle-images.yaml

It does: https://github.com/devfile/devworkspace-operator/actions/workflows/next-build.yml

This builds `quay.io/devfile/devworkspace-operator-[index|bundle]:next` and can be accessed by applying the [catalog source](https://github.com/devfile/devworkspace-operator/blob/main/catalog-source.yaml) in the devworkspace-operator repo.

Index repo: https://quay.io/repository/devfile/devworkspace-operator-index?tab=tags
Bundle repo: https://quay.io/repository/devfile/devworkspace-operator-bundle?tab=tags

Once the catalog source is installed, DWO can be installed via UI or by creating a subscription directly. One note is that I intend to update the catalog source name soon for DWO, so the current value (`custom-devworkspace-operator-catalog`) may change.

**Comment by amisevsk** [comment]
To subscribe directly, you can use the subscription
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: devworkspace-operator
spec:
  channel: fast
  installPlanApproval: Automatic
  name: devworkspace-operator
  source: custom-devworkspace-operator-catalog
  sourceNamespace: openshift-marketplace
```
where `source` and `sourceNamespace` match the catalogSource that was created.
