### ISSUE TITLE
Websocket connection to the dashboard backend is closed

### ISSUE THREAD

**Issue by akurinnoy** [eclipse/che#20898]
### Describe the bug

The Dashboard frontend can't establish the websocket connection to the Dashboard backend.

### Che version

next (development version)

### Steps to reproduce

1. Deploy Eclipse Che with devworkspaces engine enabled
  ```sh
  chectl server:deploy -p minikube --workspace-engine=dev-workspace --che-operator-cr-patch-yaml=patch.yaml
  ```

  <details>
  <summary> patch.yaml </summary>

  ```yaml
spec:
  auth:
    updateAdminPassword: false
  devWorkspace:
    enabled: true
  server:
    cheImagePullPolicy: Always
    dashboardImagePullPolicy: Always
    customCheProperties:
      CHE_INFRA_KUBERNETES_ENABLE__UNSUPPORTED__K8S: "true"
  k8s:
    singleHostExposureType: 'gateway'
  ```
  </details>
	
2. Go to the Dashboard 
3. And open JS console

### Expected behavior

The websocket connection between dashboard frontend and backend is established.

### Runtime

minikube

### Screenshots

<img width="1792" alt="Screenshot 2021-12-07 at 18 07 29" src="https://user-images.githubusercontent.com/16220722/145064701-e6ca4aa0-6528-4b9e-a852-dc074f2168ae.png">

### Installation method

chectl/next

### Environment

macOS
