### ISSUE TITLE
Create custom workspace tab is empty using dev workspace mode

### ISSUE THREAD

**Issue by vzhukovs** [eclipse/che#20923]
### Describe the bug

From the internal discussions it came up that _Create Workspace_ from the custom devfile is disabled on the Dashboard UI, but links that point to _Create Custom Workspace_ open empty window tab.

![Снимок экрана 2021-12-13 в 15 12 50](https://user-images.githubusercontent.com/1968177/145819358-9745e1a8-d58d-4aec-bdde-3ccf6579fa52.png)
![Снимок экрана 2021-12-13 в 15 13 01](https://user-images.githubusercontent.com/1968177/145819365-cc9a510a-db81-4509-a6f5-63c4843b738b.png)

### Che version

next (development version)

### Steps to reproduce

- Deploy Che with the following command using CR patch:
```
server:deploy --installer=operator --workspace-engine=dev-workspace --platform=minikube --che-operator-cr-patch-yaml=/Users/vzhukovs/Workspace/che-custom-che-server.yaml
```

- che-custom-che-server.yaml
```
spec:
  devWorkspace:
    enable: true
  server:
    dashboardImage: 'quay.io/eclipse/che-dashboard:pr-424'
    dashboardImagePullPolicy: Always
    customCheProperties:
      CHE_DEBUG_SERVER: "true"
      CHE_INFRA_KUBERNETES_ENABLE__UNSUPPORTED__K8S: "true"
```

### Expected behavior

There shouldn't be any links to _Create Custom Workspace_ or there should be a dialog with devfile editor. Choose the right one.

### Runtime

minikube

### Installation method

chectl/next

### Environment

macOS
