### ISSUE TITLE
Provision git name or email with data from personal access tokens

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse/che#20938]
### Is your task related to a problem? Please describe

Provide some defaults from git name and email configuration.

### Describe the solution you'd like

If no defaults for git name and email configuration is set and if user's namespace contains personal access token of some SCM providers (Github, Bitbucket, Gitlab) we can use PAT to repopulate git configuration. 

### Additional context

https://github.com/devfile/devworkspace-operator/pull/708

**Comment by skabashnyuk** [comment]
Closing. I think it is better to set up this data explicitly.

**Comment by l0rd** [comment]
@skabashnyuk I am no sure why it should be better to set this data explicitly so I am re-opening this issue as I think that this feature adds a lot of value to Che.

**Comment by l0rd** [comment]
A few notes:

1. the configmap should have the following annotation and labels:

```yaml
...
metadata:
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: /etc/
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/watch-configmap: "true"
...
```

2. The configmap should have a gitconfig entry in the data section:

```yaml
...
data:
  gitconfig: ...
```

3. ⚠️ If a ConfigMap with those annotations/labels/data.gitconfig exist we should **NOT** create a new ConfigMap (otherwise the user won't be able to start workspaces).
