### ISSUE TITLE
Disable openshift authentication in openshift connector plugin 

### ISSUE THREAD

**Issue by svor** [eclipse/che#20944]
### Is your task related to a problem? Please describe

Since [openshift-authentication plugin wasn't adapted to avoid requesting che-server API](https://github.com/eclipse/che/issues/20857) when devWorkspace engine is enabled, we have to provide another che plugin **vscode-openshift-connector**  without **che-openshift-authentication-plugin**:  https://github.com/eclipse-che/che-plugin-registry/blob/main/che-theia-plugins.yaml#L361-L379

### Describe the solution you'd like

Create a new che plugins which will include:
```
  - repository:
      url: 'https://github.com/redhat-developer/vscode-openshift-tools'
    sidecar:
      directory: openshift-tooling
      name: vscode-openshift-connector
      memoryLimit: 1500Mi
      memoryRequest: 20Mi
      cpuLimit: 800m
      cpuRequest: 30m
      volumeMounts:
        - name: kube
          path: /home/theia/.kube
    extension: https://open-vsx.org/api/redhat/vscode-openshift-connector/0.2.9/file/redhat.vscode-openshift-connector-0.2.9.vsix
    metaYaml:
      extraDependencies:
        - ms-kubernetes-tools/vscode-kubernetes-tools
        - redhat/vscode-yaml
```
