### ISSUE TITLE
unable to access repository present inside an organization's gitlab account (visibility private)

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#20962]
### Summary

The project repository i'm working on is maintained under `gitlab.company.com`. The `gitlab.company.com` is accessible only within the corporate network and sso is required to login into the `gitlab.company.com`. i can add ssh keys/generate accessTokens but this will be valid only inside corporate network.

The visibility of the project repository is private

i'm maintaining the`devfile.yaml` inside the same  project repository.

i have eclipseche installed in minikube. The installation is successful and i'm able to clone a public / private github repository in this eclipseche instance.

the problem i face is with `private` `gitlab.company.com` repository that is accessible only within corporate network.

i get below error message when i try to open the workspace.

Please let me know how to resolve this issue

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/10482177/147085444-ca55af37-eb94-4105-a175-a9f208694319.png">

**Comment by skabashnyuk** [comment]
@Divine1 thank you for the question. At this stage, it's important to decide the flow you want to follow.
 - Is it OAuth2 integration - then you can use factories with automated authorization flow.
 - SSH flow - then you have to create a workspace, set up ssh keys. After that, you'll be able to do clone/push.


Wich way do you want to follow?

**Comment by Divine1** [comment]
@skabashnyuk  i would like to follow ssh flow.

**Comment by Divine1** [comment]
image: quay.io/eclipse/che-server:7.40.2
devfile v1

HTTP proxy is not required.


Che7 or devWrksapce - what does it mean?

**Comment by skabashnyuk** [comment]
I found only this guide on how to mount a file https://www.eclipse.org/che/docs/che-7/end-user-guide/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/. If you are able to create secrets in your k8s namespace  I think you can follow it to mount ssh files.

@vinokurig @svor do you remember if we have documentation about how to manage ssh keys from the Theia?

**Comment by Divine1** [comment]
@skabashnyuk  i can create secrets in my k8s namespace.

i have a doubt in the value present for `settings.xml` in the docs.


As per the docs, Should i encode(base64) all the data present inside `settings.xml` and paste it as a value for `settings.xml` ?

```
data:
  settings.xml: <base64 encoded data content here>

```

![image](https://user-images.githubusercontent.com/10482177/147103022-100ff523-1341-4b25-b2fb-17d15ba60c11.png)

**Comment by vinokurig** [comment]
> @vinokurig @svor do you remember if we have documentation about how to manage ssh keys from the Theia?

This might be useful : https://www.eclipse.org/che/docs/che-7/end-user-guide/version-control/#_generating_an_ssh_key_using_the_che_command_palette

**Comment by skabashnyuk** [comment]
>incase of ssh public key, should i encode(base64) the content of publickey file and put it as below ?

I think you need both. git client inside the Theia container has to have access to the private par. The public part would be checked on the opposite side (on gitlab)

However @vinokurig 's variant I like more.

**Comment by Divine1** [comment]
> > incase of ssh public key, should i encode(base64) the content of publickey file and put it as below ?
> 
> I think you need both. git client inside the Theia container has to have access to the private par. The public part would be checked on the opposite side (on gitlab)
> 
> However @vinokurig 's variant I like more.

the `devfile.yaml` will also be present inside the repository of `gitlab.company.com` with visibility private. Will this approach work?

**Comment by skabashnyuk** [comment]
>the devfile.yaml will also be present inside the repository of gitlab.company.com with visibility private. Will this approach mentioned in this or this work for my scenario?

I think you are referring to factory flow. It's not the `silky smooth` player with ssh way scenario.
I recommend considering OAuth integration flow in this case.

**Comment by Divine1** [comment]
@skabashnyuk could you share the doc link for `OAuth integration` flow ?

**Comment by Divine1** [comment]
@skabashnyuk  do you think the step mentioned here will be relevant for my scenario?

https://www.eclipse.org/che/docs/che-7/end-user-guide/authenticating-on-scm-server-with-a-personal-access-token/#configuring_gitlab_authentication_che

**Comment by nils-mosbach** [comment]
@Divine1 Since we had the same issue, I can share some information what works in our case. :) We're quite happy with the OAuth Integration flow. Since i wrote down everything for another ticket, here's a quick summary what I did to get it working.

Have a look here: https://www.eclipse.org/che/docs/che-7/administration-guide/configuring-authorization/#configuring-gitlab-oauth2_che

My intention was to allow cloning private projects for all of our developers using GitLab OAuth **without** the need of defining SSH-Tokens or Kubernetes secrets on user side. So basically add a button to all GitLab Project-Pages (like "Open in Che") which will does the trick (Login, clone, etc.) without user interaction. Git-urls in devfiles must be http-only of course.

Thanks to the work of @skabashnyuk it now works like a charm in v7.40. Thanks a lot! (#20790)

We've setup GitLab/Keycloak/Che as described in the documentation. 

* Custom Che properties in Operator-Config: 
  * CHE_INTEGRATION_GITLAB_SERVER__ENDPOINTS: "https://git.company.dev/" 
  * CHE_INTEGRATION_GITLAB_OAUTH__ENDPOINT: "https://git.company.dev/" 
* Keycloak realm and client configured as described in the documentation
  * Created a realm "git-dev"
  * Added a identity provider "GitLab"
    - Authorization URL: https://git.company.dev/oauth/authorize
    - Token URL: https://git.company.dev/oauth/token
    - Default scopes: api read_user read_api write_repository openid profile email
    - Create a new Application in GitLab with appropriate rights and copy clientid and secret.

Our Keycloak Identity Provider config:
![image](https://user-images.githubusercontent.com/15126675/147114078-a4929171-0665-4e18-a945-5c7c0d47d68e.png)

I installed Che using chectl. Deployment: Operator.

operator-config.yaml:

``` yaml
spec:
  server:
    tlsSupport: true
    customCheProperties:
      CHE_SYSTEM_SUPER__PRIVILEGED__MODE: "true"
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "-1"
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "9000000" 
      CHE_SYSTEM_ADMIN__NAME: mosbachn
      CHE_INTEGRATION_GITLAB_SERVER__ENDPOINTS: "https://git.company.dev/"
      CHE_INTEGRATION_GITLAB_OAUTH__ENDPOINT: "https://git.company.dev/"
    cheImagePullPolicy: Always
    devfileRegistryPullPolicy: Always
    pluginRegistryPullPolicy: Always
    
  database:
    externalDb: false
    postgresImagePullPolicy: Always

  storage:
    pvcStrategy: per-workspace
    pvcClaimSize: '5Gi'

  auth:
      externalIdentityProvider: true
      identityProviderURL: 'https://auth.company.dev/auth'
      identityProviderRealm: 'git-dev'
      identityProviderClientId: 'che'
      openShiftoAuth: false

  k8s:
      ingressDomain: 'company.dev'
      ingressStrategy: 'multi-host'
      tlsSecretName: 'tls-company-dev'
```

That's it. Nice and smooth without dealing with SSH tokens! :)
