### ISSUE TITLE
[Plugin API] showWarningMessage Plugin API method doesn't work

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#20974]
### Describe the bug

`showWarningMessage` Plugin API method doesn't work

### Che version

next (development version)

### Steps to reproduce

1. Start a workspace from this devfile:
```
apiVersion: 1.0.0
metadata:
  name: wksp-mftz
components:
  - type: chePlugin
    reference: 'https://pastebin.com/raw/h3xb8aMq'
```
2. Run `Hello world` command from the command pallet which executes `vscode.window.showWarningMessage('Hello World!');`
See: nothing happens

### Expected behavior

A warning notification must appear.

### Runtime

minikube

### Installation method

chectl/latest

### Environment

macOS
