### ISSUE TITLE
Support plug-in id references for spec.server.workspacesDefaultPlugins

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#20990]
### Is your enhancement related to a problem? Please describe

Currently, the Che CR's `spec.server.workspacesDefaultPlugins[*].plugins` field only supports uri plug-in references.

Example:
```
spec:
  server:
    workspacesDefaultPlugins:
      - editor: 'eclipse/che-theia/latest'
        plugins: ['https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/containers/buildah/latest/devfile.yaml']
```

### Describe the solution you'd like

It would be great if plug-id references can also be supported, as mentioned in https://github.com/eclipse/che/issues/20090#issuecomment-976519944 and https://github.com/eclipse/che/issues/20090#issuecomment-976580723.

### Describe alternatives you've considered

Instead of using the plug-in ID from the plug-in registry, it can be possible to specify an equivalent plug-in uri.
