### ISSUE TITLE
how to specify custom namespace label for the namespaces created by `eclipse-che`?

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21028]
### Summary

i have installed `eclipse-che` in minikube using `chectl`.

![image](https://user-images.githubusercontent.com/10482177/149668105-b06dd3ea-9771-4cfa-b7ea-bc5dcc8140d1.png)

i havenot overridden any default configuration. so, the namespace `eclipse-che` , `admin-che` is created in the minikube cluster by default

Inorder to override default namespace `eclipse-che` i have used this argument `--chenamespace=customeclipse-che`

i'm not able to find the approach to override the default namespace `admin-che` in the chectl documentation. Please let me know how to override this default namespace `admin-che` to a different namespace like `customadmin-che`

![image](https://user-images.githubusercontent.com/10482177/149668389-f298599a-3424-49cb-b340-b043ee789a14.png)

### Relevant information

https://github.com/che-incubator/chectl/#chectl-serverdeploy

https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-minikube/

**Comment by l0rd** [comment]
@Divine1 admin-che is a user namespace, meaning that all Che resources for user "admin" will be created in that namespace. To name these namespaces we use the pattern `<username>-che`. That can be customized using `CheCluster` property `server.workspaceNamespaceDefault`. More information [here](https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-namespace-strategies/).

**Comment by Divine1** [comment]
@l0rd  thank you for the response. 

by default, namespaces are created for each `user` in this format  `<username>-che` 

How will setting this property work? `server.workspaceNamespaceDefault` 


Assume that i have 3 users , ueagle,upig,ucow..
if i set `server.workspaceNamespaceDefault=frogns` then in which format will the names for the new namespaces be created?

**Comment by tolusha** [comment]
`server.workspaceNamespaceDefault=frogns`
That's won't work. Operator won't propagate this configuration and prints errors.
String must contain either `<username>` or `<userid>`.

**Comment by Divine1** [comment]
@tolusha  thank you.

1. is it possible to have a `user` namespace `pre-created` that can be used to handle the workspaces created by the user?

2. how to point multiple userids to its specific precreated namespaces? 
Please consider below example, i have to
- point userid `ueagle` to `ueagle-che` namespace
- point userid `upig ` to `upig-che` namespace
- point userid `ucow ` to `ucow-che` namespace

In this case, should i use `che.eclipse.org/username: <username1>,<username2>,<username3>` ?

![image](https://user-images.githubusercontent.com/10482177/149765567-ed7a78d7-bdf4-4f7a-b0be-f5176333be9f.png)

**Comment by tolusha** [comment]
@skabashnyuk 
Could you have a look pls?

**Comment by skabashnyuk** [comment]
You'll have to have 
 - namespace `ueagle-che` annotated with `che.eclipse.org/username: ueagle`
 - namespace  `upig-che` annotated with `che.eclipse.org/username: upig `
 - namespace `ucow-che` annotated with `che.eclipse.org/username: ucow `

or use the configuration by default. It is doing exactly the same.

**Comment by Divine1** [comment]
@skabashnyuk 



```
metadata:
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-namespace
  annotations:
    che.eclipse.org/username: ueagle
    che.eclipse.org/username: upig-che
    che.eclipse.org/username: ucow-che
```

**Comment by skabashnyuk** [comment]
you have to specify `usernames`.
I doubt that is possible to set up more than one `che.eclipse.org/username` annotation on a single namespace. Moreover, the whole design is expected to have a single namespace for one user.

**Comment by Divine1** [comment]
@skabashnyuk 

so, in my scenario, should i have three yaml files like below to make use of `precreated` namespaces?

```
file1.yaml

metadata:
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: ueagle-che
  annotations:
    che.eclipse.org/username: ueagle

```

```
file2.yaml

metadata:
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: upig-che
  annotations:
    che.eclipse.org/username: upig

```

```
file3.yaml

metadata:
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: ucow-che
  annotations:
    che.eclipse.org/username: ucow

```
