### ISSUE TITLE
Devworkspace - generateName in devfile throws error

### ISSUE THREAD

**Issue by nils-mosbach** [eclipse/che#21067]
### Describe the bug

`generateName` property does not work. It seems that something broke during the work of v1 to v2 conversion.

```
Failed to create a workspace. Failed to create a new workspace from the devfile, reason: Failed to create a new workspace. Unable to create devworkspace: DevWorkspace.workspace.devfile.io "devfile-test" is invalid: [<nil>: Invalid value: "": "spec.template.components" must validate one and only one schema (oneOf). Found none valid, spec.template.components.container: Required value, spec.template.components.name: Invalid value: "": spec.template.components.name in body should match '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$']
```

![image](https://user-images.githubusercontent.com/15126675/150971417-c5f8299a-8f76-454b-92fe-8ad6df2f9eb8.png)

Devfile i used:

```
schemaVersion: 2.1.0
metadata:
  generateName: devfile-test
components:
  - name: nodejsdev
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-b452131
      endpoints:
        - exposure: public
          name: nodejs
          protocol: http
          targetPort: 3000
      memoryLimit: 1G
      mountSources: true
```

### Che version

7.42@latest

### Steps to reproduce

Run a devfile that should generate the workspaces' name.

### Expected behavior

Generate a name as described by https://devfile.io/docs/devfile/2.1.0/user-guide/adding-a-name-to-a-devfile.html.

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Linux

### Additional context

Running next-version of devworkspace-operator.
