### ISSUE TITLE
attempting to sync unrecognized object v1.Secret - error while cloning a repository containing `devfile.yaml` from `gitlab.org.com`

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21083]
### Summary

![image](https://user-images.githubusercontent.com/10482177/151430015-f4031473-8a4c-40fd-9572-08580f76af02.png)

i have installed above `eclipse-che` version in minikube cluster and installation is successful

i want to integrate `gitlab-oauth` with `eclipse-che`

l have applied below `gitlab-secret` in `eclipse-che` namespace.

```
kind: Secret
apiVersion: v1
metadata:
  name: gitlab-oauth-config
  namespace: 'eclipse-che' 
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: gitlab
    che.eclipse.org/scm-server-endpoint: 'https://gitlab.org.com'
type: Opaque
data:
  id: 'ZWFkNDhjNzE1ODQ1ZDU3NDI1M2ExOGRmZTVlOTlkMjhhYjViMmY2OGQ4NDY5ODZmMTQid'
  secret: 'OGM0MDMwNWQ2OWI1ZGQ1ZGQ3ODk0YWQ0ZDc1MjZmMzNjMmZiMTUwMzhiMDJkMGZsecret'
```
then i opened the `eclipse-che` website `https://192.168.49.2.nip.io`, then logged-in using `che@eclipse.org` / `admin`

After login, i provided my repository containing valid `devfile.yaml` `https://gitlab.org.com/demoproject.git` -> clicked create button -> this redirected the website from `eclipse-che` to `gitlab.org.com` , the `sso authentication` was successful. But the dev file cloning process failed due to this error `attempting to sync unrecognized object v1.Secret`

i have attached the screenshot showing error below. Please let me know how to fix this error.

![image](https://user-images.githubusercontent.com/10482177/151431570-ed56545c-8f6c-4fc5-b6c4-283e5e2c08ab.png)

![image](https://user-images.githubusercontent.com/10482177/151400846-78a86a79-bcf6-4b44-9418-948db31a9e0d.png)
