### ISSUE TITLE
Postgres fails to start with permission denied when deploying Che on OVH

### ISSUE THREAD

**Issue by snoopfab** [eclipse/che#21095]
### Describe the bug

I can't install che using checl on a vanilla OVH Kubernetes Cluster

The postgresql pod does not starts because of some permission issues while creating the postgresql data directory :

`mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied`

It seems related to issue #13344 but the initial poster (@mikekuzak ) did not explained how to solve the problem.

How can i fix this ?

Thanks for your time !

### Che version

7.42@latest

### Steps to reproduce

Command line used for Installation  :

`chectl server:deploy --platform k8s --skip-oidc-provider-check --domain=sub.domainxxx.com`

### Expected behavior

Postgresql pod running sucessfully

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Windows

### Eclipse Che Logs

```shell
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied`
```

### Additional context

Kubernetes version  v1.22.2

```
chectl --version
chectl/7.42.0 win32-x64 node-v12.22.9
```
Windows 10

**Comment by tolusha** [comment]
It was about giving permissions on storage for uid 26

**Comment by snoopfab** [comment]
Yes i understood this was a permission problem but I have no clue on how to do with the operator (without changing the dockerfile of the postgresql image)
I Still don't understand why gaving these rights  is not done by the che operator by default ?  

Could you give me a more detailed procedure to fix the permission error or is this a bug in the operator ?


Thanks

**Comment by tolusha** [comment]
To be honest I haven't faced such an issue, so I can only assume:

1. If you have access to underlying storage, than change permissions
2. change default pvc class

**Comment by snoopfab** [comment]
Already tried to change the default pvc class with same error.

What do you mean by "If you have access to underlying storage, than change permissions" ? 

I start to think that the problem is with the k8s OVH implementation. I'll try with their support team 

Thanks for the replies.

**Comment by EnergieZ** [comment]
Hi @snoopfab ,

I'm facing the same problem with K8S by OVH.
Did you found a solution ? 

Tried sevral things without succes :(

**Comment by l0rd** [comment]
For reference here is @EnergieZ [similar issue](https://github.com/eclipse/che/issues/21239). We do not have access to OVH Kubernetes clusters so it's hard for us to investigate. One workaround I would suggest would be to deploy Postgres as a standalone application and configure Che to use the external Postgres (related documentation: [CheCluster database configuration fields](https://www.eclipse.org/che/docs/che-7/installation-guide/checluster-custom-resource-fields-reference/#checluster-custom-resource-database-settings_che) and [Using chectl to configure the CheCluster Custom Resource during installation](https://www.eclipse.org/che/docs/che-7/installation-guide/using-chectl-to-configure-the-checluster-custom-resource-during-installation/) )

**Comment by EnergieZ** [comment]
Solution has been found !

delete the sorage class objet : csi-cinder-high-speed

recreate it with this : 
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cinder-high-speed
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"},"name":"csi-cinder-high-speed"},"parameters":{"availability":"nova","fsType":"ext4","type":"high-speed"},"provisioner":"cinder.csi.openstack.org","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: cinder.csi.openstack.org
parameters:
  availability: nova
  fsType: ext4
  type: high-speed
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

Note the extra `fsType: ext4`, wich solve the problem !
