### ISSUE TITLE
There is no CHE_DASHBOARD_URL or PLUGIN_REGISTRY_URL in the dev container

### ISSUE THREAD

**Issue by benoitf** [eclipse/che#21102]
### Describe the bug

it seems that dashboard is only adding the URLs links to the editor devWorkspaceTemplate but not to all containers

### Che version

next (development version)

### Steps to reproduce

Open a terminal in a container that is not the editor container
check that *_URL env variables are not defined

### Expected behavior

_URL env variables should be set in all containers

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

other (please specify in additional context)

**Comment by amisevsk** [comment]
Since these URLs are static per-Che installation, another option (rather than injecting them into containers and thus the DevWorkspace) is to use automount functionality in the DevWorkspace Operator. For example, a configmap like
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: che-devworkspace-env
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/watch-configmap: 'true'
  annotations:
    controller.devfile.io/mount-as: env
data:
  CHE_DASHBOARD_URL: "https://my-che-gateway/dashboard/"
  PLUGIN_REGISTRY_URL: "https://my-che-gateway/plugins/v3/"
```
could be added to the namespace provisioning process and it should result in those env vars being mounted to all containers automatically with no further modifications to DevWorkspaces being required.
