### ISSUE TITLE
User's certficates are not propagated to Dev Workspaces

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#21113]
### Is your task related to a problem? Please describe

It is possible to import certificates into Eclipse Che following the doc [1].
`ca-certs-merged` config map is created  by operator and propgated to `che-server`.
The name of this configmap is stored in a `che` configmap as `CHE_TRUSTED__CA__BUNDLES__CONFIGMAP: ca-certs-merged`. 

This configmap is propagted into all workspaces if che-server engine is used.
If devworkspace engined is used, then user's certificates are not propagted to any workspaces which cause some issues while requesting external resources.

[1] https://www.eclipse.org/che/docs/che-7/installation-guide/importing-untrusted-tls-certificates/

### Describe the solution you'd like

`ca-certs-merged` must be propagated to every workspace if devworkspace engine is used

### Additional context

https://issues.redhat.com/browse/CRW-2677

**Comment by l0rd** [comment]
@tolusha shouldn't this `ConfigMap` be propagated by Che operator when it provisions a user namespace rather than from the DevWorkspace operator at workspace startup time?
cc @ibuziuk @amisevsk

**Comment by tolusha** [comment]
I think yes, it is che-operator responsibility.

**Comment by amisevsk** [comment]
Assuming it doesn't conflict with any other standard mounted volumes, the easiest way to implement this would be to apply appropriate automount labels/annotations to mount the configmap to all workspaces in a namespace. Documentation on how to do that is [here](https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.md#automatically-mounting-volumes-configmaps-and-secrets), though in short, it would look something like
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-certs-merged
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/watch-configmap: "true"
  annotations:
    controller.devfile.io/mount-path: "/expected/path/in/containers"
    controller.devfile.io/mount-as: "subpath" # Optional -- see doc
```
