### ISSUE TITLE
Initial DevWorkspace created by dashboard has no components defined

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21138]
### Describe the bug

When creating a DevWorkspace on the cluster, the dashboard appears to first create an empty DevWorkspace object with projects but no components, e.g.
```
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  annotations:
    che.eclipse.org/che-editor: eclipse/che-theia/next
    che.eclipse.org/devfile-source: |
      factory:
        params: >-
          url=https://github.com/che-samples/django-realworld-example-app/tree/devfile2&devWorkspace=https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/devfile-registry/devfiles/python-django/devworkspace-che-theia-next.yaml
    che.eclipse.org/last-updated-timestamp: "2022-02-07T20:16:44.996Z"
  name: python-django
  namespace: amisevsk-che
spec:
  routingClass: che
  started: true
  template:
    projects:
      - name: django-realworld-example-app
        zip:
          location: http://devfile-registry.dogfooding.svc:8080/resources/v2/django-realworld-example-app.zip
```

It then quickly updates the DevWorkspace with components/the editor plugin. However, if this does not occur fast enough, the DevWorkspace may hit https://github.com/devfile/devworkspace-operator/issues/772 and fail to start.

### Che version

next (development version)

### Steps to reproduce

Not consistently reproducible

### Expected behavior

Ideally, empty DevWorkspaces should not be created as it's not entirely clear what that means (e.g. a deployment cannot be created at all for such a DevWorkspace).

Note however that this issue will be worked-around when https://github.com/devfile/devworkspace-operator/issues/772 is resolved.

### Runtime

OpenShift

### Screenshots

N/A

### Installation method

OperatorHub

### Environment

Linux

### Additional context

Causes https://github.com/eclipse/che/issues/21114
