### ISSUE TITLE
unable to find the following volume mounts in devfile volume components - facing issue with values in devfile 

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21135]
### Summary

Receiving below error when cloning `devfile` from this [repository](https://github.com/Divine1/demonodejs.git)
```
1 error occurred: * unable to find the following volume mounts in devfile volume components: volume mount remote-endpoint belonging to the container component nodejs volume mount plugins belonging to the container component nodejs
```
![image](https://user-images.githubusercontent.com/10482177/152820565-87249e3f-1ba8-4df4-96b1-4e96beabfe6d.png)

below is the `devfile` code

```
schemaVersion: 2.1.0
metadata:
  name: nodejs-web-app
projects:
  - name: demonodejs
    git:
      checkoutFrom:
        revision: master
      remotes:
        origin: https://github.com/Divine1/demonodejs.git
components:
  - container:
      image: 'quay.io/devfile/universal-developer-image:ubi8-b452131'
      memoryLimit: 1G
      mountSources: true
      sourceMapping: /projects
      volumeMounts:
        - name: remote-endpoint
          path: /remote-endpoint
        - name: plugins
          path: /plugins
    name: nodejs
commands:
  - exec:
      commandLine: npm install
      component: nodejs
      group:
        isDefault: true
        kind: build
      label: Download dependencies
      workingDir: '${PROJECTS_ROOT}/demonodejs'
    id: dependencies
```

i have made some changes that are incorrect in the `devfile`. But i'm not sure how to figure out the solution for this `schemaVersion: 2.1.0`

i viewed https://devfile.io/ website to gain understanding on how to create the devfile for `schemaVersion: 2.1.0`, but it didnt help me to fix this issue. i. don't have a clearer understanding on `schemaVersion: 2.1.0`, if there are any websiteLinks to read more on this topic , please share

below is the `chectl` version i'm using currently

![image](https://user-images.githubusercontent.com/10482177/152822213-9571a52e-cf42-4600-818c-02e167d3bde2.png)

please help me on this

**Comment by Divine1** [comment]
@svor 

i have updated the `devfile.yaml` as per your suggestion. but still i receive below error.

this is the git repository (https://github.com/Divine1/demonodejs.git) containing my `devfile.yaml` which i used for this testing 


![image](https://user-images.githubusercontent.com/10482177/152907444-7089307a-cc97-4193-97c2-8f4878fc4e4c.png)



below is the content of the `devfile.yaml` which throws the above error

```
schemaVersion: 2.1.0
metadata:
  name: nodejs-web-app
projects:
  - name: demonodejs
    git:
      checkoutFrom:
        revision: master
      remotes:
        origin: https://github.com/Divine1/demonodejs.git
components:
  - container:
      image: 'quay.io/devfile/universal-developer-image:ubi8-b452131'
      memoryLimit: 1G
      mountSources: true
      sourceMapping: /projects
      volumeMounts:
        - name: remote-endpoint
          path: /remote-endpoint
        - name: plugins
          path: /plugins
    name: nodejs
  - name: remote-endpoint
    volume:
      size: 256Mi
  - name: plugins
    volume:
      size: 256Mi
commands:
  - exec:
      commandLine: npm install
      component: nodejs
      group:
        isDefault: true
        kind: build
      label: Download dependencies
      workingDir: '${PROJECTS_ROOT}/demonodejs'
    id: dependencies
```

please let meknow how to fix this.
