### ISSUE TITLE
Devfile v2 command label not displayed in Che-theia workspace view

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#21159]
### Describe the bug

When a command is defined in a v2 devfile like so:
```
commands:
  - exec:
      commandLine: './mvnw compile quarkus:dev'
      component: tools
      group:
        isDefault: true
        kind: run
      label: Start Development mode (Hot reload + debug)
      workingDir: '${PROJECTS_ROOT}/quarkus-quickstarts/getting-started'
    id: startdev
```

The label: `Start Development mode (Hot reload + debug)` is not displayed in the Workspace view. The command's id (`startdev`) is being displayed instead:
![image](https://user-images.githubusercontent.com/83611742/153615337-ed50e803-6b3e-4b37-a5b7-fad0eebe097b.png)

### Che version

next (development version)

### Steps to reproduce

1. Open a v2 devfile Che-sample. In the example above, I opened the Quarkus REST API sample:
![image](https://user-images.githubusercontent.com/83611742/153615613-a057366c-abda-43ca-ad27-d6c3e17e2861.png)

The v2 devfile contains commands with labels: https://github.com/che-samples/quarkus-quickstarts/blob/743501d86e6e7b262029fbddbc141a77d541be5e/devfile.yaml#L49-L75

2. When the workspace starts, view the commands in the Workspace view.

### Expected behavior

If the command label is available, it would be great if the command label would be displayed instead of the id.

### Runtime

OpenShift

### Installation method

other (please specify in additional context)

### Environment

Linux
