### ISSUE TITLE
Add `controller.devfile.io/devworkspace_id_override` annotation with workspace ID during the devfile v1 -> v2 convertion

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21153]
### Is your task related to a problem? Please describe

In order to preserve the workspace sources mounted in the `claim-che-workspace` PVC, during the v1 -> v2 convertion 
resulting DevWorkspace should contain the `controller.devfile.io/devworkspace_id_override` with the original workspace id value

### Describe the solution you'd like

Let's assume there is a devfile v1 workspace with `workspacejta4u808l6myzway` id
When a user convert it to devfile v2 via UD the resulting devworkspace should contain the following annotation:

```
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: devfile-v1-workspace-name
  annotations:
    controller.devfile.io/devworkspace_id_override: workspacejta4u808l6myzway
```

Adding the id annotation allows mounting the same workspace folder that was used in the original devfile v1 after the migration to DevWorkspace

### Describe alternatives you've considered

N/A

### Additional context

DevWorkspace Controller implementation of the id handling - https://github.com/devfile/devworkspace-operator/pull/747
Related to https://github.com/eclipse/che/issues/21038
