### ISSUE TITLE
Add `project` in DevWorkspace CRD spec and deprecate `projects` from the devfile spec

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21188]
### Is your enhancement related to a problem? Please describe

We are removing `projects` from the Devfile spec and leave only `starterProjects` ([issue](https://github.com/devfile/api/issues/679)). The reasons:
- when a Devfile lives in a git repo, close to the project source code, `projects` can (and should) be omitted
- when a Devfile lives outside a git repo, far from the project source code, `projects` and `starterProjects` are pretty similar
- when the need is to open multiple projects in the IDE, it’s better to have distinct Devfiles/dw (one per project) rather than one “uber” devfile/dw for all projects 

### Describe the solution you'd like

Current DW spec
```yaml
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: theia-next
spec:
  started: true
  template:
    projects:
      - name: web-nodejs-sample
        git:
          remotes:
            origin: "https://github.com/che-samples/web-nodejs-sample.git"
(...)
```
Future DW spec
```yaml
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: theia-next
spec:
  started: true
  project:
    name: web-nodejs-sample
    git:
      remotes:
        origin: "https://github.com/che-samples/web-nodejs-sample.git"
  template:
    (...)
```
