### ISSUE TITLE
redirectURI error while creating workspace with `devfile.yaml` hosted within gitlabOrganization account using SSO

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21199]
### Summary

i have installed `eclipse-che` in `minikube` cluster.

`chectl version`
![image](https://user-images.githubusercontent.com/10482177/155004218-f4a5955a-80cb-448d-a57b-4f9da720294d.png)

When i clone a `devfile.yaml` present inside my organization's repository, i receive `The redirect URI included is not valid` error
![image](https://user-images.githubusercontent.com/10482177/155359961-4f346e96-51dc-414b-a160-f0ea3c5928ba.png)

![image](https://user-images.githubusercontent.com/10482177/155004324-276766f4-670e-4185-a4cb-87f34d58eb03.png)

below is the url taken from the screen  which shows  `The redirect URI included is not valid`  (screenshot posted above)
```
https://gitlab.myorganization.com/oauth/authorize?client_id=ead48c715845d574253a18dfe5e99d28ab5b2f68d846986f143e6249e32a06ad&redirect_uri=https://192.168.49.2.nip.io/api/oauth/callback&response_type=code&scope=api%20write_repository%20openid&state=oauth_provider%3Dgitlab%26scope%3Dapi%2Bwrite_repository%2Bopenid%26request_method%3DPOST%26signature_method%3Drsa%26redirect_after_login%3Dhttps://192.168.49.2.nip.io/f?url%3Dhttps%253A%252F%252Fgitlab.eng.vmware.com%252Fdchelladurai%252Fdemonodejs.git
```
in this url, i can see `redirect_uri=https://192.168.49.2.nip.io/api/oauth/callback`. is this url causing the error? because this [documentation](https://www.eclipse.org/che/docs/che-7/administration-guide/configuring-authorization/#configuring-gitlab-oauth2-with-devworkspace-engine_che) says that default uri ends with `/api/oauth/callback`. i dont think this URI exists in my `eclipse-che` setup.

 
Please let me know how to fix this problem.

gitlab application
![image](https://user-images.githubusercontent.com/10482177/155004926-5f4ec4bd-27b7-4982-9fd2-79e6c282b115.png)

i have added below config map to replace default `dex` login interface with my organization gitlab sso, this intergation + redirection from gitlabSSO back to `eclipse-che` works perfectly.... 
But, when cloning the repository hosted within my `gitlab.myorganization.com` repository, redirection error is thrown

 `kubectl edit configmap dex -n dex`
```
apiVersion: v1
data:
  config.yaml: |
    issuer: https://dex.192.168.49.2.nip.io
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556

    oauth2:
      skipApprovalScreen: true

    staticClients:
    - id: eclipse-che
      redirectURIs:
      - 'https://192.168.49.2.nip.io/oauth/callback'
      name: 'Eclipse Che'
      secret: Qi3zbNqJvtwdMmhWdnsm9YkPnEnDkWyTiaSFgNtlupc=
    connectors:
    - type: gitlab
      id: gitlab
      name: GitLab
      config:
        baseURL: https://gitlab.myorganization.com/
        clientID: ead48c715845d574253a18dfe5e99d28ab5b2sgds6249e32a06ad
        clientSecret: 8c40305d69b5dd5dd7894ad4d7526f33c2fb1sfdsfdfeba6ae028cdc658d0
        redirectURI: 'https://dex.192.168.49.2.nip.io/callback'
        useLoginAsID: false
kind: ConfigMap
metadata:
  creationTimestamp: "2022-02-11T08:45:21Z"
  labels:
    app: dex
  name: dex
  namespace: dex
  resourceVersion: "18867"
  uid: 9e3a897a-b416-49c5-912b-7629e6c9855c
```

i have added my below secret key `kubectl apply gitlab-secret.yaml - eclipse-che`, inorder to allow cloning of gitlabOrganization repository.
```
kind: Secret
apiVersion: v1
metadata:
  name: gitlab-oauth-config
  namespace: 'eclipse-che' 
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: gitlab
    che.eclipse.org/scm-server-endpoint: 'https://gitlab.myorganization.com'
type: Opaque
data:
  id: 'ZWFkNDhjNdfdfI1M2ExOGRmZTVlOTlkMjhhYjViMmY2OGQ4NDY5ODZmMTQzZTYyNDllMzJhMDZhZA=='
  secret: 'OGM0MDsdfZGQ3ODk0YWQ0ZDc1MjZmMzNjMmZiMTUwMzhiMDJkMGZlYmE2YWUwMjhjZGM2NThkMA=='

```

![image](https://user-images.githubusercontent.com/10482177/155005864-4d814812-43f1-4d1b-a9e9-11ef9d5b8773.png)

Please help
