### ISSUE TITLE
Gradle devfile v1 -> v2 convertion is failing 1 error occurred: * duplicate key: gradle

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21197]
### Describe the bug

v1 devfile convertion fails with `Danger alert:1 error occurred: * duplicate key: gradle`
```
apiVersion: 1.0.0
metadata:
  name: java-gradle-ies31
attributes:
  persistVolumes: 'false'
  asyncPersist: 'true'
projects:
  - name: console-java-simple
    source:
      location: 'https://github.com/che-samples/console-java-simple'
      type: git
      branch: java1.11
components:
  - id: redhat/java/latest
    preferences:
      java.server.launchMode: Standard
    type: chePlugin
  - mountSources: true
    endpoints:
      - attributes:
          public: 'false'
        name: debug
        port: 5005
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: gradle
        containerPath: /home/gradle/.gradle
    alias: gradle
    image: 'quay.io/eclipse/che-java11-gradle@sha256:cd16e0be07af69449acc32f038966b650fe148a046e0ab2843f0b5a74c4d678f'
    env:
      - value: /home/gradle/.gradle
        name: GRADLE_USER_HOME
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_TOOL_OPTIONS
      - value: /home/gradle
        name: HOME
commands:
  - name: gradle build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/console-java-simple'
        type: exec
        command: gradle build
        component: gradle
  - name: gradle run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/console-java-simple'
        type: exec
        command: gradle run
        component: gradle
```

### Che version

7.42@latest

### Steps to reproduce

Try to convert devfile using User Dashboard

### Expected behavior

devfile is converted without errors

### Runtime

OpenShift

### Screenshots

![image](https://user-images.githubusercontent.com/1461122/154995175-09f07bd2-f5a2-485c-9ff4-03798bd5d752.png)

### Installation method

OperatorHub

### Environment

Linux
