### ISSUE TITLE
dev-workspace doesnot detect `devfile.yaml` present inside branches other than master or main branch

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21218]
### Summary

below is the message i receive when i place my `devfile.yaml` within a branch other than `main` or `master`.
Kindly let me know how to fix this issue?

![image](https://user-images.githubusercontent.com/10482177/155549245-c36846a0-a309-4384-9315-8786741e9c30.png)

below is my `devfile.yaml`
```
schemaVersion: 2.1.0
metadata:
  name: botservicemeta
projects:
  - name: botservice
    git:
      checkoutFrom:
        revision: dev
      remotes:
        origin: https://gitlab.organization.com/zzz/zzzzzz.git
components:
  - container:
      image: 'quay.io/devfile/universal-developer-image:ubi8-0e189d9'
      memoryLimit: 2G
      endpoints:
        - exposure: none
          name: debug
          protocol: tcp
          targetPort: 5005
        - exposure: public
          name: 8080-tcp
          protocol: http
          targetPort: 8080
      volumeMounts:
        - name: m2
          path: /home/user/.m2
    name: tools
  - name: m2
    volume:
      size: 2G
commands:
  - exec:
      commandLine: mvn clean package -DskipTests
      component: tools
      group:
        isDefault: true
        kind: build
      label: 'build project using maven'
      workingDir: '${PROJECT_SOURCE}'
    id: mvnpackage

  - id: runjar
    exec:
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: java -jar target/zzz-0.0.1-SNAPSHOT.jar
      label: 'run jar file'
      group:
        kind: run
        isDefault: true
```

i looked into the devfile [documentation](https://devfile.io/docs/devfile/2.1.0/user-guide/api-reference/) , but unable to figure out what i missed. kindly help me out
