### ISSUE TITLE
unable to view tcp endpoint URL  generated from `devfile.yaml` spec spawned from the workspace

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21220]
### Summary

i'm not able to view the url of the tcp endpoint generated from `devfile.yaml` spec. Unable to copy it as well. i have no idea what my tcp endpoint is. How do i find what the tcp endpoint is?

But i'm able to view / copy the `http` endpoint.
![image](https://user-images.githubusercontent.com/10482177/156011569-023d808c-baab-4784-9cbc-89d7fd51c442.png)

Currently i have installed `eclipse-che` in minikube cluster.
Below is the version of `chectl` i'm currently using.
![image](https://user-images.githubusercontent.com/10482177/156012112-3a2b66f6-f9aa-443e-9658-6b7d83a12353.png)

Please share your feedback.

below is my `devfile.yaml`
```
schemaVersion: 2.1.0
metadata:
  name: introselenium-service
projects:
  - name: seleniumservice
    git:
      checkoutFrom:
        revision: main
      remotes:
        origin: https://gitlab.organization.com/introselenium.git
components:
  - container:
      image: 'quay.io/devfile/universal-developer-image:ubi8-0e189d9'
      memoryLimit: 2G
      endpoints:
        - exposure: none
          name: debug
          protocol: tcp
          targetPort: 5005
        - exposure: public
          name: 8080-http
          protocol: http
          targetPort: 8080
      volumeMounts:
        - name: m2
          path: /home/user/.m2
    name: tools
  - container:
      image: 'selenium/standalone-chrome:4.1.2-20220217'
      memoryLimit: 3G
      endpoints:
        - exposure: public
          name: 4444-tcp
          protocol: tcp
          targetPort: 4444
        - exposure: public
          name: 5900-tcp
          protocol: tcp
          targetPort: 5900
        - exposure: public
          name: 7900-http
          protocol: http
          targetPort: 7900
      volumeMounts:
        - name: m2
          path: /home/user/.m2
    name: selenium
  - name: m2
    volume:
      size: 2G
commands:
  - exec:
      commandLine: mvn clean package -DskipTests
      component: tools
      group:
        isDefault: true
        kind: build
      label: 'build project using maven'
      workingDir: '${PROJECT_SOURCE}'
    id: mvnpackage

```
