### ISSUE TITLE
error while accessing public endpoints from workspace when the application exposes  features  via both `http` and `ws` protocol 

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21222]
### Summary

My application exposes a webinterface accessible via `http protocol`. Couple of features in this application is accessible via `http protocol`, and remaining features in this application requires websocket `ws, wss` protocol.

What am i doing with `eclipse-che`?

Below `devfile.yaml` is used to create the workspace and clone my application into the workspace.  As per the details in my `devfile.yaml`, this application exposes services via `5900 tcp port` and `7900 http port`. 

**Here is the issue i'm currently facing.**
My application also exposes features via websockets. it will be making use of the same `7900 port` , this is usually how websockets work (please view my devfile.yaml below).  But it throws error when the `connection upgrades` from `http` to `ws`

below screenshot shows that i'm able to view the application feature exposed via http protocol
![image](https://user-images.githubusercontent.com/10482177/156022338-618768d6-e7a9-45a6-ad01-4684bf59bf16.png)

when i click `Connect`, the `connection upgrade` request from `http` to `ws` is initiated and this `connection upgrade` request throws error.
![image](https://user-images.githubusercontent.com/10482177/156022506-53224b45-34fd-4a15-853e-f553c33e32dd.png)
Below screenshot shows the failure of `connection upgrade` request 
![image](https://user-images.githubusercontent.com/10482177/156022688-c971f4d2-4aad-4eaf-b597-67513f15e693.png)

![image](https://user-images.githubusercontent.com/10482177/156022806-0733c187-aa6d-4454-b164-a74af0b12b82.png)

i'm not sure how to explicitly specify in my `devfile.yaml` to handle both `http protocol` and `ws protocol` with the same portnumber.

in the [devfile 2.1.0 docs](https://devfile.io/docs/devfile/2.1.0/user-guide/api-reference/) , there is option to specify only one protocol. in case of my application, initially the webpage will make use of `http` protocol , then a `connection upgrade` request will be made for `ws` protocol and `ws` protocol will be using the same port as `http`. I'm not able to comprehend what kind of value i have to specify in the `protocol` field in `devfile.yaml`
![image](https://user-images.githubusercontent.com/10482177/156171643-2b841bd4-0b68-4bae-94d1-ddcb444b3989.png)

Please help me to figure out a solution for this issue

below is my `devfile.yaml`
```
schemaVersion: 2.1.0
metadata:
  name: introselenium-service
projects:
  - name: seleniumservice
    git:
      checkoutFrom:
        revision: main
      remotes:
        origin: https://gitlab.organization.com/introselenium.git
components:
  - container:
      image: 'quay.io/devfile/universal-developer-image:ubi8-0e189d9'
      memoryLimit: 2G
      endpoints:
        - exposure: none
          name: debug
          protocol: tcp
          targetPort: 5005
        - exposure: public
          name: 8080-http
          protocol: http
          targetPort: 8080
      volumeMounts:
        - name: m2
          path: /home/user/.m2
    name: tools
  - container:
      image: 'selenium/standalone-chrome:4.1.2-20220217'
      memoryLimit: 3G
      endpoints:
        - exposure: public
          name: 4444-tcp
          protocol: tcp
          targetPort: 4444
        - exposure: public
          name: 5900-tcp
          protocol: tcp
          targetPort: 5900
        - exposure: public
          name: 7900-http
          protocol: http
          targetPort: 7900
      volumeMounts:
        - name: m2
          path: /home/user/.m2
    name: selenium
  - name: m2
    volume:
      size: 2G
commands:
  - exec:
      commandLine: mvn clean package -DskipTests
      component: tools
      group:
        isDefault: true
        kind: build
      label: 'build project using maven'
      workingDir: '${PROJECT_SOURCE}'
    id: mvnpackage
```

Currently i have installed `eclipse-che` in minikube cluster.
Below is the version of `chectl` i'm currently using.
![image](https://user-images.githubusercontent.com/10482177/156012112-3a2b66f6-f9aa-443e-9658-6b7d83a12353.png)
