### ISSUE TITLE
how to `volumeMount` on a `hostPath` in `eclipse-che` ?

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21236]
### Summary

When i create a simple pod with a kubernetes cluster, i will have the flexibility to add `volumeMounts` that points to a `hostPath` in `pod.yaml` file

incase of the below `pod.yaml` file , if there are any files generated and stored within `/app/ntemp`, those files will be available in my localComputer's `hostPath: /Users/divine/Documents/minikubehostvolume`
 
below is the `pod.yaml` configuration which i have used to implement the above scenario.
```
apiVersion: v1
kind: Pod
metadata:
  name: mydemonodejs
  labels:
    app: mydemonodejslabel
spec:
  containers:
  - image: divine6/myapp:2.0
    name: myappcontainer
    ports:
    - containerPort: 3000
    volumeMounts:
    - mountPath: /app/ntemp
      name: demonodejsvolume
  volumes:
  - name: demonodejsvolume
    hostPath:
      path: /Users/divine/Documents/minikubehostvolume
      type: Directory
```

**Here is my question,**

in case of `eclipse-che`, how can i use `hostPath` in my `devfile.yaml` ? 
Below i my `devfile.yaml`. i looked into the [devfile2.1.0 spec](https://devfile.io/docs/devfile/2.1.0/user-guide/api-reference/), but i'm not able to find an option to add `hostPath` to a volume.

My intention is to add a directory or NFS storage as a volume to a container in  `devfile.yaml`. 

Please let me know how to implement this scenario .

```
schemaVersion: 2.1.0
metadata:
  name: introselenium-service
projects:
  - name: seleniumservice
    git:
      checkoutFrom:
        revision: main
      remotes:
        origin: https://gitlab.organizationcom/divine/introselenium.git
components:
  - container:
      image: 'quay.io/devfile/universal-developer-image:ubi8-0e189d9'
      memoryLimit: 2G
      endpoints:
        - exposure: none
          name: debug
          protocol: tcp
          targetPort: 5005
        - exposure: public
          name: 8080-http
          protocol: http
          targetPort: 8080
      volumeMounts:
        - name: m2
          path: /home/user/.m2
    name: tools
  - container:
      image: 'selenium/standalone-chrome:4.1.2-20220217'
      memoryLimit: 3G
      endpoints:
        - exposure: public
          name: 4444-tcp
          protocol: tcp
          targetPort: 4444
        - exposure: public
          name: 5900-tcp
          protocol: tcp
          targetPort: 5900
        - exposure: public
          name: 7900-http
          protocol: http
          targetPort: 7900
          secure: true
      volumeMounts:
        - name: m2
          path: /home/user/.m2
    name: selenium
  - name: m2
    volume:
      size: 2G
commands:
  - exec:
      commandLine: mvn clean package -DskipTests
      component: tools
      group:
        isDefault: true
        kind: build
      label: 'build project using maven'
      workingDir: '${PROJECT_SOURCE}'
    id: mvnpackage
```

**Comment by l0rd** [comment]
@Divine1 thanks for this queston, this is a very valid scenario. 

We should avoid specifying an hostpath in a devfile as it would make the devfile not portable (it works for you because `/Users/divine/Documents/minikubehostvolume` existing folder in your host, but it doesn't work for me) and I would have some concern from a secuirty point of view.

Our approach for anything related to user specific configuration has been to [label and annotate secrets/configmaps/volumes so that they are automatically injected in a workspace even if they are not specified in the devfile](https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.md#automatically-mounting-volumes-configmaps-and-secrets).

So going back to your use case I would suggest to pre-create a `PersistentVolume` and a `PersistentVolumeClaim` like the following ones (note the PVC labels and annotations): 

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demonodejsvolume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/divine/Documents/minikubehostvolume"
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demonodejsvolume-claim
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
  annotations:
    controller.devfile.io/mount-path: "/app/ntemp"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
```

Let us know how it works and consider signing up to [Che mailing list](https://accounts.eclipse.org/mailing-list/che-dev) or joining [Che weekly community call](https://github.com/eclipse/che/wiki/Che-Dev-Meetings) to discuss about Eclipse Che features, scenarios and roadmap.
