### ISSUE TITLE
Private GitLab repositories: OAuth2 flow fails in devworkspace mode (without Keycloak)

### ISSUE THREAD

**Issue by nils-mosbach** [eclipse/che#21231]
### Describe the bug

Trying to start workspaces from private GitLab repo fails with the following message:

![image](https://user-images.githubusercontent.com/15126675/156597077-37edd53e-e4dc-4cd6-bf5a-9a3b3786cc72.png)

It seems that the token that was passed by GitLab isn't used`.

As expected authentication is triggered after `https://che.company.dev/api/factory/resolver/` fails. Following the OAuth flow: 
* Che dashboard will call `https://che.company.dev/api/oauth/authenticate?oauth_provider=gitlab&scope...` 
* which redirects to `https://git.company.dev/oauth/authorize?client_id=a6`. 
* That seems to work as well and gitlab redirects to `https://che.company.dev/api/oauth/callback?code=...`.

![image](https://user-images.githubusercontent.com/15126675/156604730-e3416543-7df4-4f0c-9cdf-80eee568a87b.png)

Browser console shows the following output.

![image](https://user-images.githubusercontent.com/15126675/156599338-d40d776a-cc1f-4ca0-ba1c-e22af320dade.png)

As a result an empty secret `workspace-credentials-secret` is created in the users namespace. Dex is configured using GitLab for Kubernetes native auth. 

Based on the configuration and OAuth flow, that looks good. Am I missing something?

### Che version

next (development version)

#### Che authentication

We've deployed dex and configured the kube api server as well as Che's authentication to use it. That works as expected.

``` yaml
# Dex config
config:
  issuer: https://dex.company.dev
  oauth2:
    responseTypes: ["code", "token", "id_token"]
    skipApprovalScreen: true
  staticClients:
    - id: kubernetes
      name: Kubernetes native auth
      redirectURIs:
        - https://che.company.dev/api/oauth/callback
        - https://che.company.dev/oauth/callback
        - https://che.company.dev/api/oauth/callback
      secret: 798
  connectors:
    - type: gitlab
      id: gitlab
      name: GitLab
      config:
        baseURL: https://git.company.dev
        clientID: c1d
        clientSecret: b07
        redirectURI: https://dex.company.dev/callback
        useLoginAsID: false
```

``` yaml
# Che Config
spec:
  server:
    customCheProperties:
      CHE_INTEGRATION_GITLAB_SERVER__ENDPOINTS: "https://git.company.dev/"
      CHE_OIDC_USERNAME__CLAIM: email
  auth:
    externalIdentityProvider: true
    openShiftoAuth: false
    identityProviderURL: 'https://dex.company.dev'
    oAuthClientName: kubernetes
    oAuthSecret: 798
```

#### GitLab OAuth2 integration

As described by https://www.eclipse.org/che/docs/next/administration-guide/configuring-authorization/#configuring-gitlab-oauth2-with-devworkspace-engine_che, we've created a new application in GitLab `Che` and created a secret 

``` yaml
# Gitlab OAuth Secret
kind: Secret
apiVersion: v1
metadata:
  name: gitlab-oauth-config
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: gitlab
    che.eclipse.org/scm-server-endpoint: http://git.company.dev
type: Opaque
data:
  id: <base64_encoded_GitLab_Application_ID>
  secret: <base64_encoded_GitLab_Secret>
```

From what I understand Che/Kubernetes-auth is independent from GitLab-auth that's being used for pulling projects, right? Just in case  `CHE_OIDC_USERNAME__CLAIM: email` shouldn't cause issues, right?
We're using trusted SSL certs.

### Expected behavior

Devfile should be retrieved from private GitLab repository using requested OAuth token.

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/next

### Environment

Linux

### Eclipse Che Logs

```shell
Che Server/ Dashboard don't show any logs.
```

### Additional context

#20831 On prem private Gitlab repositores support with OAuth2 flow (without Keycloak)
