### ISSUE TITLE
[UX] When devfile startup fails, provide actual useful logs to help with debugging

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che#21266]
### Is your enhancement related to a problem? Please describe

0. log in to https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/
1. load a devfile from https://raw.githubusercontent.com/crw-samples/fuse-rest-http-booster/devfilev2/devfile.yaml
3. stop workspace load
4. make changes to devfile to test it out (before having to commit to a repo)
5. attempt to load - but if you make a mistake, you get useless errors like this:
![image](https://user-images.githubusercontent.com/227597/158457568-f1012ae1-5507-49d2-b536-aecb4c35cddf.png)

or 

![image](https://user-images.githubusercontent.com/227597/158457756-1ad4af46-a39d-4c9f-9449-32f06d01f9ec.png)

Which just reiterates the *condition* of the problem, but provides no data to help explain WHY the container is in crashloopbackoff.

Then I click the link for "open in Verbose mode" 

and I get this, even though I don't have any workspaces running (because the failure in progress counts as a running workspace?? nice.):

![image](https://user-images.githubusercontent.com/227597/158457667-57381a32-9e2c-4f97-b4e7-694cbf065bd0.png)

### Describe the solution you'd like

More console output. More debug output. More useful information about why me making these tiny changes failed the load:

```
      image: registry.redhat.io/codeready-workspaces/plugin-java11-rhel8
      memoryLimit: 3Gi
      sourceMapping: /projects
      volumeMounts:
        - name: m2
          path: /home/jboss/.m2
        - name: gradle
          path: /home/jboss/.gradle
```
to
```
      image: 'quay.io/crw/udi-rhel8:2.16-110'
      memoryLimit: 3Gi
      sourceMapping: /projects
      volumeMounts:
        - name: m2
          path: /home/user/.m2
        - name: gradle
          path: /home/user/.gradle
```

### Describe alternatives you've considered

1. Cursing, and flipping the table.

2. Committing changes to github repo fork, then iteratively:
* delete workspace
* load workspace after each incremental change
* hope it works
* repeat if not

### Additional context

trying to reproduce https://issues.redhat.com/browse/CRW-2591
