### ISSUE TITLE
Setting devWorkspace controllerImage has no effect for airgapped environment

### ISSUE THREAD

**Issue by thenrich** [eclipse/che#21268]
### Describe the bug

Setting the following in the checluster CRD has no effect:

```yaml
spec:
  devWorkspace:
    controllerImage: path/to/controller/image
```

The default devWorkspace controller image is still used.

### Che version

7.44@latest

### Steps to reproduce

1. Deploy Che with `chectl server:deploy -a operator -b my.domain.org -p k8s --skip-oidc-provider-check --che-operator-cr-patch-yaml=che-cr-patch.yaml --che-operator-image=custom-operator-image`

che-cr-patch.yaml:
```yaml
spec:
  auth:
    externalIdentityProvider: true
    identityProviderURL: ...
    nativeUserMode: true
    oAuthClientName: kubernetes
    oAuthSecret: ...
    openShiftoAuth: false
    updateAdminPassword: true
  devWorkspace:
    controllerImage: path/to/custom/image
  database:
    postgresImage: path/to/custom/image
  server:
    customCheProperties:
      CHE_OIDC_USERNAME__CLAIM: email
    airGapContainerRegistryHostname: custom_host
    airGapContainerRegistryOrganization: custom_org
    devfileRegistryImage:path/to/custom/image
    singleHostGatewayImage: path/to/custom/image
```

2. Che deploys successfully and comes online with several custom images
3. Once devworkspace-controller namespace becomes available, `kubectl -n devworkspace-controller describe pods` shows the devworkspace-controller container with the default quay.io image and kube-rbac-proxy -- **not** the image defined by `spec.auth.devWorkspace.controllerImage` **or** the airgap host/org.

### Expected behavior

devworkspace-controller should honor the controllerImage or use the airgapped registry hostname/org

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Linux, Amazon
