### ISSUE TITLE
How configure keycloak as externel OIDC provider for Eclipse Che 

### ISSUE THREAD

**Issue by Ryder05** [eclipse/che#21282]
### Summary

I am trying to deploy Eclipse che on an Ovh managed cluster, since keycloak is deployed by che operator I need to do the job manually. 
when i tap 
`chectl server:deploy --domain=oc-perf.eu --platform=k8s -n cheche --che-operator-cr-patch-yaml=checluster.yml ` raises 
the deloyments fails 
```
    > Eclipse Che Server pod bootstrap
      √ Scheduling...done
      √ Downloading images...done
      × Starting...failed
        → Failed to start a pod, reason: Error, exitCode: 137
```
I will be gratueful if someone can give me the steps to configure my cluster with keycloak. 

### Relevant information

keycloak deployment file
 
```
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "keycloak-development"
    #namespace: "che"
  spec: 
    selector: 
      matchLabels: 
        app: "keycloak-development"
    replicas: 1
    strategy: 
      type: "RollingUpdate"
      rollingUpdate: 
        maxSurge: 1
        maxUnavailable: 1
    minReadySeconds: 5
    template: 
      metadata: 
        labels: 
          app: "keycloak-development"
      spec: 
        containers: 
          - 
            name: "keycloak-development"
            image: "quay.io/keycloak/keycloak:8.0.2"
            imagePullPolicy: "Always"
            env: 
              - 
                name: "KEYCLOAK_USER"
                value: "admin"
              -
                name: "DB_ADDR"
                value: "postgres"     
              -
                name: "DB_VENDOR"
                value: "POSTGRES"
              -  
                name: "KEYCLOAK_PASSWORD"
                value: "admin"
                
              -
                name: "PROXY_ADDRESS_FORWARDING"
                value: "true"
  
                
            ports: 
              
              - name: "http"
                containerPort: 8080
                
              - name: "https"
                containerPort: 8443
            readinessProbe:
               httpGet:
                 path: "/auth/realms/master"
                 port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-development
      
  #namespace: "che"

  labels:
    app: keycloak-development
spec:
  ports:
  - name: http
    port: 53582
    targetPort: 8443
  
  selector:
    app: keycloak-development
  type: LoadBalancer

```

checluster.yml file

```
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  auth:
    externalIdentityProvider: true
    identityProviderClientId: kubernetes
    identityProviderRealm: git-dev
    identityProviderURL:  https://152.228.168.237:53582/auth/realms/git-dev  
    openShiftoAuth: false
    updateAdminPassword: false


  server:
    customCheProperties:
      CHE_OIDC_USERNAME__CLAIM: "email"

```
