### ISSUE TITLE
Eclipse Che Server pod bootstrap failed to start pod.

### ISSUE THREAD

**Issue by Ryder05** [eclipse/che#21287]
### Summary

Hello,
I am trying to deploy Che on K8s  using chectl.   
After the deployment stops the che pod starts running and i can't resume deploying because the server already deployed !
i am using chectl/7.45.0

```
C:\Users\Oussema Mhiri\Downloads> chectl server:deploy --domain=che.oc-perf.eu --platform=k8s  --che-operator-cr-patch-yaml=checluster.yml  --skip-oidc-provider-check --che-operator-image=quay.io/eclipse/che-operator:next
› Installer type is set to: 'operator'
› Current Kubernetes context: 'kubernetes-admin@perf'
  √ Verify Kubernetes API...OK
  √ 👀  Looking for an already existing Eclipse Che instance
    √ Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not
  √ 🧪  DevWorkspace engine
    √ Verify cert-manager installation
      √ Check Cert Manager deployment...already deployed
      √ Wait for Cert Manager...ready
  √ ✈️  Kubernetes preflight checklist
    √ Verify if kubectl is installed
    √ Verify remote kubernetes status...done.
    √ Check Kubernetes version: Found v1.22.2.
    √ Verify domain is set...set to che.oc-perf.eu.
    ↓ Check if cluster accessible [skipped]
  √ Following Eclipse Che logs
    √ Start following Operator logs...done
    √ Start following Eclipse Che Server logs...done
    √ Start following PostgreSQL logs...done
    √ Start following Keycloak logs...done
    √ Start following Plug-in Registry logs...done
    √ Start following Devfile Registry logs...done
    √ Start following Eclipse Che Dashboard logs...done
    √ Start following namespace events...done
  √ Create Namespace eclipse-che...[Exists]
  √ Create Namespace eclipse-che...[Exists]
  √ 🏃‍  Running the Eclipse Che operator
    √ Create ServiceAccount che-operator in namespace eclipse-che...done.
    √ Read Roles and Bindings...done.
    √ Creating Roles and Bindings...done.
    √ Create CRD checlusters.org.eclipse.che...It already exists.
    √ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    √ Create deployment che-operator in namespace eclipse-che...done.
    √ Operator pod bootstrap
      √ Scheduling...done
      √ Downloading images...done
      √ Starting...done
    √ Prepare Eclipse Che cluster CR...Done.
    √ Create the Custom Resource of type checlusters.org.eclipse.che in the namespace eclipse-che...done.
  > ✅  Post installation checklist
    √ PostgreSQL pod bootstrap
      √ Scheduling...done
      √ Downloading images...done
      √ Starting...done
    √ Devfile Registry pod bootstrap
      √ Scheduling...done
      √ Downloading images...done
      √ Starting...done
    √ Plug-in Registry pod bootstrap
      √ Scheduling...done
      √ Downloading images...done
      √ Starting...done
    √ Eclipse Che Dashboard pod bootstrap
      √ Scheduling...done
      √ Downloading images...done
      √ Starting...done
    > Eclipse Che Server pod bootstrap
      √ Scheduling...done
      √ Downloading images...done
      × Starting...failed
        → Failed to start a pod, reason: Error, exitCode: 137
      Eclipse Che status check
    Retrieving Che self-signed CA certificate
    Prepare post installation output
    Error: Command server:deploy failed. Error log: C:\Users\Oussema Mhiri\AppData\Local\chectl\error.log.
```

### Relevant information

checluster.yml file 

```
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  auth:
    externalIdentityProvider: true
    identityProviderClientId: kubernetes
    identityProviderRealm: git-dev
    identityProviderURL:  http://135.125.85.66:443/auth/realms/git-dev  
    openShiftoAuth: false
    updateAdminPassword: false


  server:
    customCheProperties:
      CHE_OIDC_USERNAME__CLAIM: "email"

```

keycloak.yml file 

```
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "keycloak-development"
    #namespace: "che"
  spec: 
    selector: 
      matchLabels: 
        app: "keycloak-development"
    replicas: 1
    strategy: 
      type: "RollingUpdate"
      rollingUpdate: 
        maxSurge: 1
        maxUnavailable: 1
    minReadySeconds: 5
    template: 
      metadata: 
        labels: 
          app: "keycloak-development"
      spec: 
        containers: 
          - 
            name: "keycloak-development"
            image: "quay.io/keycloak/keycloak:10.0.0"
            #args: ["start-dev"]
            #args: ["standalone.sh  --start-mode=admin-only "]
            imagePullPolicy: "Always"
            env: 
              - 
                name: "KEYCLOAK_USER"
                value: "admin"
              -  
                name: "KEYCLOAK_PASSWORD"
                value: "admin"
              -
                name: "PROXY_ADDRESS_FORWARDING"
                value: "true"
              -
                name: "DB_ADDR"
                value: "postgres"     
              -
                name: "DB_VENDOR"
                value: "POSTGRES"
                
              -
                name: DB_USER
                value: "postgres" 
              - 
                name: DB_PASSWORD
                value: "postgres"

              - 
                name: DB_DATABASE
                value: keycloak
              - 
                name : KEYCLOAK_HTTP_PORT
                value : "80"
              -
                name: KEYCLOAK_HTTPS_PORT
                value: "443"
              - 
                name: VIRTUAL_PORT
                value: "8080"
              - 
                name: JDBC_PARAMS
                value: useSSL=false

                
            ports: 
              
              - name: "http"
                containerPort: 8080
                
              - name: "https"
                containerPort: 8443
            readinessProbe:
                httpGet:
                  path: "/auth/realms/master"
                  port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-development
      
  #namespace: "che"

  labels:
    app: keycloak-development
spec:
  ports:
  - name: http
    port: 443
    targetPort: 8080
  
  selector:
    app: keycloak-development
  type: LoadBalancer

```

error.log file 

```
2022-03-21T14:02:20.158Z Error: Command server:deploy failed. Error log: C:/Users/Oussema Mhiri/AppData/Local/chectl/error.log.
2022-03-21T14:02:20.158Z     at newError (C:/Users/Oussema Mhiri/AppData/Local/chectl/client/7.45.0/lib/util.js:199:19)
2022-03-21T14:02:20.158Z     at Object.wrapCommandError (C:/Users/Oussema Mhiri/AppData/Local/chectl/client/7.45.0/lib/util.js:195:12)
2022-03-21T14:02:20.158Z     at Deploy.<anonymous> (C:/Users/Oussema Mhiri/AppData/Local/chectl/client/7.45.0/lib/commands/server/deploy.js:189:35)
2022-03-21T14:02:20.158Z     at Generator.throw (<anonymous>)
2022-03-21T14:02:20.158Z     at rejected (C:/Users/Oussema Mhiri/AppData/Local/chectl/client/7.45.0/node_modules/tslib/tslib.js:115:69)
2022-03-21T14:02:20.158Z     at runMicrotasks (<anonymous>)
2022-03-21T14:02:20.158Z Cause: Error: Failed to start a pod, reason: Error, exitCode: 137
2022-03-21T14:02:20.158Z     at KubeTasks.<anonymous> (C:/Users/Oussema Mhiri/AppData/Local/chectl/client/7.45.0/lib/tasks/kube.js:134:35)
2022-03-21T14:02:20.158Z     at Generator.next (<anonymous>)
2022-03-21T14:02:20.158Z     at fulfilled (C:/Users/Oussema Mhiri/AppData/Local/chectl/client/7.45.0/node_modules/tslib/tslib.js:114:62)
2022-03-21T14:02:20.158Z     at runMicrotasks (<anonymous>)

```

```

PS C:\Users\Oussema Mhiri\che\deploy\kubernetes\helm\che> kubectl get pods -n eclipse-che
NAME                                   READY   STATUS      RESTARTS      AGE
che-9bd6b9c7c-qzghl                    1/1     Running     1 (10m ago)   18m
che-dashboard-9ddbbb44f-jcwnr          1/1     Running     0             18m
che-gateway-cdbcfddc5-968n8            4/4     Running     0             18m
che-operator-546774698d-8r2kw          1/1     Running     0             21m
che-tls-job--1-6s7lq                   0/1     Completed   0             20m
che-tls-job--1-d5st9                   0/1     Completed   0             35m
devfile-registry-7c77d695d-hsdkw       1/1     Running     0             18m
keycloak-development-d58954797-gtfpr   1/1     Running     5 (19m ago)   22m
plugin-registry-6cf7fdcd9f-lqqks       1/1     Running     0             18m
postgres-759fdddcc8-4gwm6              1/1     Running     0             19m
```
