### ISSUE TITLE
DevfileV1 to DevfileV2 converter loses storageType

### ISSUE THREAD

**Issue by olexii4** [eclipse/che#21290]
### Describe the bug

DevfileV1 to DevfileV2 converter loses storageType

### Che version

7.44@latest

### Steps to reproduce

1. Deploy Eclipse-Che with devworkspaces
2. Create a new workspace from the [DevfileV1](https://gist.githubusercontent.com/olexii4/254a21559b71f991285f44eeda6cec96/raw/82659cce2d730cc15836077c18274e30a21f7d56/apache-camel-k.yaml)
```
apiVersion: 1.0.0
metadata:
  name: apache-camel-k-345
attributes:
  persistVolumes: "false"
projects:
  -
    name: camel-k-examples
    source:
      type: git
      location: "https://github.com/che-samples/apache-camel-k"
      sparseCheckoutDir: "examples"
```
3. Open the 'Devfile' for created workspace.
```
schemaVersion: 2.1.0
metadata:
  name: apache-camel-k-345
  namespace: admin-che
projects:
  - git:
      remotes:
        origin: 'https://github.com/che-samples/apache-camel-k'
    name: camel-k-examples
components: []
```
As you can see, we lost storage-type:
```
attributes:
  controller.devfile.io/storage-type: ephemeral
```

### Expected behavior

A created workspace should be next:
```
schemaVersion: 2.1.0
attributes:
  controller.devfile.io/storage-type: ephemeral
metadata:
  name: apache-camel-k-345
  namespace: admin-che
projects:
  - git:
      remotes:
        origin: 'https://github.com/che-samples/apache-camel-k'
    name: camel-k-examples
components: []
```

### Runtime

minikube

### Screenshots

<img width="1243" alt="2022-03-22_14_33_11" src="https://user-images.githubusercontent.com/6310786/159494851-e7a72507-69f9-471a-9baf-87a7b2cf4131.png">

### Installation method

chectl/next

### Environment

macOS
