### ISSUE TITLE
User guide - Adding a VS Code extension

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21296]
### Is your enhancement related to a problem? Please describe

User Guide needs to be updated ([global issue](https://github.com/eclipse/che/issues/21285)). This issue is about the creation of a new "Add a VS Code extension" section. 

### Describe the solution you'd like

This is specific to Che Theia and, of course, VS Code

We should warn that Che Theia VS Code extension support has some flaws and provide a link to Che Theia VS Code extensions compatibility API.

We should mention that it's possible to specify a VS Code extension in:
- .vscode/extensions.json
- .che/che-theia-plugins.yaml
- in devfile.yaml attributes
and give an example for any of them as well as pros and cons.

We should provide examples on how the property of an extension can be overridden for any of those scenarios.

We should also specify where the definitions of the VS Code extensions are (plugin registry gh repository, online instance and embedded instance) and how openvsx and Che plugin registry are related.

**Comment by benoitf** [comment]
closing as PR has been merged

**Comment by Divine1** [comment]
Hi @benoitf  @l0rd 



i have a doubt on adding extension to che-theia ide

i have an extensionId `harmony-cbfsel.harmony-assist`, this extension can be installed in any vscode by any users. i want this extension to be installed and available for use in the `che-theia` ide.
so, i added the `attributes` section in devfile.yaml. but i'm unable to find my extension `harmony-cbfsel.harmony-assist` in the `che-theia` ide. Please let me know how to install `harmony-cbfsel.harmony-assist` extension in `che-theia` ide

Please help me to fix this problem


i followed [this documentation](https://www.eclipse.org/che/docs/stable/end-user-guide/adding-a-vscode-extension/#visual-studio-code-extensions-in-devfile)

```
schemaVersion: 2.1.0
metadata:
  name: cbfsel-repo
projects:
  - name: cbfsel-project
    git:
      checkoutFrom:
        revision: master
      remotes:
        origin: https://gitlab.myorg.com/cbf-sel.git
attributes:
  .vscode/extensions.json: |
    {
      "recommendations": [
        "harmony-cbfsel.harmony-assist"
      ]
    }
components:
  - container:
      image: 'artfact/qedocker/eclipseche/customopenjdk8:v10'
      memoryLimit: 4G
      volumeMounts:
        - name: m2volume
          path: /home/user/.m2
    name: javacontainer
  - container:
      image: 'artfact/eclipseche/selenium/standalone-chrome:4.3.0-20220706'
      memoryLimit: 4G
      endpoints:
        - exposure: public
          name: 4444-tcp
          protocol: tcp
          targetPort: 4444
        - exposure: public
          name: 5900-tcp
          protocol: tcp
          targetPort: 5900
        - exposure: public
          name: 7900-http
          protocol: http
          targetPort: 7900
          secure: true
    name: chromecontainer
  - name: m2volume
    volume:
      size: 4G
commands:
  - exec:
      commandLine: mvn clean package -DskipTests
      component: javacontainer
      group:
        isDefault: true
        kind: build
      label: 'build project using maven'
      workingDir: '${PROJECT_SOURCE}'
    id: mvnpackage

```

**Comment by benoitf** [comment]
Hello @Divine1 

using Che/Theia, the extension needs to be in the Che plug-in registry (here it's not so it will not add it)

Using VS Code/che integration, it will fetch it from [open-vsx.org ](https://open-vsx.org/) (and it's not there so it won't be seen as well)

VS Code marketplace is only available for VS Code product, 3rd party users can't use it. So you should probably provide your extension on open-vsx.org

**Comment by Divine1** [comment]
@benoitf thank you for this quick response.

i will try to push my extension to [open-vsx.org](https://open-vsx.org/) and share you the feedback

**Comment by Divine1** [comment]
@benoitf 
i have published my extension at `https://open-vsx.org/extension/harmony/harmony-assist` . 

The extensionId is `harmony.harmony-assist`

  
i have updated my `devfile.yaml` as shown below. but still i dont see the extension `harmony.harmony-assist` in my `che-theia` ide . please let me know what am i missing.

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/10482177/179481594-955995df-8d59-4eba-9472-6df07b02e24a.png">


```
schemaVersion: 2.1.0
metadata:
  name: cbfsel-repo
projects:
  - name: cbfsel-project
    git:
      checkoutFrom:
        revision: master
      remotes:
        origin: https://gitlab.myorg.com/cbf-sel.git
attributes:
  .vscode/extensions.json: |
    {
      "recommendations": [
        "harmony.harmony-assist"
      ]
    }
components:
  - container:
      image: 'artfact/qedocker/eclipseche/customopenjdk8:v10'
      memoryLimit: 4G
      volumeMounts:
        - name: m2volume
          path: /home/user/.m2
    name: javacontainer
  - container:
      image: 'artfact/eclipseche/selenium/standalone-chrome:4.3.0-20220706'
      memoryLimit: 4G
      endpoints:
        - exposure: public
          name: 4444-tcp
          protocol: tcp
          targetPort: 4444
        - exposure: public
          name: 5900-tcp
          protocol: tcp
          targetPort: 5900
        - exposure: public
          name: 7900-http
          protocol: http
          targetPort: 7900
          secure: true
    name: chromecontainer
  - name: m2volume
    volume:
      size: 4G
commands:
  - exec:
      commandLine: mvn clean package -DskipTests
      component: javacontainer
      group:
        isDefault: true
        kind: build
      label: 'build project using maven'
      workingDir: '${PROJECT_SOURCE}'
    id: mvnpackage
```
