### ISSUE TITLE
How does workspace idling timeout work in Eclipse Che with DW enabled?

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse/che#21322]
### Summary

How does workspace idling timeout work in Eclipse Che with DW enabled?

I tried to use next DevWorkspaceOperatorConfig object:
```
kind: DevWorkspaceOperatorConfig
apiVersion: controller.devfile.io/v1alpha1
metadata:
  name: devworkspace-operator-config
  namespace: openshift-operators
config:
  workspace:
    imagePullPolicy: Always
    idleTimeout: '1m'
```

After this object creation `devworkspace-controller-manager` pod updated configuration
```
{"level":"info","ts":1649081288.4094315,"logger":"operator-configuration","msg":"Updated config to [(default config)]"}
{"level":"info","ts":1649081310.787388,"logger":"operator-configuration","msg":"Updated config to [workspace.idleTimeout=3m]"} 
```

But workspace didn't stop after 3 min
```
{"level":"info","ts":1649084814.4158278,"logger":"controllers.DevWorkspace","msg":"Got conflict when trying to apply timing annotations to workspace","Request.Namespace":"opentlc-mgr-codeready","Request.Name":"cpp","devworkspace_id":"workspacef48ff8969efa4895"}
{"level":"info","ts":1649084814.4289684,"logger":"controllers.DevWorkspace","msg":"Error updating workspace status: Operation cannot be fulfilled on devworkspaces.workspace.devfile.io \"cpp\": the object has been modified; please apply your changes to the latest version and try again","Request.Namespace":"opentlc-mgr-codeready","Request.Name":"cpp","devworkspace_id":"workspacef48ff8969efa4895"}
```

### Relevant information

Checked on Eclipse Che 7.45.0 on Openshift 4.9 deployed from OperatorHub.
