### ISSUE TITLE
Removing user data according to GDPR does not work with the DevWorkspaces

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21330]
### Describe the bug

Docs: https://www.eclipse.org/che/docs/stable/administration-guide/removing-user-data/

Basically `AdminPermissionInitializer` is not bonded in the `CHE_AUTH_NATIVEUSER` and the following properties in the CR  are not taken into consideration:

```
spec:
 server:
   customCheProperties:
     CHE_SYSTEM_SUPER__PRIVILEGED__MODE: 'true'
     CHE_SYSTEM_ADMIN__NAME: '<admin-name>'
```

### Che version

7.44@latest

### Steps to reproduce

Follow the Docs: https://www.eclipse.org/che/docs/stable/administration-guide/removing-user-data/
on the last step during the user removal as an admin you will get 403 - Permissions denied,

### Expected behavior

Admin user can delete other user data from dd

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

other (please specify in additional context)

### Additional context

In general, the user entries / management should not be part of the che-server anymore and should be removed - https://github.com/eclipse/che/issues/21168#issuecomment-1092546048
