### ISSUE TITLE
Increase default timeout for a workspace stopping automatically

### ISSUE THREAD

**Issue by themr0c** [eclipse/che#21334]
### Is your task related to a problem? Please describe

I find workspace timeout on [workspaces.openshift.com](http://workspaces.openshift.com/) is too low. It increases the cost of an interrupt (example: reply to someone in a chat). In addition to the usual context switching, you have to wait for the workspace to restart and the IDE to become available (2 to 5 minutes, depending on the client hardware).

### Describe the solution you'd like

* Display a warning to the user before stopping the workspace, and let the user interact with this warning to choose to force the session to continue.

* Default timeout to 30 minutes.

### Describe alternatives you've considered

* Workspace starting in less than 30 seconds.
* Using a script or a web browser extension to maintain activity on the running workspace.

**Comment by amisevsk** [comment]
As a workaround, the idle timeout used for all workspaces can be configured per installation via the DevWorkspaceOperatorConfig CR. Create the CR
```yaml
apiVersion: controller.devfile.io/v1alpha1
kind: DevWorkspaceOperatorConfig
metadata:
  name: devworkspace-operator-config
  namespace: openshift-operators # or whatever DWO installation namespace is
config:
  workspace:
    idleTimeout: 30m # or 1h, or longer
```

However, users cannot do this on e.g. workspaces.openshift.com, we should look into increasing the default there cc: @ibuziuk
