### ISSUE TITLE
Allow an admin to specify Che default editor and containers

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21353]
### Is your enhancement related to a problem? Please describe

If no devfile is present in a git repository the default is to start a workspace with only one component (the Theia container) and Theia as the editor. 

That's a bad UX as the Theia container misses many langue tools and because an admin cannot change this behavior.

### Describe the solution you'd like

The default container should be a UDI container. Both the default container and the default editor should be configurable in the `CheCluster` CR.

```yaml
(...)
workspaces:
  (...)
  defaultComponent or defaultContainer ?: |
    name: universal-developer-image
    container:
        image: quay.io/devfile/universal-developer-image:ubi8-latest
        memoryRequest: 256M
        memoryLimit: 1536M
        cpuRequest: 0.1
        cpuLimit: 0.5
  defaultEditor: eclipse/che-theia/next
(...)
```

### Additional Context

This is a #21340 subtask.

### Release Notes Text

Che administrators can now configure the default editor (Theia, VS Code, IntelliJ or PyCharm) and the default container. Those defaults are used when the developer doesn't specify an editor or doesn't specify a devfile. The configuration can be done in the `CheCluster` Custom Resource in the the `workspaces` section using the just introduced `defaultComponent` and `defaultEditor` fields.

**Comment by amisevsk** [comment]
Another option for the new field in the CR is to use `[]devfile.Component` rather than `string`. This would enable k8s validation of the field, devfile/api docs/autocomplete, etc. but would have the downside of making the CheCluster CR quite a bit bigger.

```yaml
(...)
workspaces:
  (...)
  defaultComponents:
    - name: universal-developer-image
      container:
          image: quay.io/devfile/universal-developer-image:ubi8-latest
          memoryRequest: 256M
          memoryLimit: 1536M
          cpuRequest: 0.1
          cpuLimit: 0.5
    - name: some-volume
      volume: {}
  defaultEditor: eclipse/che-theia/next
(...)
```

The benefit of this approach would be that since both the Che Operator and Dashboard depend on devfile/api already, these components could be easily deserialized by both as needed and just added to empty devfiles directly, under `.components`
