### ISSUE TITLE
feeling hopeless while trying to setup eclipse che on k8s cluster

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21362]
### Summary

i have fully functional k8s cluster with 1masterNode and 1workerNode in aws ec2 instances (ubuntu 20.04, kubernetes v1.22.9).

i used `chectl` to begin the installation process of eclipse-che

below command was used but it failed several times due to below issues
`chectl server:deploy --platform=k8s --installer=operator --debug --k8spoderrorrechecktimeout=480000 --domain=eclipseche.mangotree.click --k8spodreadytimeout=480000`

- failed because OIDC provider was not present
i followed the steps mentioned in this documentation https://dexidp.io/docs/kubernetes/
i used the scripts present here ( https://github.com/che-incubator/chectl/tree/main/resources/dex) to install dex
i also referred here (https://github.com/dexidp/dex/edit/master/examples/k8s/dex.yaml) to gain additional understanding on installing dex

- failed while installing cert manager 
i used the scripts present here (https://github.com/che-incubator/chectl/tree/main/resources/cert-manager) to manually install the certManager related components ( https://raw.githubusercontent.com/che-incubator/chectl/main/resources/cert-manager/cert-manager.yml )

- failed while claiming storage for postgres, during postgress installation
i used below pv to fix the error. i have successfully installed `eclipse-che` on `minikube`, i copied this yaml content from that setup
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: postgres-data
    namespace: eclipse-che
  hostPath:
    path: /home/ubuntu/k8sinstaller_files/pv_volume_postgres
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem

```

- failed due to metrics server issue
i installed kubernetes-sigs/metrics-server and used the fix mentioned here (https://github.com/kubernetes-sigs/metrics-server/issues/917#issuecomment-1111694042) to receive the output for `kubectl top nodes`, but this didnot fix the problem with metrics server error related to `chectl` installation

- when i tried to view postgres 
- as of now i' stuck at below error
<img width="1587" alt="image" src="https://user-images.githubusercontent.com/10482177/165672749-343608a6-a291-4837-9915-bb06c783b794.png">

postgres pod failed to start
<img width="737" alt="image" src="https://user-images.githubusercontent.com/10482177/165691315-884c0433-1132-4fac-b21a-129913bc6150.png">

postgres pod description containing failure message
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/10482177/165691394-d37d00e6-513f-4fcf-872a-e311131d9aea.png">

permission error is thrown while viewing postgres logs (how to fix this problem?)
<img width="613" alt="image" src="https://user-images.githubusercontent.com/10482177/165693633-ec2b5b0e-dcc9-402a-adee-2c863516403f.png">

i'm stumbling upon different kinds of errors during installation and i'm spending lot of hours to find out solution for these errors.

i have installed and explored eclipse-che with minikube and i have gained an understanding of how to use `eclipse-che` for my project. i faced couple of issues during installation but this was resolved. i have spent like 200 hours to install and explore `eclipse-che` on `minikube`

But when i try to install `eclipse-che` on `k8s cluster` thinking that this will be easier, i receive many errors during the installation process, and i have spent more than 300 hours of effort on just the installation part and its still not successful.

These long hours includes me trying to learn about kubernetes, i'm not well-versed in kubernetes to begin with, but as of today, i feel like i have gained some knowledge on kubernetes. 

 i think if i fully understand how [chectl](https://github.com/che-incubator/chectl) works , i will be able to figure out how to install eclipse-che on k8s cluster, but i just glanced around the codebase and used the information that is necessary for installation without fully understanding all the steps.

 it will be a lot easier to finish this installation process if there are set of steps that can be followed to  install `eclipse-che` on `k8s cluster`. Please let me know if you have any details available that would help me to finish this installation process

i'm available to contribute for testing the installation steps if you share the steps to install `eclipse-che` on k8s cluster

**Comment by Divine1** [comment]
below approach helped me to fix the above issue and finish the setup. The setup is not 100% functional, but i'm not facing any of the above mentioned errors.

i used this command
`chectl server:deploy --che-operator-cr-patch-yaml=/home/ubuntu/k8sinstaller_files/che-operator-cr-patch.yaml --platform=k8s --installer=operator --debug --k8spoderrorrechecktimeout=480000 --domain=eclipseche.mangotree.click --k8spodreadytimeout=480000`

Instead of using the postgres setup that gets installed by default in chectl in the k8s cluster, is used externally hosted `postgres` by adding below configuration (i understood this option by reading [this comment ](https://github.com/eclipse/che/issues/21095#issuecomment-1063005780) by @l0rd )

che-operator-cr-patch.yaml
```
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  database:
    chePostgresHostName: datasdfgg86wjj.com
    chePostgresPassword: rasdfsfrot123
    chePostgresUser: vmsdfsfv123
    externalDb: true
```
the above file should be passed as an argument to the `chectl server:deploy` command


Below secret file should also be added if you are using externalized postgres database
postgres_secret.yaml
```
apiVersion: v1
data:
  user: dm13Ysdsf2MTIzCg==
  password: cmFpsfsdf0MTIzCg==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: che
    app.kubernetes.io/instance: che
    app.kubernetes.io/managed-by: che-operator
    app.kubernetes.io/name: che
    app.kubernetes.io/part-of: che.eclipse.org
  name: postgres-credentials
  namespace: eclipse-che
type: Opaque
```

After adding these components, the `chectl deploy ...` command posted above completed 100%. but still there are issues with my dex configuration, so i'm working on it.
