### ISSUE TITLE
is there an universal developer image with jdk8?

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21386]
### Summary

currently i'm using `quay.io/devfile/universal-developer-image ` - this has jdk11 . but i need jdk8. Please let  me know if there is any `universal-developer-image` with jdk8 version?

below is the `devfile.yaml`. i face error during workspace creation when i  change the container image from 'quay.io/devfile/universal-developer-image:ubi8-0e189d9' to `adoptopenjdk:8u292-b10-jdk-openj9-0.26.0-focal` .

is it possbile to use a different image like i mentioned above?

```
schemaVersion: 2.1.0
metadata:
  name: cbfsel-repo
projects:
  - name: cbfsel-project
    git:
      checkoutFrom:
        revision: master
      remotes:
        origin: https://gitlab.myorganization/repository.git
components:
  - container:
      image: 'quay.io/devfile/universal-developer-image:ubi8-0e189d9'
      memoryLimit: 2G
      endpoints:
        - exposure: none
          name: debug
          protocol: tcp
          targetPort: 5005
        - exposure: public
          name: 8080-http
          protocol: http
          targetPort: 8080
      volumeMounts:
        - name: m2volume
          path: /home/user/.m2
    name: javacontainer
  - container:
      image: 'mycustomdockerregistry/standalone-chrome:4.1.2-20220217'
      memoryLimit: 2G
      endpoints:
        - exposure: public
          name: 4444-tcp
          protocol: tcp
          targetPort: 4444
        - exposure: public
          name: 5900-tcp
          protocol: tcp
          targetPort: 5900
        - exposure: public
          name: 7900-http
          protocol: http
          targetPort: 7900
          secure: true
      volumeMounts:
        - name: seleniumvolume
          path: /home/user/.m2
    name: seleniumcontainer
  - name: m2volume
    volume:
      size: 2G
  - name: seleniumvolume
    volume:
      size: 2G
commands:
  - exec:
      commandLine: mvn clean package -DskipTests
      component: javacontainer
      group:
        isDefault: true
        kind: build
      label: 'build project using maven'
      workingDir: '${PROJECT_SOURCE}'
    id: mvnpackage
```
