### ISSUE TITLE
Support internal endpoints

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21387]
### Is your enhancement related to a problem? Please describe

Devfile v2 spec supports [3 types of exposures](https://github.com/devfile/api/blob/main/pkg/apis/workspaces/v1alpha2/endpoint.go#L32): public (a route or ingress is created), internal (only the service is created), none (no object is created).

Currently endpoints with exposure `internal` are processed as those that have exposure `none` by the Che DW operator.

Internal endpoints are important because services as databases can then be accessed using their names rather than using localhost.  

### Describe the solution you'd like

A service should be created if the exposure is `internal`.
And the service name should match the endpoint name.

### Additional context

Here is example devfile to try it out:

```yaml
schemaVersion: 2.1.0
metadata:
  name: redis-demo
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: redis-cli
    container:
      image: redis:latest
      args: ['tail', '-f', '/dev/null']
  - name: redis-public
    container:
      image: redis:latest
      endpoints:
        - name: redis-pub
          targetPort: 6380
          exposure: public
      args: ['redis-server', '--port', '6380']
  - name: redis-internal
    container:
      image: redis:latest
      endpoints:
        - name: redis-int
          targetPort: 6379
          exposure: internal
```

Try it on dogfooding instance [![Contribute](https://img.shields.io/static/v1?label=code%20with&message=che-theia&logo=eclipseche&color=FDB940&labelColor=525C86)](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com#https://gist.githubusercontent.com/l0rd/baa74d544f38c7fd358d1711dd46a071/raw/exposures-devfile.yaml).

<img width="1782" alt="image" src="https://user-images.githubusercontent.com/606959/167737874-c83299ea-668b-4055-9212-47b3a21eba3c.png">
