### ISSUE TITLE
VS Code loading twice at workspace startup

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21400]
### Describe the bug

When starting a che-code based workspace the IDE gets loaded a first time and shows an error message (Error loading webview) and after a few seconds gets reloaded:

https://user-images.githubusercontent.com/606959/168334199-bb99188d-51eb-414c-b5f7-f6d5eae7bc4e.mov

### Che version

next (development version)

### Steps to reproduce

Click [here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://gist.githubusercontent.com/l0rd/d6007812f2cc09ec76bdc529fbd5874f/raw/devfile.yaml?che-editor=che-incubator/che-code/insiders) (access to Che dogfooding instance is required).

### Expected behavior

VS Code is loaded once.

### Runtime

OpenShift

### Installation method

OperatorHub

### Release Notes Text

An extension was used to open the project folder at VS Code startup. The result was VS Code beeing loaded twice in the user browser. This is not necessary anymore as we use the VS Code startup parameter `--default-folder` that has been (re-)introduced recently.

**Comment by azatsarynnyy** [comment]
The work on this issue has been postponed. At least, until we fix https://github.com/eclipse/che/issues/21537

**Comment by l0rd** [comment]
We should try replacing [`?tkn=eclipse-che`](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L523) with `?folder=${PROJECT_SOURCE}`.

**Comment by azatsarynnyy** [comment]
> We should try replacing [`?tkn=eclipse-che`](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L523) with `?folder=${PROJECT_SOURCE}`.

@l0rd it's a good idea. But it works OOTB for `?folder=/projects` only. As VS Code doesn't resolve the environment variables passed through the URL query parameters.

Hardcoding `?folder=/projects` looks like the following, in Project Explorer:
![image](https://user-images.githubusercontent.com/1636395/191502371-f6e5ceae-7beb-46aa-8401-4dc169653f4d.png)

That's why we have [`che-on-start` extension](https://github.com/che-incubator/che-code/blob/d6291d3ede49eabd27e331ded40d465b7b5f0385/code/extensions/che-on-start/src/extension.ts#L65) that detects the right path VS Code should navigate to, depending on a few conditions.

As I see it, one of the options for fixing that problem would be to move that logic from the extension to [the entry point script](https://github.com/che-incubator/che-code/blob/d6291d3ede49eabd27e331ded40d465b7b5f0385/build/scripts/entrypoint-volume.sh#L76). In that case we could provide the correct path to the server side instead of redirecting the client.

**Comment by l0rd** [comment]
`${PROJECT_SOURCE}` should be resolved by the DevWorkspace operator

**Comment by l0rd** [comment]
So the proposal is to resolve `${PROJECT_SOURCE}` when setting a DevWorkspace `status.mainUrl`. 

For example, an endpoint with a path that references `$PROJECT_SOURCE` and with the attribute `type: main`:

```yaml
        endpoints:
          - name: che-code
            attributes:
              type: main
              cookiesAuthEnabled: true
              discoverable: false
              urlRewriteSupported: true
            targetPort: 3100
            exposure: public
            path: '?folder=${PROJECT_SOURCE}'
            secure: false
            protocol: https
```

should result in a DevWorkspace status where the `$PROJECT_SOURCE` has been resolved:

```yaml
"status": {
    "mainUrl": "https://workspace1bc9e32c0fcd4aed.apps.mloriedo-devworkspaces.devcluster.openshift.com/che-code/?folder=/projects/my-project",
    "message": "https://workspace1bc9e32c0fcd4aed.apps.mloriedo-devworkspaces.devcluster.openshift.com/che-code/?folder=/projects/my-project",
    "phase": "Running"
  }
```

I am adding the label `area/devworkspace-operator`.
