### ISSUE TITLE
Wrong message when the metadata.name of a devfile is absent

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21429]
### Describe the bug

I have a devfile like the following one:

```yaml
schemaVersion: 2.1.0
attributes:
  controller.devfile.io/storage-type: ephemeral
  controller.devfile.io/scc: container-build
components:
  - name: tilt-container
    container:
      image: quay.io/mloriedo/universal-developer-image:buildah
      memoryLimit: 1G
      memoryRequest: 256Mi
      cpuLimit: 200m
      cpuRequest: 30m
```

When I try to start a workspace from it I get the error:
> Failed to resolve a devfile. Failed to request factory resolver: Cannot read properties of undefined (reading 'generateName')

And I have no clue how I can fix this.

### Che version

next (development version)

### Steps to reproduce

Open this [link (dogfooding instance for Che maintainers only)](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/l0rd/tilt-example-java/tree/cc88c7f683e5ab50d36722e7b8366d871f6a73d4)

### Expected behavior

I would like to see a proper error message:

> `metadata.name` is missing from the Devfile. Please update it and retry.

### Screenshots

![image](https://user-images.githubusercontent.com/606959/170743180-c73926eb-bfb7-4c39-a7df-4bc1e2d9f15e.png)
