### ISSUE TITLE
`oauth-proxy` container in `che-gateway` pod throws error while setting up `eclipse-che` on k8s cluster

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21452]
### Summary

i have configured a k8s cluster in my virtual machine and i installed `eclipse-che` using below command. the installation completed, but i have explained the issue below
```
chectl server:deploy --che-operator-cr-patch-yaml=/home/ubuntu/kubeapps/che-operator-cr-patch.yaml --platform=k8s --installer=operator --debug --k8spoderrorrechecktimeout=480000 --domain=eclipseche.mangotree.click --k8spodreadytimeout=480000
```

i was able to follow [this documentation](https://dexidp.io/docs/kubernetes/) and integrate `dex` with an example-app successfully. Now i have to integrate `dex` and `eclipse-che`.

below screenshot shows the output after successfully installing eclipse-che in k8s cluster but without integrating `eclipse-che` with `dex`. 

But what steps should i follow to inregrate `eclipse-che` and `dex`?

(not real url)sample url is https://eclipseche.example.click:31931/ , https://eclipseche.example.click:31931/dashboard

![image](https://user-images.githubusercontent.com/10482177/172531873-790dbfc1-377b-4d7f-acfb-ae624991245f.png)

![image](https://user-images.githubusercontent.com/10482177/172532252-60f429d9-c743-4ee5-8119-a9e72d0f4b6c.png)

i investigated the error and found `che-gateway-766fdb7b54-pb8bz` pod in errored state. i investigated the state of the containers with-in the pod, `oauth-proxy` container in `che-gateway-766fdb7b54-pb8bz` pod is in errored state.

![image](https://user-images.githubusercontent.com/10482177/172538120-a9868d25-791a-459c-8ab8-110515bb2ac8.png)

<img width="988" alt="image" src="https://user-images.githubusercontent.com/10482177/172538275-16d839b9-2f49-42f5-99ab-4320035b3efe.png">

i checked the `oauth-proxy` container logs in `che-gateway-766fdb7b54-pb8bz` pod , it shows below error message. where should i update the information mentioned in the error message ?
Please help me on what should i do to fix this error?

<img width="704" alt="image" src="https://user-images.githubusercontent.com/10482177/172546732-c083aea9-6935-4719-b11e-ac507f9aeee3.png">

**Comment by l0rd** [comment]
@sparkoo may have an idea how to address that.
Adding issue to the list in #21304

**Comment by Divine1** [comment]
@sparkoo  please help me on this

**Comment by sparkoo** [comment]
you have to set these fields in CheCluster
```
spec:
  auth:
    identityProviderURL: 
    oAuthClientName: 
    oAuthSecret: 
```

**Comment by Divine1** [comment]
@sparkoo  could you please elaborate on that? where should i add it?


```
chectl server:deploy --che-operator-cr-patch-yaml=/home/ubuntu/kubeapps/che-operator-cr-patch.yaml --platform=k8s --installer=operator --debug --k8spoderrorrechecktimeout=480000 --domain=eclipseche.mangotree.click --k8spodreadytimeout=480000
```

**Comment by Divine1** [comment]
@sparkoo 

  could you please elaborate on that? where should i add it?

should i add it like below?
che-operator-cr-patch.yaml
```
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  database:
    chePostgresHostName: datasd4567fgg86wjj.com
    chePostgresPassword: rasdf5664sfrot123
    chePostgresUser: vmsdf3456sfv123
    externalDb: true
  auth:
    identityProviderURL: 
    oAuthClientName: 
    oAuthSecret: 
```


Also, after i add this configuration, which command shall i use to view the configuration in the k8scluster?

i apologize for asking the basic questions, please let me know..

```
chectl server:deploy --che-operator-cr-patch-yaml=/home/ubuntu/kubeapps/che-operator-cr-patch.yaml --platform=k8s --installer=operator --debug --k8spoderrorrechecktimeout=480000 --domain=eclipseche.mangotree.click --k8spodreadytimeout=480000
```
