### ISSUE TITLE
`error while installing eclipse-che on k8s` -  message: 0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims 

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21460]
### Summary

i'm using below command to install eclipse-che on k8s cluster
```
 chectl server:deploy --che-operator-cr-patch-yaml=/home/ubuntu/chefiles/che-operator-cr-patch.yaml --platform=k8s --installer=operator --debug --k8spoderrorrechecktimeout=480000 --domain=eclipseche.mangotree.click --k8spodreadytimeout=480000
```

OS
ubuntu 18.04 64 bit

chectl version
<img width="459" alt="image" src="https://user-images.githubusercontent.com/10482177/173419907-36e8e25d-f9c1-4aa1-8736-a58392ebb256.png">

che-operator-cr-patch.yaml 
```
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  database:
    chePostgresHostName: hostname.com
    chePostgresPassword: rdfot123
    chePostgresUser: vma123dfaf
    externalDb: true
  auth:
    identityProviderURL: https://dex.tree.click:32000
    oAuthClientName: eclipse-che
    oAuthSecret: mysecret

```
i received below error
<img width="1625" alt="image" src="https://user-images.githubusercontent.com/10482177/173419453-b71f392b-23fa-48e7-b6a5-2ea6d4f802d2.png">

the above error is due to issue in `postgres-7f58d6c56b-24cf7` pod in `eclipse-che` namespace
<img width="726" alt="image" src="https://user-images.githubusercontent.com/10482177/173495765-e27cd914-b5fd-44ca-9a45-b516e87c5d6c.png">

below is the status of `postgres-7f58d6c56b-24cf7` pod 
<img width="728" alt="image" src="https://user-images.githubusercontent.com/10482177/173495875-94b1e58f-e7da-4016-8c4f-8dc395cf6f28.png">

As i have added external postgress host details in `che-operator-cr-patch.yaml ` , why am i facing this error related to persistent volume on postgres?

please help me to fix this error

**Comment by Divine1** [comment]
@tolusha @sparkoo 

please help me on this

**Comment by tolusha** [comment]
@Divine1 

CheCluster API v2 has a different structure. Pls fine more here https://github.com/eclipse-che/che-operator/blob/0bc10490177c5d90867459e52ee7e1686cb97ff2/api/v2/checluster_types.go

```yaml
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  components:
    database:
      externalDb: true
      postgresHostName: hostname.com
      postgresPort: 3128
  networking:
    auth:
      identityProviderURL: https://dex.tree.click:32000
      oAuthClientName: eclipse-che
      oAuthSecret: mysecret
```

To store PostgreSQL credentials, create a secret `postgres-credentials` in `eclipse-che` namespace:
```yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
  name: postgres-credentials
  namespace: eclipse-che
type: Opaque
data:
  password: <BASE64_CONTENT>
  user: <BASE64_CONTENT>
```

**Comment by Divine1** [comment]
@tolusha thank you for this information. i will try this and share the feedback

**Comment by Divine1** [comment]
@tolusha 

there were 2 minor errors , i have detailed the fix below

error1

<img width="998" alt="image" src="https://user-images.githubusercontent.com/10482177/173565316-4e9b4845-1cfb-4293-b0f7-7910f8ac0f56.png">
i used below format to fix the above error

```
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: eclipse-che
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
type: Opaque
data:
  password: cfddfTIz
  user: dfdfdfIz

```

error2

<img width="1685" alt="image" src="https://user-images.githubusercontent.com/10482177/173565269-9910e94f-29cf-40f7-9897-2717d8ee717c.png">

i used below format to fix the above error 
```
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  components:
    database:
      externalDb: true
      postgresHostName: hostname.com
      postgresPort: "5432"
  networking:
    auth:
      identityProviderURL: https://dex.tree.click:32000
      oAuthClientName: eclipse-che
      oAuthSecret: sdfdf
```
