### ISSUE TITLE
chectl server:deploy platform=k8s command got stuck at step `Wait for Cert Manager`  due to `forbidden: PodSecurityPolicy: unable to admit pod`

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21469]
### Summary

i'm trying to install eclipse-che in a  k8s cluster within an organization network , below is the command i used

```
chectl server:deploy --che-operator-cr-patch-yaml=/Users/divine/Documents/office_tasks/TAP-4540/terraformCheJun14/eclipsecheFiles/che-operator-cr-patch.yaml --platform=k8s --installer=operator --debug --k8spoderrorrechecktimeout=600000 --domain=eclipseche-dchelladurai-chejune15.abc.def.com --k8spodreadytimeout=600000
```
chectl version
<img width="451" alt="image" src="https://user-images.githubusercontent.com/10482177/173863370-390ef33c-8077-4c52-839e-3eb41d3aad05.png">

the command was stuck at `Wait for Cert Manager` and failed

<img width="930" alt="image" src="https://user-images.githubusercontent.com/10482177/173862567-8f0b2f77-9c34-4d9c-8c1a-d2f16a558c8d.png">

below is the log message
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/10482177/173862769-b914df85-1142-4b0d-9a75-fe4774ee7311.png">

i have no idea about the reason for this behavior during installation, please let me know how to debug the issue.

**Comment by Divine1** [comment]
@tolusha  @sparkoo  please help me on this issue if you could.

**Comment by Divine1** [comment]
this is some issue with PodSecurityPolicy while installing `cert-manager.yaml`
```
 kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.yaml
```

<img width="712" alt="image" src="https://user-images.githubusercontent.com/10482177/173870456-8dd9cda7-a601-43a9-8e2c-fabffbcaa4e7.png">


What kind of permission should be allowed for this installation to be successful?  i'm a newbie in this , so any detail will be very helpful for me

**Comment by Divine1** [comment]
i applied below configuration, this fixed the `PodSecurityPolicy` error
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-tkg-admin-privileged-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:vmware-system-privileged
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
```
