### ISSUE TITLE
Eclipse Che doesn't check IDE preferences when initializing a project via a zip file

### ISSUE THREAD

**Issue by vatsal-uppal-1997** [eclipse/che#21500]
### Describe the bug

While I was trying to create a workspace from a devfile that refers to a zip file for the project location, I observed that Eclipse Che does not respect the user IDE preference as specified in the "che-editor.yaml" file but instead defaults to "Che Theia" IDE.

### Che version

next (development version)

### Steps to reproduce

1. Create a devfile as such:

```
schemaVersion: 2.1.0
metadata:
  name: test
projects:
  - name: test
    zip:
      location: 'http://192.168.1.101:2020/test.zip'
components: []
```

2. Make sure the project in the zip file follows the following directory structure:

```
test.zip
    | .che
        | che-editor.yaml (Should contain appropriate IDE definition or an IDE plugin ID)
    | file1
    | file2
```

3. Generate a workspace through a factory URL:

```
https://192.168.1.120.nip.io#<path to your devfile>
```

4. Once the workspace is up and running, verify if the IDE being used is as per what was specified in the "che-editor.yaml" file.

### Expected behavior

Eclipse Che should look for IDE definitions in the "che-editor.yaml" file no matter if the project is being cloned from git or being extracted from a zip file.

Relevant Docs:

https://www.eclipse.org/che/docs/stable/end-user-guide/selecting-an-ide/

### Runtime

minikube

### Installation method

chectl/next

### Environment

Windows
