### ISSUE TITLE
Create acceptance tests to go through all devfile samples and all editors using API

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#21514]
### Is your task related to a problem? Please describe

There are tens of devfile samples and several supported editors which are not covered by automated acceptance tests.

### Describe the solution you'd like

Samples in upstream and with supported editors have to be covered by automated tests:
- open workspaces in certain editor;
- execute each available command described in devfile from within workspace.

The goal is to run devfile API tests instead of GUI tests with complex scenario, a.k.a Happy Path tests.

**Comment by nallikaea** [comment]
@dmytro-ndp @l0rd colleagues, could you, please, update this description?

**Comment by dmytro-ndp** [comment]
@nallikaea : done.

**Comment by l0rd** [comment]
- Should be used as a PR check for [UDI](https://github.com/devfile/developer-images/)
- The list of samples should be grabbed automatically from [the devfile registry](https://github.com/eclipse-che/che-devfile-registry/tree/main/devfiles) main branch
- The PR Check should be reusable for other repos such as the che devfile registry and cncf devfile registry
- The core test should be:
  ```log
  1. Take in input a git repository URL or a devfile raw URL
  2. Transform the devfile in a DevWorkspace + VS Code DevWorkspaceTemplate
  3. Apply the DevWorkspace and wait until it's started
  4. Verify that the project has been cloned successfully
  5. Execute build commands and verify that they complete successfully
  6. Execute run/debug commands and verify the lifeness probe
  ```
- Build commands are commands with [`group.kind: build`](https://devfile.io/docs/2.2.0/adding-a-command-group):
  ```yaml
  commands:
    - id: build-project
      exec:
        commandLine: JAVA_HOME=$JAVA_HOME_8 mvn clean install
        component: tools
        workingDir: "${PROJECT_SOURCE}"
        group:
          kind: build
  ```
- Run/debug commands are commands that and require a livenessProbe attribute such as:
  ```yaml
    commands:
      - id: run-services
        attributes:
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              httpHeaders:
              - name: Custom-Header
                value: Awesome
            initialDelaySeconds: 3
            periodSeconds: 3
        exec:
          commandLine: JAVA_HOME=$JAVA_HOME_8 mvn spring-boot:run -DskipTests
          component: tools
          workingDir: "${PROJECT_SOURCE}"
```
- Commands that do not have `group.kind: build` and do not have `attributs.livenessProbe` should be skipped
