### ISSUE TITLE
unable to comprehend the value shown as cpu metrics in theia-ide

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21518]
### Summary

in theia-ide, cpu metrics shows `Used 127895000m (used) / 500m (limited)` . is the  value shown here correct or incorrect?

 i'm not able to comprehend the meaning of this value. i was expecting the value to be lessthan 500m. 

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/10482177/176251222-c874819d-3c33-4f8d-92c5-49d4840aaa43.png">

My understanding is 500m implies 0.5core cpu

**Comment by benoitf** [comment]
cc @svor

**Comment by Divine1** [comment]
@svor  thank you for the response

i used below devfile.yaml , but i have removed the source code repo and image information.
i used a java based project here(version jdk8). is this information sufficient?
```
schemaVersion: 2.1.0
metadata:
  name: cbfsel-repo
projects:
  - name: cbfsel-project
    git:
      checkoutFrom:
        revision: master
      remotes:
        origin: https://gitlab.org.com/cbf-sel.git
components:
  - container:
      image: 'internalOrganizationRepoDockerImage:jdk8img'
      memoryLimit: 4G
      endpoints:
        - exposure: public
          name: 4444-tcp
          protocol: tcp
          targetPort: 4444
        - exposure: public
          name: 5900-tcp
          protocol: tcp
          targetPort: 5900
        - exposure: public
          name: 7900-http
          protocol: http
          targetPort: 7900
          secure: true
      volumeMounts:
        - name: m2volume
          path: /home/user/.m2
    name: javacontainer
  - name: m2volume
    volume:
      size: 4G
commands:
  - exec:
      commandLine: mvn clean package -DskipTests
      component: javacontainer
      group:
        isDefault: true
        kind: build
      label: 'build project using maven'
      workingDir: '${PROJECT_SOURCE}'
    id: mvnpackage

```
