### ISSUE TITLE
Container has state CrashLoopBackOff

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21535]
### Summary

i created a docker image using below `Dockerfile`

When i add it to my `devfile.yaml`,i receive `Container has state CrashLoopBackOff` error
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/10482177/177731559-9b246bea-656c-49d9-8ba4-3110fa78eee6.png">

```
FROM ubuntu:focal-20220531
LABEL authors="Divine <cdivine304@gmail.com>"

#================================================
# Customize sources for apt-get
#================================================
RUN  echo "deb http://archive.ubuntu.com/ubuntu focal main universe\n" > /etc/apt/sources.list \
  && echo "deb http://archive.ubuntu.com/ubuntu focal-updates main universe\n" >> /etc/apt/sources.list \
  && echo "deb http://security.ubuntu.com/ubuntu focal-security main universe\n" >> /etc/apt/sources.list

# No interactive frontend during docker build
ENV DEBIAN_FRONTEND=noninteractive \
    DEBCONF_NONINTERACTIVE_SEEN=true

#========================
# Miscellaneous packages
# Includes minimal runtime used for executing non GUI Java programs
#========================
RUN apt-get -qqy update \
  && apt-get -qqy install \
    bzip2 \
    ca-certificates \
    tzdata \
    sudo \
    unzip \
    wget \
    jq \
    curl \
    supervisor \
    gnupg2 \
    xvfb \
    maven git openjdk-8-jdk \
  && update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/* 

#===================
# Timezone settings
# Possible alternative: https://github.com/docker/docker/issues/3359#issuecomment-32150214
#===================
ENV TZ "UTC"
RUN echo "${TZ}" > /etc/timezone \
  && dpkg-reconfigure --frontend noninteractive tzdata


ENTRYPOINT ["/bin/bash"]
```

 i linked the above dockerimage in below `devfile.yaml`

```
schemaVersion: 2.1.0
metadata:
  name: cbfsel-repo
projects:
  - name: cbfsel-project
    git:
      checkoutFrom:
        revision: master
      remotes:
        origin: https://gitlab.eng.com/dchelladurai/cbf-sel.git
components:
  - container:
      image: 'artfact-prd.com/qedocker/eclipseche/customopenjdk8:v2'
      memoryLimit: 4G
      volumeMounts:
        - name: m2volume
          path: /home/user/.m2
    name: javacontainer
  - name: m2volume
    volume:
      size: 4G
commands:
  - exec:
      commandLine: mvn clean package -DskipTests
      component: javacontainer
      group:
        isDefault: true
        kind: build
      label: 'build project using maven'
      workingDir: '${PROJECT_SOURCE}'
    id: mvnpackage

```

please let me know how to fix this error

**Comment by tolusha** [comment]
I might mistaken but Dockerfile should look like
```
....
ENTRYPOINT ["/bin/bash"]
CMD ["tail", "-f", "/dev/null"]
```

**Comment by Divine1** [comment]
> I might mistaken but Dockerfile should look like below, to never stop
> 
> ```dockerfile
> ....
> ENTRYPOINT ["/bin/bash"]
> CMD ["tail", "-f", "/dev/null"]
> ```

@tolusha thank you for the response.

i will try that approach and share the feedback in couple of minutes

**Comment by Divine1** [comment]
@tolusha it didnot work, i received the same error

**Comment by tolusha** [comment]
Confirm, something wrong with the base image `ubuntu:focal-20220531`
@svor Do you have any ideas?

**Comment by amisevsk** [comment]
One way to test this more quickly (without rebuilding the image) is to use the `command` and `args` fields in the devfile to override the entrypoint/command in the Dockerfile. I suspect that the correct combo would be something like
```dockerfile
ENTRYPOINT ["/bin/bash"]
CMD ["-c", "tail", "-f", "/dev/null"]
```
or
```
ENTRYPOINT ["tail", "-f", "/dev/null"]
```
Could you try adding
```yaml
        command:
        - tail
        - -f
        - /dev/null
```
to the `name: javacontainer` container component so we can check if it's an image issue or an entrypoint issue?

To go more into depth: this would also disable the default entrypoint in the image in case that's necessary to your use case. Typically, containers we build to run in workspaces have 
```dockerfile
ENTRYPOINT ["/bin/entrypoint.sh"]
CMD ["tail", "-f", "/dev/null"]
```
where the entrypoint is similar to
```shell
#!/bin/bash

# whatever preparation is necessary

# Execute whatever's in the CMD (called args in k8s)
exec "$@"
```

For example, in the universal developer image, we use [this](https://github.com/devfile/developer-images/blob/fbb8fc0a61a6c4e766c3f687512aae2a31971b76/base/ubi8/Dockerfile#L90-L91) in the dockerfile along with this entrypoint: https://github.com/devfile/developer-images/blob/main/base/ubi8/entrypoint.sh

**Comment by Divine1** [comment]
@amisevsk 
i have updated my `devfile.yaml` as you have mentioned. Now my container gets loaded in workspace successfully. thank you for this.

but i'm facing below error inside the terminal. by default i need `/bin/bash` shell to appear but its not the case as shown in below screenshot. please let me know what am i missing here. i have attached the `Dockerfile` i used to create the container   here
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/10482177/178097799-c61881ee-9208-45cc-9e04-cc94600cac49.png">



`devfile.yaml`
```
schemaVersion: 2.1.0
metadata:
  name: cbfsel-repo
projects:
  - name: cbfsel-project
    git:
      checkoutFrom:
        revision: master
      remotes:
        origin: https://gitlab.eng.vmware.com/dchelladurai/cbf-sel.git
components:
  - container:
      image: 'artfact-prd.com/qedocker/eclipseche/customopenjdk8:v6'
      memoryLimit: 4G
      command:
      - tail
      - -f
      - /dev/null
      volumeMounts:
        - name: m2volume
          path: /home/projectuser/.m2
    name: javacontainer
  - name: m2volume
    volume:
      size: 4G
commands:
  - exec:
      commandLine: mvn clean package -DskipTests
      component: javacontainer
      group:
        isDefault: true
        kind: build
      label: 'build project using maven'
      workingDir: '${PROJECT_SOURCE}'
    id: mvnpackage
```


`Dockerfile`

```
FROM ubuntu:focal-20220531
LABEL authors="Divine <dchelladurai@vmware.com>"

#================================================
# Customize sources for apt-get
#================================================
RUN  echo "deb http://archive.ubuntu.com/ubuntu focal main universe\n" > /etc/apt/sources.list \
  && echo "deb http://archive.ubuntu.com/ubuntu focal-updates main universe\n" >> /etc/apt/sources.list \
  && echo "deb http://security.ubuntu.com/ubuntu focal-security main universe\n" >> /etc/apt/sources.list

# No interactive frontend during docker build
ENV DEBIAN_FRONTEND=noninteractive \
    DEBCONF_NONINTERACTIVE_SEEN=true

#========================
# Miscellaneous packages
# Includes minimal runtime used for executing non GUI Java programs
#========================
RUN apt-get -qqy update \
  && apt-get -qqy install \
    bzip2 \
    ca-certificates \
    tzdata \
    sudo \
    unzip \
    wget \
    jq \
    curl \
    supervisor \
    gnupg2 \
    xvfb \
    maven git openjdk-8-jdk \
  && update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/* 

#===================
# Timezone settings
# Possible alternative: https://github.com/docker/docker/issues/3359#issuecomment-32150214
#===================
ENV TZ "UTC"
RUN echo "${TZ}" > /etc/timezone \
  && dpkg-reconfigure --frontend noninteractive tzdata

RUN groupadd projectuser \
         --gid 1201 \
  && useradd projectuser \
         --create-home \
         --gid 1201 \
         --shell /bin/bash \
         --uid 1200 \
  && usermod -a -G sudo projectuser \
  && echo 'ALL ALL = (ALL) NOPASSWD: ALL' >> /etc/sudoers \
  && echo 'projectuser:secret' | chpasswd
ENV HOME=/home/projectuser

USER projectuser
RUN ["/bin/bash", "-c", "echo I am using bash"]

```

**Comment by Divine1** [comment]
@amisevsk 

i updated the `Dockerfile` as per your suggestion. Now the container is loaded by `eclipse-che` workspace successfully.
i have attached the details below. Thank you for the inputs.


`Dockerfile`

```
FROM ubuntu:focal-20220531
LABEL authors="Divine <dchelladurai@vmware.com>"

#================================================
# Customize sources for apt-get
#================================================
RUN  echo "deb http://archive.ubuntu.com/ubuntu focal main universe\n" > /etc/apt/sources.list \
  && echo "deb http://archive.ubuntu.com/ubuntu focal-updates main universe\n" >> /etc/apt/sources.list \
  && echo "deb http://security.ubuntu.com/ubuntu focal-security main universe\n" >> /etc/apt/sources.list

# No interactive frontend during docker build
ENV DEBIAN_FRONTEND=noninteractive \
    DEBCONF_NONINTERACTIVE_SEEN=true

#========================
# Miscellaneous packages
# Includes minimal runtime used for executing non GUI Java programs
#========================
RUN apt-get -qqy update \
  && apt-get -qqy install \
    bzip2 \
    ca-certificates \
    tzdata \
    sudo \
    unzip \
    wget \
    jq \
    curl \
    supervisor \
    gnupg2 \
    xvfb \
    maven git openjdk-8-jdk \
  && update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/* 

#===================
# Timezone settings
# Possible alternative: https://github.com/docker/docker/issues/3359#issuecomment-32150214
#===================
ENV TZ "UTC"
RUN echo "${TZ}" > /etc/timezone \
  && dpkg-reconfigure --frontend noninteractive tzdata


COPY --chown=0:0 entrypoint.sh /
RUN mkdir -p /home/user && chgrp -R 0 /home && \
    # Copy the global git configuration to user config as global /etc/gitconfig
    #  file may be overwritten by a mounted file at runtime
    chmod -R g=u /etc/passwd /etc/group /home && \
    chmod +x /entrypoint.sh

USER 10001
ENV HOME=/home/user
WORKDIR /projects
ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["tail", "-f", "/dev/null"]
```

`entrypoint.sh` is copied from [here](https://github.com/devfile/developer-images/blob/fbb8fc0a61a6c4e766c3f687512aae2a31971b76/base/ubi8/entrypoint.sh)


`devfile.yaml`

```
schemaVersion: 2.1.0
metadata:
  name: cbfsel-repo
projects:
  - name: cbfsel-project
    git:
      checkoutFrom:
        revision: master
      remotes:
        origin: https://gitlab.eng.com/dchelladurai/cbf-sel.git
components:
  - container:
      image: 'artfact-prd.com/qedocker/eclipseche/customopenjdk8:v10'
      memoryLimit: 4G
      volumeMounts:
        - name: m2volume
          path: /home/user/.m2
    name: javacontainer
  - name: m2volume
    volume:
      size: 4G
commands:
  - exec:
      commandLine: mvn clean package -DskipTests
      component: javacontainer
      group:
        isDefault: true
        kind: build
      label: 'build project using maven'
      workingDir: '${PROJECT_SOURCE}'
    id: mvnpackage

```
