### ISSUE TITLE
Che-Code auto-opened terminal doesn't work (for `main` branch)

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21537]
### Describe the bug

The terminal widget that's opened automatically on Che-Code start is not connected to machine-exec.
![image](https://user-images.githubusercontent.com/1636395/177855676-3ab42dad-d1b3-468d-86cd-23d69ee62879.png)

Note, that the terminal opened manually (from the dropdown menu) works as expected:
![image](https://user-images.githubusercontent.com/1636395/177856003-7ccf45b6-c12f-4e67-9f41-13aacc93004e.png)

### Che version

next (development version)

### Steps to reproduce

Start a workspace with Che-Code editor.

### Expected behavior

The auto-opened terminal should be ready to use.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Linux

### Eclipse Che Logs

```shell
In the editor container:

time="2022-07-07T19:13:47Z" level=error msg="Unable to initialize terminal. Cause: container with name Terminal was not found."
```
```


### Additional context

_No response_

**Comment by l0rd** [comment]
The other problem is that when opening from the dropdown the lines are truncated:

![truncated-lines](https://user-images.githubusercontent.com/606959/177883733-07fc5e46-11fa-4bae-9556-981dba0b6cb1.gif)

**Comment by l0rd** [comment]
And I have also [this issue](https://github.com/eclipse/che/issues/21538)

**Comment by pdfruth** [comment]
I am impacted by this as well.
Things were working well until about 6-8 (or so) days ago, when @l0rd explained how to enable the VScode editor [here](https://github.com/eclipse/che/issues/21390#issuecomment-1170785241).

Is there any way to work around this until a resolution is found?
For example, Is there a way to explicitly set the image tag on the `id: che-incubator/che-code/insiders` in the `che-editor.yaml` file?
Looking at the image tags at https://quay.io/repository/che-incubator/che-code?tab=tags I can see that this image was tagged as follows about 8 days ago, when things were working;
quay.io/che-incubator/che-code:insiders-694ef6e

**Comment by pdfruth** [comment]
Answering my own question

> Is there any way to work around this until a resolution is found?
For example, Is there a way to explicitly set the image tag on the id: che-incubator/che-code/insiders in the che-editor.yaml file?

I have reconfigured my project's `.che/che-editor.yaml` file from this;
```
id: che-incubator/che-code/insiders
registryUrl: https://eclipse-che.github.io/che-plugin-registry/main/v3
```
to this;
```
reference: https://<mygist>/che-editor.yaml
```

And the file at `https://<mygist>/che-editor.yaml` contains this;
Notice: the explicit setting of `image: quay.io/che-incubator/che-code:insiders-694ef6e` refers to a previous version of the `quay.io/che-incubator/che-code` image, tagged approximately a day or so before the issue being reported above began to manifest
```
schemaVersion: 2.1.0
metadata:
  name: che-code
commands:
  - id: init-container-command
    apply:
      component: che-code-injector
events:
  preStart:
    - init-container-command
components:
  - name: che-code-runtime-description
    container:
      image: quay.io/devfile/universal-developer-image@sha256:53cec58dd190dd1e06100478ae879d7c28abd8fc883d5fdf5be3eb6e943fe5e7
      command:
        - /checode/entrypoint-volume.sh
      volumeMounts:
        - name: checode
          path: /checode
      memoryLimit: 1024Mi
      memoryRequest: 256Mi
      cpuLimit: 500m
      cpuRequest: 30m
      endpoints:
        - name: che-code
          attributes:
            type: main
            cookiesAuthEnabled: true
            discoverable: false
            urlRewriteSupported: true
          targetPort: 3100
          exposure: public
          path: '?tkn=eclipse-che'
          secure: false
          protocol: https
        - name: code-redirect-1
          attributes:
            discoverable: false
            urlRewriteSupported: true
          targetPort: 13131
          exposure: public
          protocol: http
        - name: code-redirect-2
          attributes:
            discoverable: false
            urlRewriteSupported: true
          targetPort: 13132
          exposure: public
          protocol: http
        - name: code-redirect-3
          attributes:
            discoverable: false
            urlRewriteSupported: true
          targetPort: 13133
          exposure: public
          protocol: http
    attributes:
      app.kubernetes.io/component: che-code-runtime
      app.kubernetes.io/part-of: che-code.eclipse.org
  - name: checode
    volume: {}
  - name: che-code-injector
    container:
      image: quay.io/che-incubator/che-code:insiders-694ef6e
      command:
        - /entrypoint-init-container.sh
      volumeMounts:
        - name: checode
          path: /checode
      memoryLimit: 128Mi
      memoryRequest: 32Mi
      cpuLimit: 500m
      cpuRequest: 30m
```
