### ISSUE TITLE
On minikube, not able to start a workspace with che installed with chectl next

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#21557]
### Describe the bug

On a minikube cluster, I'm not able to start a workspace with Che installed with chectl next due to the workspace pod terminating:
![image](https://user-images.githubusercontent.com/83611742/179563469-7c699d3f-9c2c-4fcc-a5f3-48d858b9138f.png)

I'm not able to reproduce this issue on an OpenShift environment.

### Che version

next (development version)

### Steps to reproduce

1. Start a minikube cluster:
```
minikube start --addons=ingress --vm=true --cpus=4 --memory=16384
```

2. Deploy che with [chectl next channel](https://github.com/che-incubator/chectl#installation):
```
chectl server:deploy -p minikube
```

3. After installation is complete, open the Che dashboard and start any sample project.

4. The workspace does not start. The workspace pod terminates due to a failing init container: `remote-runtime-injector`:
```
$ kubectl get event --namespace admin-che --field-selector involvedObject.name=workspace63360a48062b4ea8-b548f9cd8-p8nqp
LAST SEEN   TYPE      REASON          OBJECT                                          MESSAGE
5s          Normal    Scheduled       pod/workspace63360a48062b4ea8-b548f9cd8-p8nqp   Successfully assigned admin-che/workspace63360a48062b4ea8-b548f9cd8-p8nqp to minikube
4s          Normal    Pulling         pod/workspace63360a48062b4ea8-b548f9cd8-p8nqp   Pulling image "quay.io/eclipse/che-theia-endpoint-runtime-binary:next"
4s          Normal    Pulled          pod/workspace63360a48062b4ea8-b548f9cd8-p8nqp   Successfully pulled image "quay.io/eclipse/che-theia-endpoint-runtime-binary:next" in 428.49452ms
3s          Normal    Created         pod/workspace63360a48062b4ea8-b548f9cd8-p8nqp   Created container remote-runtime-injector
3s          Normal    Started         pod/workspace63360a48062b4ea8-b548f9cd8-p8nqp   Started container remote-runtime-injector
3s          Normal    Killing         pod/workspace63360a48062b4ea8-b548f9cd8-p8nqp   Stopping container remote-runtime-injector
1s          Normal    Killing         pod/workspace63360a48062b4ea8-b548f9cd8-p8nqp   Stopping container remote-runtime-injector
```

### Expected behavior

The workspace pod should not terminate. The workspace should start and the editor should open.

### Runtime

minikube

### Installation method

chectl/next

### Environment

macOS

**Comment by l0rd** [comment]
@dkwon17 do you have the `remote-runtime-injector` container logs?

**Comment by dkwon17** [comment]
@l0rd this was the logs I was able to get before the the pod was gone (I've set `controller.devfile.io/debug-start: "true"` for the devworkspace. [related doc](https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.adoc#debugging-a-failing-workspace)):
```
remote-runtime-injector /plugins/bash-debug-0.3.9.vsix
remote-runtime-injector /plugins/mads-hartmann.bash-ide-vscode-1.10.2.vsix
remote-runtime-injector VSIX files are already in folder /plugins, skipping the download
```

**Comment by dkwon17** [comment]
I have been able to reproduce this issue on chectl stable version (7.50) on a minikube cluster, but with one more step:

Before starting a workspace, create this config map on the user namespace:
```
cat << EOF | kubectl apply -n admin-che -f -
kind: ConfigMap
apiVersion: v1
metadata:
  name: my-config
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-configmap: 'true'
  annotations:
    controller.devfile.io/mount-as: env
data:
  TESTENV: test
EOF
```

(the above assumes that `admin-che` is the user namespace)


Multiple workpsace pods will start up and terminate one by one. But, after deleting the configmap above the workspace pod will start up successfully.

**Comment by dkwon17** [comment]
It looks like the cause of this issue in Che installed via chectl next, is because this merged PR for che-operator: https://github.com/eclipse-che/che-operator/pull/1443 creates a similar config map in the user namespace: `che-idle-settings`:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: che-idle-settings
  namespace: {USERNAMESPACE}
  labels:
    app.kubernetes.io/component: user-settings
    app.kubernetes.io/name: eclipse-che
    app.kubernetes.io/part-of: che.eclipse.org
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-configmap: 'true'
  annotations:
    controller.devfile.io/mount-as: env
data:
  SECONDS_OF_DW_INACTIVITY_BEFORE_IDLING: '1800'
  SECONDS_OF_DW_RUN_BEFORE_IDLING: '-1'

```
