### ISSUE TITLE
The workspace status changed unexpectedly to "Stopped"

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21558]
### Summary

i'm receiving `The workspace status changed unexpectedly to "Stopped"` message, i have no idea what is the reason for this issue, please help me to debug this issue. it was working fine till yesterday

below is the error message shown in dashboard
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/10482177/179664252-e53b5625-07c9-4137-820d-ff0c8b9be5f0.png">

below is the pod-workspace log
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/10482177/179665159-08aca782-5127-4a10-b090-5c1d909d2b77.png">

below is the devfile.yaml which i used to create the workspace
```
schemaVersion: 2.1.0
metadata:
  name: cbfsel-repo
projects:
  - name: cbfsel-project
    git:
      checkoutFrom:
        revision: master
      remotes:
        origin: https://gitlab.eng.vmware.com/dchelladurai/cbf-sel.git
components:
  - container:
      image: 'artfact-prd.vmware.com:5001/qedocker/eclipseche/customopenjdk8:v10'
      memoryLimit: 4G
      volumeMounts:
        - name: m2volume
          path: /home/user/.m2
    name: javacontainer
  - container:
      image: 'artfact-prd.vmware.com:5001/qedocker/eclipseche/selenium/standalone-chrome:4.3.0-20220706'
      memoryLimit: 4G
      endpoints:
        - exposure: public
          name: 4444-tcp
          protocol: tcp
          targetPort: 4444
        - exposure: public
          name: 5900-tcp
          protocol: tcp
          targetPort: 5900
        - exposure: public
          name: 7900-http
          protocol: http
          targetPort: 7900
          secure: true
    name: chromecontainer
  - name: m2volume
    volume:
      size: 4G
commands:
  - exec:
      commandLine: mvn clean package -DskipTests
      component: javacontainer
      group:
        isDefault: true
        kind: build
      label: 'build project using maven'
      workingDir: '${PROJECT_SOURCE}'
    id: mvnpackage
```

**Comment by Divine1** [comment]
@l0rd  thank you for the response

now i received a different error message. i have attached logs below
<img width="1556" alt="image" src="https://user-images.githubusercontent.com/10482177/179749883-945676d2-6f61-496b-9b39-880b675e5c1d.png">



`kubectl logs -f deploy/devworkspace-controller-manager -n devworkspace-controller -c devworkspace-controller`
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/10482177/179749788-438f3b9a-05bd-4573-a28b-c6160b0be134.png">
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/10482177/179749849-187f1959-f820-4c19-8055-627e79287803.png">



`kubectl get events -n divine-chelladurai-che-pmjg9u -w`
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/10482177/179749485-d8ddd9fa-1e3d-44bb-a679-b284aba0e01c.png">

`DW="cbfsel-repo"; kubectl logs -f -l controller.devfile.io/devworkspace_name="${DW}" --all-containers --max-log-requests 10 -n divine-chelladurai-che-pmjg9u`
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/10482177/179749958-5385c14a-46f1-458a-806b-904a15535c8d.png">


i'm looking forward for your suggestions

**Comment by Divine1** [comment]
@l0rd   thank you for the response



chectl version
<img width="535" alt="image" src="https://user-images.githubusercontent.com/10482177/179788246-16cfa5d9-19ce-463b-b1f0-782587e6847a.png">


now i received a different error message. i have attached logs below
<img width="1556" alt="image" src="https://user-images.githubusercontent.com/10482177/179749883-945676d2-6f61-496b-9b39-880b675e5c1d.png">



`kubectl logs -f deploy/devworkspace-controller-manager -n devworkspace-controller -c devworkspace-controller`
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/10482177/179749788-438f3b9a-05bd-4573-a28b-c6160b0be134.png">
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/10482177/179749849-187f1959-f820-4c19-8055-627e79287803.png">



`kubectl get events -n divine-chelladurai-che-pmjg9u -w`
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/10482177/179754351-292cf799-eee4-4efb-b514-d792f5e082d2.png">


`DW="cbfsel-repo"; kubectl logs -f -l controller.devfile.io/devworkspace_name="${DW}" --all-containers --max-log-requests 10 -n divine-chelladurai-che-pmjg9u`
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/10482177/179749958-5385c14a-46f1-458a-806b-904a15535c8d.png">


i'm looking forward for your suggestions

**Comment by l0rd** [comment]
It looks like there is no PersistentVolume in your cluster that matches the PersistentVolumeClaim created by Che, hence the PVC remains unbound. You may want to decrease the `m2volume` size in your devfile (or remove the size at all) OR you can create a new PV matching the PVC size.

**Comment by Divine1** [comment]
@l0rd 

The `PVC` status shows it is Bounded to `PV` and `Storageclass` 

PersistentVolumeClaim
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/10482177/179810814-f814b597-7b30-47c5-ba3a-df747aecef50.png">

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: csi.vsphere.vmware.com
    volumehealth.storage.kubernetes.io/health: accessible
    volumehealth.storage.kubernetes.io/health-timestamp: Tue Jul 19 12:27:08 UTC 2022
  creationTimestamp: "2022-07-19T12:23:39Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: claim-devworkspace
  namespace: divine-chelladurai-che-pmjg9u
  resourceVersion: "15076395"
  uid: e2c47772-dfd2-42b1-865f-2098582d795e
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: vmc-workload-storage-policy-cluster-1
  volumeMode: Filesystem
  volumeName: pvc-e2c47772-dfd2-42b1-865f-2098582d795e
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
```


PersistentVolume
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/10482177/179810878-e6391a6a-7dfb-4a3c-a714-6a7429fbb238.png">

```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: csi.vsphere.vmware.com
  creationTimestamp: "2022-07-19T12:23:41Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/csi-vsphere-vmware-com
  name: pvc-e2c47772-dfd2-42b1-865f-2098582d795e
  resourceVersion: "15077963"
  uid: a8b048e7-a823-4b7b-b666-ea4b500f2510
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: claim-devworkspace
    namespace: divine-chelladurai-che-pmjg9u
    resourceVersion: "15075219"
    uid: e2c47772-dfd2-42b1-865f-2098582d795e
  csi:
    driver: csi.vsphere.vmware.com
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1655847079993-8081-csi.vsphere.vmware.com
      type: vSphere CNS Block Volume
    volumeHandle: df63f994-eaeb-47a8-ac23-0e222cac3b10-e2c47772-dfd2-42b1-865f-2098582d795e
  persistentVolumeReclaimPolicy: Delete
  storageClassName: vmc-workload-storage-policy-cluster-1
  volumeMode: Filesystem
status:
  phase: Bound
```


StorageClass
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/10482177/179810922-806bfa30-6807-4fd3-9f4c-05db719e7ec5.png">

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2022-06-15T05:57:58Z"
  labels:
    isSyncedFromSupervisor: "yes"
  name: vmc-workload-storage-policy-cluster-1
  resourceVersion: "161"
  uid: 3e85fd47-ad27-4c61-bca5-44ef2b8410c7
parameters:
  svStorageClass: vmc-workload-storage-policy-cluster-1
provisioner: csi.vsphere.vmware.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Comment by Divine1** [comment]
@l0rd 

i ran this command 
`export DW="cbfsel-repo1"; kubectl logs -f -l controller.devfile.io/devworkspace_name="${DW}" --all-containers --max-log-requests 10 -n divine-chelladurai-che-pmjg9u`

i'm able to see couple of errors here, does it have anything to do with my issue?
<img width="1531" alt="image" src="https://user-images.githubusercontent.com/10482177/179816021-790ce091-0d53-4846-bd7d-545c5f9136b1.png">


<img width="1651" alt="image" src="https://user-images.githubusercontent.com/10482177/179816057-59f43291-34e4-48a6-bf8c-671cbc6b7778.png">

**Comment by l0rd** [comment]
@AObuchow do you have any clue about the PVC problem above?

**Comment by Divine1** [comment]
@l0rd 

i used this devfile.yaml (https://github.com/Divine1/demonodejs.git) to create workspace. . The `controller.devfile.io/devworkspace_name` still throws an error. please let me know what might be the issue

`export DW="nodejs-web-app-github"; kubectl logs -f -l controller.devfile.io/devworkspace_name="${DW}" --all-containers --max-log-requests 10 -n divine-chelladurai-che-pmjg9u`
<img width="1647" alt="image" src="https://user-images.githubusercontent.com/10482177/179882246-0ee6898b-222c-4ff6-9e75-efce1228d1cf.png">

**Comment by Divine1** [comment]
i did `chectl server:delete` and `chectl server:deploy` with my updated checluster policy to reduce the pvc claim to 5gi from 10gi [doc link](https://www.eclipse.org/che/docs/next/administration-guide/advanced-configuration-options-for-the-che-server-component/#_che_infra_kubernetes_pvc_quantity)


but the pvc claim is still 10gi when i start a new workspace. 

```
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  components:
    cheServer:
      extraProperties:
        CHE_INFRA_KUBERNETES_WORKSPACE__START__TIMEOUT__MIN: "15"
        CHE_INFRA_KUBERNETES_PVC_QUANTITY: "5Gi"
    database:
      externalDb: true
      postgresHostName: sc2-10-186-67-195.eng.vmware.com
      postgresPort: "5432"
  networking:
    auth:
      identityProviderURL: https://dex-dchelladurai-chejune15.calatrava.vmware.com
      oAuthClientName: eclipse-che
      oAuthSecret: ZXhhbXBsZS1hcHAtc2VjcmV0
```
