### ISSUE TITLE
Each pod should explicitly declare it's securityContext

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#21559]
### Is your task related to a problem? Please describe

For best security practices, the securityContext under each Pod must be fully declared in order to clearly communicate the workload's security posture. In order to be declarative about their security posture, Pods must define every parameter available in its securityContext and each container's securityContext.

Continuation of https://github.com/eclipse/che/issues/18362

### Describe the solution you'd like

Explicitly define container SecurityContext:

```yaml
      securityContext:
        capabilities:
          drop:
            - ALL
        allowPrivilegeEscalation: false
        runAsNonRoot: true
```
