### ISSUE TITLE
Workspace fails to start when VS Code is the editor and the git repository has no devfile

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21560]
### Describe the bug

If a Git repository hasn't a devfile at its root and VS Code is the editor the workspace creation fails with this error:

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/606959/179738154-5dc2d609-2e15-477d-8cd9-42e4f2633d72.png">

### Che version

next (development version)

### Steps to reproduce

On the dogfooding instance (because VS Code is the default editor there), in the `Create Workspace` page put the URL of a Git repo that doesn't have a Devfile in the `Git repo URL` (I reproduced it with https://github.com/devfile/developer-images that doesn't have a devfile yet)

On any other Che instance use a factory URL using a Git repo that doesn't have a Devfile and the parameter `che-editor=che-incubator/che-code/insiders`

### Expected behavior

The workspace should be started using a default devfile component [as mentioned in this issue](https://github.com/eclipse/che/issues/21340) and in particular [here](https://github.com/eclipse/che/issues/21353).

### Runtime

OpenShift

### Installation method

OperatorHub, other (please specify in additional context)

### Environment

Amazon

**Comment by ibuziuk** [comment]
@l0rd @nickboldt @tolusha my suggestion for fixing this issue would be to set the default value for default components on the operator level e.g. 

```
devEnvironments:
    defaultComponents:
      - container:
          image: 'quay.io/devfile/universal-developer-image:ubi8-latest'
          sourceMapping: /projects
        name: universal-developer-image
```

this is the config we apply to the dogfooding instance. The question is what image should we use for the Dev Spaces product taking into account that the airgap flow needs to be supported
