### ISSUE TITLE
Request installPlugin failed with message: getaddrinfo ENOTFOUND extension

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21585]
### Summary

i have added my plugin to the custom `che-plugin-registry` image and built the image using  `
./build.sh --offline -t divinev1 -r divine6`(https://hub.docker.com/r/divine6/che-plugin-registry) 

[source code for the custom plugin configuration and custom `che-plugin-registry`](https://github.com/Divine1/che-plugin-registry/blob/master/che-theia-plugins.yaml)
```
version: 1.0.0
plugins:
  - repository:
      url: 'https://github.com/Divine1/theiaSeleniumplugin'
      revision: 0.0.1
    aliases:
      - divine1/theiaSeleniumplugin
    extension: https://open-vsx.org/api/harmony/harmony-assist/0.0.1/file/harmony.harmony-assist-0.0.1.vsix
```

When i tried to install my plugin in che-theia editor, it threw below error 
```
Unable to install plugin 'divine1/theiaSeleniumplugin/latest'. Request installPlugin failed with message: getaddrinfo ENOTFOUND extension
```
<img width="1427" alt="Image Pasted at 2022-7-26 12-11" src="https://user-images.githubusercontent.com/10482177/180946877-98d22cec-7791-49cf-9d21-382c943fd94d.png">
Also, in the screenshot you can see 2 search results. why 2 results of my plugin are showing up?

i have also uploaded my Plugin here (https://open-vsx.org/extension/harmony/harmony-assist)

Please let me know what might be the issue
