### ISSUE TITLE
problem with latest chectl version: unable to view containers,plugins in the workspace pane in `che-theia` ide

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21597]
### Summary

below is my chectl version
<img width="462" alt="image" src="https://user-images.githubusercontent.com/10482177/181681542-40df1e9b-0e32-47c7-af05-d310021002ec.png">

below is my `devfile.yaml`
```
schemaVersion: 2.1.0
metadata:
  name: cbfsel-repo
projects:
  - name: cbfsel-project
    git:
      checkoutFrom:
        revision: master
      remotes:
        origin: https://gitlab.eng.organization.com/cbf-sel.git
components:
  - container:
      image: 'artfact-prd/customopenjdk8:v10'
      memoryLimit: 4G
    name: javacontainer
  - container:
      image: 'artfact-prd/standalone-chrome:4.3.0-20220706'
      memoryLimit: 4G
      endpoints:
        - exposure: public
          name: 4444-tcp
          protocol: tcp
          targetPort: 4444
        - exposure: public
          name: 5900-tcp
          protocol: tcp
          targetPort: 5900
        - exposure: public
          name: 7900-http
          protocol: http
          targetPort: 7900
          secure: true
    name: chromecontainer
commands:
  - exec:
      commandLine: mvn clean package -DskipTests
      component: javacontainer
      group:
        isDefault: true
        kind: build
      label: 'build project using maven'
      workingDir: '${PROJECT_SOURCE}'
    id: mvnpackage
```

after i upgraded my `chectl` to latest version, i'm not able view the containers,plugins configured in `devfile.yaml` in my `che-theia` code editor
<img width="1712" alt="image" src="https://user-images.githubusercontent.com/10482177/181681503-a9e194b7-677e-4487-846f-22a4473a58ca.png">

please let me know how to fix this problem. what did i miss?
