### ISSUE TITLE
problem with latest chectl version: cloning sourcecode from gitlab private repository prompts for username/password even after adding gitlab-oauth-config secret

### ISSUE THREAD

**Issue by Divine1** [eclipse/che#21596]
### Summary

my chectl version
<img width="443" alt="image" src="https://user-images.githubusercontent.com/10482177/181679571-f52a4217-747c-4b48-bc2d-742a35c5d2b6.png">

i have added my private organization gitlab account in `devfile`.
```
schemaVersion: 2.1.0
metadata:
  name: cbfsel-repo
projects:
  - name: cbfsel-project
    git:
      checkoutFrom:
        revision: master
      remotes:
        origin: https://gitlab.eng.organization.com/cbf-sel.git
components:
  - container:
      image: 'artfact-prd/customopenjdk8:v10'
      memoryLimit: 4G
    name: javacontainer
  - container:
      image: 'artfact-prd/standalone-chrome:4.3.0-20220706'
      memoryLimit: 4G
      endpoints:
        - exposure: public
          name: 4444-tcp
          protocol: tcp
          targetPort: 4444
        - exposure: public
          name: 5900-tcp
          protocol: tcp
          targetPort: 5900
        - exposure: public
          name: 7900-http
          protocol: http
          targetPort: 7900
          secure: true
    name: chromecontainer
commands:
  - exec:
      commandLine: mvn clean package -DskipTests
      component: javacontainer
      group:
        isDefault: true
        kind: build
      label: 'build project using maven'
      workingDir: '${PROJECT_SOURCE}'
    id: mvnpackage

```
i have added `gitlab-oauth-config` secret in `eclipse-che` namespace.

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/10482177/181679879-aa059573-4fed-4e73-ad18-9affe7d4b9d3.png">

until my previous version of `chectl`, i was able to clone my `https://gitlab.eng.organization.com/cbf-sel.git` repository when i clicked `yes` in below screen
<img width="1706" alt="image" src="https://user-images.githubusercontent.com/10482177/181679535-b4ae774e-889a-4564-b4e9-345a2903213c.png">

but, after upgrading my `chectl` to `chectl/0.0.20220726-next.72bcbab darwin-x64 node-v16.13.2` , the `che-theia` ide prompts for gitlab credentials. This wasn't the case with my previous chectl version. 

i have added my master gitlab credentials in `gitlab-oauth-config`, why is it required to enter my gitlab credentials again? 
![image](https://user-images.githubusercontent.com/10482177/181680368-855f4024-f870-4125-b493-7563d700ee38.png)

could you please let me know how to make this to work as it was working in the previous version?
