### ISSUE TITLE
Disable OIDC provider and enable it post installation through installer=operator

### ISSUE THREAD

**Issue by abhijeetka** [eclipse/che#21602]
### Summary

Che Version: 7.51.0
Chectl Version : 7.51.0 

While installing we are using chectl with `--skip-oidc-provider-check` and the pods are up however the che pods are trying to use the default oidc provier.

However, we want eclipce-che to use some other oidc provider however we are not sure how to provide that, we went through the documentation and we observered to edit the CRD checluster however the documentation provided is for `org.eclipse.che/v1` and we are using `org.eclipse.che/v2`

Please guide us to the appropriate documentation or share the URL's which can help us to fix this problem.

Thanks in Advance

**Comment by ibuziuk** [comment]
@tolusha could you please take a look?

**Comment by tolusha** [comment]
Hello. @abhijeetka 

To use a custom OIDC provider:

1. create a patch file
```
$ cat > che-patch.yaml << EOF
kind: CheCluster
apiVersion: org.eclipse.che/v2
spec:
  networking:
    auth:
      oAuthClientName: <CLIENT_ID>
      oAuthSecret: <CLIENT_SECRET>
      identityProviderURL: <IDENTITY_PROVIDER_URL>
  components:
  #
  #  cheServer:
  #    extraProperties:
  #      CHE_OIDC_USERNAME__CLAIM: email
EOF
```

2. Deploy Eclipse Che using `chectl` providing the patch file
```bash
chectl server:deploy --platform k8s --domain <KUBERNETES_PUBLIC_DOMAIN> --che-operator-cr-patch-yaml che-patch.yaml
```

For instance we have a draft doc explaining how configure Minikube with a Keycloak as OIDC provider and deploy Eclipse Che
https://github.com/eclipse-che/che-docs/pull/2408

**Comment by abhijeetka** [comment]
@tolusha  I will give it a try today.

**Comment by vkatta88** [comment]
Hi,


We tried installing with the above given hint.

We have created the che-patch.yaml with the below content.

```
kind: CheCluster
apiVersion: org.eclipse.che/v2
spec:
  networking:
    auth:
      identityProviderURL: https://sts.windows.net/{TENANTID}/v2.0/
      identityToken: access_token
      oAuthClientName: {CLIENTID}
      oAuthSecret: {CLIENTSECRET}
      oAuthScope: openid email profile
  components:
    cheServer:
      extraProperties:
        CHE_OIDC_AUTH__SERVER__URL: https://sts.windows.net/{TENANTID}/v2.0/
        CHE_OIDC_EMAIL__CLAIM: unique_name
```
we are using AWS EKS cluster. After adding the above OIDC Azure AD details able to resolve che dashboard URL but it is keep on loading the dashboard page and throwing the error `'Failed to fetch available workspaces, reason: Failed to fetch the list of devWorkspaces. Unable to list devworkspaces: Unauthorized'`

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/44397185/183848916-0dbcc712-1d20-4c4e-8a00-740bbf009e23.png">


Please check and let us know what needs to be modified. Thanks in advance
