### ISSUE TITLE
Allow to set environment variables into Eclipse Che core components using CheCluster

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#21605]
### Is your task related to a problem? Please describe

There a couple of requests [1] and [2]  to set environment variables into Eclipse Che containers. Currently we have a way to do so [3] by creating a ConfigMap or Secret. But it does not work for Gateway containers and it is harder than setting them via CheCluster CR.

[1] https://github.com/eclipse/che/issues/21260
[2] https://github.com/eclipse/che/issues/21530
[3] https://www.eclipse.org/che/docs/stable/administration-guide/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-container/#mounting-a-secret-or-a-configmap-as-an-environment-variable-into-a-container_che

### Describe the solution you'd like

Allow to set environment variables into Eclipse Che containers by configuring CheCluster CR.
For instance, setting environment variables for containers will look like:

```yaml
spec:
  components:
    dashboard:
      deployment:
        containers:
          -  env:
              - name: <NAME>
                value: <VALUE>
    che-server:
      deployment:
        containers:
          -  env:
              - name: <NAME>
                value: <VALUE>
  networking:
    auth:
      gateway:
        deployment:
          containers:
            - name: oauth-proxy
              env:
                - name: <NAME>
                  value: <VALUE>
```

### Release Notes Text

An admin can now specify arbitrary environment variables that will be applied to the containers of the core components of Eclipse Che. Those environment variables can be specified in the `CheCluster` Custom Resource.
