### ISSUE TITLE
Failed to start a workspace on a minikube cluster

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#21643]
### Describe the bug

There are several issues, that user might face during starting up a workspace on the minikube cluster. Basically because of pulling Universal developer image which takes around ~15 min.

1. `ImagePullBackOff` error
![ImagePullBackOff](https://user-images.githubusercontent.com/36936974/184819614-8264e68f-b3fd-4486-93e1-352bbd46c37d.PNG)

**Solution**: restart the minikube cluster with the additional flag `--kubernetes-version=v1.23.9`

---

2. `'Starting' for longer than timeout` error
![screenshot-192 168 39 246 nip io-2022 08 19-16_53_19](https://user-images.githubusercontent.com/1640675/185634445-6eee8fde-4559-4628-9231-0441391510c3.png)

**Solution**: Create a `WorkspaceOperatorConfig`:

```yaml
apiVersion: controller.devfile.io/v1alpha1
kind: DevWorkspaceOperatorConfig
metadata:
  name: devworkspace-operator-config
  namespace: devworkspace-controller
config:
  workspace:
    progressTimeout: 30m
```

---

3. `The workspace status remains "Starting" in the last 300 seconds` error
![screenshot-192 168 39 246 nip io-2022 08 19-16_46_24](https://user-images.githubusercontent.com/1640675/185634669-2868f4c9-c681-4025-8355-e11a1d0b03b8.png)

**Solution**: Ensure that required images exist on the cluster before starting a workspace. To achieve this, we can use:
* KubernetesImagePuller  https://github.com/che-incubator/kubernetes-image-puller
* Pull image locally and copy it to the cluster
```bash
docker pull ${IMAGE}
docker save "${IMAGE}" > universal-developer-image.tar
eval $(minikube docker-env) && docker load -i  universal-developer-image.tar
```
* Create a job to pull image:
```yaml
kind: Job
apiVersion: batch/v1
metadata:
  name: prepull-universal-image
spec:
  template:
    metadata:
      name: prepull-universal-image
    spec:
      containers:
        - name: prepull-universal-image
          image: "${IMAGE}"
          imagePullPolicy: Always
      restartPolicy: OnFailure
```

### Che version

next (development version)

### Steps to reproduce

1. Deploy Eclipse Che on minikube
2. Try to start a workspace

### Expected behavior

Workspace is up and running

### Runtime

minikube

### Installation method

chectl/next

### Environment

Linux
