### ISSUE TITLE
Telemetry Plugin support for Che-Code editor

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21661]
### Is your task related to a problem? Please describe

Telemetry Plugin support in DevWorkspaces (workspaces started with the DevWorkspace engine) has been implemented as part of https://github.com/eclipse/che/issues/20090
Need to make sure that the plugin works not only with theia, but also with Che-Code 

### Describe the solution you'd like

https://github.com/che-incubator/devworkspace-telemetry-woopra-plugin works with both che-code and theia

on CR level it should be enabled the following way:

```
workspacesDefaultPlugins:
        - editor: eclipse/che-theia/latest
          plugins:
            - >-
              https://<plugin-devfile.yaml>
        - editor: che-incubator/che-code/insiders
          plugins:
            - >-
               https://<plugin-devfile.yaml>
```

NOTE: plugin-devfile.yaml is expected to be the same for both editors

### Describe alternatives you've considered

N/A
