### ISSUE TITLE
Running a clusterwide service alongside eclipse che

### ISSUE THREAD

**Issue by Deel96** [eclipse/che#21677]
### Summary

Hi,

I have the usecase that I want to provide a service clusterwide for all workspaces.
Think of a complex simulation program which needs a high amount of resources that exceed the typical workspace limits (Or may only run 1 instance because of licenses).

I tried to create a simple demo app with nodejs, which just should return "Hello World"

When I successfully deployed my service, I tried to access it via it's service name, which don't succeed. But id I do the same from for example a workspace pod, I get a successful response.
I also get a sucessfull response when calling the server via localhost on the `internal service` pod

In my service pod, as well as my workspace pod I used following command to trigger the nodejs server:
```
wget internal-service.services:4455
```
On the workspace pod that gets deployed from che with a traefik/che-gateway sidecar container I get a response.
When I try it inside the service pod (basicly calling itself)

Request via the `internal service` pod:
```
wget localhost:4455
Connecting to localhost:4455 (127.0.0.1:4455)
saving to 'index.html'
index.html           100% |**|    34  0:00:00 ETA
'index.html' saved

wget internal-serivce:4455 // or internal.service.services:4455
Connecting to internal-serivce (10.110.34.34:4455)
```

Request via `workspace` pod

```
wget internal-serivce.services:4455 // or internal.service.services:4455
Connecting to internal-serivce (10.110.34.34:4455)
saving to 'index.html'
index.html           100% |**|    34  0:00:00 ETA
'index.html' saved

```

Is there something I have to add to get this working?

### Relevant information

Kubernetes ressource

<details>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-service
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-service # match deployment to the pod below
  template: # pod
    metadata:
      labels:
        app: internal-service # to match pod to deployment
    spec:
      containers:
      - name: internal-service
        image: localhost:5000/internal-service:latest
        ports:
        - name: api-port
          containerPort: 4455
---
apiVersion: v1
kind: Service
metadata:
  name: internal-service
  namespace: services
spec:
  ports:
  - name: api-port
    port: 4455
    targetPort: api-port
  selector:
    app: internal-service # match the service to pod
```

</details>

Dockerfile

<details>

```yaml

FROM node:14-alpine
WORKDIR /usr/src/app/server

COPY . .

RUN npm install

ENV INTERNAL_SERVICE_PORT=4455


EXPOSE 4455

CMD ["npm","run", "start"]

```

</details>

Dummy Nodejs program

<details>

```js
'use strict';

console.log("Starting express");

const express = require('express');

// Constants
const PORT = 4455;
const HOST = '0.0.0.0';

// App
const app = express();
app.get('/', (req, res) => {
  res.send('Hello World from internal service');
});

app.listen(PORT, HOST);
console.log(`Running on http://${HOST}:${PORT}`);

```

</details>

Descriptions of the pod/deployment/service

Pod

<details>

```yaml

user@pc:~/GIT/stellar$ kubectl describe pod internal-service
Name:         internal-service-85f85d4886-srxn8
Namespace:    default
Priority:     0
Node:         minikube/192.168.49.2
Start Time:   Wed, 31 Aug 2022 17:18:50 +0200
Labels:       app=internal-service
              pod-template-hash=85f85d4886
Annotations:  <none>
Status:       Running
IP:           172.17.0.20
IPs:
  IP:           172.17.0.20
Controlled By:  ReplicaSet/internal-service-85f85d4886
Containers:
  internal-service:
    Container ID:   docker://f38efc18684cad570b1c16901ce15f0d7c2f9aeb9b9544e5a14a1a07f83fcf1f
    Image:          localhost:5000/internal-service:latest
    Image ID:       docker-pullable://localhost:5000/internal-service@sha256:45b860e27df9f4b415d2a3da96a711e8705b37ce3789fcd3be2f665a72c453da
    Port:           4455/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 31 Aug 2022 17:18:51 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-sffff (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  kube-api-access-sffff:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  10m   default-scheduler  Successfully assigned default/internal-service-85f85d4886-srxn8 to minikube
  Normal  Pulling    10m   kubelet            Pulling image "localhost:5000/internal-service:latest"
  Normal  Pulled     10m   kubelet            Successfully pulled image "localhost:5000/internal-service:latest" in 29.253746ms
  Normal  Created    10m   kubelet            Created container internal-service
  Normal  Started    10m   kubelet            Started container internal-service

```

</details>

Deployment

<details>

```yaml

user@pc:~/GIT/cluster/internal-service$ kubectl describe deployment internal-service
Name:                   internal-service
Namespace:              default
CreationTimestamp:      Wed, 31 Aug 2022 17:18:50 +0200
Labels:                 <none>
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=internal-service
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=internal-service
  Containers:
   internal-service:
    Image:        localhost:5000/internal-service:latest
    Port:         4455/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   internal-service-85f85d4886 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  42s   deployment-controller  Scaled up replica set internal-service-85f85d4886 to 1

```

</details>

Service

<details>

```yaml

user@pc:~/GIT/cluster/internal-service$ kubectl describe service internal-service
Name:              internal-service
Namespace:         default
Labels:            <none>
Annotations:       <none>
Selector:          app=internal-service
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.102.113.230
IPs:               10.102.113.230
Port:              api-port  80/TCP
TargetPort:        4455/TCP
Endpoints:         172.17.0.20:4455
Session Affinity:  None
Events:            <none>
```
</details>
