### ISSUE TITLE
Che-docs devfile is out-of-date with repo

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21717]
### Describe the bug

The devfile in the [che-docs repo](https://github.com/eclipse-che/che-docs) contains the default command 
```yaml
  - exec:
      commandLine: bash tools/newtopic.sh
      component: tools
      label: Create a new topic
      workingDir: "${PROJECT_SOURCE}"
    id: create-a-new-topic
```
which is used to create a new topic. The `tools/newtopic.sh` script uses `newdoc` to create the actual file, but since https://github.com/eclipse-che/che-docs/pull/2370 the `newdoc` binary is no longer available in the `quay.io/eclipse/che-docs:next` image, causing that command to fail.

### Che version

next (development version)

### Steps to reproduce

1. Start a workspace using the che-docs URL: https://github.com/eclipse-che/che-docs.git
2. Attempt to run the `create-a-new-topic` command

### Expected behavior

An alternative way to allow users to create docs should be provided.

### Runtime

other (please specify in additional context)

### Screenshots

![2022-09-19-15:23:39](https://user-images.githubusercontent.com/16168279/191098807-73951f5b-a3da-4436-be68-4fa703e02da7.png)

### Installation method

OperatorHub

### Environment

other (please specify in additional context)
