### ISSUE TITLE
Allow to configure subdomain isolation for GitHub Enterprise Server in CheCluster CR

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21724]
### Is your enhancement related to a problem? Please describe

GitHub Enterprise Server customers have the option to enable/disable [subdomain isolation](https://docs.github.com/en/enterprise-server@3.5/admin/configuration/configuring-network-settings/enabling-subdomain-isolation). URLs to GitHub resources depend on this configuration:

<table>
<tr>
	<td>Path without subdomain isolation 
	<td>Path with subdomain isolation
<tr>
	<td>`http(s)://HOSTNAME/raw/`
	<td>`http(s)://raw.HOSTNAME/`
</table>

### Describe the solution you'd like

A Dev Spaces admin should be able to specify if subdomain-isolated is enabled or not in CheCluster CR:

```yaml
spec:
  gitServices:
    github:
      - endpoint: 'https://github.com'
        secretName: github-oauth-config
        disableSubdomainIsolation: true 
```

And Che server should use paths with or without subdomain isolation, when resolving GitHub files, based on that configuration.

Note: GitHub suggest to enable subdomain-isolation so when not specified we assume that `disableSubdomainIsolation: false` (that's also the github.com config anyway)

### Release Notes Text

In GitHub Enterprise Server subdomains can be [isolated](https://docs.github.com/en/enterprise-server@3.5/admin/configuration/configuring-network-settings/enabling-subdomain-isolation) (as it's the case for `github.com`) and it's now supported by Eclipse Che.
