### ISSUE TITLE
How do I enable gitlab authentification prompt in che with a custom theia-based ide?

### ISSUE THREAD

**Issue by Deel96** [eclipse/che#21720]
### Summary

How do I enable the gitlab authentification prompt in che with a custom theia-based ide?

### Relevant information

che-theia = unmodified official version
my ide= based on theia

I have setup gitlab oauth for private repositories with this tutorial: https://www.eclipse.org/che/docs/stable/administration-guide/configuring-oauth-2-for-github/
If you use something like https://192.168.49.2.nip.io/dashboard/#https://gitlab.private.com/repo

You get prompted on startup of the workspace/ide for your gitlab information so the repo can be checked out.
I use a custom ide (based on theia only) which I use via the factory link
https://192.168.49.2.nip.io/dashboard/#https://gitlab.private.com/repo?che-editor=https:urltocheyaml.com.

When doing so I don't get prompted for my credentials and inside the /projects folder I find the following:
```
$ pwd
/projects

$ ls -al
total 16
drwxrwxrwx 3 root  root 4096 Sep 22 07:53 .
drwxr-xr-x 1 root  root 4096 Sep 22 07:53 ..
drwx------ 2 theia root 4096 Sep 22 07:53 project-clone-3526001976
-rw-r--r-- 1 theia root  454 Sep 22 07:53 project-clone-errors.log

$ cat project-clone-errors.log
2022/09/22 07:53:14 Read DevWorkspace at /devworkspace-metadata/flattened.devworkspace.yaml
2022/09/22 07:53:14 Processing project projectB
2022/09/22 07:53:14 Cloning project projectB to /projects/project-clone-3526001976/project
2022/09/22 07:53:15 Encountered error while setting up project projectB: failed to clone project: failed to git clone from https://gitlab.private.com/groupA/projectB/repoC.git: exit status 128
```
I get the a similar content with che-theia, before I enter my credentials/ I click that I trust the repo:

```
bash-5.1$ pwd
/projects
bash-5.1$ ls
che.theia-workspace       project-clone-1948403954  project-clone-948947021   project-clone-errors.log
bash-5.1$ cd project-clone-1948403954/
bash-5.1$ ls -al
total 8
drwx------    2 root     root          4096 Sep 22 08:03 .
drwxrwxrwx    4 0        root          4096 Sep 22 08:07 ..
bash-5.1$ cd ..
bash-5.1$ cd project-clone-948947021/
bash-5.1$ ls -al
total 8
drwx------    2 root     root          4096 Sep 22 08:07 .
drwxrwxrwx    4 0        root          4096 Sep 22 08:07 ..
bash-5.1$ cd ..
bash-5.1$ cat che.theia-workspace 
{"folders":[]}bash-5.1$ cat project-clone-errors.log 
2022/09/22 08:07:56 Read DevWorkspace at /devworkspace-metadata/flattened.devworkspace.yaml
2022/09/22 08:07:56 Processing project projectB
2022/09/22 08:07:56 Cloning project projectB to /projects/project-clone-948947021/projectB
2022/09/22 08:07:57 Encountered error while setting up project projectB: failed to clone project: failed to git clone from https://gitlab.private.com/groupA/projectB/repoC.git: exit status 128
```
 
I also noticed that for the workspace name the name of the subgroup is used. In The repo has the gitlab url of gitlab.private.com/groupA/projectB/repoC and the workspace gets the name "projectB". This happens also with che-theia.

In the che-theia repo I found a github-oauth plugin but none for gitlab. I get same content with che-theia before I get prompted for my credentials. After I put in my credentials but there I get the prompt for the credentials.

This is my custom che-editor.yaml:

<details>

```yaml
schemaVersion: 2.1.0
metadata:
  name: che-theia
commands:
  - id: init-remote-runtime-injector
    apply:
      component: remote-runtime-injector
events:
  preStart:
    - init-remote-runtime-injector
components:
  - name: theia-ide
    container:
      image: 'custom'
      env:
        - name: THEIA_HOST
          value: 127.0.0.1
      volumeMounts:
        - name: plugins
          path: /plugins
        - name: theia-local
          path: /home/theia/.theia
      mountSources: true
      memoryLimit: 2048M
      cpuLimit: 2000m
      cpuRequest: 200m
      endpoints:
        - name: theia
          exposure: public
          secure: true
          targetPort: 3100
          attributes:
            type: main
            cookiesAuthEnabled: true
            discoverable: false
            urlRewriteSupported: true
          protocol: http
    attributes:
      app.kubernetes.io/component: che-theia
      app.kubernetes.io/part-of: che-theia.eclipse.org
      ports:
        - exposedPort: 3100
  - name: plugins
    volume: {}
  - name: theia-local
    volume: {}
  - name: che-machine-exec
    container:
      image: 'quay.io/eclipse/che-machine-exec:next'
      memoryLimit: 128Mi
      memoryRequest: 32Mi
      cpuLimit: 500m
      cpuRequest: 30m
      command:
        - /go/bin/che-machine-exec
        - '--url'
        - '127.0.0.1:3333'
        - '--idle-timeout'
        - '30m'
      endpoints:
        - name: terminal
          targetPort: 3333
          exposure: public
          secure: true
          protocol: ws
          attributes:
            type: collocated-terminal
            discoverable: false
            cookiesAuthEnabled: true
            urlRewriteSupported: true
    attributes:
      app.kubernetes.io/component: machine-exec
      app.kubernetes.io/part-of: che-theia.eclipse.org
      ports:
        - exposedPort: 3333
  - name: remote-runtime-injector
    attributes:
      app.kubernetes.io/component: remote-runtime-injector
      app.kubernetes.io/part-of: che-theia.eclipse.org
    container:
      image: 'quay.io/azatsary/che-theia-endpoint-runtime-binary:filter'
      memoryLimit: 128Mi
      memoryRequest: 32Mi
      cpuLimit: 500m
      cpuRequest: 30m
      env:
        - name: PLUGIN_REMOTE_ENDPOINT_EXECUTABLE
          value: /remote-endpoint/plugin-remote-endpoint
        - name: REMOTE_ENDPOINT_VOLUME_NAME
          value: remote-endpoint
      volumeMounts:
        - name: plugins
          path: /plugins
        - name: remote-endpoint
          path: /remote-endpoint
  - name: remote-endpoint
    volume:
      ephemeral: true
```

</details>
