### ISSUE TITLE
[devworkspace-handler] Predefined extensions in component attributes in the devfile are being overwritten when workspace creation

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse/che#21734]
### Is your task related to a problem? Please describe

As it was mentioned here https://github.com/eclipse/che/issues/21165, we do not have a proper way to add a custom .vsix ot .theia based extension to che-theia.

The first thing that came to mind how to do that is to add the extension to the container attributes in the devfile like this
```
schemaVersion: 2.1.0
metadata:
  name: asciidoctor-vscode
components:
  - name: tools
    attributes:
      che-theia.eclipse.org/vscode-extensions:
        - https://open-vsx.org/api/asciidoctor/asciidoctor-vscode/2.8.7/file/asciidoctor.asciidoctor-vscode-2.8.7.vsix
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-0e189d9
      mountSources: true
```

At the same time, sample project https://github.com/vitaliy-guliy/asciidoctor-vscode contains `.vscode/extensions.json` file with recommended Yaml extension.

It's expected, that both `asciidoctor` and `yaml` extensions will be downloaded into `/plugins/sidecars/tools`.
But the directory contains only yaml extension, attributes of tools container appeared to be overwritten with a new value.

```
- attributes:
    app.kubernetes.io/name: tools
    che-theia.eclipse.org/vscode-extensions:
    - https://open-vsx.org/api/redhat/vscode-yaml/0.14.0/file/redhat.vscode-yaml-0.14.0.vsix
```

![Screenshot from 2022-09-28 18-57-31](https://user-images.githubusercontent.com/1655894/192827958-1502ba3f-e508-45d6-ac56-a2a5ae67a805.png)

The extension works fine after downloading its binary to the directory by hands and restarting the workspace

![Screenshot from 2022-09-28 18-12-05](https://user-images.githubusercontent.com/1655894/192827686-92d583f2-545f-47fd-8598-e3f4d5289aa3.png)

### Describe the solution you'd like

Component attributes must contain both extensions like this

```
- attributes:
    app.kubernetes.io/name: tools
    che-theia.eclipse.org/vscode-extensions:
    - https://open-vsx.org/api/asciidoctor/asciidoctor-vscode/2.8.7/file/asciidoctor.asciidoctor-vscode-2.8.7.vsix
    - https://open-vsx.org/api/redhat/vscode-yaml/0.14.0/file/redhat.vscode-yaml-0.14.0.vsix
```

It should be possible to add an extension in the same way to editor container.

### Additional context

To reproduce, create a workspace with https://github.com/vitaliy-guliy/asciidoctor-vscode
