### ISSUE TITLE
Dashboard should put plugins in DevWorkspace `.spec.contributions` instead of as plugin components in `.spec.templates`

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21737]
### Is your enhancement related to a problem? Please describe

Once https://github.com/devfile/devworkspace-operator/pull/939 is merged, DevWorkspaces will support a new field `.spec.contributions`. This functions like plugin components in `.spec.template.components` but allows for plugins to be defined separately from the rest of the devfile, and hopefully makes provisioning workspaces simpler.

When injecting editors/other components into a workspace, the dashboard should instead use the contributions field:
```diff
 apiVersion: workspace.devfile.io/v1alpha2
 kind: DevWorkspace
 metadata:
   name: golang-example
   namespace: <username>-che
 spec:
   routingClass: che
   started: false
   contributions:
+    - name: theia
+      kubernetes:
+        name: che-code-workspace1cfc13df8bcf497a
+        namespace: <username>-che
   template:
     components:
       - name: tools
         container:
           image: udi8
           # etc
-      - name: theia
-        plugin:
-          kubernetes:
-            name: che-code-workspace1cfc13df8bcf497a
-            namespace: <username>-che
```
Note that the structure of the component being added is slightly different, with the `plugin` field being removed (since all items in `.spec.contributions` are treated as plugins)

**Note:** to avoid an issue where dashboard uses this field before it is available in DevWorkspaces, this issue should not be implemented until DWO ships these changes. Otherwise we risk running into an issue like https://github.com/eclipse/che/issues/21729

### Describe the solution you'd like

Adopt the `.spec.contributions` field for specifying editors and additional components not present in the original Devfile. This has the additional benefit of making conversion from Devfile -> DevWorkspace simpler, as the basic structure is
```yaml
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: <devfile.name>
spec:
  started: true
  routingClass: che
  template:
    # components, commands, events, attributes from original devfile, unchanged
    # if setting additional attributes (e.g. storage-type), inject into attributes
    # as is done currently
    <devfile>
  contributions:
    <editors, default plugins>
```

### Additional context

This issue is part of https://github.com/eclipse/che/issues/21736
