### ISSUE TITLE
Certificates are not propagated to DevWorkspace Operator git configuration

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#21732]
### Describe the bug

The DevWorkspace Operator has a mechanism for propagating custom certificates into a workspace's git config by creating a configmap from template
```yaml
apiVersion: v1
kind: ConfigMap
metadata: 
  name: <any>
  labels: 
    controller.devfile.io/git-tls-credential: "true"
    controller.devfile.io/watch-configmap: "true"
    controller.devfile.io/mount-to-devworkspace: "true"
  annotations: 
    controller.devfile.io/mount-path: /tmp/git-certs/ # any path; default is `/etc/config/<.metadata.name>`
data: 
  host: https://<git-host>.com # optional; sets sslCAInfo for a specific domain (if e.g. using multiple servers)
  certificate: <certificate content> # note: key name 'certificate' is currently required
```

The labels/annotations on this configmap tell DWO to
1. Mount the certificate to `controller.devfile.io/mount-path`
2. Add `http.sslCAInfo` config to the global git config to use this certificate

Currently, when using custom certificates as documented in Che, user namespaces get a configmap
```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    che.eclipse.org/included-configmaps: custom-certs-52975
    controller.devfile.io/mount-as: file
    controller.devfile.io/mount-path: /public-certs
  labels:
    app.kubernetes.io/component: user-settings
    app.kubernetes.io/name: eclipse-che
    app.kubernetes.io/part-of: che.eclipse.org
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/watch-configmap: "true"
  name: che-trusted-ca-certs
data:
  custom-certs.<original-name>.crt: "<CERT>"
```
which _does_ mount the certificate to workspaces, but does not configure `http.sslCAInfo`, resulting in the project-clone init container failing to clone the project. Simply adding the `controller.devfile.io/git-tls-credential` does not work here, as DWO currently expects the `.data` field with the certificate to be named `certificate`.

### Che version

next (development version)

### Steps to reproduce

1. Configure custom certificate for git server
2. Start a workspace that uses a project from that git server
3. Project clone fails to clone project.

### Expected behavior

Since all the required data is already present, Che should support configuring Git TLS certs in addition to general certificates.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

### Additional context

Originally reported in https://issues.redhat.com/browse/CRW-3381
