### ISSUE TITLE
[RFE] - Deploy SSH keys to enable Git actions on SSH only accessible SCM

### ISSUE THREAD

**Issue by ahenshaw-work** [eclipse/che#21740]
### Is your enhancement related to a problem? Please describe

Some private (not publically accessible) Source Control Management (SCM) solutions can have PKI authentication. In this situation, it is generally much easier to use SSH to interact; for example when cloning, pulling or pushing to a repository.

Currently it doesn't appear as though there is a way to specify SSH keys to use when interacting with a repository, nor a way to deploy/inject SSH keys into the container that is responsible for initially cloning repositories (`theia-ide` in some cases?), nor in the `workspace` container.

In the downstream `Dev Spaces` SSH keys are automatically generated, but this would be inefficient to use, as you would need to add them to the Git repository everytime you start up your workspace.

### Describe the solution you'd like

My preferred solution, would be to create a kubernetes secret containing the private and public SSH keys.
The secret would have a label or annotation so that CHE/DS is aware the secret exists, and deploys/injects/maps the SSH keys into the appropriate locations in order to allow Git actions to occur without manual intervention.

### Describe alternatives you've considered

Current workflow consists of:
1. create secret
```yaml
---
kind: Secret
apiVersion: v1
metadata:
  name: git-ssh-secret
  namespace: <username>-devspaces
  labels:
    controller.devfile.io/watch-secret: 'true'
    controller.devfile.io/mount-to-devworkspace: 'true'
data:
  id_rsa: >-
    <private-key>
  id_rsa.pub: >-
    <public-key>
```
2. start workspace
  a. ensure `devfile` contains `projects` that use `ssh` not `https` [devfile](https://github.com/ahussey-redhat/devspaces/blob/develop/devfile.yaml)
3. start a terminal for the `theia-ide` container
4. `cp` the secrets from `/etc/secrets/git-ssh-secret/*` to `~/.ssh`
5. correct the permissions `chmod 0600 ~/.ssh/<private-key>`
6. when a timeout or incorrect permissions prompt appears in the IDE, click `retry`
7. projects clone successfully

### Additional context

This is my repo that I have been using for testing:
https://github.com/ahussey-redhat/devspaces/tree/develop

@vinokurig - tagging you for reference
