### ISSUE TITLE
Allow che administrators to enable container build capabilities for developers workspaces

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21752]
### Is your enhancement related to a problem? Please describe

Today it's only possible to add the capability through an attribute in a devfile and this is not portable.

### Describe the solution you'd like

Add to the CheCluster a field to enable the container build capabilties and update the dashboard to consume it at workspace startup:

```yaml
spec:
  devEnvironments:
    disableContainerBuildCapabilities: true # initially the default is `true` 
                                            # but will be switched to `false` as soon
                                            # as #21764 sub-tasks are completed.
```

### Release Notes Text

An administrator can enable container builds using `devEnvironments.disableContainerBuildCapabilities: true` in CheCluster configuration. This allow using `podman build` on any workspace (adding the attribute `controller.devfile.io/scc: container-build` in a Devfile is not required anymore) .

**Comment by tolusha** [comment]
@l0rd 
Could you help with CheCluster CR fields?

**Comment by l0rd** [comment]
```yaml
spec:
  devEnvironments:
    disableContainerBuildCapabilities: false # <== default is false
```
