### ISSUE TITLE
Dashboard should inject `controller.devfile.io/scc: container-build` based on the CR property

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21756]
### Is your task related to a problem? Please describe

As part of this issues, dashboard should inject the container build attribute based on the:

```
attributes:
  controller.devfile.io/scc: container-build
```

based on the CR property implemented as part of the https://github.com/eclipse/che/issues/21752

### Describe the solution you'd like

attribute is injected in every workspace is admin enabled the dedicated property

**Comment by l0rd** [comment]
I have opened #21768 to makes the container build SCC configurable. The dashboard should pick the SCC name from `spec.devEnvironments.containerBuildConfiguration.openShiftSecurityContextConstraint` (instead of using the hardcoded `container-build` SCC).

**Comment by l0rd** [comment]
I don't think this issue is necessary anymore. [Setting `containerOverrides` should be enough](https://github.com/eclipse/che/issues/21770). I am saying that because I have figure out that a Pod with the following spec (without the annotation `openshift.io/scc: container-build` but with the capabilities and `allowPrivilegeEscalation: true`) is automatically annotated by the scheduler:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: rootless
spec:
  containers:
    - name: podman
      image: quay.io/mloriedo/podman:rootless
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 100m
          memory: 1G
      securityContext:
        capabilities:
          add:
           - SETGID
           - SETUID
          drop:
           - KILL
           - MKNOD
        allowPrivilegeEscalation: true
```
