### ISSUE TITLE
Cannot start a workspace from devfile with  cpu request / limit specified in CPU units (e.g. `0.1`)

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#21757]
### Describe the bug

WORKAROUND: specify the cpu request/limit using millicores, see: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-cpu

When trying to create a workspace from a devfile with this component:
```
  - name: tooling-container
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      memoryRequest: 256M
      memoryLimit: 1536M
      cpuRequest: 0.1
      cpuLimit: 0.5
```

My workspace isn't created and I get the following error from the dashboard:
<details>
<summary>First Error: </summary>
<br>

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/83611742/195199330-d70222d9-2a25-4c69-8637-23cb5aac74e9.png">

</details>

If I change the `cpuRequest` and `cpuLimit` to be strings like so:
```
      cpuRequest: "0.1"
      cpuLimit: "0.5"
```
, and recreate my workspace, the workspace gets created, but I get a new error:
      
<details>
<summary>Second Error: </summary>
<br>

</details>

Upon investigating the DevWorkspace, the `cpuLimit` and `cpuRequest` is both set to `NaNundefined`:

<details>
<summary>DevWorkspace: </summary>
<br>

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/83611742/195200729-6393277e-d996-4600-a399-3515124ce51c.png">

</details>

### Che version

next (development version)

### Steps to reproduce

The first error can be reproduced by creating a workspace with this project: https://github.com/dkwon17/cpulimitproject

The first error can be reproduced by creating a workspace with this project: https://github.com/dkwon17/cpulimitproject/tree/cpuRequestLimitString

### Expected behavior

There should be no errors when creating the workspace

### Runtime

OpenShift

### Installation method

other (please specify in additional context)

### Environment

macOS
