### ISSUE TITLE
Support Devfile exec commands env in VS Code tasks

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21760]
### Is your enhancement related to a problem? Please describe

In Devfile v2 spec it's possible to specify some environment variables for commands exec:

```yaml
commands:
  - id: command-using-env
    exec:
      component: tooling-container
      commandLine: echo "Hello $USER"
      env:
        - name: USER
          value: janedoe
```

But these variables are not set in the task process when executed:

```
*  Executing task: echo "Hello $USER" --component tooling-container 

Hello
*  Terminal will be reused by tasks, press any key to close it. 
```

### Describe the solution you'd like

Support exc commands env in VS Code tasks and, in IntelliJ run configuration (if it's not implemented yet).

### Additional context

Can be tested on [developer sandbox](https://workspaces.openshift.com/#https://gist.githubusercontent.com/l0rd/e62b57dbba9fde9d8e74e65a73de8891/raw/8976279f8316154ed1cd6993d6c4ece23c69a0a0/devfile.yaml?che-editor=che-incubator/che-code/insiders)
