### ISSUE TITLE
Automatically manage the `container-build` SCC if containerBuildCapabilities are enabled

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21764]
### Is your enhancement related to a problem? Please describe

As mentioned in [this blog post](https://che.eclipseprojects.io/2022/10/10/@mloriedo-building-container-images.html), to allow container build capabilities in workspaces admins and users have to go through some extra steps. Those steps are manual, not documented, and error prone.

### Describe the solution you'd like

Che should
- #21752
- #21768
- #21769
- #21770
- #21756

Once those are completed we should change the default of `disableContainerBuildCapabilities` to `false` (today the default is `true`:

```yaml
spec:
  devEnvironments:
    disableContainerBuildCapabilities: false # initially the default is `true`
    containerBuildConfiguration:
       openShiftSecurityContextConstraint: 'container-build'
       containerOverrides: {"securityContext":{"capabilities":{"add": ["SETGID", "SETUID"]}}}
       podOverrides: {"spec": {"securityContext": {"allowPrivilegeEscalation": false}}}
```
