### ISSUE TITLE
Support Devfile command's `exec/group/isDefault` in VS Code tasks

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21762]
### Is your enhancement related to a problem? Please describe

In Devfile v2 spec it's possible to specify if the command is a default one in the group:
```yaml
commands:
  - exec:
      commandLine: sh tools/preview.sh
      component: tools
      group:
        isDefault: true
        kind: build
      workingDir: "${PROJECT_SOURCE}"
    id: start-preview-server
```

Vanilla VS Code allows specifying the default Task in the built-in groups `build` and `test`. So that it is executed directly when triggering `Run Build Task (Ctrl+Shift+B)` or `Run Test Task` VS Code's commands from the Command Palette.

But `exec/group/isDefault` is ignored by VS Code (Che-Code).

### Describe the solution you'd like

When importing the Commands from a Devfile, VS Code should respect the Command's `exec/group/isDefault` attribute.
That would add value for the user, as they can expect to run such a Devfile Command by calling VS Code's `Run Build/Test Task` command.
