### ISSUE TITLE
Obstacles to deploying Che on Digital Ocean Kubernetes

### ISSUE THREAD

**Issue by ghost** [eclipse/che#21773]
### Summary

I have deployed Che on Digital Ocean Kubernetes, but receive an error response when creating a workspace: "Unable to create devworkspace: Unauthorized". I suspect this has to do with the cluster API server not having OIDC flags provided. [According to Digital Ocean](https://www.digitalocean.com/community/questions/configuring-the-api-server), it is not possible to configure these flags. I got around this for the deploy step by passing `--skip-oidc-provider-check` to Che. I also pass `--che-operator-cr-patch-yaml` passing it this file:
```yaml
apiVersion: org.eclipes.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  server:
    cheDebug: 'true'
    cheLogLevel: DEBUG
    customCheProperties:
      CHE_LIMITS_USER_WORKSPACES_COUNT: "20"
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "20"
  auth:
    identityProviderURL: https://<our app>
    oAuthSecret: <>
    oAuthClientName: kube
```
This configuration worked previously in a development environment, with the kubernetes cluster hosted locally via `kind`. Our app acts as the OIDC provider for the cluster.

So, with this configuration Che is able to start and OIDC seems to work, but it does not have permission to create a workspace.

Without being able to configure OIDC provider flags on the cluster API server, is there another way to give Che the required permissions? Hoping someone knows what I will need to do.
