### ISSUE TITLE
Support running VS Code in the containers that don't include the pre-requisites

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21778]
### Depends on:
- https://github.com/eclipse/che/issues/22345
### Is your task related to a problem? Please describe

Currently, Che-Code works perfectly in a UDI8-based container.
But, as a user, I should be able to run the Che-Code editor in my own container which, ideally, can be based on any image.
E.g.: `maven:3.8.6-openjdk-18`, `registry.access.redhat.com/ubi9/ubi`, etc.

For example, if I run Che-Code in a DevWorkspace created from the following Devfile:
```yaml
schemaVersion: 2.1.0
metadata:
  name: che-code-on-ubi
components:
  - name: dev
    container:
      image: registry.access.redhat.com/ubi8/ubi
      memoryLimit: 7Gi
      cpuLimit: 3500m
  - name: projects
    volume:
      size: 3Gi
```

Che-Code starts well, as it brings the Node.js runtime copied into the dedicated volume. But there's a problem when opening a terminal: `The terminal process "/sbin/nologin" failed to launch (exit code: 1).`

![term](https://user-images.githubusercontent.com/1636395/197528309-c2b43ea8-528f-440c-83a2-6a34044eb1aa.gif)

Some logs from the container:
```
[12:27:52] ptyHost was unable to resolve shell environment Error: Unable to resolve your shell environment: Unexpected exit code from spawned shell (code 1, signal null)
    at /checode/checode-linux-libc/out/vs/server/node/server.main.js:92:2608
    at async /checode/checode-linux-libc/out/vs/server/node/server.main.js:68:23642
...
[12:28:08] ExtensionHostConnection#buildUserEnvironment resolving shell environment failed Error: Unable to resolve your shell environment: Unexpected exit code from spawned shell (code 1, signal null)
    at /checode/checode-linux-libc/out/vs/server/node/server.main.js:92:2608
    at async /checode/checode-linux-libc/out/vs/server/node/server.main.js:68:23642
```

### Describe the solution you'd like

It looks like the only problem we should solve it's opening the VS Code terminal. But need to check if other functionality works well.

### Additional context
Running Che-Code in a UBI9-based container is problematic as well:
```yaml
schemaVersion: 2.1.0
metadata:
  name: che-code-on-ubi
components:
  - name: dev
    container:
      image: registry.access.redhat.com/ubi9/ubi
      memoryLimit: 7Gi
      cpuLimit: 3500m
  - name: projects
    volume:
      size: 3Gi
```
See for more details at https://github.com/eclipse/che/issues/21629.
Currently, there's a workaround described in https://github.com/che-incubator/che-code/tree/main/build/dockerfiles.
It also requires a more stable solution.

**Comment by azatsarynnyy** [comment]
The workaround for the terminal issue is setting the `bash` as the VS Code default terminal profile.
It can be set in the settings directly or with the `Terminal: Select Default Profile` VS Code command, in Command Palette.

**Comment by azatsarynnyy** [comment]
It turned out [Che-Code's entrypoint](https://github.com/che-incubator/che-code/blob/7d395281fb16f7afc34906fc497d23e9634e759f/build/scripts/entrypoint-volume.sh#L15-L20
) failed to patch the `/etc/passwd`.
It has no shell and no home dir: `1003120000:x:1003120000:0:1003120000 user:/:/sbin/nologin`

**Comment by l0rd** [comment]
The arbitrary user that runs the container doesn't have write privileges on `/etc/passwd` and `/etc/groups`. That explains why our `entrypoint-volume.sh` fails. 

And in general it's a good practice deny write access to `/etc/passwd` so we have to live with that. We should probably deny access to `/etc/passwd` on UBI images too. From an editor point of view we should see if there is a env variable (`$SHELL`?) or parameter that changes the behavior of VS Code terminal, or otherwise hardcode the vscode settings to use `/bin/bash` (or `/bin/sh` that's more universal). 

Note to self:
Running images as arbitrary user with CRI-O (so OpenShift) is easier than a couple of years ago because CRI-O automatically patches `/etc/passwd` [when the container is created](https://github.com/cri-o/cri-o/blob/1e6fd9c520d03d47835d1d4c3209e0f77c38f542/utils/utils.go#L291):
- the username is retrieved from the image config `User` or, when not set, from the arbitrary UID
- the home directory is retrieved from the image env variable `HOME`, from the image config `WorkingDir` and otherwise set to `/tmp`
- the shell is hardcoded to `/sbin/nologin`

**Comment by RomanNikitenko** [comment]
Today I faced with the error at starting a workspace:

```
Detected unrecoverable event FailedPostStartHook: 
Exec lifecycle hook ([/bin/sh -c nohup /checode/entrypoint-volume.sh > /checode/entrypoint-logs.txt 2>&1 &]) 
for Container "tools" in Pod "workspace835)" failed - 
error: rpc error: code = NotFound desc = container is not created or running: 
checking if PID of tools is running failed: container process not found, message: "".

Workspace stopped due to error
```
For the `tools` container I used UBI9-based image, it contains `Node.js`, also I provided `VSCODE_NODEJS_RUNTIME_DIR` env variable. But the workspace failed...
 
Definition for my `tools` container:

```
components:
  - name: tools
    container:
      image: quay.io/rnikitenko/ubi9/go-toolset:latest
      env:
        - name: VSCODE_NODEJS_RUNTIME_DIR
          value: /usr/bin
      endpoints:
        - exposure: public
          name: nodejs
          protocol: http
          targetPort: 3000
      memoryLimit: 2Gi
      memoryRequest: 256Mi
      mountSources: true
    attributes:
      controller.devfile.io/merge-contribution: true
```
My editor starts on the `post-start` event:
```
commands:
    - id: init-container-command
      apply:
        component: che-code-injector
    - id: init-che-code-command
      exec:
        component: che-code-runtime-description
        commandLine: 'nohup /checode/entrypoint-volume.sh > /checode/entrypoint-logs.txt 2>&1 &'
  events:
    preStart:
      - init-container-command
    postStart:
      - init-che-code-command
```
I was able to fix the problem by:

![image](https://user-images.githubusercontent.com/5676062/230419291-584e8a70-2165-4338-9a5c-735fd8b30e60.png)

**Comment by RomanNikitenko** [comment]
@l0rd 
about 
`CMD ["tail", "-f", "/dev/null"]`
(please see my previous comment)

I would like to know your opinion here.
Should it be a requirement for the image which is used for the `tools` container?

**Comment by l0rd** [comment]
@RomanNikitenko the requirement is that the container has to be non terminating. From the [documentation](https://devfile.io/docs/2.2.0/adding-a-container-component):

> Either the command defined by the image or by the container component within the devfile must be non-terminating, such as the case of setting command to sleep with the infinity argument.

**Comment by l0rd** [comment]
In fact the [devfile in the devfile registry has](https://github.com/devfile/registry/blob/main/stacks/go/2.0.0/devfile.yaml#L40):

```yaml
  - container:
      (...)
      image: registry.access.redhat.com/ubi9/go-toolset:1.18.9-14
      args: ['tail', '-f', '/dev/null']
```
