### ISSUE TITLE
Specify the workspace Pods securityContext (`SETGID` and `SETUID`) when developers have container build capabilities

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21770]
### Is your enhancement related to a problem? Please describe

Even if the [container build is enabled in the CheCluster CR](https://www.eclipse.org/che/docs/stable/administration-guide/checluster-custom-resource-fields-reference/#checluster-custom-resource-devEnvironments-settings), the required build capabilities (`SETUID`, `SETGID` and "allowPrivilegeEscalation": true) are not explicitly requested in the workspaces Pod SecurityContext.

This is not an issue if the container-build SCC is the only SCC of the workspaces service accounts. 

But, if the workspace ServiceAccount is associated with multiple SCCs, the capabilities of the SCC that requires less privileges are picked. And the developer container won't have `SETUID` and `SETGID` capabilities and trying to run a container build will fail.

### Describe the solution you'd like

The DevWorkspace Operator provides a way to specify Pods security context using a DevWorkspaceOperatorConfiguration (DWOC) CR. When the build capabilities are enabled, Che Operator should apply a DWOC with the security context `{"securityContext":{"capabilities":{"add": ["SETGID", "SETUID"]}, "allowPrivilegeEscalation": true}}`).

### Additional context

This was initially considered a DWO issue (devfile/devworkspace-operator#884) but the DWO already exposes a mechanism to specify Pods SecurityContext (with the DWOC) so that issue has been closed.

The corresponding [OpenShift Dev Spaces issue](https://issues.redhat.com/browse/CRW-3400).

In the future we may allow administrators to specify a custom security context in the CheCluster:

```
spec:
  devEnvironments:
    podsSecurityContext: {"capabilities":{"add": ["SETGID", "SETUID"]}, "allowPrivilegeEscalation": true}
```

but that's a separate issue.

**Comment by AObuchow** [comment]
From what I understand, this issue is about propagating containerOverrides and podOverrides from the Che Cluster CR into the Che-owned DWOC and then having DWO inject these overrides into devworkspaces. 

Currently, containerOverrides and podOverrides must be [specified from an attribute in the devworkspace](https://github.com/devfile/devworkspace-operator/pull/944). There is no DWOC field to automatically inject container and pod overrides into devworkspaces, though this could probably be added (@amisevsk let me know if you have any thoughts on this topic).

However, in the example given for this issue, the pod and container overrides are being used to specify the workspace pod and container security contexts. Setting the pod security context for workspaces in the DWOC is [already possible](https://github.com/devfile/devworkspace-operator/blob/main/apis/controller/v1alpha1/devworkspaceoperatorconfig_types.go#L130) and setting the container security context for workspaces in the DWOC [will soon be possible](https://github.com/devfile/devworkspace-operator/pull/953).

Thus, an alternate solution could be to allow setting the pod and container security contexts from the Che Cluster CR, which then are propagated to the Che-owned DWOC, and used by DWO.
This could look something like the following in the Che Cluster spec:

```YAML
spec:
  devEnvironments:
    containerBuildConfiguration:
       containerSecurityContext: {"capabilities":{"add": ["SETGID", "SETUID"]}}
       podSecurityContext:  {"allowPrivilegeEscalation": false}
```

@l0rd @ibuziuk let me know if you have any thoughts on this alternate proposal.

**Comment by ibuziuk** [comment]
@AObuchow the proposal absolutely makes sense e.g. security context is set on Eclipse Che CR level and propagated to the DWOC without the dashboard being involved. However if I remember correctly podSecurityContext is currently ignored on OpenShift cc: @amisevsk

**Comment by amisevsk** [comment]
> However if I remember correctly podSecurityContext is currently ignored on OpenShift 

PR https://github.com/devfile/devworkspace-operator/pull/953 adds the `containerSecurityContext` config field and also makes DWO take `podSecurityContext` into account when running on OpenShift :) 

Note another potentially simpler approach, if our specific goal is supporting `containerBuildCapability` -- we don't yet need to have CheCluster fields for pod/container securityContext:

### Step 1
Add CheCluster functionality to provision "known, good" container and pod security context into Che-owned DevWorkspaceOperatorConfig when `containerBuildCapability: true`. This basically automates what we would have to document in a "enabling container build in Che" docs:

CheCluster:
```yaml
spec:
  devEnvironments:
    disableContainerBuildCapabilities: false # Enable container build
```
...causes Che Operator to add fields to DevWorkspaceOperatorConfig:
```yaml
config:
  workspace:
    # Whatever Che Operator decides is necessary here, maybe even a full config
    containerSecurityContext: {"capabilities":{"add": ["SETGID", "SETUID"]}}
    podSecurityContext: {"allowPrivilegeEscalation": false}
```

This provides a starting point for enabling container builds by simply toggling one field in CheCluster

### Step 2
What Andrew is suggesting -- add CheCluster fields to allow further customizing securityContext:
```yaml
spec:
  devEnvironments:
    disableContainerBuildCapabilities: true/false
    containerSecurityContext: <securityContext>
    podSecurityContext: <podSecurityContext>
```
Setting containerSecurityContext updates the security contexts propagated to the DWOC and allows for finer-grained configuration in situations where it's necessary, but 90%+ of users ideally don't need to set these fields.
