### ISSUE TITLE
Support running IDEA editor in the containers that don't include the pre-requisites

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21780]
### Is your task related to a problem? Please describe

Currently, the IDEA editor works perfectly in a UDI8-based container.
But, as a user, I should be able to run the IDEA editor in my own container which, ideally, can be based on any image.
E.g.: `maven:3.8.6-openjdk-18`, `registry.access.redhat.com/ubi9/ubi`, etc.

For example, if I run the IDEA editor in a DevWorkspace created from the following Devfile:
```yaml
schemaVersion: 2.1.0
metadata:
  name: idea-on-ubi
components:
  - name: dev
    container:
      image: registry.access.redhat.com/ubi8/ubi
      memoryLimit: 7Gi
      cpuLimit: 3500m
  - name: projects
    volume:
      size: 3Gi
```
the container is terminated before opening an IDE.

### Describe the solution you'd like

Need to provide a solution that would allow running the IDEA editor in any container provided by the user in a Devfile.
