### ISSUE TITLE
Increase k8s client timeouts and potentailly remove calls of the project API

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21801]
### Is your task related to a problem? Please describe

After facing issues like https://github.com/openshift/openshift-apiserver/pull/327 we should consider increasing k8s client timeouts and potentially remove the project API calls with namespace equivalents. We should also consider updating k8s client to the latest 6.2.0 version 

### Describe the solution you'd like

see descriptoin

**Comment by ibuziuk** [comment]
The timeouts can be increased via the dedicated env vars, which has been done for Developer Sandbox

```
    server:
      customCheProperties:
        KUBERNETES_CONNECTION_TIMEOUT: '60000'
        KUBERNETES_REQUEST_TIMEOUT: '60000'
```
Also, bumped the client to the latest 5.12.4 version - https://github.com/eclipse-che/che-server/pull/379
