### ISSUE TITLE
Storageclass name for PVC is not getting set for workspaces being created by checluster

### ISSUE THREAD

**Issue by ghost** [eclipse/che#21807]
### Describe the bug

I have deployed eclipse-che 7.56.x successfully on **on prem k8s cluster** (1 master, 1 worker). All the pods are assigned to worker node only. 

the storageclass name passed in the checluster is not set to the PersistentVolumeClaim (claim-devworkspace) created by che when i created the sample workspace. 

**CR path file :-** 

```
apiVersion: org.eclipse.che/v2
spec:
  components:
    database:
      pvc:
       storageClass: postgres-storage
  devEnvironments:
    storage:
      pvcStrategy: per-user
      perUserStrategyPvcConfig:
              storageClass: workspace-storage
  networking:
    auth:
      identityProviderURL: 'http://dex.dex:5556'
      oAuthClientName: "clientname"
      oAuthSecret: 'secret'
```
**PVs:-** 

```
NAME                  CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                       STORAGECLASS        REASON   AGE
postgres-pv-volume    1Gi        RWO            Retain           Bound       eclipse-che/postgres-data   postgres-storage             126m
workspace-pv-volume   20Gi       RWO            Retain           Available                               workspace-storage            136m
```

**Comparison of postgres-data and username-che workspace PVCs : -**

```
Namespace:     admin-che
**StorageClass**:
Status:        Pending
Volume:
Labels:        <none>
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       workspace7ebd5e269d544ff1-7bc4c4768f-kwsv2
Events:
  Type    Reason         Age                  From                         Message
  ----    ------         ----                 ----                         -------
  Normal  FailedBinding  3m7s (x42 over 13m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set


Name:          postgres-data
Namespace:     eclipse-che
**StorageClass:  postgres-storage**
Status:        Bound
Volume:        postgres-pv-volume
Labels:        app.kubernetes.io/component=postgres
               app.kubernetes.io/instance=che
               app.kubernetes.io/managed-by=che-operator
               app.kubernetes.io/name=che
               app.kubernetes.io/part-of=che.eclipse.org
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       postgres-5c84d97768-w4hql
Events:        <none>
```

### Che version

7.56@latest

### Steps to reproduce

1. Setup K8s cluster on Ubuntu VMs. 
2. Install DEX as OIDC and configure the OIDC parameters for kube-apiserver 
3. Install Che using the below command 
`chectl server:deploy --platform k8s --domain=abc.example.com --postgres-pvc-storage-class-name=postgres-storage --workspace-pvc-storage-class-name=workspace-storage --che-operator-cr-patch-yaml cr-patch.yaml`
4. open che dashboard and create any sample workspace for example. empty workspace.

### Expected behavior

Workspace pods should be running 
Persistent Volume claim by che should be bound to PVs and able to access workspace in dashboard successfully. 

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Linux
