### ISSUE TITLE
Update monitoring docs to use Prometheus and Grafana Operator

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#21805]
### Is your enhancement related to a problem? Please describe

In the current [monitoring docs](https://www.eclipse.org/che/docs/stable/administration-guide/monitoring-with-prometheus-and-grafana/), there are instructions to set up Prometheus and Grafana with Deployments and ConfigMaps.

### Describe the solution you'd like

However, setting up the monitoring with the Prometheus Operator is a bit different because it requires using `ServiceMonitor` CRs to specify the metrics targets. It would be great if there were documentation for this.

For reference, the `ServiceMonitor`s look similar to the following:

For monitoring Che Server:
```
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: che-host
  spec:
    endpoints:
    - interval: 30s
      port: metrics
      scheme: http
    selector:
      matchLabels:
        app.kubernetes.io/name: devspaces
```

For monitoring the DWO:
```
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: devworkspace-controller
  spec:
    endpoints:
    - interval: 30s
      port: metrics
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
    selector:
      matchLabels:
        app.kubernetes.io/name: devworkspace-controller
```
