### ISSUE TITLE
Storage configuration is not applied during the workspace creation on dogfooding

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#21817]
### Describe the bug

Storage configuration set on the CR level is not applied correctly by the Dashboard 

### Che version

7.56@latest

### Steps to reproduce

Reproducible on the dogfooding:
- create and start a workspace
- open openshift console and see that common PVC is used not the per-workspace specified in the CR

```
    storage:
      perWorkspaceStrategyPvcConfig:
        claimSize: 5Gi
      pvcStrategy: per-workspace
```

### Expected behavior

Need to make sure that the dashboard sets correctly the attributes required for the storage configuration and the workspace is started with the expected attributes:

- https://github.com/eclipse/che/issues/21692 
- https://github.com/eclipse/che/issues/21691

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon
