### ISSUE TITLE
VS Code should open multiple projects as a multi-root workspace

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21833]
### Is your enhancement related to a problem? Please describe

If I have a Devfile with multiple project sources declared
```yaml
schemaVersion: 2.1.0
metadata:
  name: dashboard-with-ws-client
projects:
  - git:
      remotes:
        origin: 'https://github.com/eclipse-che/che-dashboard.git'
    name: dashboard
  - git:
      remotes:
        origin: 'https://github.com/eclipse-che/che-workspace-client.git'
    name: ws-client
```

VS Code opens the first project source only (which the `PROJECT_SOURCE` environment variable points to):

![image](https://user-images.githubusercontent.com/1636395/203541446-df83a6e1-6a79-45cb-9c1f-661ffab7c743.png)

In order to see other projects I need to add them by hand with the help of the `Add Folder to Workspace...` command:

![image](https://user-images.githubusercontent.com/1636395/203540282-59d9b6bc-1cec-48aa-8519-630af4e2216e.png)

### Describe the solution you'd like

VS Code should open all the cloned projects as a [multi-root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces):

![image](https://user-images.githubusercontent.com/1636395/203542007-873a3058-9604-45ea-8b88-a3e173db2f0a.png)

It would allow starting working on the projects immediately, without the need to configure a VS Code's workspace by hand.

### Describe alternatives you've considered

VS Code could open the `PROJECTS_ROOT` folder by default. But it has serious disadvantages that arise from the fact that VS Code would open actually a single-folder (`/projects`) workspace.
