### ISSUE TITLE
Custom docker image as workspace

### ISSUE THREAD

**Issue by DerKnerd** [eclipse/che#21856]
### Summary

Hey everyone,

I just deployed a che environment on my microk8s server and it works great with the sample devfiles. Now I want to use my own repo with a custom devfile.

But everytime I try to start the environment I get the following error message: `Container tools has state CrashLoopBackOff`.

This only happens with the custom devfile.yaml but not with the default one. The problem is, I need a more recent version of Golang, so I need a different file.

This is the devfile.yaml

```
schemaVersion: 2.1.0
metadata:
  name: kubernetes-image-version-checker
components:
  - name: tools
    container:
      image: quay.io/devfile/golang:latest
      env:
        - name: GOPATH
          value: /projects:/home/user/go
        - name: GOCACHE
          value: /tmp/.cache
      memoryLimit: 2Gi
      mountSources: true
projects:
  - name: kubernetes-image-version-checker
    git:
      remotes:
        origin: "https://gitlab.imanuel.dev/DerKnerd/kubernetes-image-version-checker.git"
```

The repo is public so feel free to check it yourself.

**Comment by tolusha** [comment]
@DerKnerd 
Adding sleep command to the devfile helps:
```
...
components:
  - container:
      command:
        - sleep
        - infinity
...        
```

**Comment by DerKnerd** [comment]
@tolusha That worked partially, I get a new error message now.

```
Failed to open the workspace
devworkspace failed to progress past phase 'Starting' for longer than timeout (5m)
```

Do you, by any chance, know how to increase the timeout?

**Comment by ibuziuk** [comment]
@DerKnerd could you please share the k8s events, one of the reasons is that image pulling time could be time-consuming
you can try pre-pulling the images on the cluster beforehand using https://github.com/che-incubator/kubernetes-image-puller

**Comment by tolusha** [comment]
All workspace pods are up and running but I got a different error:
```
The workspace has not received an IDE URL in the last 20 seconds. Try to re-open the workspace.
```

**Comment by DerKnerd** [comment]
@ibuziuk The images get pulled fast, it now even creates the workspace. But when I try to access it I get a bad gateway error, when the IDE tries to open. There is no error message logged, neither in my Traefik ingress nor in the Che pods.

**Comment by DerKnerd** [comment]
I just tried again to start the workspace and now I do have errors in my events, check below:

```
LAST SEEN   TYPE      REASON              OBJECT                                           MESSAGE
29m         Normal    Scheduled           pod/workspace2483bf8179dc4924-799bf68f6-xj8md    Successfully assigned me-imanuel-dev-che-i291gf/workspace2483bf8179dc4924-799bf68f6-xj8md to v220210587729153147
29m         Normal    Pulling             pod/workspace2483bf8179dc4924-799bf68f6-xj8md    Pulling image "quay.io/che-incubator/che-code@sha256:cbe4267190274fc397958bada2a084525f693366c21a1f8bbbe6e54e4ab29dca"
29m         Normal    Pulled              pod/workspace2483bf8179dc4924-799bf68f6-xj8md    Successfully pulled image "quay.io/che-incubator/che-code@sha256:cbe4267190274fc397958bada2a084525f693366c21a1f8bbbe6e54e4ab29dca" in 493.026402ms
29m         Normal    Created             pod/workspace2483bf8179dc4924-799bf68f6-xj8md    Created container che-code-injector
29m         Normal    Started             pod/workspace2483bf8179dc4924-799bf68f6-xj8md    Started container che-code-injector
28m         Normal    Pulling             pod/workspace2483bf8179dc4924-799bf68f6-xj8md    Pulling image "quay.io/devfile/project-clone:v0.17.0"
28m         Normal    Pulled              pod/workspace2483bf8179dc4924-799bf68f6-xj8md    Successfully pulled image "quay.io/devfile/project-clone:v0.17.0" in 485.820205ms
28m         Normal    Created             pod/workspace2483bf8179dc4924-799bf68f6-xj8md    Created container project-clone
28m         Normal    Started             pod/workspace2483bf8179dc4924-799bf68f6-xj8md    Started container project-clone
28m         Normal    Pulling             pod/workspace2483bf8179dc4924-799bf68f6-xj8md    Pulling image "quay.io/devfile/golang:latest"
28m         Normal    Pulled              pod/workspace2483bf8179dc4924-799bf68f6-xj8md    Successfully pulled image "quay.io/devfile/golang:latest" in 519.316507ms
28m         Normal    Created             pod/workspace2483bf8179dc4924-799bf68f6-xj8md    Created container tools
28m         Normal    Started             pod/workspace2483bf8179dc4924-799bf68f6-xj8md    Started container tools
28m         Normal    Pulled              pod/workspace2483bf8179dc4924-799bf68f6-xj8md    Container image "quay.io/eclipse/che--traefik:v2.8.1-4e52a5e2495484f5e19a49edfd2f652b0bce7b3603fa0df545ed90168ffae1c3" already present on machine
28m         Normal    Created             pod/workspace2483bf8179dc4924-799bf68f6-xj8md    Created container che-gateway
28m         Normal    Started             pod/workspace2483bf8179dc4924-799bf68f6-xj8md    Started container che-gateway
3m9s        Warning   FailedMount         pod/workspace2483bf8179dc4924-799bf68f6-xj8md    MountVolume.SetUp failed for volume "che-server-cert" : failed to sync secret cache: timed out waiting for the condition
3m9s        Warning   FailedMount         pod/workspace2483bf8179dc4924-799bf68f6-xj8md    MountVolume.SetUp failed for volume "devworkspace-gitconfig" : failed to sync configmap cache: timed out waiting for the condition
3m9s        Warning   FailedMount         pod/workspace2483bf8179dc4924-799bf68f6-xj8md    MountVolume.SetUp failed for volume "user-profile" : failed to sync secret cache: timed out waiting for the condition
3m9s        Warning   FailedMount         pod/workspace2483bf8179dc4924-799bf68f6-xj8md    MountVolume.SetUp failed for volume "che-trusted-ca-certs" : failed to sync configmap cache: timed out waiting for the condition
3m9s        Warning   FailedMount         pod/workspace2483bf8179dc4924-799bf68f6-xj8md    MountVolume.SetUp failed for volume "devworkspace-merged-git-credentials" : failed to sync secret cache: timed out waiting for the condition
3m7s        Warning   FailedMount         pod/workspace2483bf8179dc4924-799bf68f6-xj8md    MountVolume.SetUp failed for volume "workspace-metadata" : failed to sync configmap cache: timed out waiting for the condition
3m7s        Warning   FailedMount         pod/workspace2483bf8179dc4924-799bf68f6-xj8md    MountVolume.SetUp failed for volume "che-gateway" : failed to sync configmap cache: timed out waiting for the condition
3m5s        Warning   FailedMount         pod/workspace2483bf8179dc4924-799bf68f6-xj8md    MountVolume.SetUp failed for volume "kube-api-access-hfh7t" : failed to sync configmap cache: timed out waiting for the condition
29m         Normal    SuccessfulCreate    replicaset/workspace2483bf8179dc4924-799bf68f6   Created pod: workspace2483bf8179dc4924-799bf68f6-xj8md
29m         Normal    ScalingReplicaSet   deployment/workspace2483bf8179dc4924             Scaled up replica set workspace2483bf8179dc4924-799bf68f6 to 1
```

**Comment by DerKnerd** [comment]
I updated the config a and added the code that it runs the `'/checode/entrypoint-volume.sh'`. And I get the following errors in the log.

```
whoami: cannot find name for user ID 1234
total 24
drwxrwxrwx 5 root root 4096 Dec  2 16:09 .
drwxr-xr-x 1 root root 4096 Dec  2 16:09 ..
drwxr-xr-x 2 1234 root 4096 Dec  2 16:09 bin
drwxr-xr-x 7 1234 root 4096 Dec  2 16:09 checode-linux-libc
drwxr-xr-x 7 1234 root 4096 Dec  2 16:09 checode-linux-musl
-rwxr-xr-x 1 1234 root 2838 Dec  2 16:09 entrypoint-volume.sh
time="2022-12-02T16:09:23Z" level=info msg="Default 'info' log level is applied"
time="2022-12-02T16:09:23Z" level=info msg="Exec containers configuration:"
time="2022-12-02T16:09:23Z" level=info msg="==> Debug level info"
time="2022-12-02T16:09:23Z" level=info msg="==> Application url 0.0.0.0:3333"
time="2022-12-02T16:09:23Z" level=info msg="==> Absolute path to folder with static resources "
time="2022-12-02T16:09:23Z" level=info msg="==> Use bearer token: false"
time="2022-12-02T16:09:23Z" level=info msg="==> Pod selector: controller.devfile.io/devworkspace_id=workspace1ce2b2bad518455e"
time="2022-12-02T16:09:23Z" level=info msg="==> Idle timeout: 30m0s"
time="2022-12-02T16:09:23Z" level=info msg="==> Stop retry period: 10s"
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)
```

**Comment by amisevsk** [comment]
Hi @DerKnerd, 

I tested the devfile you provided and there seems to be a few layers of things going wrong (which I now see you've also figured out :slightly_smiling_face:). Some of which may be bugs in Che, though I'm not entirely sure what's going wrong.

* I tested in an earlier version of Che (technically Dev Spaces on workspaces.openshift.com) using the Theia editor, and the workspace started without issue using the devfile with `sleep infinity`
* I also tested on `next` Che with the Che Code editor (which is what you're using, from the logs), and found:
  * On one occasion, Che failed to inject the Che Code entrypoint, resulting in the workspace failing to start (editor never gets started and so workspace is never marked running)
  * Most of the time, Che injects the editor correctly (`entrypoint: /checode/entrypoint-volume.sh`), but this still fails with the log above

It looks like there are two separate things happening here
* Che is failing to inject the editor properly in some cases (entrypoint is left blank or as `sleep infinity`) -- you should not need to edit the command in this way to make the workspace function
* The image we're substituting for the UBI image cannot run Che Code, potentially because node is not installed (though I'm not 100% sure how bootstrapping the editor works here)

I tested with both `quay.io/devfile/golang:latest` and `registry.access.redhat.com/ubi9/go-toolset:latest` and neither seem to be able to run `/checode/entrypoint-volume.sh`, though with different error messages.

**Comment by DerKnerd** [comment]
Hey @amisevsk,

first of all, thank you for the long response. I managed to get it work. I forked the eclipse-che/che-devfile-registry and built my own, Golang 1.19 image based of UBI8. Might not be the best solution but it works.

This is the new devfile.yaml:

```
schemaVersion: 2.1.0
metadata:
  name: kubernetes-image-version-checker
components:
  - name: tools
    container:
      image: quay.imanuel.dev/base-images/che-golang-1.19:ac70c9d
      env:
        - name: GOPATH
          value: /projects:/home/user/go
        - name: GOCACHE
          value: /tmp/.cache
      memoryLimit: 2Gi
      mountSources: true
projects:
  - name: kubernetes-image-version-checker
    git:
      remotes:
        origin: "https://gitlab.imanuel.dev/DerKnerd/kubernetes-image-version-checker.git"
```

The image itself is public, so if anyone needs Golang 1.19 in Che, feel free to use it :slightly_smiling_face:
