### ISSUE TITLE
To start VS Code, use `post-start` rather than overriding the entrypoint

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21879]
### Is your enhancement related to a problem? Please describe

VS Code `che-code-runtime-description` component contributes the container `command` to the tooling container:

```yaml
(...)
  - schemaVersion: 2.1.0
    metadata:
      name: che-incubator/che-code/insiders
    (...)
    components:
      - name: che-code-runtime-description
        attributes:
          controller.devfile.io/container-contribution: true 
        container:
          (...)
          command:
            - /checode/entrypoint-volume.sh
```

As a result, the script `/checode/entrypoint-volume.sh` is executed at workspace startup, but the tooling container entrypoint (for example [UDI's](https://github.com/devfile/developer-images/blob/main/base/ubi8/entrypoint.sh)) is not. 

This is problematic as the tooling container entrypoint may be used to initialise development tools and runtimes.

### Describe the solution you'd like

We should use [a `post-start` event](https://devfile.io/docs/2.2.0/adding-event-bindings#post-start-object) rather than the `command` to start VS Code.

That should be tested though and may require some tweaks to the VS Code startup script (or not).

This is currently VS Code specific but will JetBrains and Theia may be affected too if [this feature is implemented in the meantime](https://github.com/eclipse/che/issues/21878).
