### ISSUE TITLE
Eclipse Che 7.57.0 Installed via chectl references non-existent container images in quay.io

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#21891]
### Describe the bug

The che-gateway Deployment fails to roll out due to failed image pulls:

```bash
Failed to pull image "quay.io/openshift/origin-kube-rbac-proxy@sha256:511e2288e987027a9e044f789ca117cd1d9a91744a8427e3dc841dd613554613": rpc error: code = Unknown desc = reading manifest sha256:511e2288e987027a9e044f789ca117cd1d9a91744a8427e3dc841dd613554613 in quay.io/openshift/origin-kube-rbac-proxy: manifest unknown: manifest unknown
```

```bash
Failed to pull image "quay.io/openshift/origin-oauth-proxy@sha256:0e72ed64cdf76828392ef8cfe4ee49d644a013ac00ff1590d6c53774d77615e3": rpc error: code = Unknown desc = reading manifest sha256:0e72ed64cdf76828392ef8cfe4ee49d644a013ac00ff1590d6c53774d77615e3 in quay.io/openshift/origin-oauth-proxy: manifest unknown: manifest unknown
```

The referenced images do not appear to exist in quay.io.  A `podman pull` with the same image reference returns the same errors as above.

### Che version

7.57

### Steps to reproduce

```bash
chectl server:deploy --platform openshift
```

Observe that the che-gateway Deployment fails to roll out.

### Expected behavior

Successful rollout of all Deployments

### Runtime

OpenShift

### Installation method

chectl/latest

### Environment

macOS

**Comment by cgruver** [comment]
__Note:__ The issue appears to be resolved in the `next` channel.

```bash
    ✔ Wait Eclipse Che active...[OK]
  ✔ Retrieving Eclipse Che self-signed CA certificate...[OK: /var/folders/69/jbwfymx15kn6_xw4bc5rsg_m0000gn/T/cheCA.crt]
  ✔ Prepare post installation output...[OK]
  ✔ Show important messages
    ✔ Eclipse Che next has been successfully deployed.
    ✔ Documentation             : https://www.eclipse.org/che/docs/
    ✔ -------------------------------------------------------------------------------
    ✔ Users Dashboard           : https://eclipse-che.apps.okd4-region-01.dc1.clg.lab/dashboard/
    ✔ -------------------------------------------------------------------------------
    ✔ Plug-in Registry          : https://eclipse-che.apps.okd4-region-01.dc1.clg.lab/plugin-registry/v3/
    ✔ Devfile Registry          : https://eclipse-che.apps.okd4-region-01.dc1.clg.lab/devfile-registry/
    ✔ -------------------------------------------------------------------------------
Command server:deploy has completed successfully in 05:08.
```

**Comment by tolusha** [comment]
@cgruver 
Please try:
1. `chectl update stable` updates chectl to 7.58.0
2. `chectl server:deploy -p openshift`

It seems `quay.io/repository/openshift/origin-oauth-proxy:4.9` has been unexpectedly updated.

[1] https://quay.io/repository/openshift/origin-oauth-proxy?tab=tags&tag=4.9

**Comment by cgruver** [comment]
@tolusha  It looks like `chectl 7.58.0` is still installing Che `7.57.0`

I deleted the install from `next` channel first.  Then switched chectl to the stable channel.

```bash
chectl --version
chectl/7.58.0 darwin-x64 node-v16.13.2
```

Output from `chectl server:deploy -p openshift`

```bash
    ❯ Gateway pod bootstrap
      ✔ Scheduling...[OK]
      ✖ Downloading images
        → Failed to download image, reason: ErrImagePull, message: rpc error: co
…
        Starting
      Eclipse Che Server pod bootstrap
      Wait Eclipse Che active
    Retrieving Eclipse Che self-signed CA certificate
    Prepare post installation output
    Error: Command server:deploy failed with the error: Failed to download 
    image, reason: ErrImagePull, message: rpc error: code = Unknown desc = 
    reading manifest 
    sha256:511e2288e987027a9e044f789ca117cd1d9a91744a8427e3dc841dd613554613 in
     quay.io/openshift/origin-kube-rbac-proxy: manifest unknown: manifest 
```

Installed version of the Che Operator is still 7.57.0:

```bash
oc get csv -n openshift-operators
NAME                            DISPLAY                 VERSION   REPLACES                        PHASE
devworkspace-operator.v0.17.0   DevWorkspace Operator   0.17.0    devworkspace-operator.v0.16.0   Succeeded
eclipse-che.v7.57.0             Eclipse Che             7.57.0    eclipse-che.v7.56.0             Succeeded
```

**Comment by cgruver** [comment]
I switched back to the `next` channel for now.  It installs `7.58.0-737.next`

**Comment by tolusha** [comment]
I use chectl 7.58.0 and successfully deployed Eclipse Che 7.58.0 on OpenShift.
Have you uninstalled a previous version with `chectl server:delete --delete-all` before?

```
chectl server:deploy -p openshift                                                                                                                  
...
    ✔ Eclipse Che 7.58.0 has been successfully deployed.
```

**Comment by cgruver** [comment]
I did delete the previous install, but did not include the `--delete-all` flag.  I'll try that again and see if my cluster just had a stale catalog source from the stable channel.

**Comment by cgruver** [comment]
@tolusha I re-ran the delete, update, and install.

```bash
chectl server:delete --delete-all
chectl update stable
```

```bash
chectl version
chectl/7.58.0 darwin-x64 node-v16.13.2
```

```bash
chectl server:deploy -p openshift 
...
    ❯ Gateway pod bootstrap
      ✔ Scheduling...[OK]
      ✖ Downloading images
        → Failed to download image, reason: ErrImagePull, message: rpc error: code = Unknown desc = reading manifest 
…
        Starting
      Eclipse Che Server pod bootstrap
      Wait Eclipse Che active
    Retrieving Eclipse Che self-signed CA certificate
    Prepare post installation output
    Error: Command server:deploy failed with the error: Failed to download image, reason: ErrImagePull, message: 
    rpc error: code = Unknown desc = reading manifest 
    sha256:511e2288e987027a9e044f789ca117cd1d9a91744a8427e3dc841dd613554613 in 
    quay.io/openshift/origin-kube-rbac-proxy: manifest unknown: manifest unknown. See details: 
    /Users/charrogruver/Library/Caches/chectl/error.log. Eclipse Che logs: 
    /var/folders/69/jbwfymx15kn6_xw4bc5rsg_m0000gn/T/chectl-logs/1671541044614.
```

The `CSV` is still `v7.57.0` for some reason...

```bash
oc get csv -n openshift-operators
NAME                            DISPLAY                 VERSION   REPLACES                        PHASE
devworkspace-operator.v0.17.0   DevWorkspace Operator   0.17.0    devworkspace-operator.v0.16.0   Succeeded
eclipse-che.v7.57.0             Eclipse Che             7.57.0    eclipse-che.v7.56.0             Succeeded
```

**Comment by cgruver** [comment]
The instance of Eclipse Che reported in the Community Operators is still `v7.57.0` I think that's what's going on here.

I'm going restart the Community Operators catalog source and see if it pulls an updated image for `v4.12`.

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
    operatorframework.io/managed-by: marketplace-operator
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
  creationTimestamp: '2022-12-14T21:16:25Z'
  ...
  name: community-operators
  namespace: openshift-marketplace
spec:
  displayName: Community Operators
  ...
  image: 'registry.access.redhat.com/redhat/community-operator-index:v4.12'
  priority: -400
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m0s
status:
  connectionState:
    address: 'community-operators.openshift-marketplace.svc:50051'
    lastConnect: '2022-12-20T12:57:50Z'
    lastObservedState: READY
  latestImageRegistryPoll: '2022-12-20T13:07:51Z'
  registryService:
    createdAt: '2022-12-14T21:16:25Z'
    port: '50051'
    protocol: grpc
    serviceName: community-operators
    serviceNamespace: openshift-marketplace
```
