### ISSUE TITLE
Running multiple postStart events is not allowed.

### ISSUE THREAD

**Issue by MazArslan** [eclipse/che#21903]
### Describe the bug

When I try to use multiple post start events, i get an error saying that `Error processing devfile: component tools has multiple postStart events attached to it`. As per the devfile 2 schema validation, this is a valid syntax, since both, postStart and commands are accepting array of elements.

### Che version

7.58@latest

### Steps to reproduce

```
schemaVersion: 2.1.0
metadata:
  name: demo-project
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-f5ffca8
      memoryRequest: 1Gi
      memoryLimit: 3Gi
      cpuLimit: 1000m
      cpuRequest: 500m
commands:
  - id: second-command
    exec:
      component: tools
      commandLine: "echo second command"
  - id: install
    exec:
      component: tools
      commandLine: "/home/user/.sdkman/candidates/jbang/current/bin/jbang trust add -o --fresh --quiet https://github.com/apache/camel/blob/HEAD/dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java"
events:
  postStart:
    - install
    - second-command
```

create 2 commands and use both on a post start

when trying to run use the devfile getting this issue when trying to create workspace
`Error processing devfile: component tools has multiple postStart events attached to it`

### Expected behavior

to apply the both/multiple post start events. 

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

other (please specify in additional context)

**Comment by karatkep** [comment]
I guess the issue that you want to run two `postStart` events for one `component`.
If you want to run two (or more) `postStart` events for the one `component` you can try to split commands by ";". For example:
```
schemaVersion: 2.1.0
metadata:
  name: demo-project
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-f5ffca8
      memoryRequest: 1Gi
      memoryLimit: 3Gi
      cpuLimit: 1000m
      cpuRequest: 500m
commands:
  - id: two-commands
    exec:
      component: tools
      commandLine: "/home/user/.sdkman/candidates/jbang/current/bin/jbang trust add -o --fresh --quiet https://github.com/apache/camel/blob/HEAD/dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java; echo second command"
events:
  postStart:
    - two-commands
```
