### ISSUE TITLE
What is  best practice installing Che locally in M1 Mac

### ISSUE THREAD

**Issue by yuki-ohnaka-cv** [eclipse/che#21908]
### Summary

I've tried installing che on M1 Mac but it doesn't work.
If you have a track record of working well on M1 Mac, can you let me know?

- [Installing Che on Minikube](https://www.eclipse.org/che/docs/stable/administration-guide/installing-che-on-minikube/)
- https://github.com/eclipse/che/issues/21889

### Relevant information

- Apple M1 Pro
- macOS 13.1

**Comment by AObuchow** [comment]
Eclipse Che is not currently supported on the M1 ARM architecture, as the container images used in Che are not being compiled for this architecture. The main reason being that the primary use case is to run Che on a cluster, and the M1 ARM architecture is currently targeting personal computers. 

However, making M1 ARM builds of the container images used in Che should be possible - though I do not foresee these builds being officially supported. 

I briefly looked into Docker supporting x86 binaries and found [this issue](https://github.com/docker/roadmap/issues/384 ), which is still not resolved, unfortunately.

I have a personal M1 MacBook Pro and may be able to help in this area (e.g. configuring builds for m1 ARM & testing them), though I cannot make any promises due to other task priorities.

 CC: @l0rd

**Comment by yuki-ohnaka-cv** [comment]
@AObuchow 
Thank you for the answer.I'm sorry Che not supported M1 ARM.
Have you tried Lima, which can run x86_64 VMs on M1 ARM?(I'm not doing well...  #21889 )

CC: @l0rd

**Comment by sgaist** [comment]
Hi,

You can deploy che on a Mac M1. The main issue is the che-operator image however that can be easily circumvented. Use the image hash to ensure that one is used. Docker on an M1 is capable of running both amd64 and arm64 images. For example: `--che-operator-image=quay.io/eclipse/che-operator@sha256:e61d2f3a43edb62c8b06a98d3113b0a14df5cb58b39d9c55a7e235a10262af3c` (this is for version 7.59.0 of the operator).

For the rest, you will have to adapt the minikube guidelines. You can get some inspiration from this [gist](https://gist.github.com/tolusha/345c59eb36a136ffdbce61acbee9c50a) written for minikube. While the stack is a bit different, the workflow is the same. 

- generate endpoints certificates
- configure Docker Desktop's k8s cluster
- deploy Keycloak
- configure Keycloak
- deploy Che

For the Docker-Desktop configuration, you will have to go into the VM to edit the `kube-apiserver.yaml` manifest file that can be found in `/var/lib/kubeadm/manifests` (make a copy first).

To copy the certificate for Keycloak, copy and paste it in vi, it's the easier way. Note that you will also need to add a volume and a volumeMount for it in the `kube-apiserver.yaml` manifest.

On a side note, the way Keycloak is deployed in the gist means that every time it's restarted you'll lose the data in there. If you want something that is persistent, you should deploy it with a PostgreSQL backend.

You can then finally install Che using `chectl` rather than the helm chart as done in the gist. You will want to use larger timeouts, the che pod can take very long to start. Check the pod states even if `chectl` claims failure as it could simply be the startup time.

Here is an example CheCluster CRD

```yaml
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  networking:
    domain: WWW.XXX.YYY.ZZZ.nip.io
    auth:
      identityProviderURL: https://keycloak.WWW.XXX.YYY.ZZZ.nip.io/realms/che
      oAuthClientName: k8s-client
      oAuthSecret: k8s-client

  components:
    cheServer:
      extraProperties:
        CHE_OIDC_USERNAME__CLAIM: 'email'
```

the oAuthXXX values matches the one that you will have if using the gist to create the Keycloak realm.

You might also want to give more storage and RAM for Docker to run.
