### ISSUE TITLE
When configuring remotes with url param keep `checkoutFrom.revision` if able

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#21921]
When creating a workspace with a factory url with a branch:
```
{CHE-HOST}/#https://github.com/eclipse-che/che-plugin-registry/tree/7.59.x
```

The `checkoutFrom.revision` for the resulting DW is `7.59.x`, meaning, when opening the workspace, the branch that is checked out is `7.59.x`:
```
projects:
  - git:
      checkoutFrom:
        revision: 7.59.x
      remotes:
        origin: 'https://github.com/eclipse-che/che-plugin-registry'
    name: che-plugin-registry
```

But, if we take the url above and configure remotes on top of it, by setting `origin` to `https://github.com/dkwon17/che-plugin-registry` and `upstream` to `https://github.com/eclipse-che/che-plugin-registry`:

```
{CHE-HOST}/#https://github.com/eclipse-che/che-plugin-registry/tree/7.59.x?remotes={{origin,https://github.com/dkwon17/che-plugin-registry},{upstream,https://github.com/eclipse-che/che-plugin-registry}}
```

The `checkoutFrom.revision` is not set in this case, because there is no guarantee that the `7.59.x` branch exists in the newly configured `origin` remote:
```
projects:
  - git:
      checkoutFrom:
        remote: origin
      remotes:
        origin: 'https://github.com/dkwon17/che-plugin-registry'
        upstream: 'https://github.com/eclipse-che/che-plugin-registry'
    name: che-plugin-registry
```

Therefore, it would be great to have some way to configure the `checkoutFrom.revision` field when specifying remotes.

### Describe the solution you'd like

Add logic to confirm that the remote specified in `git.checkoutFrom.remote` contains the branch/revision from the Git Url used to create the project.

If yes, set `checkoutFrom.revision`.

### Describe alternatives you've considered

https://github.com/eclipse/che/issues/21922

### Additional context

This feature is helpful for https://github.com/redhat-actions/try-in-web-ide/issues/14, since it would help the GitHub action to set up remotes as well as set up the `checkoutFrom.revision` branch.
