### ISSUE TITLE
If re-branded che-code won't connect to the embedded openvsx

### ISSUE THREAD

**Issue by jsomsanith** [eclipse/che#21962]
### Summary

Hi Eclipse Che team 👋
(I don't know if that's a bug or something I missed in my configuration)

**What am I trying to do ?**
I want to run a vscode that consumes a custom che-plugin-registry for vscode extensions, instead of the default open-vsx.

**What have I done ?**
1. Build a che-plugin-registry with my extra extension in it.

2. Deploy Che on kubernetes, overriding the plugin registry image and setting `openVSXURL` to an empty string. (This is supposed to force the extension url to use the one from the embedded plugin-registry)

```yaml
kind: CheCluster
apiVersion: org.eclipse.che/v2
spec:
  components:
    pluginRegistry:
      openVSXURL: ""
      deployment:
        containers:
        - image: jsomsanith/che-plugin-registry:7.59.0
          imagePullPolicy: Always
```

**What result I have ?**
I create a new workspace in che, and in vs-code, while searching for extensions, it still consumes open-vsx and it doesn't find my extra extension.

### Relevant information

**What have I discovered during investigation ?**

1. The default extension url (open-vsx) is set in the [product.json](https://github.com/che-incubator/che-code/blob/main/code/product.json#L95) file in vscode.

2. On vscode build, a [script](https://github.com/che-incubator/che-code/blob/main/code/build/gulpfile.vscode.web.js#L100) replaces a placeholder in [product.ts](https://github.com/che-incubator/che-code/blob/d774fdfb748e0276c330fa478c80609fcef11b11/code/src/vs/platform/product/common/product.ts#L56) code. This code is the class that is injected everywhere to get the `product.json` configuration. It takes the content of `globalThis._VSCODE_PRODUCT_JSON` if defined, otherwise, it's the default content (that replaced the placeholder).

3. The che customisation of vscode introduces a script: [entrypoint-volume.sh](https://github.com/che-incubator/che-code/blob/main/build/scripts/entrypoint-volume.sh#L50). This script is executed on [workspace creation](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L370).
If the `OPENVSX_REGISTRY_URL` env var is defined and is empty, it replaces the extensions url in product.json with the value of `CHE_PLUGIN_REGISTRY_URL` env var.

4. In my workspace devfile, I can see the correct values of the env vars
```yaml
components:
  - attributes:
      controller.devfile.io/merge-contribution: true
    container:
      env:
        - name: CHE_DASHBOARD_URL
          value: 'https://che.localtest.me'
        - name: CHE_PLUGIN_REGISTRY_URL
          value: 'https://che.localtest.me/plugin-registry/v3'
        - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
          value: 'http://plugin-registry.eclipse-che.svc:8080/v3'
        - name: OPENVSX_REGISTRY_URL
          value: ''
      image: 'quay.io/devfile/universal-developer-image:ubi8-0e189d9'
      memoryLimit: 512Mi
      mountSources: true
      sourceMapping: /projects
    name: tools
```

5. I checked the `product.json` in the pod and it contains the right replaced values (no open-vsx) 🎉.
**But**, in the che-code output, there is no web client code that will import and consume this `product.json`; only imported by some code that is executed on the (node) server side. 🤔
The scripts that the web vscode downloads, consumes the values from `product.ts`. `globalThis._VSCODE_PRODUCT_JSON` is not defined, so I end up with the default extension url.
