### ISSUE TITLE
Add support for VS Code Predefined Variables for Devfile Commands

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#21976]
### Is your task related to a problem? Please describe

> Visual Studio Code supports variable substitution in [Debugging](https://code.visualstudio.com/docs/editor/debugging) and [Task](https://code.visualstudio.com/docs/editor/tasks) configuration files

https://code.visualstudio.com/docs/editor/variables-reference

It works OOTB for the Debug Configurations and all Tasks except the translated from the Devfile Commands.
It's because for running the Devfile Commands we have a [custom extension](https://github.com/che-incubator/che-code/tree/main/code/extensions/che-commands) that knows nothing about VS Code's Predefined Variables.

When I try to run a Devfile Command like:
```yaml
...
commands:
    - id: current-file
        exec:
          label: "Test current file"
          component: nodejs
          workingDir: ${PROJECTS_ROOT}/web-nodejs-sample/app
          commandLine: cat "${file}"
```

Che-Code isn't able to process it:

![image](https://user-images.githubusercontent.com/1636395/215830602-ed1e3223-beeb-4bbe-9305-c7a031b7cba7.png)

### Describe the solution you'd like

We need to add support for VS Code Predefined Variables for the Tasks translated from the Devfile Commands.

The biggest challenge here is that we need to find a way how to implement it on the extension side reusing VS Code's built-in functionality.  

### Additional context

Test project: https://github.com/svor/web-nodejs-sample/tree/test-commands
