### ISSUE TITLE
[CheCode] Websocket closed & project not showing in file explorer

### ISSUE THREAD

**Issue by AObuchow** [eclipse/che#21977]
### Describe the bug

I recently have been experiencing a `The workbench failed to connect to the server (Error: Websocket close with status code 1006)` error when using a DevWorkspace that has Che Code being contributed. Upon refreshing the page, the same error would pop up, or one that says `The workbench failed to connect to the server (Error: Canceled)`.

Here are screenshots of the errors:
![image](https://user-images.githubusercontent.com/10300119/215968758-86b1f771-348b-4f03-9bb8-4ce58ad7600d.png)
![image](https://user-images.githubusercontent.com/10300119/215968771-656c12aa-b99e-4bfd-9095-d74893f66f4f.png)

Two other behaviours I noticed:
1. The editor starts up, but the project name in the file explorer has yellowed text. When clicking on the project in the file explorer, I got the following error:
![image](https://user-images.githubusercontent.com/10300119/215969117-61055f68-4363-47bb-bc98-73a3c92ef747.png)
This behaviour wasn't always reproducible, however - I only got it to occur once in testing.

2. When using a DevWorkspace that defined multiple projects, only a single project appears in the file explorer. Opening a terminal and navigating to the projects folder shows that all projects have been cloned to the file system correctly. Perhaps this is just a result of the DevWorkspace configuration, rather than a bug?

 I apologize that this bug report is a bit unclear (3 different types of issue behaviours are described) - I am not sure yet if this all results from Che Code bug(s) or a DevWorkspace that isn't correctly configured. The DevWorkspaces used to reproduce these issues used to use Theia and are now using Che Code.

### Che version

7.60@latest

### Steps to reproduce

To reproduce the `The workbench failed to connect to the server (Error: Websocket close with status code 1006)` and `The workbench failed to connect to the server (Error: Canceled)` errors:

1. Install DWO 0.18.0
2. Apply the following DevWorkspace:

```YAML
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: code-latest
spec:
  started: true
  template:
    projects:
      - name: web-nodejs-sample
        git:
          remotes:
            origin: "https://github.com/che-samples/web-nodejs-sample.git"
    components:
      - name: dev
        container:
          image: quay.io/devfile/universal-developer-image:latest
    commands:
      - id: say-hello
        exec:
          component: dev
          commandLine: echo "Hello from $(pwd)"
          workingDir: ${PROJECT_SOURCE}/app
  contributions:
    - name: che-code
      uri: https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/che-incubator/che-code/latest/devfile.yaml
      components:
        - name: che-code-runtime-description
          container:
            env:
              - name: CODE_HOST
                value: 0.0.0.0
```
3. Wait for the workspace to start then try opening the workspace URL. The error pop-ups should appear. I found that this happened more frequently on Firefox, but still happened sometimes on Chrome.

I also experienced the websocket error in testing [another issue](https://github.com/eclipse/che/issues/21971#issuecomment-1410887921). The following [factory link](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/l0rd/quarkus-api-example?che-editor=https://gist.githubusercontent.com/l0rd/a47c07e4202fa4c5ad6f35a5fd9c1622/raw/abf43e583edca62ac5c226259137fc02b91afd63/vscode-poststart.yaml) resulted in similar behaviour.

To reproduce the behaviour where only a single project is shown in the file explorer, despite the DevWorkspace defining multiple projects:
1. Install DWO 0.18.0
2. Apply the following DevWorkspace:

```YAML
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: git-clone-sample-devworkspace
spec:
  started: true
  template:
    projects:
      - name: web-nodejs-sample
        git:
          remotes:
            origin: "https://github.com/che-samples/web-nodejs-sample.git"
      - name: devworkspace-operator
        git:
          checkoutFrom:
            remote: amisevsk
            revision: clone-projects-on-start
          remotes:
            origin: "https://github.com/devfile/devworkspace-operator.git"
            amisevsk: "https://github.com/amisevsk/devworkspace-operator.git"
    commands:
      - id: say-hello
        exec:
          component: che-code-runtime-description
          commandLine: echo "Hello from $(pwd)"
          workingDir: ${PROJECT_SOURCE}/app
  contributions:
    - name: che-code
      uri: https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/che-incubator/che-code/latest/devfile.yaml
      components:
        - name: che-code-runtime-description
          container:
            env:
              - name: CODE_HOST
                value: 0.0.0.0
```

3. Wait for the workspace URL to become available `kubectl get dw -n $NAMESPACE -w`
4. Open the workspace URL, and see that there is only the web-nodejs-sample project in the file explorer and that the devworkspace-operator project is missing in the file explorer.

![image](https://user-images.githubusercontent.com/10300119/215971580-93bfaac8-4789-4ac8-bdbf-986929fcd525.png)

### Expected behavior

No websocket related error popups should be showing (these prevent you from actually using the editor) and all projects defined in the DevWorkspace should be viewable from the file explorer.

### Runtime

OpenShift

### Installation method

other (please specify in additional context)

### Environment

Linux

### Additional context

These issues came up while updating the DevWorkspace repo samples to use che code rather than theia: https://github.com/devfile/devworkspace-operator/pull/1025#issuecomment-1411007467

The issue also occurred in testing another bug: https://github.com/eclipse/che/issues/21971#issuecomment-1410887921
