### ISSUE TITLE
Add an optional annotation for disableSubdomainIsolation config

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#21986]
### Is your enhancement related to a problem? Please describe

There is an ability to configure OAuth for Github Enterprise server without subdomain isolation added by https://github.com/eclipse/che/issues/21724 :
```
spec:
  gitServices:
    github:
      - endpoint: 'https://github.com'
        secretName: github-oauth-config
        disableSubdomainIsolation: true
```
It would be great to have the similar configuration via the oauth secret annotations.

### Describe the solution you'd like

Add an optional annotation field to the github oauth secret config e.g.
```
  annotations:
    che.eclipse.org/oauth-scm-server: github
    che.eclipse.org/scm-server-endpoint: <github_server_url>
    che.eclipse.org/scm-github-disableSubdomainIsolation: <true/false>
```

### Additional context

See https://github.com/eclipse/che/issues/21964
