### ISSUE TITLE
Improving git configuration with PAT documentation

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21989]
### Is your enhancement related to a problem? Please describe

Making PAT work at first try is hard, that's the recurrent feedback we get from customers. I have tried to configure it for BitBucket following [the documentation](https://www.eclipse.org/che/docs/stable/end-user-guide/using-a-git-provider-access-token/) and spent a couple of hours to make it work.

### Describe the solution you'd like

- [ ] Retrieving BB user id (for the annotation `che.eclipse.org/scm-userid`) is not straightforward. That's because using the curl command that is linked in the documentation fails with non-authorized. **A link to the [authentication for BB API](https://developer.atlassian.com/server/bitbucket/how-tos/example-basic-authentication/) should be added too**.
- [ ] I initially set `che.eclipse.org/scm-userid: 2` because BB user id is an integer. But the secret failed to be parsed because a string is expected. **We should document that the `scm-userid` should be wrapped with `""` or `''`.**
- [x] I accidentally included a newline char in the PAT that I copied in the secret. As a result che-server thrown an Internal Server Error (`java.lang.IllegalArgumentException: invalid header value:...`). That was a mistake on my side but **che-server should be more robust and trim blank chars at the beginning and at the end of the token string**.
- [x] I didn't know exactly what URL to use: `https://{bb-host}/users/{user-slug}/repos/{repo-name}/` didn't work but `https://{bb-host}/scm/~{user-slug}/{repo-name}.git`. **We should support both BB URL schemas**.
- [ ] When using PAT and the repository is private (the default for BB), cloning fails and the workspace does not work. That's because the DevWorkspace operator is not mounting the PAT as a git-credential store and `project-clone` fails to git clone the repository. **We should mention that PAT and git-credentials should be used together and we should document how to do that.**
- [ ] After successfully setting up the PAT secret, git clone continued to fail because BB was using an untrusted SSL certificate. **The article "[Deploying Che with support for Git repositories with self-signed certificates](https://www.eclipse.org/che/docs/stable/administration-guide/deploying-che-with-support-for-git-repositories-with-self-signed-certificates/)" should be referenced as an "additional resource".**
- [ ] The article "[Deploying Che with support for Git repositories with self-signed certificates](https://www.eclipse.org/che/docs/stable/administration-guide/deploying-che-with-support-for-git-repositories-with-self-signed-certificates/)" had its problems too:
  - [ ] It's hard to find although I suspect that's one of the most read articles (`admin guide -> configuring dev spaces -> configuring workspaces globally -> git with self-signed certificates`...) 
  - [ ] Specifying the `gitTrustedCertsConfigMapName` in `CheCluster` is redudant: we should just use labels/annotations to automatically inject the config map.
  - [ ] As some point the configmap is referenced as a secret ("All Secrets that hold certificate files...")
  - [ ] It's not clear if certs in binary format are supported or not (they are not supported but this sentence is confusing "Also, they can be encoded as binary data, for example, .cer...")
  - [ ] It doesn't mention that the certificate chain is required
  - [ ] It doesn't mention that in the `githost` the protocol (i.e. `https`) is required
  - [ ] It doesn't mention what cert should used (`ingress operator` or `*.apps`?)

### Additional information

For reference this is the PAT secret that I had to use to make it work (I had to add `controller.devfile.io/*` labels/annotations + `credentials` in `data`) :

```
kind: Secret
apiVersion: v1
metadata:
  name: personal-access-token-mario-bb
  labels:
    app.kubernetes.io/component: scm-personal-access-token
    app.kubernetes.io/part-of: che.eclipse.org
    controller.devfile.io/git-credential: 'true'
    controller.devfile.io/watch-secret: 'true'
  annotations:
    che.eclipse.org/che-userid: kube:admin 
    che.eclipse.org/scm-personal-access-token-name: bitbucket-server 
    che.eclipse.org/scm-url: https://bitbucket-bitbucket.apps.mloriedo-devworkspaces.devcluster.openshift.com 
    che.eclipse.org/scm-userid: '2' 
    che.eclipse.org/scm-username: mario
    controller.devfile.io/mount-path: /etc/secret
data:
  token: ...
  credentials: ...
type: Opaque
```
