### ISSUE TITLE
Specify labels for eclipse-che deployments using CheCluster

### ISSUE THREAD

**Issue by matcasx** [eclipse/che#22005]
### Is your enhancement related to a problem? Please describe

I'd like to have the possibility to add custom labels to eclipse-che pods (che-dashboard, che gateway, che) using the CheCluster CR.
It would be useful to integrate eclipse-che with tools like istio that use of labels such as "istio-injection=enabled" to select pods.

### Describe the solution you'd like

CheCluster CR already allow some kind of customization for the for the different che components. I 'dlike to have an additional key "labels" for each component where I can specify additional labels to add to the deployment.
```
spec:
  components:
    cheServer:
      deployment: 
         labels:
           app: foo
    dashboard:
      deployment: 
         labels:
           app: foo
    database:
      deployment: 
         labels:
           app: foo
    auth:
      gateway:
        deployment: 
           labels:
             app: foo

```

### Describe alternatives you've considered

Even a different specification for the CheCluster CR would be fine.

**Comment by martinelli-francesco** [comment]
It would be useful to have the same thing for workspace deployments as well.
Maybe it is already supported by devfile (attributes entry of components?), but I didn't understand if it is and what the syntax is.

**Comment by tolusha** [comment]
@matcasx 
To specify additional labels for workspace pod, you can modify your devfile [1], for instance: 
```
  - attributes:
      pod-overrides:
        metadata:
          labels:
            a: b
```

[1] https://devfile.io/docs/2.2.0-alpha/overriding-pod-and-container-attributes#pod-overrides
