### ISSUE TITLE
defaultPlugins from CR are ignored and not applied anymore during workspace startup

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22017]
### Describe the bug

Previously it was possible to reference default plugins as devfile.yaml  for various editors from CR:
```
devEnvironments:
      defaultComponents:
        - container:
            image: 'quay.io/devfile/universal-developer-image:ubi8-38da5c2'
            sourceMapping: /projects
          name: universal-developer-image
      defaultNamespace:
        template: <username>-dev
      defaultPlugins:
        - editor: eclipse/che-theia/latest
          plugins:
            - >-
              https://example.com/devfile.yaml
        - editor: eclipse/che-theia/next
          plugins:
            - >-
              https://example.com/devfile.yaml
       - editor: che-incubator/che-code/insiders
         plugins:
            - >-
              https://example.com/devfile.yaml 
```

### Che version

7.58

### Steps to reproduce

1. update CR accordingly based on description
2. start a workspace and check if the default plugin is applied
3. ERROR: plugins specified in CR are ignored

### Expected behavior

plugins are added to the resulting DevWorkspace

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon
