### ISSUE TITLE
Support passthrough TLS termination on Devfile endpoints in OpenShift

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#22028]
### Is your enhancement related to a problem? Please describe

There is no way to configure TLS termination for devfile endpoints in Che workspaces on OpenShift. This makes it difficult to use in cases where we want to test SSL in the application being developed. 

### Describe the solution you'd like

Define an attribute(s) for endpoints that enable configuring TLS termination for an endpoint in the devfile, e.g. 
```yaml
- attributes:
    tls-termination: Passthrough
  exposure: public
  name: my-endpoint
  protocol: https
  targetPort: 8080
```

### Additional context

Originally reported in https://issues.redhat.com/browse/CRW-4079
