### ISSUE TITLE
Make every workspace containers and init containers configurable

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22036]
### Is your enhancement related to a problem? Please describe

The spec of these workspace pod containers is not configurable:
- gateway container
- project-clone container

This can be annoying if we want to remove the CPULimit of these containers for example.

### Describe the solution you'd like

Add the fields `gatewayContainer` and `projectCloneContainer` under CheCluster `devEnvironments`:

```yaml
spec:
  devEnvironments:
    gatewayContainer:
        (...container settings...)
    projectCloneContainer:
        (...container settings...)
```

- The container API is already defined in [the CheCluster API](https://github.com/eclipse-che/che-operator/blob/main/api/v2/checluster_types.go#L546).
- Setting a container field empty should result in the property not being set. For example, to unset the gateway CPU limit (and keep the other container properties):

  ```yaml
  spec:
    devEnvironments:
      gatewayContainer:
        resources:
          limits:
            cpu: '0'
  ```

### Additional context

- [Downstream issue](https://issues.redhat.com/browse/CRW-4070)
