### ISSUE TITLE
To start JetBrains IDEs, use `post-start` rather than overrideing the entrypoint

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22034]
### Is your enhancement related to a problem? Please describe

The [editor command](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L452) overrides the tooling container entrypoint:
- if the user had specified the container `command` in his devfile
- if the tooling container had a specific entrypoint + command

This blocks services as kubedock (to support `docker run`) to be run at startup in tooling containers.

### Describe the solution you'd like

The solution is the same as the one provided [for VS Code](https://github.com/eclipse-che/che-plugin-registry/pull/1566/files), remove the command in the editor container and a an `init-che-code-command` among the devfile commands associated to a post-start event:

```yaml
(...)
  commands:
      - id: init-che-code-command
        exec:
          component: che-code-runtime-description
          commandLine: 'nohup /checode/entrypoint-volume.sh > /checode/entrypoint-logs.txt 2>&1 &'
  events:
      postStart:
        - init-che-code-command
```
