### ISSUE TITLE
Add the Smoke test PR check for Che-Server repository

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#22047]
### Is your task related to a problem? Please describe

Run Smoke GUI test on new pull request (PR) or new commit to pull request in repo https://github.com/eclipse-che/che-server/

### Describe the solution you'd like

Create GitHub actions on pull request events to do:
1. Build che-server image
2. Deploy OpenShift instance on Prow Ci
3. Install Eclipse Che next using che-server image from PR, by patching CheCluster, e.g.:
```
apiVersion: org.eclipse.che/v2
spec:
  components:
    cheServer:
      deployment:
        containers:
          - image: 'quay.io/crw_pr/che-server:<PR_NUMBER>'
```
4. Run smoke GUI test against Eclipse Che instance
5. Collect the logs and shutdown OpenShift instance.
