### ISSUE TITLE
As an Admin, I want to have the possibility to configure a number of replicas for operands from the CR

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22067]
### Is your task related to a problem? Please describe

After the removal of dependency on database, it is now possible to run multiple che-servers (and other operands) in parallel. As an Admin, I want to have the possibility to configure a number of replicas for operands from the CR.

### Describe the solution you'd like

`replicas` CR property for each operand e.g. 

```
spec:
  components:
    cheServer:
      deployment:
        replicas: 1
    dashboard:
      deployment:
        replicas: 1
    devfileRegistry:
      deployment:
        replicas: 1
    pluginRegistry:
      deployment:
        replicas: 1
```

By default, we can opt for 1, but admin can update the CR accordingly with explicit number of replicas for each operand

### Describe alternatives you've considered

N / A

### Additional context

Related to https://github.com/eclipse/che/issues/7662

**Comment by ibuziuk** [comment]
@l0rd @tolusha could you please review the proposal? I do think we have the bandwidth to add it in the next 234 sprint but would be great to discuss it and prioritize for the future sprints

**Comment by l0rd** [comment]
Thanks @ibuziuk for opening this. I would rather add it under deployment as replica is a deployment spec:

```yaml
spec:
  components:
    cheServer:
      deployment:
        replicas: 1
    dashboard:
      deployment:
        replicas: 1
    devfileRegistry:
      deployment:
        replicas: 1
    pluginRegistry:
      deployment:
        replicas: 1
```
