### ISSUE TITLE
Can't run an homemade editor with an empty devfile

### ISSUE THREAD

**Issue by sgandon** [eclipse/che#22065]
### Describe the bug

Hello,
I can't get to run my home made editor that I contributed to the plugin registry and provide an empty dev file and clone a given git repository.

I have try to launch using : 
1/ this url
```
https://192.168.49.2.nip.io#https://github.com/sgandon/studio-project?new&che-editor=talend/studio/8.0&url=https://192.168.49.2.nip.io/devfile-registry/devfiles/talend-studio-jobs/devfile.yaml
```
By doing this it does consider the my devfile and use it but it does not consider the github repository and does not launch the `project-clone` init-container and also does not record the github repo in the configmap in the `projects:` item.

2/ using this url
```
https://192.168.49.2.nip.io#https://github.com/sgandon/studio-project?new&che-editor=talend/studio/8.0
```
This creates the workspace with the "default" devfile (which I never found the definition of). It takes my git repo into account and run the `project-clone` and record nicely the git repo url in the configmap. But it also add a universal image in my pod which I don't need.
So how can I launch my editor, which take my editor into account and clone my repo and does not inject unnecessary images to my pod ?

### Che version

7.61@latest

### Steps to reproduce

create a simple editor devfile that defines a container in the plugin registry
create an empty devfile in the defile registry
use either
1/ https://che_url#https://git_public_repo?new&che-editor=my_editor&url=https://che/devfile-registry/devfiles/empty_devfile.yaml
=> and see that my repo is not cloned

or
https://che_url#https://git_public_repo?new&che-editor=my_editor
=> And see that repo is cloned but the universal gets injected.

### Expected behavior

I'd like to have a workspace with the cloned repo and nothing extra injected in the pod.

### Runtime

minikube

### Installation method

chectl/latest

### Environment

macOS

**Comment by amisevsk** [comment]
@sgandon what is the editor definition you are using -- i.e. what's the editor's devfile?

**Comment by sgandon** [comment]
Hello and thank you @amisevsk for your response,
I probably was not clear enough, the editor is not relying on Theia, vs code or Intellij, this is a tool we are building ourself and we dont need any other tooling appart from the containers of own IDE.
This a bit a the problem with Eclipse-Che that may not be flexible enough to use other IDEs that the one already supported.
So here is the dev file used to define our editor but not sure this will be of a big help
```
schemaVersion: 2.1.0
metadata:
  name: talend-studio
components:
  - container:
      image: nginx
      sourceMapping: /projects
      memoryLimit: 256Mi
      memoryRequest: 128Mi
      cpuLimit: 400m
      cpuRequest: 100m
      endpoints:
        - name: main
          attributes:
            discoverable: false #if true this create a K8s svc with a fixed name `main` and will conflict if other workspaces are created
            type: main
            urlRewriteSupported: true #this open https://192.168.49.2.nip.io/workspace33430124dfe24025/talend-studio/80/ instead of direct ingress definition https://workspace33430124dfe24025-192.168.49.2.nip.io/
          targetPort: 8080
          exposure: public
          protocol: http
          path: /studio
        - name: mainingress
          attributes:
            discoverable: false
            urlRewriteSupported: false # this will create an ingress
          targetPort: 8080
          exposure: public
          protocol: http
    name: nginx
    attributes: 
      ports:
        - exposedPort: 8080
      controller.devfile.io/merge-contribution: true
      pod-overrides:
        spec:
          securityContext:
            runAsNonRoot: false
      container-overrides: 
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        imagePullPolicy: IfNotPresent


  - name: studio-web-app
    container:
      image: ourartifactory.com/studio-cloud-app:2.0.0-20230301152930
      mountSources: false
      memoryLimit: 256M
      memoryRequest: 128Mi
      cpuLimit: 250m
      cpuRequest: 100m
    attributes: 
      pod-overrides:
        spec:
          securityContext:
            runAsNonRoot: false
      container-overrides: 
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        imagePullPolicy: IfNotPresent
  - name: studio-backend
    container:
      image: ourartifactory.com/studio-cloud-backend:0.0.1-SNAPSHOT-20230215
      mountSources: true
      memoryLimit: 4096Mi
      memoryRequest: 1024Mi
      cpuLimit: 2000m
      cpuRequest: 200m
    attributes: 
      pod-overrides:
        spec:
          securityContext:
            runAsNonRoot: false
      container-overrides: 
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        imagePullPolicy: IfNotPresent
```

**Comment by amisevsk** [comment]
@sgandon thank you for the explanation. I believe Che should be able to support your use case, though it does somewhat go against some design choices we've made.

Regarding the editor devfile you shared, I have a few questions:
* If the developer wants to build and run the application, which container is responsible for building and running? Is it the backend container?
* What is the nginx component for? Note that Eclipse Che will already inject a sidecar to manage auth and ingress into the pod
* Why does the nginx component have the `controller.devfile.io/merge-contribution: true` attribute? Do you intend for it to be merged into another container?

The reason you are seeing the injected component is due to the `.spec.devEnvironments.defaultComponents` field in the CheCluster custom resource:
```yaml
spec:
  devEnvironments:
    defaultComponents:
      - container:
          image: 'quay.io/devfile/universal-developer-image:ubi8-38da5c2'
          sourceMapping: /projects
        name: universal-developer-image
```

This value currently cannot be unset, as it is defaulted by the Che Operator. The reason for this is that the general idea behind how Che manages workspaces is
* The user provides a devfile which contains a _development_ container, which has all the dependencies needed for building their code, and
* Che adds an editor, which runs _within_ that development container

This results in an IDE environment with the specific set of dependencies your project requires (e.g. runtimes, libraries, etc., pinned to the versions you require). The example here is e.g. using the builder image for your Go project to develop the code itself.

There are a few ways we can work around this for your case, though none of them are particularly clean -- I'll have to think about it a bit more to see if we can come up with a reasonable workaround. One approach that may work at least for a development use case is skipping the dashboard altogether for workspace creation and creating DevWorkspaces manually (i.e. using `kubectl apply`):
```yaml
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: my-workspace-name
  namespace: <user-namespace>
spec:
  started: true
  routingClass: che
  template:
    projects:
      - name: <project-name>
        git:
          remotes:
            origin: <git-url>
  contributions:
    - name: <editor-name>
      uri: <URI to the editor devfile you shared>
```
You should still see the workspace in the dashboard after it has been created.

Note that if you _do_ want the `nginx` component from your editor devfile, you may be able to work around all these issues by updating the `defaultComponents` field in your CheCluster to be the same image, as the `controller.devfile.io/merge-contribution: true` attribute will result in the editor-defined nginx component being merged with the default component:
```yaml
spec:
  devEnvironments:
    defaultComponents:
      - container:
          image: nginx
          sourceMapping: /projects
        name: nginx-internal # This name cannot collide with nginx from the editor definition, sadly
```
