### ISSUE TITLE
Devfile default commands should be configured as VS Code default tasks

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22060]
### Is your enhancement related to a problem? Please describe

VS Code allows to configure a default Build Task and default Test Task:

![image](https://user-images.githubusercontent.com/606959/225269161-33c49d54-e843-4a31-8461-b4c194d54792.png)

So that a user can then run them with a keyboard shortcut or via the command line:

![image](https://user-images.githubusercontent.com/606959/225269554-fa56d197-d4a2-48d2-92e3-c334b882dd48.png)

The defile allows to specify the kind of the command (`build`, `run`, `test`, `debug` and `deploy`) and if its the default:

```yaml
  - id: package
    exec:
      label: "1. Package"
      component: tools
      commandLine: mvn clean package
      group:
        kind: build
        isDefault: true
```

The problem is that if I specify a default `build` or `test` command in my devfile that's not configured as the default build or test task in VS Code.

### Describe the solution you'd like

If I specify a default `build` command in my devfile that should be configured as the default build task in VS Code.

If I specify a default `test` command in my devfile that should be configured as the default test task in VS Code.
