### ISSUE TITLE
devworkspace-operator is not being installed when target platform is k8s

### ISSUE THREAD

**Issue by pantoninho** [eclipse/che#22074]
### Describe the bug

When deploying che with chectl targeting a k8s platform, the devworkspace-operator is not being included. It does not even appear in the installation log. I've tried deploying che targeting a minikube cluster and I did not have this issue.

### Che version

7.61@latest

### Steps to reproduce

1. `chectl server:deploy --platform k8s --che-operator-cr-patch-yaml patch.yaml --domain che.example.com`
2. Login
3. Create a workspace

These are the contents of `patch.yaml`:
```yaml
kind: CheCluster
apiVersion: org.eclipse.che/v2
spec:
  components:
    cheServer:
      debug: true
      logLevel: DEBUG
      extraProperties:
        CHE_OIDC_USERNAME__CLAIM: email
  networking:
    annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/load-balancer-name: <redacted>
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    auth:
      oAuthClientName: <redacted>
      oAuthSecret: <redacted>
      identityProviderURL: <redacted>

```

### Expected behavior

I would expect to be able to create a workspace.

### Runtime

Kubernetes (vanilla), other (please specify in additional context)

### Screenshots

<img width="1840" alt="Screenshot 2023-03-20 at 17 14 37" src="https://user-images.githubusercontent.com/14220276/226417057-92e2b0a2-95f3-41ce-9665-25cd35c7498e.png">

### Installation method

chectl/latest

### Environment

Amazon
