### ISSUE TITLE
Post start commands should be run detached

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22081]
### Is your enhancement related to a problem? Please describe

Workspaces Pod is stuck in `PodInitializing` status until postStart command doesn't complete.

This can be tested with the [devfile in this repository](https://github.com/l0rd/inventory-quarkus/tree/post-start-issue) where the postStart command is `tail -f /dev/null` and the workspaces never starts:

```yaml
schemaVersion: 2.2.0
(...)
commands:
(...)
  - id: neverendingcommand
    exec:
      label: "8. Tail /dev/null"
      component: tools
      commandLine: |
        tail -f /dev/null
      group:
        kind: build
events:
  postStart:
    - neverendingcommand
```

<img width="614" alt="image" src="https://user-images.githubusercontent.com/606959/226710472-93f9a041-259c-45f8-8847-b869406ad3d8.png">

### Describe the solution you'd like

A `postStart` event should never block the workspace startup. The command should run detached. One way to do that would be to prefix the command with `nohup` and suffix it with `&`:

A command in a devfile or devworkspace should then be transformed into a container lifecycle postStart like the following one:

```yaml
      lifecycle:
        postStart:
          exec:
            command:
              - 'nohup'
              - 'tail'
              - '-f'
              - '/dev/null'
              - '&'
```
