### ISSUE TITLE
DevWorkspace generator tool should add a dev component if a devfile doesn't provide any

### ISSUE THREAD

**Issue by svor** [eclipse/che#22082]
### Is your task related to a problem? Please describe

In case when devfile.yaml doesn't contain any component, DevWorkspace generator tool can't generate all in one file and fails with the message:
```
stack=Error: Not able to find any dev container component in DevWorkspace
```

### Describe the solution you'd like

[DevWorkspace generator tool](https://github.com/eclipse-che/che-devfile-registry/tree/main/tools/devworkspace-generator) should generate devworkspace even if a devfile.yaml doesn't provide any component, in this case the component should be generated:
```
   components:
      - name: dev
        container:
          image: quay.io/devfile/universal-developer-image:latest
```
