### ISSUE TITLE
wrong storageClassName in workspace's PVC

### ISSUE THREAD

**Issue by pantoninho** [eclipse/che#22092]
### Describe the bug

I'm having issues setting the workspace's PVC storageClassName.
Following the documentation, I've set the required configuration in the CheCluster resource patch:
```yaml
kind: CheCluster
apiVersion: org.eclipse.che/v2
spec:
  devEnvironment:
    storage:
      pvc:
        storageClass: efs-sc
(...)
```

After creating a new account, I see a PVC in the account's namespace but the storage class is the cluster's default, gp2 (which I would prefer not to change):
```bash
❯ kubectl get --namespace <account-namespace> persistentvolumeclaims claim-devworkspace
NAME                 STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
claim-devworkspace   Pending                                      gp2            8m11s
```

This problem is also visible through the workspace event log in the dashboard:
```
waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator
```

I've also noticed an unexpected warning in the [docs](https://www.eclipse.org/che/docs/stable/administration-guide/configuring-storage/): `Che does not support the Network File System (NFS) protocol`. Is this true? 

### Che version

7.61@latest

### Steps to reproduce

1. Setup EKS cluster
2. Setup EFS
3. Install and setup [aws-efs-csi-driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver) in the cluster
5. Install eclipse che through chectl with the following patch:
```
kind: CheCluster
apiVersion: org.eclipse.che/v2
spec:
  devEnvironment:
    storage:
      pvc:
        storageClass: efs-sc
```

### Expected behavior

I would expect the workspace's PVC storage class to be the one set in the CheCluster resource configuration.

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Amazon
