### ISSUE TITLE
Support for CustomResource `openshift` & `kubernetes` devfile components is not working

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#22137]
### Describe the bug

I am attempting to create a devfile which will deploy a Kafka cluster and Kafka topics in the workspace along with the other workspace components.

Following the documentation at [https://devfile.io/docs/2.2.0/adding-a-kubernetes-or-openshift-component](https://devfile.io/docs/2.2.0/adding-a-kubernetes-or-openshift-component) yields unsuccessful results.

This feature appears to have been enabled by: [https://github.com/devfile/devworkspace-operator/pull/961](https://github.com/devfile/devworkspace-operator/pull/961)

However, variations on a devfile to implement it have failed.

### Che version

7.63@latest

### Steps to reproduce

Example Devfile `#1`:

With this devfile, the workspace silently excludes all of the included components...  No errors are obvious.

```yaml
schemaVersion: 2.2.0
attributes:
  controller.devfile.io/storage-type: per-workspace
metadata:
  name: che-test-workspace
components:
- name: dev-tools
  container: 
    image: image-registry.openshift-image-registry.svc:5000/eclipse-che-images/quarkus:latest
    memoryRequest: 1Gi
    memoryLimit: 6Gi
    cpuRequest: 500m
    cpuLimit: 2000m
    mountSources: true
    sourceMapping: /projects
    args:
      - '-f'
      - /dev/null
    command:
      - tail
    env:
    - name: SHELL
      value: "/bin/zsh"
    volumeMounts:
    - name: m2
      path: /home/user/.m2
- name: ubi
  container:
    args:
      - '-f'
      - /dev/null
    command:
      - tail
    image: registry.access.redhat.com/ubi9/ubi-minimal
    memoryLimit: 64M
    mountSources: true
    sourceMapping: /projects
- volume:
    size: 4Gi
  name: projects
- volume:
    size: 2Gi
  name: m2
- name: kafka-cluster
  openshift:
    deployByDefault: true
    inlined: |
      apiVersion: kafka.strimzi.io/v1beta2
      kind: Kafka
      metadata:
        name: che-demo
        labels:
          app: che-demo
      spec:
        kafka:
          config:
            offsets.topic.replication.factor: 1
            transaction.state.log.replication.factor: 1
            transaction.state.log.min.isr: 1
            inter.broker.protocol.version: '3.4'
          version: 3.4.0
          storage:
            size: 1Gi
            deleteClaim: true
            type: persistent-claim
          replicas: 1
          listeners:
            - name: plain
              port: 9092
              type: internal
              tls: false
            - name: tls
              port: 9093
              type: internal
              tls: true
        entityOperator:
          topicOperator: {}
          userOperator: {}
        zookeeper:
          storage:
            deleteClaim: true
            size: 1Gi
            type: persistent-claim
          replicas: 1
- name: kafka-topic
  openshift:
    deployByDefault: true
    inlined: |
      apiVersion: kafka.strimzi.io/v1beta2
      kind: KafkaTopic
      metadata:
        name: che-demo
        labels:
          strimz.io/cluster: che-demo
      spec:
        config:
          retention.ms: 604800000
          segment.bytes: 1073741824
        partitions: 10
        replicas: 1
        topicName: che-demo
commands:
- exec:
    commandLine: "cp /home/user/.kube/config /projects/config"
    component: dev-tools
    group:
      kind: run
    label: Copy Kubeconfig
    workingDir: '/'
  id: copy-kubeconfig
```

Example Devfile `#2`:

With this devfile, the workspace deploys with the correct container components, but there is no obvious way to run the `apply` commands.  Further, the `apply` commands cannot be created with the `deploy` group as that group does not appear to be implemented.  __Note:__ you have to remove the `group` entries from the `apply` commands for this example to not throw an error.

```yaml
schemaVersion: 2.2.0
attributes:
  controller.devfile.io/storage-type: per-workspace
metadata:
  name: che-test-workspace
components:
- name: dev-tools
  container: 
    image: image-registry.openshift-image-registry.svc:5000/eclipse-che-images/quarkus:latest
    memoryRequest: 1Gi
    memoryLimit: 6Gi
    cpuRequest: 500m
    cpuLimit: 2000m
    mountSources: true
    sourceMapping: /projects
    args:
      - '-f'
      - /dev/null
    command:
      - tail
    env:
    - name: SHELL
      value: "/bin/zsh"
    volumeMounts:
    - name: m2
      path: /home/user/.m2
- name: ubi
  container:
    args:
      - '-f'
      - /dev/null
    command:
      - tail
    image: registry.access.redhat.com/ubi9/ubi-minimal
    memoryLimit: 64M
    mountSources: true
    sourceMapping: /projects
- volume:
    size: 4Gi
  name: projects
- volume:
    size: 2Gi
  name: m2
- name: kafka-cluster
  openshift:
    inlined: |
      apiVersion: kafka.strimzi.io/v1beta2
      kind: Kafka
      metadata:
        name: che-demo
        labels:
          app: che-demo
      spec:
        kafka:
          config:
            offsets.topic.replication.factor: 1
            transaction.state.log.replication.factor: 1
            transaction.state.log.min.isr: 1
            inter.broker.protocol.version: '3.4'
          version: 3.4.0
          storage:
            size: 1Gi
            deleteClaim: true
            type: persistent-claim
          replicas: 1
          listeners:
            - name: plain
              port: 9092
              type: internal
              tls: false
            - name: tls
              port: 9093
              type: internal
              tls: true
        entityOperator:
          topicOperator: {}
          userOperator: {}
        zookeeper:
          storage:
            deleteClaim: true
            size: 1Gi
            type: persistent-claim
          replicas: 1
- name: kafka-topic
  openshift:
    inlined: |
      apiVersion: kafka.strimzi.io/v1beta2
      kind: KafkaTopic
      metadata:
        name: che-demo
        labels:
          strimz.io/cluster: che-demo
      spec:
        config:
          retention.ms: 604800000
          segment.bytes: 1073741824
        partitions: 10
        replicas: 1
        topicName: che-demo
commands:
- exec:
    commandLine: "cp /home/user/.kube/config /projects/config"
    component: dev-tools
    group:
      kind: run
    label: Copy Kubeconfig
    workingDir: '/'
  id: copy-kubeconfig
- apply:
    component: kafka-cluster
    group:
      kind: deploy
    label: deploy-kafka-cluster
  id: kafka-cluster
- apply:
    component: kafka-topic
    group:
      kind: deploy
    label: kafka-topic
  id: kafka-topic
```

### Expected behavior

Workspace deployed with Kafka cluster and Topic

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

macOS

### Additional context

The Strimzi Operator is installed with cluster scope.

**Comment by l0rd** [comment]
@amisevsk can you please have a look

**Comment by amisevsk** [comment]
I'm looking into the first example (with `deployByDefault: true`). For the second example, I believe it's expected that the editor will provide some way of applying the resources, e.g. via `oc apply`, as it's an interactive action and not something we can do with the DevWorkspace Operator. Perhaps we need an issue for supporting this in editors?

**Comment by cgruver** [comment]
@amisevsk Yes, I'll apply that RBAC and update here.

**Comment by cgruver** [comment]
@amisevsk   I had the wrong API version in the CRs.  I failed to notice that it had recently updated to `v1beta2` so your first error above is legit.  That API version does not exist.

**Comment by cgruver** [comment]
Never mind.  I get the same error after the correction:

```
Error provisioning workspace Kubernetes components: could not process component kafka-cluster: no kind "Kafka" is registered for version "kafka.strimzi.io/v1beta2" in scheme "pkg/runtime/scheme.go:100"
Workspace stopped due to error
```

**Comment by cgruver** [comment]
If I grant my user `edit` permissions to the Che provisioned namespace, then I can successfully create the Kafka resources manually within the workspace.

I'd prefer not to do that thought, because I would like the resources to be managed by the workspace.  i.e. shutdown and/or removed when the workspace stops or is deleted.

**Comment by cgruver** [comment]
Update:

I validated that the creation of OpenShift resources works if it's something that the service account has permission to create:

```yaml
- openshift:
    deployByDefault: true
    inlined: |
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: test-config
      data:
        test: "value"
  name: config-map
```
