### ISSUE TITLE
DevWorkspace generator tool should add routingClass: che into the resulted DevWorkspace

### ISSUE THREAD

**Issue by svor** [eclipse/che#22149]
### Is your task related to a problem? Please describe

The current version of generated DevWorkspace doesn't provide an information about `routingClass` in this case the default value is used. That's why the editor is inaccessible in che if start a workspace via `oc apply -f generatedDevWorkspace` 

### Describe the solution you'd like

Resulted DevWorkspace should contain `routingClass: che` under the `spec`:
```
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: spring-petclinic
spec:
  started: true
  routingClass: che
```

**Comment by dmytro-ndp** [comment]
Could you, please, also make sure that it will not interfere with next CheCluster property ? :
```
spec:
  components:
    networking:
      auth:
        gateway:
          configLabels:
            app: che
            component: che-gateway-config
```
