### ISSUE TITLE
Che fails to properly create a workspace if `controller.devfile.io/merge-contribution: true` is set on a container component.

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#22155]
### Describe the bug

I am trying to explicitly tell Che which container component to use for injecting the IDE at workspace startup.

To accomplish this I am adding the following attribute to the desired container component in the devfile:

```yaml
  attributes:
    controller.devfile.io/merge-contribution: true
```

If I modify an existing workspace and remove the attribute from the first container component and move it to the desired component, the workspace starts and runs as expected.

However, if I create a new workspace with a devfile containing that attribute, the workspace starts, but is created with an empty array of components, much like the error here: https://github.com/eclipse/che/issues/22145

### Che version

7.63@latest

### Steps to reproduce

Create a workspace with the following devfile:

```yaml
schemaVersion: 2.2.0
attributes:
  controller.devfile.io/storage-type: per-workspace
metadata:
  name: che-demo-app
projects:
- name: che-demo-app
  git:
    checkoutFrom:
      remote: origin
      revision: main
    remotes:
      origin: https://github.com/eclipse-che-demo-app/che-demo-app.git
- name: che-demo-app-ui
  git:
    checkoutFrom:
      remote: origin
      revision: main
    remotes:
      origin: https://github.com/eclipse-che-demo-app/che-demo-app-ui.git
- name: che-demo-app-service
  git:
    checkoutFrom:
      remote: origin
      revision: main
    remotes:
      origin: https://github.com/eclipse-che-demo-app/che-demo-app-service.git
components:
- name: quarkus-runner
  container: 
    image: quay.io/cgruver0/che/che-demo-app:latest
    memoryLimit: 1Gi
    mountSources: true
    sourceMapping: /projects
    volumeMounts:
      - name: m2
        path: /home/user/.m2
    endpoints:
      - name: https-quarkus
        targetPort: 8080
        exposure: public
        protocol: https
      - name: debug
        exposure: none
        targetPort: 5858
      - name: dt-socket
        exposure: none
        targetPort: 5005
    env:
      - name: DEBUG_PORT
        value: '5858'
      - name: JAVA_HOME 
        value: /etc/alternatives/jre_17
      - name: API_PORT
        value: '8080'
      - name: DB_USER
        value: postgres
      - name: DB_PWD
        value: postgres
      - name: DB_HOST
        value: localhost
      - name: DB_SCHEMA
        value: postgres
      - name: CORS_ORIGINS
        value: "/.*/"
      - name: CORS_METHODS
        value: "GET,POST,DELETE"
    args:
      - '-f'
      - /dev/null
    command:
      - tail
- name: node-runner
  container: 
    image: quay.io/cgruver0/che/che-demo-app:latest
    memoryLimit: 1Gi
    mountSources: true
    sourceMapping: /projects
    volumeMounts:
      - name: npm
        path: /home/user/.npm
    endpoints:
      - name: node
        targetPort: 4200
        exposure: public
        protocol: https
    args:
      - '-f'
      - /dev/null
    command:
      - tail
- name: postgres
  container:
    image: quay.io/sclorg/postgresql-15-c9s:c9s
    memoryLimit: 512M
    sourceMapping: /projects
    mountSources: true
    env:
    - name: POSTGRESQL_USER
      value: postgres
    - name: POSTGRESQL_PASSWORD
      value: postgres
    - name: POSTGRESQL_DATABASE
      value: postgres
    volumeMounts:
    - name: pgdata
      path: /var/lib/pgsql/data
    endpoints:
      - name: postgres
        targetPort: 5432
- name: oc-cli
  container:
    args:
      - '-f'
      - /dev/null
    command:
      - tail
    image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
    sourceMapping: /projects
    mountSources: true
    memoryLimit: 64M
    env:
    - name: KUBECONFIG
      value: /projects/config
- name: dev-tools
  attributes:
    controller.devfile.io/merge-contribution: true
  container: 
    image: quay.io/cgruver0/che/che-demo-app:latest
    memoryRequest: 1Gi
    memoryLimit: 6Gi
    cpuRequest: 500m
    cpuLimit: 2000m
    mountSources: true
    sourceMapping: /projects
    args:
      - '-f'
      - /dev/null
    command:
      - tail
    env:
    - name: SHELL
      value: "/bin/zsh"
    - name: TESTCONTAINERS_RYUK_DISABLED
      value: "true"
    - name: TESTCONTAINERS_CHECKS_DISABLE
      value: "true"
    - name: DOCKER_HOST
      value: "tcp://127.0.0.1:2475"
    volumeMounts:
    - name: m2
      path: /home/user/.m2
    - name: npm
      path: /home/user/.npm
    endpoints:
      - name: kubedock
        targetPort: 2475
        exposure: none
- volume:
    size: 4Gi
  name: projects
- volume:
    size: 2Gi
  name: m2
- volume:
    size: 2Gi
  name: npm
- volume:
    size: 2Gi
  name: pgdata
commands:
- exec:
    commandLine: mvn package
    component: dev-tools
    group:
      isDefault: true
      kind: build
    workingDir: '/projects/che-demo-app-service'
  id: package
- exec:
    commandLine: mvn package -Dnative -Dmaven.test.skip -Dquarkus.native.native-image-xmx=2G
    component: dev-tools
    group:
      kind: build
    label: Package Native
    workingDir: '/projects/che-demo-app-service'
  id: package-native
- exec:
    commandLine: 'quarkus dev -Dmaven.repo.local=/home/user/.m2/repository -Dquarkus.http.host=0.0.0.0'
    component: quarkus-runner
    hotReloadCapable: true
    group:
      isDefault: true
      kind: run
    label: Start Quarkus Development mode (Hot reload)
    workingDir: '/projects/che-demo-app-service'
  id: quarkus-dev-mode
- exec:
    commandLine: 'ng serve --disable-host-check --host 0.0.0.0'
    component: node-runner
    hotReloadCapable: true
    group:
      isDefault: true
      kind: run
    label: Start NodeJS Development mode (Hot reload)
    workingDir: '/projects/che-demo-app-ui'
  id: node-dev-mode
- exec:
    commandLine: "POD=$(oc get pod --selector controller.devfile.io/devworkspace_name=che-demo-app -o name) ; oc rsh -c node-runner ${POD}"
    component: oc-cli
    group:
      kind: run
    label: Terminal - App UI
    workingDir: '/'
  id: demo-app-ui-shell
- exec:
    commandLine: "POD=$(oc get pod --selector controller.devfile.io/devworkspace_name=che-demo-app -o name) ; oc rsh -c quarkus-runner ${POD}"
    component: oc-cli
    group:
      kind: run
    label: Terminal - App Service
    workingDir: '/'
  id: ubi-shell
- exec:
    commandLine: "POD=$(oc get pod --selector controller.devfile.io/devworkspace_name=che-demo-app -o name) ; oc rsh -c postgres ${POD}"
    component: oc-cli
    group:
      kind: run
    label: Terminal - PostgreSQL
    workingDir: '/'
  id: postgres-shell
- exec:
    commandLine: "POD=$(oc get pod --selector controller.devfile.io/devworkspace_name=che-demo-app -o name) ; oc rsh -c oc-cli ${POD}"
    component: oc-cli
    group:
      kind: run
    label: Terminal - OC CLI
    workingDir: '/'
  id: oc-cli-shell
- exec:
    commandLine: "kubedock server --port-forward"
    component: dev-tools
    group:
      kind: run
    label: Kubedock
    workingDir: '/'
  id: kubedock
- exec:
    commandLine: "cp /home/user/.kube/config /projects/config"
    component: dev-tools
    group:
      kind: run
    label: Copy Kubeconfig
    workingDir: '/'
  id: copy-kubeconfig
- exec:
    commandLine: "/projects/che-demo-app/setUiEnv.sh -f=/projects/che-demo-app-ui/src/environments/environment.development.ts -s=/projects/che-demo-app-ui/env.dev -c=quarkus-runner -w=che-demo-app -p=8080 -e=https-quarkus -v=backendApiUrl"
    component: oc-cli
    group:
      kind: run
    label: Set Angular Environment
    workingDir: '/'
  id: set-ui-env
```

### Expected behavior

A running workspace with the IDE injected into the attributed component.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

macOS
