### ISSUE TITLE
Workspace startup warnings when there are unknown metadata in the Devfile

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22193]
### Describe the bug

This can be reproduced with a devfile like this one:

```
schemaVersion: 2.2.0
metadata:
  name: devspaces-sample
  version: 1.0.0
  displayName: devspace-sample
  description: uber devspace sample
  icon: https://python.astrotech.io/_static/favicon.png
  website: https://github.com/AstroMatt/book-python/blob/main/devfile.yaml
  projectType: "all-in-one"
  language: "go"
  tags: ["Hugo", "go"]
...
```

<img width="2520" alt="image" src="https://user-images.githubusercontent.com/606959/235885143-e69ced22-7b5b-4409-b537-1e525249bcae.png">

### Che version

7.65@latest

### Steps to reproduce

Start a workspace using a github repo with a devfile with the metadata described above.

### Expected behavior

No warnings

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon
