### ISSUE TITLE
Add ability to apply workspace scoped patches to pods and service accounts

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#22197]
### Is your enhancement related to a problem? Please describe

This is a superset of the request captured in #22134 - Add ability to annotate Service Account

Development teams need the ability to apply customizations to the workspace scoped items that are created for a workspace.  Examples include Annotations as referenced in #22134, Labels that are needed to drive other behaviors like operator injected resources, etc...

Need to be able to automatically apply user and/or workspace specific labels or annotations to:

* Namespaces created by Che for users
* Service Accounts
* Routes
* Services
* etc...

### Describe the solution you'd like

Add an object to the Devfile that represents patches to be applied to workspace provisioned objects:

```yaml
...
patches:
- name: serviceAccountAnnotations
  type: serviceAccount
  patch: -|
    <YAML HERE>
- name: someOtherPatch
  type: Pod
  etc...
```

This might alternatively be better suited for a new CRD that gets included in the Devfile as just a `kubernetes:` or `openshift:` object witch is already supported.

See the alternative below

### Describe alternatives you've considered

It is possible that this need could be satisfied with: [https://github.com/redhat-cop/patch-operator](https://github.com/redhat-cop/patch-operator)

But, that adds an external dependency on the ecosystem.
