### ISSUE TITLE
How to use multi github enterprise services

### ISSUE THREAD

**Issue by top1436** [eclipse/che#22220]
### Summary

I am using version 7.56.0. and I want to use 2 github enterprise services. so In CR, I set up the 2 github services and create 2 oauth config k8s secrets. but it doesn't work. I got error from che-operator, 2 oauth configs can not be created.
For now, Is it impossible to use 2 github enterprise in 1 eclipse-che instance?

CR
``` yaml
gitServices:
    github:
    - disableSubdomainIsolation: true
      endpoint: <enterprise1>
      secretName: <enterprise1>-oauth-config
    - disableSubdomainIsolation: true
      endpoint: <enterprise2>
      secretName: <enterprise2>-oauth-config
```

oauth config k8s secrets (create 2 secrets like below)
```yaml
kind: Secret
apiVersion: v1
metadata:
  name: githubenterprise1-oauth-config
  namespace: eclipse-che
  labels:
    app.kubernetes.io/component: oauth-scm-configuration
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    che.eclipse.org/oauth-scm-server: githubEnterprise1
    che.eclipse.org/scm-github-disable-subdomain-isolation: 'true'
    che.eclipse.org/scm-server-endpoint: <enterprise1>
data:
  id: <id>
  secret: <secret>
type: Opaque
```
