### ISSUE TITLE
Mount sources on kubernetes resources. Kubernetes pod as sidecard ?

### ISSUE THREAD

**Issue by disaster37** [eclipse/che#22236]
### Describe the bug

Previously, on devfile v1, we can create kubernetes resource like pod that is created on sidecard on current workspace pod. More over, we can mout source on it. We use this pattern to create docker dind container (with privilege) and mount source on it to use like on local desktop (old kernel, no way to use docker or podman rootless).

With devfile v2, we can now recreate kubernetes resources, but it create new pod, not sidecard container. So we can't continue to access on localhost ... More over, it seems no way to mount source on this pods ?

### Che version

7.67@latest

### Steps to reproduce

Deploy eclipse che 7.67.0
Create new workspace with the following devfile:
```yaml
schemaVersion: 2.2.0
metadata:
  name: golang-test
components:
  - name: home
    volume:
      size: 1Gi
  - name: tools
    container:
      image: quay.io/webcenter/developer-image:golang-ubi9-latest
      env:
        - name: GOPATH
          value: /projects:/home/user/go
        - name: GOCACHE
          value: /tmp/.cache
      #endpoints:
      #  - name: web
      #    targetPort: 8080
      #    exposure: public
      memoryLimit: 4Gi
      cpuLimit: 4000m
      cpuRequest: 1000m
      memoryRequest: 2Gi
      mountSources: true
      volumeMounts:
        - name: home
          path: /profile
  - name: docker
    kubernetes:
      deployByDefault: true
      inlined: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: test-pod
          labels:
            test: test-app
        spec:
          containers:
          - name: test-container
            image: quay.io/wto/web-terminal-tooling:next
            resources:
              limits:
                memory: "128Mi"
                cpu: "500m"
            ports:
              - containerPort: 8080
            command:
              - "tail"
              - "-f"
              - "/dev/null"

commands:
  - id: run
    exec:
      label: "1.1 Run"
      component: tools
      workingDir: ${PROJECT_SOURCE}/
      commandLine: "go run ."
      group:
        kind: run

  - id: stop
    exec:
      label: "1.2 Stop"
      component: tools
      commandLine: "kill $(pidof go)"
      group:
        kind: run

  - id: test
    exec:
      label: "1.3 Test"
      component: tools
      workingDir: ${PROJECT_SOURCE}/
      commandLine: "go test -v"
      group:
        kind: test

  - id: run-current-file
    exec:
      label: "Run current file"
      component: tools
      workingDir: ${fileDirname}
      commandLine: "go run ${file}"
      group:
        kind: run
```

The container `docker` is created on external pod, not as sidecard container on current workspace. So we need to create extra services to access on it, we doesn't use localhost like before.
We doesn't found the way to also mount source on it ?

### Expected behavior

Have ability to mount source code on it, and maybee have the choice between create new pod or inject container on current worpsace, depend of the nature of the container...

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Linux
