### ISSUE TITLE
devfile Kubernetes resource not working out of the box on k8s 

### ISSUE THREAD

**Issue by disaster37** [eclipse/che#22235]
### Describe the bug

When start workspace with following devfile.yaml, it doesn't work out of the box

```yaml
schemaVersion: 2.2.0
metadata:
  name: golang-test
components:
  - name: home
    volume:
      size: 1Gi
  - name: tools
    container:
      image: quay.io/webcenter/developer-image:golang-ubi9-latest
      env:
        - name: GOPATH
          value: /projects:/home/user/go
        - name: GOCACHE
          value: /tmp/.cache
      memoryLimit: 4Gi
      cpuLimit: 4000m
      cpuRequest: 500m
      memoryRequest: 1Gi
      mountSources: true
      volumeMounts:
        - name: home
          path: /profile
  - name: test
    kubernetes:
      deployByDefault: true
      inlined: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: test-pod
          labels:
            test: test-app
        spec:
          containers:
          - name: test-container
            image: quay.io/wto/web-terminal-tooling:next
            resources:
              limits:
                memory: "128Mi"
                cpu: "500m"
            ports:
              - containerPort: 8080
            command:
              - "tail"
              - "-f"
              - "/dev/null"

commands:
  - id: run
    exec:
      label: "1.1 Run"
      component: tools
      workingDir: ${PROJECT_SOURCE}/
      commandLine: "go run ."
      group:
        kind: run

  - id: stop
    exec:
      label: "1.2 Stop"
      component: tools
      commandLine: "kill $(pidof go)"
      group:
        kind: run

  - id: test
    exec:
      label: "1.3 Test"
      component: tools
      workingDir: ${PROJECT_SOURCE}/
      commandLine: "go test -v"
      group:
        kind: test

  - id: run-current-file
    exec:
      label: "Run current file"
      component: tools
      workingDir: ${fileDirname}
      commandLine: "go run ${file}"
      group:
        kind: run
```

We get error when starting workspace because of my regular user doesn't have the `update` right on `pod` resource. It's the same for `service` resource or `pvc` resource. Maybee the right must be fix on ``

As a workground, I have created the following `clusterRole`
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
  name: che-users-extras
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - delete
  - update
```

And the following `clusterRoleBinding:
```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: che-users-extras
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
subjects:
  - kind: ServiceAccount
    name: che-operator
    namespace: eclipse-che
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: che-users-extras
```

And patch my CheCluster CR:
```yaml
spec:
  components:
    cheServer:
      clusterRoles:
      - che-users-extras
  devEnvironments:
    user:
      clusterRoles:
      - che-users-extras
```

### Che version

7.67@latest

### Steps to reproduce

Deploy eclipse che 7.67.0
Login with regular user that doesn't have any right on kubernetes cluster
Create new workspace with devfile seen on previous section.

You get error during provisionning, because of you have the right update on resource pod. The error is throw by `admission webhook "mutate.devworkspace-controller.svc"`

### Expected behavior

The workspace is provisionning out of the box, without the need to create extra clusterRole, clusterRolebinding when works with standard kubernetes resource like pod, pvc, service deployment, etc.

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Linux
