### ISSUE TITLE
Simplify Che documentation by using secret `stringData` field instead of `data`

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#22245]
### Is your enhancement related to a problem? Please describe

A number of places in the Eclipse Che documentation include steps for base64-encoding data for usage in a secret. Instead, we could update the documentation to use the [`.stringData` field](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#secret-v1-core) on secrets, which allows specifying plain-text input which is automatically encoded by the cluster on save:

> stringData allows specifying non-binary secret data in string form. It is provided as a write-only input field for convenience. All keys and values are merged into the data field on write, overwriting any existing values. The stringData field is never output when reading from the API.

Doing this would simplify the documentation by avoiding steps around "encode data to base64", "paste the base64 data you from step X", etc. 

### Describe the solution you'd like

Drop documentation steps that require base64-encoding and replace them with stringData. For example, the docs for configuring Bitbucket OAuth could be simplified to

* Drop steps 7 and 8 from the "Setting up an OAuth consumer in the Bitbucket Cloud" procedure section
* Simplify step 1 in the "Applying an OAuth consumer Secret for the Bitbucket Cloud" procedure section
    ```yaml
    kind: Secret
    apiVersion: v1
    metadata:
      name: bitbucket-oauth-config
      namespace: eclipse-che 
      labels:
        app.kubernetes.io/part-of: che.eclipse.org
        app.kubernetes.io/component: oauth-scm-configuration
      annotations:
        che.eclipse.org/oauth-scm-server: bitbucket
    type: Opaque
    stringData:
      id: <Bitbucket_Oauth_Consumer_Key> 
      secret: <Bitbucket_Oauth_Consumer_Secret> 
    ```

### Additional context

Originally occurred to me after reviewing PR https://github.com/eclipse-che/che-docs/pull/2610/ which exists to clarify details around using base64-encoded data.
