### ISSUE TITLE
Rename `spec.devEnvironments.defaultPlugins` field

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#22262]
### Is your enhancement related to a problem? Please describe

The `spec.devEnvironments.defaultPlugins` field in the Che CR can be used to specify additional containers to workspaces via `spec.contributions`.

For example, if the CR is configured like so:

```
spec:
  devEnvironments:
    defaultPlugins:
      - editor: che-incubator/che-code/latest
        plugins:
          - >-
          https://gist.githubusercontent.com/dkwon17/a0e0265f020fbd02bcc7428652a987a8/raw/b01f7207a57f4f35b1b6085d4037a2bae11a3424/extra-container
```

With the configuration above, on startup, the following is added to all devworkspaces that use the `che-incubator/che-code/latest` editor:
```
spec:
  contributions:
    - attributes:
        che.eclipse.org/default-plugin: true
      name: default-233572838f95fa59eacc
      uri: >-
        https://gist.githubusercontent.com/dkwon17/a0e0265f020fbd02bcc7428652a987a8/raw/b01f7207a57f4f35b1b6085d4037a2bae11a3424/extra-container
```

The name `devEnvironments.defaultPlugins` can be misleading, and sounds similar to `devEnvironments.defaultComponents` which has a different behaviour and use-case compared to `devEnvironments.defaultPlugins`.

### Describe the solution you'd like

Different names for `devEnvironments.defaultPlugins` could be:

 - `devEnvironments.extraContainers`
 - `devEnvironments.extraContributions`
 - `devEnvironments.enforcedContainers`
 - `devEnvironments.additionalContainers`
 - `devEnvironments.additionalContributions`
