### ISSUE TITLE
Unable to create workspaces from a raw devfile published as a secret gist

### ISSUE THREAD

**Issue by akurinnoy** [eclipse/che#22318]
### Describe the bug

I tried creating a new workspace from a devfile which is the secret gist [1] and got this error message: `Cannot build factory with any of the provided parameters. Please check parameters correctness, and resend query.`. But I could successfully create a workspace using another secret gist [2].

[1] https://gist.github.com/akurinnoy/3640bd9b5a734304d96a0283368f20e7
[2] https://gist.github.com/akurinnoy/ef8a3e9324478e81add75818fbacc69f

### Che version

7.69@latest

### Steps to reproduce

Watch the screencast for steps to reproduce.

### Expected behavior

Workspace creation finished successfully from the secret gist [1].

### Runtime

OpenShift

### Screenshots

https://github.com/eclipse/che/assets/16220722/d4fa929f-47b9-4474-ae44-fe3f37fdbd85

### Installation method

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Additional context

Tried on the dogfooding cluster.

**Comment by amisevsk** [comment]
@akurinnoy Looking at the gists you shared, I noticed that the first example (the one that fails) does not have a trailing newline. I wonder if that might be causing the issue.

```
❯ curl https://gist.githubusercontent.com/akurinnoy/ef8a3e9324478e81add75818fbacc69f/raw/d4646c1c5e308790606f01d65b58240724170e72/empty.devfile.yaml
schemaVersion: 2.1.0
metadata:
  name: empty-wksp
❯ curl https://gist.githubusercontent.com/akurinnoy/3640bd9b5a734304d96a0283368f20e7/raw/98dac5e7f305355f071cf4d9affd2587cf63eb04/dev-dashboard.yaml
schemaVersion: 2.1.0
metadata:
  name: dev-dashboard%
```
(the `%` at the end of the line signifies that there's no `\n` at the end)
