### ISSUE TITLE
As an Admin I want to customize Eclipse Che logo from the Custom Resource

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22319]
### Is your task related to a problem? Please describe

As an Admin I want to customize Eclipse Che logo from the Custom Resource

### Describe the solution you'd like

```
spec:
  components:
    dashboard:
       logo:
         - base64data: <base64-encoded-data>
           mediatype: image/png
 ```

logo: a base64 encoded image. The base64data parameter contains the data and the mediatype specifies the type of image, eg. `image/png` or `image/svg`.

![image](https://github.com/eclipse/che/assets/1461122/47233053-5263-47eb-a65b-c39a6d24d03e)

Inspired by the https://github.com/operator-framework/operator-lifecycle-manager/blob/4197455/Documentation/design/building-your-csv.md#operator-metadata

### Describe alternatives you've considered

N/A

### Additional context

part of https://github.com/eclipse/che/issues/21571

**Comment by tolusha** [comment]
The similar image [1] is used to configure OpenShift ConsoleLink.
But, the image url is the only way to set image for ConsoleLink object [2]

[1] https://github.com/eclipse-che/che-operator/blob/main/config/manager/manager.yaml#L96-L97
[2] https://docs.openshift.com/container-platform/4.9/rest_api/console_apis/consolelink-console-openshift-io-v1.html

**Comment by tolusha** [comment]
What about this structure:

```yaml
spec:
  components:
    dashboard:
       branding:
         logo:
           - base64data: <base64-encoded-data>
             mediatype: image/png
```
