### ISSUE TITLE
Login and logout problems

### ISSUE THREAD

**Issue by ced360** [eclipse/che#22324]
### Describe the bug

Half the time when I log into eclipse che with keycloak I get a 403 Forbidden error : Login Failed: Unable to find a valid CSRF token. Please try again. Request ID: xxxxxxxxxxxxxxxxxxxxx When I click on Sign In, the page reloads and I access eclipse che. In the logs of the oauth-proxy container in the che-gateway pod, I find this : 

```
10.42.0.8:56270 - eb1f37ea9a2f4c21f2ceb49b14223ea7 - xxxxxxxxxxxxxxxxx@xxxxxxxxxxxxxx.fr [2023/06/16 14:57:28] [AuthFailure] Invalid authentication via OAuth2: CSRF token mismatch, potential attack
10.42.0.8:56270 - eb1f37ea9a2f4c21f2ceb49b14223ea7 - - [2023/06/16 14:57:28] eclipse.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.fr GET - "/oauth/callback?state=k90KFMdZvvJU8KwIfYdOiDdNzS3T1Cd-tggYILSzhEY%3A%2Fdashboard%2F&session_state=a7048f71-60d5-4362-979f-8190413fe39d&code=2056515f-9dc1-4eb0-aa9a-ffdd49898543.a7048f71-60d5-4362-979f-8190413fe39d.k8s-client" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.11) Gecko/20100101 Firefox/102.11" 403 2795 0.027
```

And then :

```
10.42.0.8:56270 - d4002361c9a6aff8c95f6a9e17a36cbe - - [2023/06/16 14:58:08] eclipse.xxxxxxxxxxxxxxxxxxxxxxxxxxx.fr GET - "/oauth/sign_in?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.11) Gecko/20100101 Firefox/102.11" 302 403 0.000
10.42.0.8:56270 - 1b32ce31881dec68341dd0455720be33 - xxxxxxxxxxxxxxxxxx@xxxxxxxxxxxxxxxx.fr [2023/06/16 14:58:08] [AuthSuccess] Authenticated via OAuth2: Session{email:xxxxxxxxxxxxxxxxxxxx@xxxxxxxxxxxxxxxxxxxxxx.fr user:a276a8fc-a01e-49d4-90de-9cdb7fa59848 PreferredUsername:xxxxxxxxxxxxxx token:true id_token:true created:2023-06-16 14:58:08.88964119 +0000 UTC m=+2158174.139088687 expires:2023-06-16 15:03:08.881902625 +0000 UTC m=+2158474.131350170 refresh_token:true}
```

Then, and I think it's related. In the top right menu, which pops up when I click on my user's name, I only have two choices: User Preferences and Logout. I saw more choices on different screenshots. And when I click on Logout, the page reloads, and I land again on the home page, still logged in.

If I use a network inspector, the one included in Firefox for example, I can see a call to https://eclipse.xxxxxxxxxxxxxxxxxxxxxxxxxxx.fr/oauth/sign_out. Then immediately after, the page in /dashboard/ reloads. Again, in the logs of the oauth-proxy container in the che-gateway pod, I find this :

```
10.42.0.8:59770 - 5ad2ded03e7eeb6cd7592af555a677dd - xxxxxxxxxxxxxxxxxxx@xxxxxxxxxxxxx.fr [2023/06/26 09:24:24] eclipse.xxxxxxxxxxxxxxxxxxxxxxxxxxxx.fr GET / "/dashboard/api/websocket" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.11) Gecko/20100101 Firefox/102.11" 0 0 273.060
10.42.0.8:40140 - cc04f24506fe580170218c895eaa770a - - [2023/06/26 09:28:58] eclipse.xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.fr GET - "/oauth/sign_out" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.11) Gecko/20100101 Firefox/102.11" 302 24 0.000
[2023/06/26 09:28:58] [oauthproxy.go:959] No valid authentication in request. Initiating login.
10.42.0.8:40140 - 65525bb1258332f21ae30d3752f191ac - - [2023/06/26 09:28:58] eclipse.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.fr GET - "/dashboard/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.11) Gecko/20100101 Firefox/102.11" 302 415 0.001
10.42.0.8:40140 - 870b2863a77f270fa9ae710a99971c65 - xxxxxxxxxxxxxxxxx@xxxxxxxxxxxxxxxx.fr [2023/06/26 09:28:58] [AuthSuccess] Authenticated via OAuth2: 
Session{email:xxxxxxxxxxxxxxx@xxxxxxxxxxxxxxxxxx.fr user:a276a8fc-a01e-49d4-90de-9cdb7fa59848 PreferredUsername:xxxxxxxxxxx token:true id_token:true created:2023-06-26 09:28:58.583195984 +0000 UTC m=+3002423.832643556 expires:2023-06-26 09:33:58.576903686 +0000 UTC m=+3002723.826351164 refresh_token:true} 
```

Are there things I didn't understand in the keycloak / che configuration? Regarding users, should they only exist at the keycloak level or are there manipulations to be done on the Kubernetes cluster that hosts che? I'm a bit at a loss for explanations.

Dashboard Version
    7.62.0-next
Server Version
    7.62.0

### Che version

other (please specify in additional context)

### Steps to reproduce

- Install keycloak on a kube cluster by creating a che realm, a dedicated che client, and users.
- Deploy another Kube cluster and install che using the official helm chart.
- Use the following yaml file for the CheCluster object creation :

```
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: eclipse-che
  namespace: eclipse-che
spec:
  components:
    cheServer:
      logLevel: ERROR
      extraProperties:
        CHE_OIDC_USERNAME__CLAIM: email 
  containerRegistry: {}
  devEnvironments:
    startTimeoutSeconds: 3000
  gitServices: {}
  networking:
    hostname: "eclipse.xxxxxxxxxxxxxxxxxxxxx.fr"
    tlsSecretName: pem-secret
    domain: "eclipse.xxxxxxxxxxxxxxxxxxxx.fr"
    auth:
      externalIdentityProvider: true
      identityProviderURL: "https://xxxxxxxxxxxxxxxxxxx/keycloak/realms/che"
      oAuthClientName: "k8s-client"
      oAuthSecret: "{{ keycloak_k8s_client_secret }}"
```

Everything seems to be going well. You can connect, then create a workspace, and work in this workspace.

### Expected behavior

By connecting, we do not encounter any error message, and we arrive on the home page directly. The top right menu shows us more choices (I believe...). A click on Logout brings us back to the keycloak interface to log in, and we're no longer able to create a workspace or open existing one.

### Runtime

Kubernetes (vanilla)

### Screenshots

![image](https://github.com/eclipse/che/assets/6669782/414e0fd5-0e9f-40bb-89dc-bab475fc8505)

### Installation method

other (please specify in additional context)

### Environment

Linux
