### ISSUE TITLE
Che Operator defaults cleaner makes it impossible to set some fields

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#22322]
### Describe the bug

Attempting to set any of the CheCluster fields "cleaned up" by the `CheClusterDefaultsCleaner` to what was once a default results in the operator overwriting that field and removing it. 

### Che version

7.69@latest

### Steps to reproduce

1. Create CheCluster
2. Set `checluster.spec.components.pluginRegistry.openVSXURL` to `"https://open-vsx.org"`
3. Reload CheCluster after saving, field is not set

### Expected behavior

Che should not overwrite fields set in the CheCluster spec

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

other (please specify in additional context)

**Comment by amisevsk** [comment]
As a workaround for `openVSXURL`, setting the field to `https://open-vsx.org/` (i.e. with a trailing slash) avoids this issue.

The Che Operator should probably not be un-setting fields in the CR if doing so would change behavior (i.e. if the internal default value is different from the 'detected' default value in the CheCluster).

**Comment by tolusha** [comment]
Operator does cleans up the default value for `openVSXURL` field. My bad, it should NOT do for fresh installations.
The workaround is to add annotation for CheCluster CR sample, like this:
```yaml
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: openshift-operators
  annotations:
    che.eclipse.org/checluster-defaults-cleanup: '{"spec.components.pluginRegistry.openVSXURL":"true"}' 
spec:
  components:
...
```
