### ISSUE TITLE
Using custom certificates with checluster

### ISSUE THREAD

**Issue by BlueCog** [eclipse/che#22329]
### Summary

I'd like to use a ca-bundle (_made vailable via configmap_) to use with GIT or any other tool available to the user workspace.

I followed the documentation and the result is that the ca-bundle from my configmap is made vailable in the folder **/public-certs** at the user workspace. But this ca-bundle is not active(?) for the workspace. 

GIT fails for example, but also a curl command fails. When I configure GIT to use this bundle. Or define a curl command with a flag to use the certificate it works correctly

Did i miss any setting? Or do I need to define environment variables for example?

### Relevant information

The configmap (platform here is OpenShift) this results in a configmap with the key "ca-bundle.crt" which contains the ca-bundle of the cluster

**configmap with ca-bundle**
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: ca-bundle
  labels:
    app.kubernetes.io/component: ca-bundle
    app.kubernetes.io/part-of: che.eclipse.org
    config.openshift.io/inject-trusted-cabundle: 'true'
```

**checluster CRD**
```
  devEnvironments:
    trustedCerts:
        gitTrustedCertsConfigMapName: ca-bundle
```

**Comment by dkwon17** [comment]
Hello @BlueCog , was this the documentation you followed [1]?  cc @vinokurig 


[1] https://www.eclipse.org/che/docs/stable/administration-guide/deploying-che-with-support-for-git-repositories-with-self-signed-certificates/

**Comment by BlueCog** [comment]
> Hello @BlueCog , was this the documentation you followed [1]? cc @vinokurig
> 
> [1] https://www.eclipse.org/che/docs/stable/administration-guide/deploying-che-with-support-for-git-repositories-with-self-signed-certificates/

Thanks for getting back to me @dkwon17 

Yes i've followed that documenation but noting/using this extra info:

> Optional parameter to specify the https:// host and port of the HTTPS connection on the Git server. When omitted, the self-signed certificate is used for all repositories over HTTPS.
>
> Certificate files are typically stored as Base64 ASCII files, such as. .pem, .crt, .ca-bundle. All ConfigMaps that hold certificate files should use the Base64 ASCII certificate rather than the binary data certificate.
> 
> A certificate chain of trust is required. If the ca.crt is signed by a certificate authority (CA), the CA certificate must be included in the ca.crt file.

My understanding is that a ca-bundle crt is allowed. Therefor i used the `config.openshift.io/inject-trusted-cabundle: 'true'` label what injects a ca bundle in the config map to use with GIT. And i didn't define a git host (so it would be used for any host). 

And a second cert to use with any other tool (mounted in /public-certs)

1: config map for GIT:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: che-git-self-signed-cert
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    config.openshift.io/inject-trusted-cabundle: 'true'
data:
  ca-bundle.crt: |
    { ca-bundle here }
```

What I use in the che cluster
```
spec:
  devEnvironments:
    trustedCerts:
      gitTrustedCertsConfigMapName: che-git-self-signed-cert
```

**Result**: this cert is not defined in the gitconfig.

2: config map for any other tool:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: che-self-signed-cert
  labels:
    app.kubernetes.io/component: ca-bundle
    app.kubernetes.io/part-of: che.eclipse.org
    config.openshift.io/inject-trusted-cabundle: 'true'
data:
  ca-bundle.crt: |
    { ca-bundle here }
```

Result: che-self-signed-cert.crt is available in **/public-certs**
I can use this certificate to use with GIT or any other tool succesfully.

-----

I'm seems the ca-bundle method is not possible together with the che cluster gitTrustedCertsConfigMapName setting?
The result of the second configmap is available in **/public-certs** and is usable with GIT or any other tool. So the ca-bundle itself is correct and functional.

Therefor I was wondering if it is possible to set environment variables  for example to let GIT and any other tool know where to find the right certificate to use in **/public-certs**
