### ISSUE TITLE
How to make Che use a production certificate?

### ISSUE THREAD

**Issue by ghost** [eclipse/che#22349]
### Summary

So, when deploying with chectl, che seems to generate a self-signed certificate. But to run it in production, you need a certificate signed by a real CA. I am using cert-manager to generate LetsEncrypt certificates for other parts of my application, but I don't know how to make Che use a real certificate too.

There doesn't seem to be anything in the docs about this, and old Github issues are all full of dead links.

**Comment by tolusha** [comment]
That's a good question deserved to be put in the doc.
Let me know if it helps you.

1. Create the following secrets before deploying Eclipse Che:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: che-tls
  namespace: eclipse-che
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
type: kubernetes.io/tls
data:
  tls.crt: <BASE64_ENCODED_SERVER_PRIVATE_KEY>
  tls.key: <BASE64_ENCODED_SERVER_PUBLIC_KEY>
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
  name: self-signed-certificate
  namespace: eclipse-che
type: Opaque
data:
  ca.crt: <BASE64_ENCODED_CERTIFICATE_CHAIN_OF_TRUST>
```
