### ISSUE TITLE
There is quay.io/che-incubator/che-code image version mismatch in https://eclipse-che.github.io/che-devfile-registry/ DevWorkspace templates

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#22340]
### Describe the bug

There is outdated quay.io/che-incubator/che-code:**7.66.0** image reference in https://eclipse-che.github.io/che-devfile-registry/7.67.0/devfiles/index.json DevWorkspace templates.

It seems to be common problem, because there is quay.io/che-incubator/che-code:**7.63.0** image reference in https://eclipse-che.github.io/che-devfile-registry/7.64.0/devfiles/index.json DevWorkspace templates.

### Che version

7.64.0, 7.67.0

### Steps to reproduce

Open 
https://eclipse-che.github.io/che-devfile-registry/7.67.0/devfiles/dotnet-asp.net/devworkspace-che-code-latest.yaml and look at `che-code-injector > container > image` address.

There is:
```
   - name: che-code-injector
      container:
        image: >-
          quay.io/che-incubator/che-code@sha256:018394d5100c79d532ea0baf5ed0e902783b33ca57c7fb862108e3d688d97d84
```
Where quay.io/che-incubator/che-code@sha256:018394d5100c79d532ea0baf5ed0e902783b33ca57c7fb862108e3d688d97d84 == quay.io/che-incubator/che-code:7.66.0

![Screenshot from 2023-06-30 17-28-25](https://github.com/eclipse/che/assets/1197777/093712a5-c0af-4b1e-8085-8a2888cb97c9)

### Expected behavior

```
    - name: che-code-injector
      container:
        image: >-
          quay.io/che-incubator/che-code@sha256:235f2028e1869ac4630a61adbc5cd33e75584275f1789eb5cd5ad36ff6713a6a
```

where quay.io/che-incubator/che-code@sha256:235f2028e1869ac4630a61adbc5cd33e75584275f1789eb5cd5ad36ff6713a6a == quay.io/che-incubator/che-code:7.67.0

![Screenshot from 2023-06-30 17-51-33](https://github.com/eclipse/che/assets/1197777/b78f30c6-cf17-43bb-a6aa-8c94e54866f2)

### Runtime

OpenShift

### Installation method

chectl/latest

### Environment

Linux
