### ISSUE TITLE
Devfile without metadata fails to start

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22350]
### Describe the bug

Trying to start the following [devfile](https://gist.githubusercontent.com/l0rd/ba1f55dcc7c230fb4a7f51e3f4529c24/raw/5febd3f60cacc271d8d2cd9b7b160be1bb2daddc/simple-devfile.yaml) on dogfooding instance result in an error:

```yaml
schemaVersion: 2.2.0
attributes:
  controller.devfile.io/storage-type: ephemeral
projects:
  - name: quarkus-api
    git:
      remotes:
        origin: https://github.com/l0rd/quarkus-api
components:
  - name: dev-tooling
    container:
      image: quay.io/mloriedo/devtools:latest
      memoryRequest: 2G
      memoryLimit: 8G
      cpuRequest: '1'
      cpuLimit: '4'
```

<img width="543" alt="image" src="https://github.com/eclipse/che/assets/606959/2ada253f-5042-495b-bcee-4a4c893cc540">

### Che version

7.70@latest

### Steps to reproduce

Click [here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://gist.githubusercontent.com/l0rd/ba1f55dcc7c230fb4a7f51e3f4529c24/raw/5febd3f60cacc271d8d2cd9b7b160be1bb2daddc/simple-devfile.yaml).

### Expected behavior

In the Devfile spec [metadata](https://devfile.io/docs/2.2.0/devfile-schema#metadata) is an optional field.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon
