### ISSUE TITLE
When the devfile uses a parent then VS Code is executed in a sidecar container

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22371]
### Describe the bug

I am using a devfile like the following one:

```yaml
schemaVersion: 2.2.0
metadata:
  name: simple-quarkus
parent:
  uri: https://gist.githubusercontent.com/l0rd/e55119c949165337b061c4af25961101/raw/parent-devfile.yaml
```

The referenced parent is as simple as:

```yaml
schemaVersion: 2.2.0
metadata:
  name: simple-parent
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
```

The problem is that VS Code is run in the `che-code-runtime-description` pod rather than the `tools` container:

<img width="268" alt="image" src="https://github.com/eclipse/che/assets/606959/5c7a65b9-8632-4dac-9b28-901dbe3421b3">

As a consequences the container, the env variables, the endpoints, the volumes defined in the `tools` component are not visible in the main container where VS Code is running. 

##### Workaround:

Add attribute ` controller.devfile.io/merge-contribution: true` to the parent tooling component:

```yaml
schemaVersion: 2.2.0
metadata:
  name: simple-parent
components:
  - name: tools
     attributes:
       controller.devfile.io/merge-contribution: true
     container:
       image: quay.io/devfile/universal-developer-image:ubi8-latest
```

### Che version

7.71@latest

### Steps to reproduce

[Click here](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://gist.githubusercontent.com/l0rd/e55119c949165337b061c4af25961101/raw/f0c181ce894620664daa594ca8e83296f0158d78/devfile.yaml) to reproduce on dogfooding
[Click here](https://workspaces.openshift.com/#https://gist.githubusercontent.com/l0rd/e55119c949165337b061c4af25961101/raw/f0c181ce894620664daa594ca8e83296f0158d78/devfile.yaml) to reproduce on devsandbox 

### Expected behavior

The container `che-code-runtime-description` should not be included in the workspace pod, it should only contribute to the tools container, as it has the attribute `controller.devfile.io/container-contribution: true`.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

#### The flattened DevWorkspace:

```yaml
attributes:
  controller.devfile.io/devworkspace-config:
    name: devworkspace-config
    namespace: dogfooding
  controller.devfile.io/scc: container-build
  controller.devfile.io/storage-type: per-workspace
  dw.metadata.annotations:
    che.eclipse.org/devfile-source: |
      url:
        location: >-
          https://gist.githubusercontent.com/l0rd/e55119c949165337b061c4af25961101/raw/f0c181ce894620664daa594ca8e83296f0158d78/devfile.yaml
      factory:
        params: >-
          url=https://gist.githubusercontent.com/l0rd/e55119c949165337b061c4af25961101/raw/f0c181ce894620664daa594ca8e83296f0158d78/devfile.yaml
commands:
- apply:
    component: che-code-injector
  attributes:
    controller.devfile.io/imported-by: editor
  id: init-container-command
- attributes:
    controller.devfile.io/imported-by: editor
  exec:
    commandLine: nohup /checode/entrypoint-volume.sh > /checode/entrypoint-logs.txt
      2>&1 &
    component: che-code-runtime-description
  id: init-che-code-command
components:
- attributes:
    controller.devfile.io/imported-by: parent
  container:
    image: quay.io/devfile/universal-developer-image:ubi8-latest
  name: tools
- attributes:
    app.kubernetes.io/component: che-code-runtime
    app.kubernetes.io/part-of: che-code.eclipse.org
    controller.devfile.io/container-contribution: true
    controller.devfile.io/imported-by: editor
  container:
    cpuLimit: 500m
    cpuRequest: 30m
    endpoints:
    - attributes:
        controller.devfile.io/endpoint-url: https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/l0rd/simple-quarkus/3100/
        cookiesAuthEnabled: true
        discoverable: false
        type: main
        urlRewriteSupported: true
      exposure: public
      name: che-code
      protocol: https
      secure: false
      targetPort: 3100
    - attributes:
        controller.devfile.io/endpoint-url: http://l0rd-simple-quarkus-code-redirect-1.apps.che-dev.x6e0.p1.openshiftapps.com/
        discoverable: false
        urlRewriteSupported: false
      exposure: public
      name: code-redirect-1
      protocol: http
      targetPort: 13131
    - attributes:
        controller.devfile.io/endpoint-url: http://l0rd-simple-quarkus-code-redirect-2.apps.che-dev.x6e0.p1.openshiftapps.com/
        discoverable: false
        urlRewriteSupported: false
      exposure: public
      name: code-redirect-2
      protocol: http
      targetPort: 13132
    - attributes:
        controller.devfile.io/endpoint-url: http://l0rd-simple-quarkus-code-redirect-3.apps.che-dev.x6e0.p1.openshiftapps.com/
        discoverable: false
        urlRewriteSupported: false
      exposure: public
      name: code-redirect-3
      protocol: http
      targetPort: 13133
    env:
    - name: CHE_DASHBOARD_URL
      value: https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com
    - name: CHE_PLUGIN_REGISTRY_URL
      value: https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/plugin-registry/v3
    - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
      value: http://plugin-registry.dogfooding.svc:8080/v3
    - name: CLUSTER_CONSOLE_URL
      value: https://console-openshift-console.apps.che-dev.x6e0.p1.openshiftapps.com
    - name: CLUSTER_CONSOLE_TITLE
      value: OpenShift console
    - name: OPENVSX_REGISTRY_URL
      value: https://open-vsx.org
    image: quay.io/devfile/universal-developer-image@sha256:9b8f171125d1b0f8023258f343ce9d044f073fe769a3d360b25a6ea52d915bfd
    memoryLimit: 1024Mi
    memoryRequest: 256Mi
    sourceMapping: /projects
    volumeMounts:
    - name: checode
      path: /checode
  name: che-code-runtime-description
- attributes:
    controller.devfile.io/imported-by: editor
  name: checode
  volume: {}
- attributes:
    controller.devfile.io/imported-by: editor
  container:
    command:
    - /entrypoint-init-container.sh
    cpuLimit: 500m
    cpuRequest: 30m
    env:
    - name: CHE_DASHBOARD_URL
      value: https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com
    - name: CHE_PLUGIN_REGISTRY_URL
      value: https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/plugin-registry/v3
    - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
      value: http://plugin-registry.dogfooding.svc:8080/v3
    - name: CLUSTER_CONSOLE_URL
      value: https://console-openshift-console.apps.che-dev.x6e0.p1.openshiftapps.com
    - name: CLUSTER_CONSOLE_TITLE
      value: OpenShift console
    - name: OPENVSX_REGISTRY_URL
      value: https://open-vsx.org
    image: quay.io/che-incubator/che-code:insiders
    memoryLimit: 256Mi
    memoryRequest: 32Mi
    sourceMapping: /projects
    volumeMounts:
    - name: checode
      path: /checode
  name: che-code-injector
events:
  postStart:
  - init-che-code-command
  preStart:
  - init-container-command
```
