### ISSUE TITLE
Parent commands are not available in VS Code tasks

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22373]
### Describe the bug

When a devfile uses a parent and the parent has some commands those are not visible as tasks in VS Code. This is probably due to the fact that the commands have the attribute `controller.devfile.io/imported-by: parent` in the flattened devfile:

```yaml
- attributes:
    controller.devfile.io/imported-by: parent
  exec:
    commandLine: ./mvnw clean package -DskipTests=true
    component: tools
    group:
      isDefault: true
      kind: build
    label: 1. Package
  id: package
```

### Che version

7.71@latest

### Steps to reproduce

Start a workspace using the branch `parent` of this git repository: https://github.com/l0rd/inventory-quarkus/

### Expected behavior

I would like to see the parents commands but I only see the ones coming from the devfile:

<img width="786" alt="image" src="https://github.com/eclipse/che/assets/606959/751b48bd-1c12-4605-8dd2-22dc597c0303">
