### ISSUE TITLE
Provide easy way for admins to set `log.level = DEBUG` for traefik container in gateway

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#22415]
### Is your enhancement related to a problem? Please describe

Currently, the gateway pod's traefik container has a `log.level` of `INFO` (see [here](https://github.com/eclipse-che/che-operator/blob/edd6a92582f8f7aeac06f8f7b7bc45e46206caf1/pkg/deploy/gateway/gateway.go#L404)). For debugging potential issues with traefik, it is helpful to set `log.level` to `DEBUG`.

It would be great if an admin can easily increase the log level (ie. output more verbose logs) for traefik (as well as other che-gateway containers too like `oauth-proxy`, `kube-rbac-proxy`)

### Describe the solution you'd like

Maybe a new attribute in the Che CR spec like:
```
spec.networking.auth.gateway.verboseLogs = true|false
```

with the default being `false`

### Describe alternatives you've considered

An alternative that I tried, was to provide the `TRAEFIK_LOG_LEVEL` environment variable to the `gateway` container in the che cluster CR:
```
networking:
    auth:
      gateway:
        ...
        deployment:
          containers:
            - env:
                - name: TRAEFIK_LOG_LEVEL
                  value: DEBUG
              name: gateway
```

but this does not work, since for traefik, the env variable config is not applied since we are already using the static config from the `che-gateway-config` configmap.

For traefik, we cannot mix the sources for which the static config comes from:
```
There are three different, mutually exclusive (e.g. you can use only one at the same time), ways to define static configuration options in Traefik:
```
https://doc.traefik.io/traefik/getting-started/configuration-overview/#the-static-configuration
