### ISSUE TITLE
As an Admin I want to easily update 'Getting Started' / 'Select a Sample' view and point it to repositories we use inside our organization

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22429]
### Is your task related to a problem? Please describe

**Motivation**

Currently, it is very hard to add custom samples and update devfile registry - https://github.com/ibuziuk/che-devfile-registry 
There is a plan to switch to devfile.io and a dedicated devfile registry operator to decouple samples from Dev Spaces as part of - https://github.com/eclipse/che/issues/20251 
Whereas this is an ultimate goal and would allow removing devfile-registry operand from the operator,  there could be challenges for customers to use this approach
- devfile registry operator is community supported 
- setup and configuration of yet another operator could be challenging

### Describe the solution you'd like

As an Admin I want to update 'Getting Started' / 'Select a Sample' view and point it to repositories we use inside our organization. Basically, this could boil down to creating the cm with the list of repositories that would be read by the dashboard and displayed accordingly

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: getting-started
labels:
    app.kubernetes.io/part-of: che.eclipse.org
data:
  getting-started-samples: |-
    [
      {
        "name": "Java Quarkus",
        "description": "Quarkus example with a default REST endpoint application sample",
        "tag": "Community",
        "url": "https://github.com/che-incubator/quarkus-api-example/",
        "icon": {
          "base64data": <base64-encoded-data>,
          "mediatype": "image/png"
        }
      },
      {
        "name": "Eclipse Che Dashboard",
        "description": "Specifies development environment needed to develop the Eclipse Che Dashboard.",
        "tag": "Eclipse Che",
        "url": "https://github.com/che-incubator/quarkus-api-example/",
        "icon": {
          "base64data": <base64-encoded-data>,
          "mediatype": "image/png"
        }
      }
    ]
```
The pros of this approach:
- simple and straight-forward configuration via single k8s resource
- airgap / private repo support OOTB assuming that OAuth / PAT is configured

### Additional context

- `description` is optional
- `tag` is optional
- `icon` is optional, if not set on UD we display the default image:

![image](https://github.com/eclipse/che/assets/1461122/b55dea51-b015-42c9-a569-47c15fe2d80e)

**Comment by ibuziuk** [comment]
we can use a different or similar structure to devfile.io - whatever would be easier to support/maintain. Also, maybe this cm should be managed by the operator

**Comment by tolusha** [comment]
> Also, maybe this cm should be managed by the operator
What does it mean?

My suggestion:
```yaml
      {
        "displayName": "Eclipse Che Dashboard",
        "description": "Specifies development environment needed to develop the Eclipse Che Dashboard.",
        "tags": ["Eclipse Che", "Dashboard"],
        "url": "https://github.com/che-incubator/quarkus-api-example/",
        "icon": {
          "base64data": <base64-encoded-data>,
          "mediatype": "image/png"
        }
      }
```

**Comment by ibuziuk** [comment]
format lgtm, I do not know if it makes sense to have the cm be managed by the operator e.g. `app.kubernetes.io/managed-by: che-operator`

**Comment by tolusha** [comment]
The ConfigMap must have some distinguish labels.
I suggest: 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: getting-started
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: devfile-metadata
data:
  getting-started-samples: |-
    [
      {
        "displayName": "Eclipse Che Dashboard",
        "description": "Specifies development environment needed to develop the Eclipse Che Dashboard.",
        "tags": ["Eclipse Che", "Dashboard"],
        "url": "https://github.com/che-incubator/quarkus-api-example/",
        "icon": {
          "base64data": <base64-encoded-data>,
          "mediatype": "image/png"
        }
      }
    ]
```
