### ISSUE TITLE
Upgrade devfile on existing workspace not working on 7.72.0

### ISSUE THREAD

**Issue by disaster37** [eclipse/che#22432]
### Describe the bug

The PR #22242 of this issue is include on this release, but it not working.

When i run task `Eclipse Che: Restart workspace from local devfile` on fresh workspace (cheCode 1.81.0), I get error 

```
Can not restart the workspace from the local devfile: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: squid.squid.svc.cluster.local. is not in the cert's altnames: DNS:ran37hpd2.hm.dm.ad, DNS:ran37hpd1.hm.dm.ad, DNS:ran37hpd3.hm.dm.ad, DNS:api.rancher-hpd.hm.dm.ad, DNS:localhost, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:10.221.70.204, IP Address:10.221.70.203, IP Address:10.221.70.205, IP Address:127.0.0.1, IP Address:10.43.0.1
```

I can't understand why it search the proxy hostnane on certificats:

```yaml
apiVersion: org.eclipse.che/v2
kind: CheCluster
spec:
  components:
    cheServer:
      proxy:
        url: http://squid.squid.svc.cluster.local
        port: '8080'
        nonProxyHosts: 
          - 'localhost'
          - '.svc'
          - '.svc.cluster.local'
```

During test of issue #22242, the update of workspace work fine. But it not working on release 7.72.0

### Che version

7.72@latest

### Steps to reproduce

Deploy eclipse che with proxy set, for exemple

```yaml
apiVersion: org.eclipse.che/v2
kind: CheCluster
spec:
  components:
    cheServer:
      proxy:
        url: http://squid.squid.svc.cluster.local
        port: '8080'
        nonProxyHosts: 
          - 'localhost'
          - '.svc'
          - '.svc.cluster.local'
```

Start fresh workspace, then try to update it from local devfile.yml

### Expected behavior

It update workspace without error

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Linux

**Comment by disaster37** [comment]
Here a dynamic screen capture:

![mRhUVb7DJ2](https://github.com/eclipse/che/assets/10331073/6c790b71-0301-48bc-8e97-61110ea357f5)

**Comment by tolusha** [comment]
@azatsarynnyy @RomanNikitenko 
Could you have a look please?

**Comment by RomanNikitenko** [comment]
> During test of issue https://github.com/eclipse/che/issues/22242, the update of workspace work fine. But it not working on release 7.72.0

I'm really sorry, but we tested it and it worked for you, it's really strange...
On the Che-Code side we use a library to generate a new Devfile context.
So, maybe some changes were on the library side...

About the fix for the current issue: there is an idea from @l0rd: pass to the library the `pluginRegistryUrl` parameter using the `CHE_PLUGIN_REGISTRY_INTERNAL_URL` env variable.  There is little change, but I'm not able to reproduce the issue, so it is a problem for me to test if the idea fixes the problem...

**Comment by disaster37** [comment]
You know why it try to check dns entry on certificat provided by `components.cheServer.proxy.url` ?

If you wan't, I can test on my cluster like last time if you provide me est devfile somewhere ...

**Comment by tolusha** [comment]
I've just checked the latest Eclipse Che on disconnected OpenShift cluster with proxy configured.
I can't reproduce the issue.

@RomanNikitenko 
Could you point to source code where this problem comes from?

**Comment by RomanNikitenko** [comment]
@tolusha 
On the che-code side [we use devWorkspaceGenerator](https://github.com/che-incubator/che-code/blob/ca52be6f259098c36965541fab1aa583637b01e3/code/extensions/che-remote/src/extension.ts#L120) to generate a new Devfile context

The corresponding part of the library is [here](https://github.com/eclipse-che/che-devfile-registry/blob/main/tools/devworkspace-generator/src/main.ts#L30).

I created a draft with potential fix: https://github.com/che-incubator/che-code/pull/268.
It includes idea from Mario: https://github.com/eclipse/che/issues/22388#issuecomment-1670409073
The image for testing is: `quay.io/che-incubator-pull-requests/che-code:pr-268-amd64`, see [here](https://github.com/che-incubator/che-code/pull/268#issuecomment-1687667499).

https://github.com/RomanNikitenko/web-nodejs-sample/tree/fix-restart-from-devfile can be used for testing, it contains reference for editor image from the PR: https://github.com/RomanNikitenko/web-nodejs-sample/blob/fix-restart-from-devfile/.che/che-editor.yaml#L33

**Comment by disaster37** [comment]
Hi,

I have tested the following [devfile](https://github.com/RomanNikitenko/web-nodejs-sample/tree/fix-restart-from-devfile). But I get the same error.
The `che-code-injector` image is `quay.io/che-incubator-pull-requests/che-code:pr-268-amd64`, so devfile seems good.

```
Can not restart the workspace from the local devfile: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: squid.squid.svc.cluster.local. is not in the cert's altnames: DNS:ran37hpd2.hm.dm.ad, DNS:ran37hpd1.hm.dm.ad, DNS:ran37hpd3.hm.dm.ad, DNS:api.rancher-hpd.hm.dm.ad, DNS:localhost, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:10.221.70.204, IP Address:10.221.70.203, IP Address:10.221.70.205, IP Address:127.0.0.1, IP Address:10.43.0.1
```

**Comment by tolusha** [comment]
Do you use man-in-the-middle proxy?
If so, have you added proxy certificate into the Che like this [1]
[1] https://eclipse.dev/che/docs/stable/administration-guide/importing-untrusted-tls-certificates/

**Comment by RomanNikitenko** [comment]
@disaster37 
thank you very much for testing!

As far as I understand, Mario's idea was:
- there is a request to the plugin registry to get editor's devfile content
- there is a problem with certificates if the request goes by `https`
- there is should be no problem if we pass [internal plugin registry URL](https://github.com/che-incubator/che-code/pull/268/files#diff-c5a53854fa57c473aaff2645f24bb65e720b623b4cffa2601c2089366293f222R120) to the library: the URL is `http` based, so the request should go by `http`

It would be helpful to check browser console to confirm that `internal` plugin registry URL is `http` and is passed to the library. So, `F1` => `Restart Workspace from Local Devfile` => check the log in the browser console.

<img width="707" alt="Screenshot 2023-08-23 at 10 33 00" src="https://github.com/eclipse/che/assets/5676062/b88c0899-f0cb-483c-b409-acd63ddeffa3">

**Comment by disaster37** [comment]
I past here the actual CheCluster resource, maybee there are something more that enter in the dance ...

```yaml
pec:
  components:
    cheServer:
      clusterRoles:
        - che-users-extras
      debug: false
      deployment:
        containers:
          - image: quay.io/webcenter/che-server:7.72.0
            name: che
      extraProperties:
        CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATIONS: >-
          che.eclipse.org/username=<username>,field.cattle.io/projectId=c-57d7n:p-8j45h
        CHE_INFRA_KUBERNETES_NAMESPACE_LABELS: >-
          app.kubernetes.io/part-of=che.eclipse.org,app.kubernetes.io/component=workspaces-namespace,field.cattle.io/projectId=p-8j45h
        CHE_INFRA_KUBERNETES_WORKSPACE__START__TIMEOUT__MIN: '15'
        CHE_INFRA_KUBERNETES_WORKSPACE__UNRECOVERABLE__EVENTS: >-
          MountVolume.SetUpfailed,Failed to pull
          image,FailedCreate,ReplicaSetCreateError
        CHE_OIDC_USERNAME__CLAIM: email
        CHE_WORKSPACE_DEFAULT__CPU__LIMIT__CORES: '1'
        CHE_WORKSPACE_DEFAULT__CPU__REQUEST__CORES: 500m
        CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__LIMIT__CORES: 300m
        CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__REQUEST__CORES: 50m
      logLevel: INFO
      proxy:
        nonProxyHosts:
          - localhost
          - 10.0.0.0/8
          - .hm.dm.ad
          - .rancher-hpd.hm.dm.ad
          - .svc.cluster.local
          - .svc
        port: '8080'
        url: http://squid.squid.svc.cluster.local
    dashboard: {}
    devWorkspace: {}
    devfileRegistry: {}
    imagePuller:
      enable: false
      spec: {}
    metrics:
      enable: true
    pluginRegistry: {}
  containerRegistry: {}
  devEnvironments:
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: container-build
    defaultNamespace:
      autoProvision: true
      template: <username>-che
    disableContainerBuildCapabilities: true
    maxNumberOfRunningWorkspacesPerUser: 5
    maxNumberOfWorkspacesPerUser: -1
    persistUserHome:
      enabled: true
    secondsOfInactivityBeforeIdling: -1
    secondsOfRunBeforeIdling: 43200
    startTimeoutSeconds: 300
    storage:
      pvcStrategy: per-workspace
    user:
      clusterRoles:
        - che-users-extras
  gitServices: {}
  networking:
    annotations:
      monitor.k8s.webcenter.fr/templates: '[{"namespace":"etloutils-monitoring-operator", "name": "check-ingress"}]'
    auth:
      gateway:
        configLabels:
          app: che
          component: che-gateway-config
      identityProviderURL: https://dex.rancher-hpd.hm.dm.ad
      oAuthClientName: k8s
      oAuthScope: openid email profile
      oAuthSecret: XXX
    domain: che.rancher-hpd.hm.dm.ad
    ingressClassName: nginx
    tlsSecretName: che-tls-certificates
status:
  chePhase: Active
  cheURL: https://che.rancher-hpd.hm.dm.ad
  cheVersion: 7.72.0
  devfileRegistryURL: https://che.rancher-hpd.hm.dm.ad/devfile-registry
  gatewayPhase: Established
  pluginRegistryURL: https://che.rancher-hpd.hm.dm.ad/plugin-registry/v3
  workspaceBaseDomain: che.rancher-hpd.hm.dm.ad
```
