### ISSUE TITLE
404 preview URL of the Eclipse Che Port extension

### ISSUE THREAD

**Issue by Mbd06b** [eclipse/che#22445]
### Describe the bug

When I launch a default workspace, the Eclipse Che Port extension detects the running process and provides a Preview Link, but on visiting the preview link I'm getting a generic nginx 404. 

I'm looking for pointers debugging this particular issue. I'm not sure where to start.. 

### Che version

7.72@latest

### Steps to reproduce

- Launch default spring-petclinic Workspace, 
- Add maven vs code extensions, update/install dependencies. 
- Maven Launch ... something like "mvn spring-boot:run" 

Eclipse Che Port extension shows a Preview URL notification. 
- Open link shows 404. 

### Expected behavior

The preview URL should show the landing page of the Spring Boot app launched. 

### Runtime

other (please specify in additional context)

### Screenshots

After deploying, running the pet-clinic default workspace project, I get the preview URL popup. 

![image](https://github.com/eclipse/che/assets/12649222/b08fe4a0-4d83-4527-b2f4-c688901dd5f7)

Visiting the popup, I'm getting a 404 not found: 

Preview Link:  
![image](https://github.com/eclipse/che/assets/12649222/bb4c7d4d-7c78-4a06-8581-4fbdb08bf446)

### Installation method

chectl/next

### Environment

other (please specify in additional context)

### Eclipse Che Logs

```shell
I've used chectl to save logs, there's a lot,  if there's something specific in a certain component that I should look for to share that would be helpful.
```

### Additional context

I use Microk8s (ubuntu 22)
I use GCP for Google Cloud Domains and CloudDNS, but only to facilitate FQDN traffic and DNS settings to my cluster
and deploy chectl with a domain;. 

In order to get valid  https certificates working to reach the dashboard. I manually created a certificate resource using cert manager, and applied the suspected labels, in order to have cert-manager provied a secure certificate instead of the Eclipse-che Local certs. 

Since it was the last thing I seem to get working before I was able to get into Eclipse Che, my recency-bias is telling me that there might be some configuration I missed that could be impacting how this workspace/preview routing handoff might be happening. 

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: che-tls
  namespace: eclipse-che
  labels:
    app.kubernetes.io/component: che-tls
    app.kubernetes.io/instance: che
    app.kubernetes.io/managed-by: che-operator
    app.kubernetes.io/name: che
    app.kubernetes.io/part-of: che.eclipse.org
spec:
  secretName: che-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - code.example.com
    - '*.code.example.com'`
```
