### ISSUE TITLE
Unable to use Azure Devops Git repos using visualstudio.com domain

### ISSUE THREAD

**Issue by rafaeltuelho** [eclipse/che#22459]
### Describe the bug

Devspaces fails to create a new workspace from an Azure Devops Git Repo using the visualstudio.com domain.
It seems Azure uses different domains for their repos hosted in Azure. Devspaces seems to work for azure.com but not with visualstudio.com

### Che version

7.73@latest

### Steps to reproduce

We saw and Azure gitrepo using visualstudio.com as the URL domain. So, I am not sure if it is possible to reproduce this.
Maybe need to check which domains Azure uses to host Git repos.

### Expected behavior

It should work regardless of the URL domain.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Linux

**Comment by tolusha** [comment]
Could you provide an example of such a repo?
Not sure, but could you try this.

```
spec:
  components:
    cheServer:
      extraProperties:
        CHE_INTEGRATION_AZURE_DEVOPS_SCM_API__ENDPOINT: "https://visualstudio.com"
```
