### ISSUE TITLE
Failed to read devfile from `registry.devfile.io` deployed on the cluster

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#22456]
### Describe the bug

Failed to read devfile from `registry.devfile.io` deployed on the cluster

### Che version

7.73@latest

### Steps to reproduce

1. Start a minikube
```
minikube start --cpus 4 --memory 10240 --disk-size=50GB --vm-driver=kvm 

```
2. Generate certificates for the minikube cluster [1]
```
bash <(curl -sL  https://gist.githubusercontent.com/tolusha/ac9e11e04b1d4b3e6da43acc872425b7/raw/fd9aefcc5f6b01494e1f0c613ce6fd3f48e2b4ee/generate-minikube-certs.sh)

cat domain.crt ca.crt > chain.crt
kubectl -n kube-system create secret tls mkcert --key domain.key --cert chain.crt
minikube addons enable ingress 
minikube addons configure ingress <<< kube-system/mkcert
minikube addons disable ingress
minikube addons enable ingress
```

3. Deploy devfile registry operator
```
git clone https://github.com/devfile/registry-operator
cd registry-operator
make install-cert
kubectl wait --for=condition=ready pod -l app.kubernetes.io/component=controller -n cert-manager --timeout=60s 
kubectl wait --for=condition=ready pod -l app.kubernetes.io/component=cainjector -n cert-manager --timeout=60s 
kubectl wait --for=condition=ready pod -l app.kubernetes.io/component=webhook -n cert-manager --timeout=60s
make install
make deploy
kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=devfileregistry-operator -n registry-operator-system --timeout=60s

kubectl create namespace registry
cat <<EOF | kubectl apply -f -                                                                                                                                       
apiVersion: registry.devfile.io/v1alpha1
kind: DevfileRegistry
metadata:
  name: devfile-registry
  namespace: registry
spec:
  devfileIndex:
    image: quay.io/devfile/devfile-index:next
  tls:
    enabled: true
  k8s:
    ingressDomain: $(minikube ip).nip.io
  telemetry:
    registryName: test
EOF
```

4. Deploy Eclipse Che (chectl next version)
```
cat > p.yaml <<EOF
kind: CheCluster
apiVersion: org.eclipse.che/v2
spec:
  networking:
    tlsSecretName: ""
  components:
    devfileRegistry:
      disableInternalRegistry: true
      externalDevfileRegistries:
      - url: https://devfile-registry.$(minikube ip).nip.io
EOF

chectl server:deploy -p minikube --che-operator-cr-patch-yaml p.yaml --skip-cert-manager
```

5. Open dashboard and try to start a workspace
```
chectl dashboard:open
```

### Expected behavior

Dashboard successfully read a devfile from the registry.

### Runtime

minikube

### Screenshots

![Screenshot from 2023-08-25 13-31-38](https://github.com/eclipse/che/assets/1640675/d7b552a7-4753-43a8-9979-0db721394082)

### Installation method

chectl/next

### Environment

Linux
