### ISSUE TITLE
[UD] Eclipse Che logo from the Custom Resource does not affect the `About` modal window

### ISSUE THREAD

**Issue by olexii4** [eclipse/che#22477]
### Describe the bug

Eclipse Che logo from the Custom Resource does not affect the `About` modal window.

### Che version

7.73@latest

### Steps to reproduce

1. Deploy Eclipse CHE.
2. Added a logo as a base64 encoded image into Custom Resource.
```
spec:
  components:
    dashboard:
       branding:
         logo:
           base64data: 'PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgaWQ9IlJlZGhhdCI+PHBhdGggZD0iTTE2LjEyNSAxOS44MzdjLTIuOTA4IDAtNS44NC0uNjczLTcuNjE0LTEuMzA0QzQuODkyIDE3LjI0NC4xMDQgMTMuOTM5LjUyOSAxMS40ODJjLjIyNS0xLjMwNyAxLjc2Mi0xLjk3OSA0LjU2OS0ybC4wMjItLjExMmMuMzYzLTEuODY0Ljk3LTQuOTgzIDQuMDA4LTQuOTgzLjUyMSAwIDEuMDk2LjEgMS43MTIuMjk0bC4xNDktLjA1MWMxLjUwMy0uNTE2IDYuODExLTIuMjMyIDguNjQgNi45NzEgMS4xOTguMTg2IDIuOTA1Ljg3MiAzLjU4MyAyLjI0Mi4zNTQuNzE5LjU1OCAxLjkxMi0uNTAxIDMuNTItMS4wNjUgMS42MTctMy4zNDIgMi40NzQtNi41ODYgMi40NzR6TTUuMjM0IDEwLjQ4MmMtMi4yMzYgMC0zLjU5Mi40MjYtMy43MjEgMS4xNjktLjI2MyAxLjUyNSAzLjUwNiA0LjU3OCA3LjMzMiA1LjkzOSAxLjY5NS42MDQgNC40OTggMS4yNDYgNy4yNzkgMS4yNDYgMi4wMTcgMCA0LjY1MS0uMzUgNS43NTItMi4wMjEuNjQtLjk3NS43ODgtMS44MjQuNDQtMi41MjctLjU2NS0xLjE0MS0yLjIyOS0xLjY2OC0zLjE0Ni0xLjczMmwtLjM4Ny0uMDI2LS4wNy0uMzgyYy0uODUxLTQuNjQ4LTIuNjEyLTcuMDA1LTUuMjM5LTcuMDA1LS44OTYgMC0xLjY4OC4yNzItMi4xNjMuNDM1LS4xNDcuMDUtLjI2Ny4wOS0uMzUzLjExNGwtLjE0NS4wMzgtLjE0Mi0uMDQ4QzEwLjEgNS40ODkgOS41OCA1LjM5IDkuMTI1IDUuMzljLTIuMDQ1IDAtMi41OTkgMS45NzUtMy4wMjYgNC4xNzVsLS4xOTEuOTI4LS42NzQtLjAxMXoiIGZpbGw9IiNkODViNTMiIGNsYXNzPSJjb2xvcjAwMDAwMCBzdmdTaGFwZSI+PC9wYXRoPjxwYXRoIGQ9Ik0xNC4yMDYgMTQuMzYxYy0xLjEwOCAwLTIuMjgtLjE1NS0zLjQ1My0uNDc4LTIuNDQyLS42NzEtNC41NzItMS45NzktNS44NDMtMy41ODVsLjc4NC0uNjIxYzEuMTQyIDEuNDQ0IDMuMDgyIDIuNjI1IDUuMzIzIDMuMjQxIDMuMjI1Ljg4NiA2LjUwNi4zOTcgNy45ODYtMS4xODdsLjczMS42ODJjLTEuMTgyIDEuMjY4LTMuMjE0IDEuOTQ4LTUuNTI4IDEuOTQ4eiIgZmlsbD0iI2Q4NWI1MyIgY2xhc3M9ImNvbG9yMDAwMDAwIHN2Z1NoYXBlIj48L3BhdGg+PC9zdmc+'
           mediatype: 'image/svg+xml'
```
3. Press 'f5' to reload the CHE dashboard page and click the `About` button.
4. The Modal window will include the default logo.

### Expected behavior

The custom logo should be applied to the main page and the `About` modal window.

### Runtime

minikube

### Screenshots

![Знімок екрана 2023-09-06 о 03 59 40](https://github.com/eclipse/che/assets/6310786/5297cf1d-4a97-4fd8-a0f6-38efb5d130ce)

### Installation method

chectl/next

### Environment

macOS
