### ISSUE TITLE
Use the first 'starterProject' during DevWorkspace creation from devfile.io samples / stacks

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22486]
### Is your task related to a problem? Please describe

Devfile.io samples could have one or multiple `starterProjects` defined e.g. https://registry.devfile.io/devfiles/java-vertx/1.2.0
When DevWorkspace is created based on the devfile with `startedProjects` defined we should use `controller.devfile.io/use-starter-project` attribute and reference the first `starterProject` defined in the devfile.

### Describe the solution you'd like

Resulting DevWorkspace should have the the following attribute set:

```yaml
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
spec:
  template:
    attributes:
      controller.devfile.io/use-starter-project: first-starter-project-from-devfile
    starterProjects:
      - name: first-starter-project-from-devfile
        git:
           (...)
```

### Describe alternatives you've considered

N/A

### Additional context

More details in 
- https://github.com/devfile/devworkspace-operator/pull/1130
- https://github.com/devfile/devworkspace-operator/issues/1084
