### ISSUE TITLE
Eclipse Che installed in OpenShift or OKD clusters doesn't respect setting .spec.network.ingressClassName in CheCluster resource

### ISSUE THREAD

**Issue by jharmison-redhat** [eclipse/che#22498]
### Summary

When configuring a CheCluster on OpenShift or OKD, nothing enables using Ingress resources instead of Route resources - even if a separate Ingress controller is installed and working for other uses on the cluster. Is this a deliberate design choice, forcing the use of the OpenShift Router, or an accidental result of an overzealous implicit default?

There are many good reasons to use multiple Ingress controllers per cluster, and in my case my configuration makes using the OpenShift Router for dynamic Ingress creation (e.g. exposing an app running in a workspace) more cumbersome than it would be for one of my other Ingresses.

I'm not sure if this is a bug, a feature request, or something in between.

### Relevant information

To reproduce:
- create an OpenShift or OKD cluster
- install an alternative ingress implementation such as nginx or Istio Ingress Gateway
- install Eclipse Che and create the following CheCluster:
  ```yaml
  ---
  apiVersion: org.eclipse.che/v2
  kind: CheCluster
  metadata:
    name: eclipse-che
    namespace: eclipse-che
  spec:
    components:
      cheServer:
        debug: false
        logLevel: INFO
      metrics:
        enable: true
    containerRegistry: {}
    devEnvironments:
      startTimeoutSeconds: 300
      secondsOfRunBeforeIdling: -1
      maxNumberOfWorkspacesPerUser: -1
      containerBuildConfiguration:
        openShiftSecurityContextConstraint: container-build
      defaultNamespace:
        autoProvision: true
        template: che-<username>
      secondsOfInactivityBeforeIdling: 1800
      storage:
        pvcStrategy: per-user
    gitServices: {}
    networking:
      ingressClassName: nginx # or whatever you installed
    ```
- Observe that a Route is created and not an ingress:
![screenshot-2023-09-07_10:34:40](https://github.com/eclipse/che/assets/55772684/ddc26823-e401-43f9-9fab-38bf4822b14d)
