### ISSUE TITLE
[UD] CHE samples can't start with IntelliJ IDEA 

### ISSUE THREAD

**Issue by olexii4** [eclipse/che#22515]
### Describe the bug

CHE samples can't start with IntelliJ IDEA because of the relative link:
```yaml
links: {
  v2: "https://github.com/che-samples/apache-camel-k/tree/main",
  devWorkspaces: {
    che-incubator/che-idea/next: "/devfiles/apache-camel-k/devworkspace-che-idea-next.yaml",
  ...
}
...
```

### Che version

7.74@latest

### Steps to reproduce

1. Deploy Eclipse CHE.
2. Open `Create Workspace`.
3. Create a new workspace from the samples from [che-devfile-registry](https://github.com/eclipse-che/che-devfile-registry) with IntelliJ IDEA.
4. A 404 page not found error message will appear.

### Expected behavior

UD should resolve relative links correctly. We should be able to create a new workspace from samples with IntelliJ IDEA.

### Runtime

minikube

### Screenshots

![Знімок екрана 2023-09-15 о 16 16 12](https://github.com/eclipse/che/assets/6310786/be43bd0a-667c-40fa-932c-43224440bab7)
![Знімок екрана 2023-09-15 о 16 16 30](https://github.com/eclipse/che/assets/6310786/58a21a64-c67a-4792-9a23-ec0b751d6f63)

### Installation method

chectl/next

### Environment

macOS
