### ISSUE TITLE
Not able to run che-dashboard after building it: Error from server (Forbidden): pods is forbidden

### ISSUE THREAD

**Issue by moonbse** [eclipse/che#22553]
### Summary

I could build the project from dev file but while trying to run it using `yarn start -c` , I am getting permission denied/forbidden issue. My set up is standard minikube on ubuntu with default dex users. 
![Screenshot from 2023-09-26 19-14-06](https://github.com/eclipse/che/assets/29522373/fb2e773f-803b-440c-9af1-950de75991b9)

**Comment by tolusha** [comment]
@AObuchow 
You are right, user's permissions are limited.
Th error is expected.

**Comment by tolusha** [comment]
Here is the guide [1] how to add extra permissions for users.
[1] https://eclipse.dev/che/docs/stable/administration-guide/configuring-cluster-roles-for-users/

**Comment by AObuchow** [comment]
Thank you for the clarification @tolusha.
@moonbse the link @tolusha provided should help you resolve your issue.

If this helped, please close this issue - thank you !

**Comment by moonbse** [comment]
Thanks for the help @AObuchow @tolusha , my only confusion is what are USER_ROLES, for my case, I just used 'admin' to run all those commands with eclipse-che namespace. I have one admin and four users created on dex, do I need to configure for some user or this applies globally.

I have used following configuration and their results are attached:

`export USER_ROLES="admin" `

`kubectl apply -f - <<EOF
 kind: ClusterRole
 apiVersion: rbac.authorization.k8s.io/v1
 metadata:
   name: $USER_ROLES
   labels:
     app.kubernetes.io/part-of: che.eclipse.org
 rules:
   - verbs:
       - "*"
     apiGroups:
       - ""
     resources:
       - "*"
 EOF
Warning: resource clusterroles/admin is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
clusterrole.rbac.authorization.k8s.io/admin configured

`

`
kubectl apply -f - <<EOF
 kind: ClusterRoleBinding
 apiVersion: rbac.authorization.k8s.io/v1
 metadata:
   name: $USER_ROLES
   labels:
     app.kubernetes.io/part-of: che.eclipse.org
 subjects:
   - kind: ServiceAccount
     name: che-operator
     namespace: eclipse-che
 roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: $USER_ROLES
 EOF
clusterrolebinding.rbac.authorization.k8s.io/admin created
`

`
kubectl patch checluster eclipse-che \
>   --patch '{"spec": {"components": {"cheServer": {"clusterRoles": ["'$USER_ROLES'"]}}}}' \
>   --type=merge -n eclipse-che
checluster.org.eclipse.che/eclipse-che patched
`
`
kubectl patch checluster eclipse-che \
>   --patch '{"spec": {"devEnvironments": {"user": {"clusterRoles": ["'$USER_ROLES'"]}}}}' \
>   --type=merge -n eclipse-che
checluster.org.eclipse.che/eclipse-che patched`

Trying to run now, will update

**Comment by tolusha** [comment]
@moonbse 
My bed, that approach won't let user to get resources beyond his namespace.
Probably the easiest way is to create ClusterRoleBinding for the specific user to delegate admin rights.

```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: <USER>-admin
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: <USER_NAME>
    namespace: <USER_NAMESPACE>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
```

**Comment by moonbse** [comment]
@tolusha  what will be `USER_NAMESPACE`? for example for dex user I am going with `che@eclipse.org` user so configuration looks like

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: che@eclipse.org-admin
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: che@eclipse.org
    namespace: eclipse-che
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin

```

**Comment by tolusha** [comment]
> what will be USER_NAMESPACE

Visit https://<che_fqdn>/api/kubernetes/namespace to get your Che user namespace as name

**Comment by tolusha** [comment]
> che@eclipse.org

username:
![screenshot-192 168 39 29 nip io-2023 09 27-10_20_07](https://github.com/eclipse/che/assets/1640675/42b63f2c-c5c2-4cf3-8181-8f4cddedd469)

**Comment by moonbse** [comment]
Started with correct namespace and user , now I see some change in output but broadly it is still forbidden. Other issue that came up is file watcher limit which is VS-code specific issue. 

After running 

```
kubectl apply -f - <<EOF 
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: che@eclipse.org-admin
  subjects:
   - kind: User
     apiGroup: rbac.authorization.k8s.io
     name: admin
     namespace: admin-che
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
EOF
clusterrolebinding.rbac.authorization.k8s.io/che@eclipse.org-admin configured

```
Restarted with `chectl server:stop` & `chectl server:start` now getting a this


```
yarn run v1.22.17
$ ${PWD}/run/local-run.sh $@ -c
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
Error from server (Forbidden): checlusters.org.eclipse.che is forbidden: User "admin" cannot list resource "checlusters" in API group "org.eclipse.che" in the namespace "eclipse-che"
Detected gateway and oauth-proxy inside. Running in native auth mode.

$ nodemon --inspect lib/server/backend.js --publicFolder ../../../../packages/dashboard-frontend/lib/public
[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node --inspect lib/server/backend.js --publicFolder ../../../../packages/dashboard-frontend/lib/public`
[nodemon] Internal watch failed: ENOSPC: System limit for number of file watchers reached, watch '/projects/che-dashboard/packages/dashboard-backend'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
bash-4.4$ cat /proc/sys/fs/inotify/max_user_watches
8192
```

**Comment by moonbse** [comment]
Removed watcher error for adding `**/packages/common/*/**` pattern to watcher exclude, now I am able to run with server error with following output:

```
yarn start -c
yarn run v1.22.17
$ ${PWD}/run/local-run.sh $@ -c
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
grep: run/.che-dashboard-pod: No such file or directory
Error from server (Forbidden): checlusters.org.eclipse.che is forbidden: User "admin" cannot list resource "checlusters" in API group "org.eclipse.che" in the namespace "eclipse-che"
Detected gateway and oauth-proxy inside. Running in native auth mode.

$ nodemon --inspect lib/server/backend.js --publicFolder ../../../../packages/dashboard-frontend/lib/public
[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node --inspect lib/server/backend.js --publicFolder ../../../../packages/dashboard-frontend/lib/public`
Debugger listening on ws://127.0.0.1:9229/a26db01c-b136-47a5-b9c9-5dcd9559d766
For help, see: https://nodejs.org/en/docs/inspector
Running locally, setting up stubs
Dashboard proxies requests to Che Server API on null/api.
Static server's serving "/projects/che-dashboard/packages/dashboard-frontend/lib/public" on 0.0.0.0:8080/
Che Dashboard swagger is running on "/dashboard/api/swagger".
node:internal/url:552
  throw new ERR_INVALID_URL(input);
  ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at e.exports (/projects/che-dashboard/packages/dashboard-backend/lib/server/backend.js:2:450122)
    at /projects/che-dashboard/packages/dashboard-backend/lib/server/backend.js:2:444226
    at p.exec (/projects/che-dashboard/packages/dashboard-backend/lib/server/backend.js:8:92811)
    at g.u (/projects/che-dashboard/packages/dashboard-backend/lib/server/backend.js:8:91891)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  input: 'null',
  code: 'ERR_INVALID_URL'
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by olexii4** [comment]
@moonbse You need to run `yarn start:prepare` first. At least once. We have the particular command in the [devfile.yaml](https://github.com/eclipse-che/che-dashboard/blob/main/devfile.yaml):
```yaml
...
  - id: startcheinche
    exec:
      label: "[UD] start che-in-che"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: "yarn start:prepare && yarn start -c"
...
```
