### ISSUE TITLE
Devfile DevWorkspace Operator Config is overwritten by the dashboard

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22573]
### Describe the bug

The DevWorkspace operator configuration CR can be referenced from a devfile or Devworkspace. But that get overridden by the dashboard. 

### Che version

7.75@latest

### Steps to reproduce

**1. Create a DWOC object in your workspaces namespace**

```yaml
apiVersion: controller.devfile.io/v1alpha1
kind: DevWorkspaceOperatorConfig
metadata:
  name: custom-dwoc
  namespace: l0rd-che
config:
  workspace:
    persistUserHome:
      enabled: true
```

**2. Reference a the DWOC from a devfile**

```diff
schemaVersion: 2.2.0
metadata:
  name: my-app
+ attributes:
+   controller.devfile.io/devworkspace-config:
+     name: custom-dwoc
+     namespace: l0rd-che
components:
```

For example I did it in [this repository branch devfile](https://github.com/l0rd/inventory-quarkus/tree/custom-dwoc).

**3. Create the workspace from the dashboard and verify that the DWOC has been overidden**

```bash
$ kubectl get dw -o json | jq '.items[0].spec.template.attributes."controller.devfile.io/devworkspace-config"'
{
  "name": "devworkspace-config",
  "namespace": "dogfooding"
}
```

### Expected behavior

The DevWorkspace object should reference the DWOC specified in the devfile:

```bash
$ kubectl get dw -o json | jq '.items[0].spec.template.attributes."controller.devfile.io/devworkspace-config"'
{
  "name": "custom-dwoc",
  "namespace": "l0rd-che"
}
```

### Runtime

OpenShift

### Screenshots

![custom-dwoc-issue](https://github.com/eclipse/che/assets/606959/d4865b10-6e05-4086-aafa-f741067edc3f)

### Installation method

chectl/latest

### Environment

Amazon
