### ISSUE TITLE
Dashboard doesn't apply externalPluginRegistries attribute from CheCluster CR

### ISSUE THREAD

**Issue by svor** [eclipse/che#22589]
### Describe the bug

If update CheCluster CR to disable internal plugin registry url and set external plugin registry, dashboard won't take into account **externalPluginRegistries** attribute.

Example of CheCluster configuration:
```yaml
    pluginRegistry:
      disableInternalRegistry: true
      externalPluginRegistries:
        - url: 'https://eclipse-che.github.io/che-plugin-registry/main/v3/'
      openVSXURL: 'http://aaa.com'
```
with this configuration dashboard tries to read plugins from https://che-instance/plugins and ignores value of **externalPluginRegistries**.

### Che version

next (development version)

### Steps to reproduce

1. Deploy Che on OS cluster
2. Update CheCluster CR:
```yaml
    pluginRegistry:
      disableInternalRegistry: true
      externalPluginRegistries:
        - url: 'https://eclipse-che.github.io/che-plugin-registry/main/v3/'
      openVSXURL: 'https://open-vsx.org/'
```
3. Save changes and wait wen all pods will be ready
4. Try to open/refresh the dashboard page
5. Failed to fetch plugins from registry URL: , reason: 404 page not found

### Expected behavior

It should be possible to read plugins form the external plugin registry

### Runtime

OpenShift

### Screenshots

![screenshot-nimbusweb me-2023 10 09-17_36_35](https://github.com/eclipse/che/assets/1271546/5a4ccc35-bad9-4f8e-bf24-41d3bd5156bc)
![screenshot-nimbusweb me-2023 10 09-17_30_31](https://github.com/eclipse/che/assets/1271546/b5d131b7-9246-4d50-9dd1-8d201e4eef93)

### Installation method

chectl/next

### Environment

Linux

Downstream issue: https://issues.redhat.com/browse/CRW-4926
