### ISSUE TITLE
Dashboard clears `controller.devfile.io/debug-start` annotation when starting a workspace

### ISSUE THREAD

**Issue by amisevsk** [eclipse/che#22608]
### Describe the bug

It looks like the dashboard is clearing the `controller.devfile.io/debug-start` annotation from DevWorkspace CRs when starting a workspace. This makes it slightly more difficult to follow a workspace debugging flow where the annotation `controller.devfile.io/debug-start: 'true'` is added to a DevWorkspace to prevent removal of objects when a failure condition occurs.

### Che version

7.75@latest

### Steps to reproduce

1. Add `controller.devfile.io/debug-start: 'true'` to a DevWorkspace
2. Start DevWorkspace through dashboard
3. Reload DevWorkspace object and note annotation has been removed

Workaround: Start the workspace by setting `.spec.started = true` on the DevWorkspace object (i.e. start it without dashboard) 

### Expected behavior

I'd like the annotation to be left in place if added by the user, as this makes debugging slightly more confusing.

### Runtime

OpenShift

### Screenshots

N/A

### Installation method

OperatorHub

### Environment

Linux

### Additional context

If distinguishing between the annotation being set by dashboard vs the user is an issue, perhaps `.metadata.managedFields` may be of use. If I set the annotation via my browser, for example, I see
```yaml
    - apiVersion: workspace.devfile.io/v1alpha2
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:controller.devfile.io/debug-start': {}
      manager: Mozilla
      operation: Update
      time: '2023-10-13T20:14:58Z'
```
