### ISSUE TITLE
Eclipse Che with Keycloak on GKE

### ISSUE THREAD

**Issue by serhii-kuzniechykov** [eclipse/che#22633]
### Describe the bug

Hello
I`m trying to deploy Eclipse Che on GKE 
Initial setup was successful but  after login to the dashboard I got:
```
Failed to fetch available workspaces, reason: Failed to fetch the list of devWorkspaces. Unable to list devworkspaces: Unauthorized
Danger alert:Failed to fetch the user profile data. Unable to get user profile data: Unauthorized
```

After some investigation, I could see strange behavior of gke-oidc-service:
```
Envoy adapter received a new request from 10.1.1.17
Handling GET request for https://gke-oidc-envoy.anthos-identity-service/api/v1/namespaces
Stopping OIDC authentication for https://keycloak.xxxxxx.xx/realms/master. Unable to verify the OIDC ID token: Token's audiences "https://container.googleapis.com/v1/projects/xxxxxxxxx/locations/xxxxxxxx/clusters/xxxxx" do not match; allowed: "kubernetes"
```
I could not figure out where I have broken behavior in the line of Che -> Keycoal -> GCP Identity Service.
My  patch for  Che:
```
kind: CheCluster
apiVersion: org.eclipse.che/v2
metadata:
    name: eclipse-che
    namespace: eclipse-che
spec:
  networking:
    domain: "che.xxxxxx.xxx"
    auth:
      oAuthClientName: "kubernetes"
      oAuthSecret: "xxxxxxxxxxxxxxxxxxxxx"
      identityProviderURL: "https://keycloak.xxxxxx.xx/realms/master"
  components:
    cheServer:
      extraProperties:
        CHE_OIDC_USERNAME__CLAIM: email
        CHE_INFRA_KUBERNETES_MASTER__URL: "https://gke-oidc-envoy.anthos-identity-service"
        CHE_INFRA_KUBERNETES_PORT: "tcp://10.0.0.34:443"
        CHE_INFRA_KUBERNETES_PORT_443_TCP_ADDR: "10.0.0.34"
        CHE_INFRA_KUBERNETES_PORT_443_TCP: "tcp://10.0.0.34:443"
        CHE_INFRA_KUBERNETES_SERVICE_HOST: "10.0.0.34" 
```
Configuration for Identity Service:
```
 authentication:
  - name: oidc
    oidc:
      clientID: kubernetes
      clientSecret: xxxxxxxxxxxxxxxxxxxxxx
      groupsClaim: groups
      issuerURI: https://keycloak.xxxxxx.xx/realms/master
      kubectlRedirectURI: http://localhost:10000/callback
      scopes: openid profile email
      userClaim: email

### Che version

7.75@latest

### Steps to reproduce

Install Che with:

chectl server:deploy --installer operator --domain=che.xxxxxx.xx --platform=k8s --che-operator-cr-patch-yaml=./che-patch.yaml --telemetry=off --skip-cert-manager -n default 


### Expected behavior

Dashboard could authenticate to kube-api

### Runtime

other (please specify in additional context)

### Screenshots

_No response_

### Installation method

chectl/latest

### Environment

GCE

### Eclipse Che Logs

_No response_

### Additional context

_No response_
