### ISSUE TITLE
Dev Spaces 3.11 with Dashboard 7.76.0 on board failed to load external devfile registry

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#22643]
### Describe the bug

Dev Spaces 3.11 with Dashboard 7.76.0 on board failed to load external devfile registry, showing next error popup in Dashboard:
> Failed to fetch devfiles metadata from registry URL: https://eclipse-che.github.io/che-devfile-registry/7.74.0/, reason: Returned value is not array

### Che version

next (development version)

### Steps to reproduce

1. Install Eclipse Che with external devfile registry config in CheCluster:
```
devfileRegistry:
  disableInternalRegistry: true
  externalDevfileRegistries:
  - url: https://eclipse-che.github.io/che-devfile-registry/7.74.0/
```

2. Go to **Dashboard > Create Workspace** page.

### Expected behavior

Dashboard shows workspace samples from https://eclipse-che.github.io/che-devfile-registry/7.74.0/

### Runtime

OpenShift

### Screenshots

![Screenshot from 2023-10-31 15-51-01](https://github.com/eclipse/che/assets/1197777/02fccca1-a90b-4408-a363-1e8961397c00)

### Installation method

chectl/next

### Environment

Linux

### Additional context

Dev Spaces 3.11 with Dashboard 7.76.0 on board: https://devspaces.apps.sandbox-stage.gb17.p1.openshiftapps.com/dashboard/#/create-workspace
