### ISSUE TITLE
Don't ask to add a redirect for endpoints with non `public` exposure

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22655]
### Is your enhancement related to a problem? Please describe

Containers endpoints can have an exposure `public`, `internal` or `none` (see the [documentation](https://devfile.io/docs/2.2.1/devfile-schema#components-container-endpoints-exposure)).  

If a developer specifies that an endpoint in a devfile has exposure `internal` or `none`

```yaml
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      endpoints:
        - exposure: none
          name: debug
          protocol: tcp
          targetPort: 5005
``` 

we are still proposing to add a redirect:

<img width="939" alt="image" src="https://github.com/eclipse/che/assets/606959/90b4ba51-72d3-4620-b0c9-47babaea2e22">

### Describe the solution you'd like

We should not show a prompt for endpoints that have exposure other than `public`.
