### ISSUE TITLE
Eclipse Che: need to understand how to integrate private container registry for pulling the custom dashboard image

### ISSUE THREAD

**Issue by debkantap** [eclipse/che#22669]
### Summary

Eclipse Che: need to understand how to integrate private container registry for pulling the custom dashboard image.
Created a secret "regcred" , but unable to pass this as "imagePullSecrets" during eclipse che deployment.
Any clue would be helpful

**Comment by ibuziuk** [comment]
@tolusha could you please take a look? Can we reference private images from the CR:
```
spec:
  components:
    dashboard:
      deployment:
        containers:
          - image: <private image> ?
```
