### ISSUE TITLE
Logo customization from the CR should be also applied to the favicon and OpenShift UI

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22675]
### Describe the bug

Customizable OpenShift Dev Spaces logo on User Dashboard from the https://access.redhat.com/documentation/en-us/red_hat_openshift_dev_spaces/3.9/html/release_notes_and_known_issues/new-features does not apply to favicon and OpenShift UI

### Che version

7.77@latest

### Steps to reproduce

1. apply the cusom logo from CR

```
spec:
  components:
    dashboard:
      branding
        logo:
          base64data: <base64-encoded-data>
          mediatype: image/png
 ```

2. SUCCESS: logo is changed on UD after F5
3. ERROR: logo is not changed for favion and OpenShift UI

<img width="377" alt="Screenshot 2023-11-17 at 15 41 16" src="https://github.com/eclipse/che/assets/1461122/df3e86a7-326a-45ed-b365-21a2d84f28df">

### Expected behavior

the new logo should be applied to Open Shift UI / favicon, not Eclipse Che one

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon
