### ISSUE TITLE
if devfile from 'GitHub Enterprise Server' repo contains multiple `projects`, those would not be cloned after workspace startup

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22688]
### Describe the bug

if devfile from 'GitHub Enterprise Server' repo contains multiple `projects`, those would not be cloned after workspace startup. Note that this functionality works fine for repositories hosted on github.com e.g. https://github.com/ibuziuk/meta-workspace/blob/main/devfile.yaml

### Che version

7.77@latest

### Steps to reproduce

1. The reproducer is https://github.com/ibuziuk/meta-workspace/blob/main/devfile.yaml
2. Start workspace on workspaces.openshift.com base on the devfile above ^
3. SUCCESS: once workspace is started 4 extra projects defined in the devfile are cloned 
4. Create the same repository on GitHub Enterprise Server and repeat the steps above
5. ERROR: once workspace is started 4 extra projects defined in the devfile are NOT cloned

### Expected behavior

if devfile from 'GitHub Enterprise Server' repo contains multiple `projects`, those shoud be cloned after workspace startup.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

### Additional context

Note that this functionality works fine on github.com and GitLab

**Comment by ibuziuk** [comment]
not able to reproduce the issue against `3.7.0` version of GitHub Enterprise Server with Dev Spaces 3.9.1 running on OpenShift 4.14 ROSA cluster and OAuth configured

```
kind: Secret
apiVersion: v1
metadata:
  name: github-oauth-config
  namespace: openshift-operators
  labels:
    app.kubernetes.io/component: oauth-scm-configuration
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    che.eclipse.org/oauth-scm-server: github
    che.eclipse.org/scm-server-endpoint: 'http://ges-iv.crw-qe.com/'
stringData:
  id: <>
  secret: <>
```

All extra projects defined in the devfile are clonned
