### ISSUE TITLE
Projects are not cloned after restarting the workspace using `Eclipse Che: Restart Workspace from Local Devfile` command

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse/che#22722]
### Describe the bug

I created a workpsace with following devfile
```
schemaVersion: 2.2.0
metadata:
  name: java-spring-petclinic

# projects:
#   - name: nodejs-devfile-test
#     git:
#       remotes:
#         origin: https://github.com/vitaliy-guliy/nodejs-devfile-test.git

#   - name: lombok-project-sample
#     git:
#       remotes:
#         origin: https://github.com/vitaliy-guliy/lombok-project-sample.git

components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      memoryLimit: 1G
      mountSources: true
```
Then I opened the devfile in the editor, uncommented the projects section and launched `Eclipse Che: Restart Workspace from Local Devfile`.
After restarting the workspace, it appeared that projects were not  being cloned to the file system, despite they are properly described in flattened devworkspace yaml file.

### Che version

7.78@latest

### Steps to reproduce

- create a workspace with https://github.com/vitaliy-guliy/java-spring-petclinic/tree/test-che-22630
- open the devfile, add few projects, run `Eclipse Che: Restart Workspace from Local Devfile` command  

### Expected behavior

Projects must be cloned to the file system
