### ISSUE TITLE
As a User I want to have a possibility to specify an editor container image when starting workspace

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#22729]
### Is your enhancement related to a problem? Please describe

Today, to specify a custom editor to use in my workspace I need to:

1) build and publish a custom editor image (e.g. `quay.io/mloriedo/che-rider:2023:2`)
2) create and publish the yaml editor definition (e.g. [https://gist.githubusercontent.com/.../jetbrains_rider.yaml](https://gist.githubusercontent.com/l0rd/6fd05947bfebf8732a7a43b513b75eb0/raw/0c09ede4c516b16364e493d790aa7b0f4b946cb1/jetbrains_rider.yaml))

While creating and publishing an image is inevitable (step 1), the yaml definition (step 2) looks mostly redundant and unnecessary (most of the times the default editor definition can be reused by updating only the `<editor>-injector` container image only). Moreover there is no clear indication about where a user should publish the yaml (for the image the choice is obvious: a container registry).

#### Step1

Add a new URL parameter named `editor-image` with the following behavior:

- The parameter is passed to the DevWorkspace generator that uses it to patch the `<editor>-injector` image.
- This should work together with the `editor` URL parameter too. For example: 
	- `editor-image=quay.io/mloriedo/che-code:copilot-builtin` ==> replace the default editor image 
	- `editor=che-incubator/che-idea/next&editor-image=quay.io/mloriedo/che-rider:2023.2` ==> replace che-incubator/che-idea/next

#### Step2

Remove the need for an `editor.yaml` or even for a DevWorkspaceTemplate

<details>

<summary>Looking at editors definitions they all have the same format:</summary>

| PARAMETER  | che-code | che-idea | che-pycharm |
| --- | --- | --- | --- |
| `<editor-name>` | che-code | che-idea | che-pycharm |
| `<editor-startup-command>` | /checode/entrypoint-volume.sh | /projector/entrypoint-volume.sh | /projector/entrypoint-volume.sh |
| `<editor-env-variables>` | none | `PROJECTOR_ASSEMBLY_DIR` and `PROJECTOR_CONFIG_DIR` |  |
| `<editor-specific-volumes>` | none | `/home/user/.jetbrains` and `/home/user/.java` |  |
| `<editor-memory-limit>` | 1024Mi | 6144Mi |  |
| `<editor-memory-request>` | 256Mi | 2048Mi |  |
| `<editor-cpu-limit>` | 500m | 2000m |  |
| `<editor-cpu-request>` | 30m | 1500m |  |
| `<editor-endpoint-port>` | 3100 | 8887 |  |
| `<editor-endpoint-path>` | none | `/?backgroundColor=434343&wss` |  |
| `<editor-image>` | `quay.io/che-incubator/che-code:insiders` | `quay.io/che-incubator/che-idea:next` | `eclipse/che-theia:next` |

Beyond <editor-image>, the other necessary parameters are <editor-memory-limit>, <editor-cpu-limit>, <editor-endpoint-port> and <editor-endpoint-path> that can all be specified as image metadata.

In fact:
  `<editor-name>`: can be inferred from the image name
  `<editor-startup-command>`: can be conventionized as `/editor/entrypoint-volume.sh` by default
  `<editor-env-variables>`: can be set in the `entrypoint-volume.sh`
  `<editor-specific-volumes>`: don't look necessary and anyway are related to the persistence of $HOME
  `<editor-memory-request>`: can be set to 1/4 of the limit by default
  `<editor-cpu-request>`: can be set to 1/2 of the limit by default

```yaml
schemaVersion: 2.2.0
metadata:
  name: <editor-name>
commands:
  - id: editor-copy-command
    apply:
      component: editor-container
  - id: editor-startup-command
    exec:
      component: main-cde-container
      commandLine: nohup <editor-startup-command> > /tmp/editor-entrypoint-logs.txt 2>&1 &
events:
  preStart:
    - editor-copy-command
  postStart:
    - editor-startup-command
components:
  - name: main-cde-container
    container:
      image: not/used
      env: <editor-env-variables>
      volumeMounts:
        - name: editor-volume
          path: /editor
        <editor-volumes>
      memoryLimit: <editor-memory-limit>
      memoryRequest:  <editor-memory-request>
      cpuLimit:  <editor-cpu-limit>
      cpuRequest:  <editor-cpu-request>
      endpoints:
        - name: editor
          attributes:
            type: main
            cookiesAuthEnabled: true
            discoverable: false
            urlRewriteSupported: true
            secure: false
          targetPort: <editor-endpoint-port>
          exposure: public
          path: <editor-endpoint-path>
          protocol: https
        - name:redirect-1
          attributes:
            discoverable: false
            urlRewriteSupported: false
          targetPort: 13131
          exposure: public
          protocol: https
        - name: redirect-2
          attributes:
            discoverable: false
            urlRewriteSupported: false
          targetPort: 13132
          exposure: public
          protocol: https
        - name: redirect-3
          attributes:
            discoverable: false
            urlRewriteSupported: false
          targetPort: 13133
          exposure: public
          protocol: https
    attributes:
      controller.devfile.io/container-contribution: true
  - name: editor-volume
    volume: {}
  <editor-volumes>
  - name: editor-container
    container:
      image: <editor-image>
      volumeMounts:
        - name: editor-volume
          path: /editor-volume
      memoryLimit: 128Mi
      memoryRequest: 32Mi
      cpuLimit: 500m
      cpuRequest: 30m
```
<details>
