### ISSUE TITLE
Allow to configure securityContext for che-gateway container

### ISSUE THREAD

**Issue by karatkep** [eclipse/che#22747]
### Is your enhancement related to a problem? Please describe

Restricted Pod Security Standards (see more https://kubernetes.io/docs/concepts/security/pod-security-standards/) can not be applied to the user devworspace pod due to lack of che-gateway container configuration.

Example of error:
```
Error creating DevWorkspace deployment: 
Detected unrecoverable deployment condition: 
FailedCreate pods "workspace007423daa3654c20-7d55dc8c5-lvfrx" is forbidden: 
violates PodSecurity "restricted:latest": 
allowPrivilegeEscalation != false (container "che-gateway" must set securityContext.allowPrivilegeEscalation=false),
unrestricted capabilities (container "che-gateway" must set securityContext.capabilities.drop=["ALL"])
```

Important: **CheCluster** has a proper configuration which applied to the all containers except che-gateway:
```yaml
spec:
  devEnvironments:
    security:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
```
I see we have **gatewayContainer** under **devEnvironments** to configure che-gateway. But this configuration has nothing related to the securityContext

### Describe the solution you'd like

che-gateway container should respect securityContext configuration as well
```yaml
spec:
  devEnvironments:
    security:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
```
