### ISSUE TITLE
Allow pod-overrides of `volumes` and container-overrides of `volumeMounts` in Devfiles

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#22751]
### Is your enhancement related to a problem? Please describe

It is not currently possible to add CSI volume mounts to a users workspace.

CSI is not permitted in the SCC used by Dev Spaces.

There is no mechanism in the devfile to specify volumes other than from the cluster storage provisioner 

### Describe the solution you'd like

Create a mechanism to add CSI volume mounts to a workspace.

The ideal solution is probably through the volumes fields in a devfile, but that might take longer to implement.

A near-term solution is to allow adding volumes to the workspace pod with `pod-overrides` and volume-mounts to a container with `container-overrides`

```
schemaVersion: 2.2.0
attributes:
  controller.devfile.io/storage-type: per-workspace
metadata:
  name: che-demo
  attributes:
    pod-overrides: {"spec": {"volumes": [{"name": "mysecret-volume", "csi": {"driver": "some-csi-driver", "readOnly" : true, "volumeAttributes": {"attrib1": "some-value"}}}]}}
components:
- name: workspace
  attributes:
    container-overrides: {"volumeMounts": [{"name": "mysecret", "mountPath": "/var/my/path", "readOnly": true}]}
  container: 
    image: quay.io/some/image:latest
    etc...
```

**Comment by l0rd** [comment]
There are currently a couple of options to mount a CSI volume:
1) Che administrator can specify a specific storage class using `.spec.devEnvironments.storage.perWorkspaceStrategyPvcConfig.storageClass` in the [CheCluster CR](https://doc.crds.dev/github.com/eclipse-che/che-operator/org.eclipse.che/CheCluster/v2@7.78.0#spec-devEnvironments-storage-perWorkspaceStrategyPvcConfig-storageClass)
2) The developer can pre-create the CSI volume and a corresponding PVC with the label `controller.devfile.io/mount-to-devworkspace: "true"` and this will be [automounted in workspaces](https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.adoc#automatically-mounting-volumes-configmaps-and-secrets).  

@cgruver can you confirm that those 2 options don't work for your use case? And that what you are requesting is to add the capability in the Devfile API? For example:

```diff
schemaVersion: 2.2.0
metadata:
  name: mydevfile
components:
  - name: mydevfile
    container:
      (...)
      volumeMounts:
        - name: cache
          path: /.cache
  - name: cache
    volume:
      size: 2Gi
+      csi:
+        driver: some-csi-driver
```

 My worry is this will make the Devfile less portable (i.e. it works on my cluster but doesn't on yours).

**Comment by cgruver** [comment]
@l0rd   The use case in question here is not for PVCs, but for things like AWS Secrets Manager or SPIFFE.

The CheCluster CR config will not work, because these CSI volumes will often be workspace specific, and it's possible that there will be a need for volumes from different drivers.

The most portable option is probably to allow them to be injected via `pod-overrides` and `container-overrides`

**Comment by l0rd** [comment]
@cgruver ok, I am still not sure if the developer can or not pre-create the volume. And adding this information in the devfile still looks like a hack. However I think we should investigate why the `pod/container-overrides` you are trying to apply don't work and figure out how to fix it (if that's a problem with the default SCC, then it's configurable and doesn't require any change in the code).

For a better solution to this use case: have you thought about leveraging the [cloud-credential-operator](https://github.com/openshift/cloud-credential-operator)? We introduced the support for [SA token volume projection](https://github.com/eclipse/che/issues/22012) to add GCP credentials in workspaces (see [GCP workload identity federation](https://cloud.google.com/iam/docs/workload-identity-federation)) when the cloud-credential-operator is installed and configured in the cluster. The cloud-credential-operator supports AWS out of the box (and I assume that SPIFFE could be supported too).

**Comment by dkwon17** [comment]
Pod/container overrides is now possible thanks to https://github.com/devfile/devworkspace-operator/pull/1223

I'm able to add a CSI volume to a devworkspace pod/container by following these steps to create a `SharedSecret`: https://docs.openshift.com/container-platform/4.14/storage/container_storage_interface/ephemeral-storage-shared-resource-csi-driver-operator.html

Example overrides:
```
schemaVersion: 2.2.0
attributes:
  controller.devfile.io/storage-type: per-workspace
metadata:
  name: che-demo
  attributes:
    pod-overrides:
      spec:
        volumes:
          - csi:
              driver: csi.sharedresource.openshift.io
              readOnly: true
              volumeAttributes:
                sharedSecret: my-share
            name: my-csi-volume
components:
- name: workspace
  attributes:
    container-overrides:
      volumeMounts:
        - mountPath: /etc/my-csi-volume
           name: my-csi-volume
           readOnly: true
  container: 
    ...
```

I believe this covers your use case @cgruver ?

**Comment by dkwon17** [comment]
I have a permissions issue when trying with Che however (my cluster died):

<details><summary>Status</summary>

```
status:
  conditions:
    - lastTransitionTime: '2024-01-31T01:54:49Z'
      message: 'Error creating DevWorkspace deployment: Detected unrecoverable deployment condition: FailedCreate pods "workspace07eac1a5666447ee-6d865d86cb-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .initContainers[0].capabilities.add: Invalid value: "SETGID": capability may not be added, provider restricted-v2: .initContainers[0].capabilities.add: Invalid value: "SETUID": capability may not be added, provider restricted-v2: .initContainers[0].allowPrivilegeEscalation: Invalid value: true: Allowing privilege escalation for containers is not allowed, provider restricted-v2: .containers[0].capabilities.add: Invalid value: "SETGID": capability may not be added, provider restricted-v2: .containers[0].capabilities.add: Invalid value: "SETUID": capability may not be added, provider restricted-v2: .containers[0].allowPrivilegeEscalation: Invalid value: true: Allowing privilege escalation for containers is not allowed, provider "restricted": Forbidden: not usable by user or serviceaccount, spec.volumes[0]: Invalid value: "csi": csi volumes are not allowed to be used, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]'
```

</details>
