### ISSUE TITLE
Allow customizing oauth2 proxy configuration

### ISSUE THREAD

**Issue by hrishin** [eclipse/che#22777]
### Is your enhancement related to a problem? Please describe

With the given OIDC setup, users group scope is returning quite a good amount of data in our case. Which resulting into `Multiple cookies are required for this session as it exceeds the 4kb cookie limit. Please use server side session storage (eg. Redis) instead` with 502 bad gateway response. 

To setup the redis or configure the session store parameter CheServer CRD has no option nor che operator can account for predefined the CM for `che-gateway-config-oauth-proxy`

### Describe the solution you'd like

Ideally allow user to supply the custom configmap or allow passing session store details

**Comment by tolusha** [comment]
Hello @hrishin 
You can configure oauth-proxy with environment variables [1]. To achieve this, add the following configuration into CheCluster CR:
```
spec:
  networking:
    auth:
     gateway:
        deployment:
          containers:
          - env:
            - name: OAUTH2_PROXY_<...>
              value: <...>
            - name: OAUTH2_PROXY_<...>
              value: <...>
...              
            name: oauth-proxy
```

[1] https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#environment-variables
