### ISSUE TITLE
As an admin, I want to enable fuse overlay storage driver for all workspaces

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#22809]
### Is your enhancement related to a problem? Please describe

As an admin, I want to enable fuse overlay storage driver for Podman in all workspaces by setting a field in the CheCluster CR.

### Describe the solution you'd like

For example:
```
spec:
  devEnvironments:
    disableFuseOverlay: true/false
```

For using the fuse overlay storage driver for Podman in workspaces, we need:
1. The OpenShift cluster's CRI-O engine should allow pods to access the `/dev/fuse` device.
    - For OpenShift < 4.15, a MachineConfig needs to be created to edit a CRI-O config file to enable this. (See [blog post](https://upstreamwithoutapaddle.com/blog%20post/2023/08/10/Podman-In-Dev-Spaces-With-Fuse-Overlay.html#configure-your-openshift-cluster-to-allow-pods-to-mount-devfuse))
2. Workspaces must have the `io.kubernetes.crio-o.Devices: "/dev/fuse"` annotation in order to access `/dev/fuse`
    - For OpenShift < 4.15, an additional annotation is needed. (See [blog post](https://upstreamwithoutapaddle.com/blog%20post/2023/08/10/Podman-In-Dev-Spaces-With-Fuse-Overlay.html#configure-your-openshift-cluster-to-allow-pods-to-mount-devfuse))

3. For images based on UDI, Podman storage driver must be set to `overlay`
    - This is because the UDI image has the `vfs` storage driver set in the dockerfile: 
https://github.com/devfile/developer-images/blob/7e57123d72a7dcf183ce973a46fb6087f4dbeba2/universal/ubi8/Dockerfile#L233-L234
    - The `/home/user/.config/containers/storage.conf` file must be changed to:
```diff
[storage]
- driver = "vfs"
+ driver = "overlay"

+ [storage.options.overlay]
+ mount_program="/usr/bin/fuse-overlayfs"
```

**Comment by dkwon17** [comment]
To enable fuse for a workspace, there are three requirements:
1. For OpenShift versions older than 4.15, the administrator has enabled /dev/fuse access on the cluster by following [Configuring fuse-overlayfs](https://eclipse.dev/che/docs/stable/administration-guide/configuring-fuse/)
2. The storage.conf file in the workspace container has been configured to use fuse-overlayfs. See [Enabling fuse-overlayfs with a Configmap](https://eclipse.dev/che/docs/stable/end-user-guide/enabling-overlay-with-a-configmap/).
3. The workspace has the necessary annotations for using the /dev/fuse device. See [Accessing /dev/fuse from a workspace](https://eclipse.dev/che/docs/stable/end-user-guide/accessing-fuse/).

For this feature I believe we can assume that the admin has already completed the first requirement.

The idea I have for how this feature can be implemented is:

If `spec.devEnvironments.disableFuseOverlay = false`, have the che-operator create this configmap in the Eclipse Che namespace to mount the new `storage.conf` file to all user workspaces:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: overlayfs-storageconf
  namespace: eclipse-che
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-config
  annotations:
    controller.devfile.io/mount-as: file
    controller.devfile.io/mount-path: /home/user/.config/containers
data:
  storage.conf: |
    [storage]
    driver = "overlay"

    [storage.options.overlay]
    mount_program="/usr/bin/fuse-overlayfs"

```
This configmap satisfies the second requirement.

There is no easy way at the moment to satisfy the third requirement, because there is no easy way for an admin specify necessary `spec.template.attributes` for all workspaces in the cluster.

A possible solution would be to introduce a field in the [DWOC](https://github.com/devfile/devworkspace-operator/blob/067847d900c18a3fe0d47de920a9ce77af29e722/apis/controller/v1alpha1/devworkspaceoperatorconfig_types.go) for adding annotations (or maybe even pod or container overrides) for all workspaces, and have che-operator edit the DWOC (similar to what's happening in [dev_workspace_config.go](https://github.com/eclipse-che/che-operator/blob/e2a42e487721d06c13d4ad0e4ef38fca47591565/pkg/deploy/dev-workspace-config/dev_workspace_config.go).

Any thoughts @AObuchow @tolusha @ibuziuk ?
