### ISSUE TITLE
devfile commandLine support for heredoc

### ISSUE THREAD

**Issue by jorgeadrian93** [eclipse/che#22803]
### Summary

Hello, I'm trying to create a `devfile` command that supports `heredoc` notation for an OpenShift deployment.

```
commands: 
  - id: deployment
    exec:
      label: "Create OpenShift Deployment"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: "oc apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  namespace: ${WORKSPACE_NAMESPACE}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deploymentconfig: busybox
    spec:
      containers:
      - image: busybox
        name: busybox
        command: [ "/bin/sh", "-c", "while true ; do date; sleep 1; done;" ]
EOF "
```

The reason I'm trying to do this is to _pass environment variables to the deployment yaml._ 
Is that possible or do you know any other method?

Thanks! 

### Relevant information

The `oc apply -f - <<EOF [yaml info] EOF` directly in the terminal works fine. 

I've tried the options:

```
commandLine: "oc apply -f - <<EOF
apiVersion: apps/v1
[...]
EOF " 
```

```
commandLine: "cat <<EOF | oc apply -f -
apiVersion: apps/v1
[...]
EOF " 
```

But I me getting the following error: 
```
sh: warning: here-document at line 0 delimited by end-of-file (wanted `EOF')
```

**Comment by AObuchow** [comment]
> The reason I'm trying to do this is to _pass environment variables to the deployment yaml._ 
Is that possible or do you know any other method?

I'm not entirely sure I follow your line of thought, but devfiles have native support for setting [environment variables](https://devfile.io/docs/2.2.2/defining-environment-variables).

In your main devfile component, you might be able to add an `env` that contains your deployment:

```YAML
      env:
        - name: to-apply
          value:  |
			<<EOF 
			apiVersion: apps/v1
			kind: Deployment
			metadata:
			  name: simple-deployment
			  namespace: ${WORKSPACE_NAMESPACE}
			spec:
			  replicas: 1
			  strategy:
			    type: Recreate
			  template:
			    metadata:
			      labels:
			        deploymentconfig: busybox
			    spec:
			      containers:
			      - image: busybox
			        name: busybox
			        command: [ "/bin/sh", "-c", "while true ; do date; sleep 1; done;" ]
					EOF
```

Then in your component's command:

commands: 
```
  - id: deployment
    exec:
      label: "Create OpenShift Deployment"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: "oc apply -f - ${to-apply}"
```


Though I believe this is a misguided approach. I think what you are looking for is the [Kubernetes (devfile) component type](https://devfile.io/docs/2.2.2/defining-kubernetes-resources). This allows you to define a devfile component that is based on Kubernetes resource. Note however, that URI's for Kubernetes and OpenShift components are not supported in Che, so you have to inline your component (with the `|` operator). See the Devfile schema for [Kubernetes components](https://devfile.io/docs/2.2.2/devfile-schema#components-kubernetes-endpoints) 

For example:

```YAML
schemaVersion: 2.2.0
metadata:
  name: mydevfile
projects:
  - name: my-go-project
    clonePath: go/src/github.com/acme/my-go-project
    git:
      remotes:
        origin: 'https://github.com/acme/my-go-project.git'
components:
  - name: my-deployment
    kubernetes:
      inlined: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: simple-deployment
        namespace: ${WORKSPACE_NAMESPACE}
      spec:
        replicas: 1
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              deploymentconfig: busybox
          spec:
            containers:
            - image: busybox
              name: busybox
              command: [ "/bin/sh", "-c", "while true ; do date; sleep 1; done;" ]
```

**Comment by jorgeadrian93** [comment]
Hi @AObuchow Thank you for your response and I apologize if I didn't explain my use case well.

Building on the Kubernetes component you mention, the deployment will be initialized at startup and what I am looking for is a Task/Command in which I can decide when to execute it. 

Looking at a simpler use case, I want to create a ServiceAccount from the tools (universal-developer-image) component, using an inline command: 

I can do it directly in the terminal as follows:
```
$ oc apply -f - <<EOF
> apiVersion: v1
> kind: ServiceAccount
> metadata:
>   name: sa-example
>   namespace: ${WORKSPACE_NAMESPACE}
> EOF
serviceaccount/sa-example created
```
I would like to do the same but through a task in the `devfile`

```
commands:
  - id: serviceaccount
    exec:
      label: "Create ServiceAccount"
      component: tools
      commandLine: "oc apply -f - <<EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-example
  namespace: ${WORKSPACE_NAMESPACE}
EOF"
```

**Comment by mkuznyetsov** [comment]
@jorgeadrian93 how about this one, for both of your commands:

```
...
commands: 
  - id: serviceaccount
    exec:
      label: "Create ServiceAccount"
      component: tools
      commandLine: |- 
        oc apply -f - <<EOF
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: sa-example
          namespace: ${WORKSPACE_NAMESPACE}
        EOF
  - id: deployment
    exec:
      label: "Create OpenShift Deployment"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: |-
        oc apply -f - <<EOF
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: simple-deployment
          namespace: ${WORKSPACE_NAMESPACE}
        spec:
          replicas: 1
          strategy:
            type: Recreate
          template:
            metadata:
              labels:
                deploymentconfig: busybox
            spec:
              containers:
              - image: busybox
                name: busybox
                command: [ "/bin/sh", "-c", "while true ; do date; sleep 1; done;" ]
        EOF
```

**Comment by jorgeadrian93** [comment]
This is exactly what I was looking for @mkuznyetsov Thanks a TON! 🚀

**Comment by jorgeadrian93** [comment]
Hi @mkuznyetsov, sorry for disturbing you again, but back to this topic I did a little test to pass environment variables to my command, I even followed some examples as described [here](https://github.com/devfile/api/blob/main/samples/devfiles/spring-boot-http-booster-devfile.yaml#L75) but no luck. 

The environment variable exists
```
$ printenv | grep WORKSPACE_NAMESPACE
WORKSPACE_NAMESPACE=jorgemb-devspaces 
```

Sample from devfile
```
- id: buildimage
    exec:
      label: "Build Image"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: "podman build -t image-registry.openshift-image-registry.svc:5000/$WORKSPACE_NAMESPACE/app ."
      group:
        kind: build
```

Result
```
*  Executing task: devfile: Build Image 

Error: tag image-registry.openshift-image-registry.svc:5000//app: invalid reference format
```

**Comment by AObuchow** [comment]
@jorgeadrian93 something that comes to mind: IIRC devfile commands (and events) are run with `/bin/sh` rather than bash. I would try to run `/bin/sh` in a VSCode terminal in your workspace, then do `printenv | grep WORKSPACE_NAMESPACE` or `echo $WORKSPACE_NAMESPACE`. If the environment variable is not present in `sh` then you might need to workaround this somehow.

If sh is missing the environment variable, maybe you can get access to it by sourcing the `.bashrc` to load environment variables first, then run your command? Eg.

```YAML
- id: buildimage
    exec:
      label: "Build Image"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: "source ~/.bashrc && podman build -t image-registry.openshift-image-registry.svc:5000/$WORKSPACE_NAMESPACE/app ."
      group:
        kind: build
```

**Comment by AObuchow** [comment]
@jorgeadrian93 Also are you defining your environment variable as a devfile [env](https://devfile.io/docs/2.2.2/defining-environment-variables)? All devfile level environment variables will be replaced with their actual value before starting up your workspace.

**Comment by jorgeadrian93** [comment]
@AObuchow I am not defining the environment variables in the devfile, because the variable `WORKSPACE_NAMESPACE` I am trying to use for my use case comes by `default` once I start my workspace. Should I define it anyway?

```
env:
        - name: WORKSPACE_NAMESPACE
          value: $(WORKSPACE_NAMESPACE)
```

**Comment by jorgeadrian93** [comment]
Interesting ... 
idk where the `WORKSPACE_NAMESPACE` environment variable comes from, the `printenv` command shows it

```
$ printenv | grep WORKSPACE_NAMESPACE
DEVWORKSPACE_NAMESPACE=jorgemb-devspaces
WORKSPACE_NAMESPACE=jorgemb-devspaces
```

but checking the workspace pod, only `DEVWORKSPACE_NAMESPACE` exists. I made the replacement and now it gets it properly 😀 

The code snippet was finally

```
  - id: buildimage
    exec:
      label: "Build Image"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: "podman build -t image-registry.openshift-image-registry.svc:5000/$DEVWORKSPACE_NAMESPACE/app ."
      group:
        kind: build
```

Anyway, I'll do some more research around `sh` vs `bash`, thank you @AObuchow 🚀
