### ISSUE TITLE
Only some settings in .vscode/settings.json are applied in Dev Spaces 3.11

### ISSUE THREAD

**Issue by APINYK** [eclipse/che#22833]
### Summary

Hi! 

Thanks for all your great work! 

I am struggling to understand the behavior of the .vscode/settings.json at the root of my project. 

As a user, when starting a workspace from a repository, I would like to have all settings in .vscode/settings.json to be applied as we know it from the desktop Visual Studio Code and the vscode.dev project. However in Dev Spaces only some settings are applied.
Other settings give the following message: 
![image](https://github.com/eclipse/che/assets/127222595/04abf6b4-0ed5-4382-bfd8-cf18a95f5486)
And nothing happens (settings are "greyed out"): 
![image](https://github.com/eclipse/che/assets/127222595/0116e02d-f5e4-421b-8519-3fc42faa98ed)

My (strange) workaround for now:
If a create the environment variable, VSCODE_DEFAULT_WORKSPACE, with any random (?) value in my devfile.yaml

```
schemaVersion: 2.1.0
metadata:
  name: openshift_test
components:
  - name: python
    container:
      image: registry.redhat.io/devspaces/udi-rhel8
      env:
        - name: VSCODE_DEFAULT_WORKSPACE
          value: random
```
Result:
![image](https://github.com/eclipse/che/assets/127222595/d0b87047-6219-4f1d-a61d-5973bfbf8bb6)

... it all works like a charm! 

Feel free to test it in this repository; 
https://github.com/Nykredit/openshift-test/tree/migrating_to_dev_spaces_3_11

Can you help me understand this? I would really like not to have the redundant "random" VSCODE_DEFAULT_WORKSPACE environment variable in my devfile.yaml.

Hope you can help!
