### ISSUE TITLE
Eclipse Che with Azure Kubernetes Service OIDC

### ISSUE THREAD

**Issue by maheshrajrp** [eclipse/che#22845]
### Summary

Hi All,

Currently I am trying to upgrade to latest eclipse-che, but blocked as Azure Kubernetes Service doesn't support External OIDC [1] and Azure Entra doesn't fit our use-case.
What are the other reliable approaches that can be used for production cases ?
One approach I was able to gather is to use vCluster (Thanks @monaka), do we have any production setup steps related to that other than [2] ?

[1] https://github.com/Azure/AKS/issues/2861
[2] https://vrelevant.net/vcluster-with-oidc/

Thanks

**Comment by monaka** [comment]
These configs are a digest.

As I'm working to release my Che distribution for commercial, my whole configurations are huge and too complex to share here. 
But I think these configs will give some hints.
 
```
# values.yaml for vcluster.
api:
  image: registry.k8s.io/kube-apiserver:v1.27.1
  extraArgs:
    - --oidc-issuer-url=https://keycloak.c.pizzafactory.jp/auth/realms/che
    - --oidc-client-id=che-private
    - --oidc-username-claim=sub
    - --oidc-username-prefix=-
    - --oidc-groups-claim=groups

sync:
  ingresses:
    enabled: true
```

```
kind: CheCluster
apiVersion: org.eclipse.che/v2
spec:
  networking:
    auth:
      oAuthClientName: "che-private"
      oAuthSecret: "{{hidden}}"
      identityProviderURL: "https://keycloak.c.pizzafactory.jp/auth/realms/che"
      externalIdentityProvider: true
      openShiftoAuth: false
      gateway:
        oAuthProxy:
          cookieExpireSeconds: 30 # see also eclipse/che#22765
```

**Comment by maheshrajrp** [comment]
Hi @monaka ,
Thanks for responding. I think  `externalIdentityProvider: true`, is relevant anymore I'm getting `error: checlusters.org.eclipse.che "eclipse-che" is invalid` error.

**Comment by maheshrajrp** [comment]
> These configs are a digest.
> 
> As I'm working to release my Che distribution for commercial, my whole configurations are huge and too complex to share here. But I think these configs will give some hints.
> 
> ```
> # values.yaml for vcluster-k8s.
> api:
>   image: registry.k8s.io/kube-apiserver:v1.27.1
>   extraArgs:
>     - --oidc-issuer-url=https://keycloak.c.pizzafactory.jp/auth/realms/che
>     - --oidc-client-id=che-private
>     - --oidc-username-claim=sub
>     - --oidc-username-prefix=-
>     - --oidc-groups-claim=groups
> 
> sync:
>   ingresses:
>     enabled: true
> ```
> 
> ```
> kind: CheCluster
> apiVersion: org.eclipse.che/v2
> spec:
>   components:
>     cheServer:
>       extraProperties:
>         CHE_OIDC_USERNAME__CLAIM: sub
> 
>   networking:
>     auth:
>       oAuthClientName: "che-private"
>       oAuthSecret: "{{hidden}}"
>       identityProviderURL: "https://keycloak.c.pizzafactory.jp/auth/realms/che"
>       externalIdentityProvider: true
>       openShiftoAuth: false
>       gateway:
>         oAuthProxy:
>           cookieExpireSeconds: 30 # see also eclipse/che#22765
> ```
> 
> Note that "Che on vcluster-oidc" approach can be used in almost all k8s clusters. Not only in AKS.

Also, I have one more doubt, you seem to be using same client-id for both CheCluster and vCluster, I am guessing you are using keycloak. So, in that sense, one should be private client (i.e. with client_id and client_secret for CheCluster) and vCluster is public client (i.e. with just client_id, username and password). I believe I am running into this issue, I am getting 401in Eclipse Che when I try to start workspace, not sure why. It would be great if you have some idea on that.

**Comment by maheshrajrp** [comment]
Here's my values.yaml of vCluster

```
api:
  extraArgs:
    - --oidc-issuer-url=https://private.keycloak.com/realm/sample
    - --oidc-client-id=client-kubernetes
    - --oidc-username-claim=email
    - --oidc-groups-claim=groups
init:
  manifestsTemplate: |-
    ---
    kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: oidc-cluster-admin
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cluster-admin
    subjects:
    - kind: Group
      name: {{ .Values.ClusterAdminGroup }}
service:
  type: LoadBalancer
  loadBalancerAnnotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"

```

CheCluster Patch YAML

```
kind: CheCluster
apiVersion: org.eclipse.che/v2
spec:
  networking:
    auth:
      oAuthClientName: some-other-kubernetes
      oAuthSecret: dsadsad
      identityProviderURL: "https://private.keycloak.com/realm/sample"
  components:
    cheServer:
      extraProperties:
        CHE_OIDC_USERNAME__CLAIM: email

```
