### ISSUE TITLE
Change the StorageClass of the CheCluster resource

### ISSUE THREAD

**Issue by jorgeadrian93** [eclipse/che#22897]
### Summary

We recently added new storage to the OpenShift cluster that supports the Red Hat DevSpaces Operator. In the instance specs, I initially attached storage as the following: 

```
storage:
      perUserStrategyPvcConfig:
        claimSize: 5Gi
        storageClass: managed-storage
      perWorkspaceStrategyPvcConfig:
        claimSize: 10Gi
        storageClass: managed-storage
      pvcStrategy: per-workspace
```

I'd like to attach the new StorageClass to my DevSpaces CR. 
Is it possible to attach a secondary StorageClass or should I overwrite the current one with the new one? 

Applying the overwrite action ... Will I lose the information currently stored?
