### ISSUE TITLE
Debugging C# projects

### ISSUE THREAD

**Issue by evilguest** [eclipse/che#22904]
### Summary

I have successfully deployed Che sample in minikube.
I managed to create a new `dotnet60` workspace with a sample project and open it via VS Code.
However, there are no language features beyond syntax highlighting. I.e. there is no way to "go to definition", neither there any Run/Debug capabilities.

What do I need to install in order to enable the real language support and/or debug experience?

**Comment by svor** [comment]
hello @evilguest, 
to enable language support install C# extension:
![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2024 03 29-11_34_31](https://github.com/eclipse/che/assets/1271546/6ae79b47-eec7-4a09-b6b6-ea60cd785d67)

Currently C# debugger doesn't work on ubi8 based image. If you want to enable debugger try to use custom ubi9 based image in your devfile. You can build the image from Dockerfile:
```dockerfile
FROM registry.access.redhat.com/ubi9/ubi:9.1.0-1782

ENV HOME /home/user

USER 0

RUN dnf install -y diffutils git iproute jq less lsof man nano procps \
    perl-Digest-SHA net-tools openssh-clients rsync socat sudo time vim wget zip && \
    dnf update -y && \
    dnf clean all

RUN \
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash && \
export NVM_DIR="$HOME/.nvm" && \
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
nvm install 18.18.0
ENV VSCODE_NODEJS_RUNTIME_DIR="$HOME/.nvm/versions/node/v18.18.0/bin/"

RUN \
    # add user and configure it
    useradd -u 10001 -G wheel,root -d /home/user --shell /bin/bash -m user && \
    # Setup $PS1 for a consistent and reasonable prompt
    echo "export PS1='\W \`git branch --show-current 2>/dev/null | sed -r -e \"s@^(.+)@\(\1\) @\"\`$ '" >> /home/user/.bashrc && \
    # Set permissions on /etc/passwd and /home to allow arbitrary users to write
    chgrp -R 0 /home && \
    chmod -R g=u /etc/passwd /etc/group /home

# Install .NET
# .NET
ENV DOTNET_RPM_VERSION=7.0
RUN dnf install -y dotnet-hostfxr-${DOTNET_RPM_VERSION} dotnet-runtime-${DOTNET_RPM_VERSION} dotnet-sdk-${DOTNET_RPM_VERSION}

USER 10001
WORKDIR /projects
```
and then use it in the devfile, for example:
```yaml
schemaVersion: 2.2.0
metadata:
  name: dotnet
components:
  - name: tools
    container:
      image: quay.io/vsvydenk/dotnet:7.0-UBI-9
      memoryLimit: 6Gi
      mountSources: true
      args: ['tail', '-f', '/dev/null']
      endpoints:
        - name: 'hello-endpoint'
          targetPort: 5032
          protocol: https
        - name: 'debug-endpoint'
          targetPort: 5000
      volumeMounts:
        - name: nuget
          path: /home/user/.nuget
  - name: nuget
    volume:
      size: 1G
commands:
  - id: 1-update-dependencies
    exec:
      label: Update dependencies
      component: tools
      workingDir: ${PROJECTS_ROOT}/dotnet-web-simple
      commandLine: "dotnet restore"
      group:
        kind: build
  - id: 2-build
    exec:
      label: Build
      component: tools
      workingDir: ${PROJECTS_ROOT}/dotnet-web-simple
      commandLine: "dotnet build"
      group:
        kind: build
  - id: 3-run
    exec:
      label: Run
      component: tools
      workingDir: ${PROJECTS_ROOT}/dotnet-web-simple
      commandLine: "dotnet run"
      group:
        kind: run
```
