### ISSUE TITLE
che-machine-exec image does not work properly

### ISSUE THREAD

**Issue by stringang** [eclipse/che#22917]
### Describe the bug

when using the `devworkspacetemplate` resource to create a workspace, the `che-machine-exec` image(`quay.io/eclipse/che-machine-exec:7.84.0`) cannot be started.

error message:
```
exec /go/bin/che-machine-exec: no such file or directory
```

### Che version

7.84@latest

### Steps to reproduce

1. Create the `devworkspacetemplate` resource(`che-machine-exec`)
2. Create `workspace` resources

### Expected behavior

`che-machine-exec` container runs normally

### Runtime

Kubernetes (vanilla)

### Installation method

other (please specify in additional context)

### Environment

Linux

**Comment by tolusha** [comment]
@stringang 
Could you share the devfile ?

**Comment by stringang** [comment]
@tolusha 
```
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  annotations:
    controller.devfile.io/allow-import-from: '*'
  name: web-terminal-exec
  namespace: openshift-operators
  labels:
    console.openshift.io/terminal: 'true'
spec:
  components:
    - container:
        cpuRequest: 100m
        command:
          - /go/bin/che-machine-exec
          - '--authenticated-user-id'
          - $(DEVWORKSPACE_CREATOR)
          - '--idle-timeout'
          - $(WEB_TERMINAL_IDLE_TIMEOUT)
          - '--pod-selector'
          - controller.devfile.io/devworkspace_id=$(DEVWORKSPACE_ID)
          - '--use-bearer-token'
        env:
          - name: WEB_TERMINAL_IDLE_TIMEOUT
            value: 15m
        memoryRequest: 128Mi
        sourceMapping: /projects
        cpuLimit: 400m
        memoryLimit: 128Mi
        image: 'quay.io/eclipse/che-machine-exec:7.84.0'
        endpoints:
          - attributes:
              type: main
            exposure: public
            name: exec
            protocol: http
            targetPort: 4444
        mountSources: false
      name: web-terminal-exec

---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  annotations:
    controller.devfile.io/allow-import-from: '*'
  name: web-terminal-tooling
  namespace: openshift-operators
  labels:
    console.openshift.io/terminal: 'true'
spec:
  components:
    - container:
        args:
          - tail
          - '-f'
          - /dev/null
        cpuLimit: 400m
        cpuRequest: 100m
        image: 'quay.io/wto/web-terminal-tooling:latest'
        memoryLimit: 512Mi
        memoryRequest: 128Mi
        mountSources: false
        sourceMapping: /projects
      name: web-terminal-tooling

```
