### ISSUE TITLE
Add meaningful dashboard warnings during the failures on namespace provisioning when auto-provisioning is disabled and advanced authorization is enabled

### ISSUE THREAD

**Issue by dipakkarde** [eclipse/che#22912]
### Is your enhancement related to a problem? Please describe

I have a customer with below concern :

Customer is using `OpenShift DevSpaces 3.12.0` and setting `auto-provisioning` of namespaces turned off and setting `advanced authorization` as below :

```
 devEnvironments:
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: container-build
    defaultNamespace:
      autoProvision: false                                <---------
      template: <username>-devspaces
    maxNumberOfWorkspacesPerUser: -1
    secondsOfInactivityBeforeIdling: 1800
    secondsOfRunBeforeIdling: -1
    security: {}
    startTimeoutSeconds: 300
    storage:
      pvcStrategy: per-user
```

```
$ oc get checluster devspaces -n openshift-operators -o yaml | grep -i networking -A12
  networking:
    auth:
      advancedAuthorization:                               <------------
        allowUsers:
        - test
      gateway:
        configLabels:
          app: che
          component: che-gateway-config
        kubeRbacProxy:
          logLevel: 0
        oAuthProxy:
          cookieExpireSeconds: 86400
```

After this when tried creating a sample workspace with kubeadmin user, But was not able to access the workspace with and was getting below errors in upper right corner :

`Automatic namespace provisioning is disabled. Namespace might note have been configured yet. Please contact the administrator.
`
`Advanced authorization is enabled. User might not be allowed. Please, contact the administrator.`

and in middle of the screen we get below error :

`HTTP Error code 500. Endpoint which throws an error https://devspaces.apps.occ.cc.corp/api/kubernetes/namespace/provision. Check the browser logs message.`

### Describe the solution you'd like

Customer Expectation :

The error message in the upper right corner is correct.

But they don't like the error message in the middle of the screen:

`HTTP Error code 500. Endpoint which throws an error https://devspaces.apps.occ.cc.corp/api/kubernetes/namespace/provision. Check the browser logs message.`

![Screenshot from 2024-04-09 09-34-41](https://github.com/eclipse-che/che/assets/88081595/3a4dd857-507b-4a32-948b-c2f595e8c8cc)

Their request is that this "ugly" message should be replaced with a more user-friendly message, that is, messages like:

`Automatic namespace provisioning is disabled. Namespace might note have been configured yet. Please contact the administrator.`

or

`Advanced authorization is enabled. User might not be allowed. Please, contact the administrator.`

Should be displayed in the middle of the screen instead of the top right corner.
