### ISSUE TITLE
An empty project is displayed in the editor's project tree.

### ISSUE THREAD

**Issue by vinokurig** [eclipse/che#22941]
### Describe the bug

An empty project is displayed in the vscode editor project tree, if several starter projects are defined in the devfile.

### Che version

7.84@latest

### Steps to reproduce

1. Start a workspace from a devfile with several starter projects:
```yaml
schemaVersion: 2.2.0
metadata:
  name: test
starterProjects:
  - name: project-1
    zip:
      location: https://code.quarkus.io/d?e=io.quarkus%3Aquarkus-resteasy&e=io.quarkus%3Aquarkus-micrometer&e=io.quarkus%3Aquarkus-smallrye-health&e=io.quarkus%3Aquarkus-openshift&cn=devfile&j=17
  - name: project-2
    zip:
      location: https://code.quarkus.redhat.com/d?e=io.quarkus%3Aquarkus-resteasy&e=io.quarkus%3Aquarkus-smallrye-health&e=io.quarkus%3Aquarkus-openshift
```
See: ptoject-2 is displayed as an empty tree:
![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2024 04 24-15_49_15](https://github.com/eclipse-che/che/assets/7668752/a9d7a1ea-e1ea-478c-bff8-00c29b28e729)

### Expected behavior

The second project should be omitted.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

macOS
