### ISSUE TITLE
Expose editor yaml definitions from the dashboard

### ISSUE THREAD

**Issue by dkwon17** [eclipse/che#22994]
### Is your enhancement related to a problem? Please describe

When the plugin registry hosted editor definitions, it allowed defining editors in devworkspaces by providing a url to the plugin registry service:
```
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: my-devworkspace
  namespace: user1-dev
spec:
  routingClass: che
  started: true
  contributions:
    - name: ide
      uri: http://plugin-registry.eclipse-che.svc.cluster.local:8080/v3/plugins/che-incubator/che-code/latest/devfile.yaml
  template:
    projects:
      - name: my-project-name
        git:
          remotes:
            origin: https://github.com/eclipse-che/che-docs
    components:
      - name: tooling-container
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-latest
```

### Describe the solution you'd like

With the plugin registry will soon not provide editor definitions anymore, this is would now not be possible.

It would be great if the dashboard provides an endpoint to get editor definitions:
```
http://che-dashboard.eclipse-che.svc.cluster.local:8080/dashboard/api/editor/che-incubator/che-code/latest
```
should return the yaml definition of `che-incubator/che-code/latest`

### Additional context

Related issue: PRs related to https://github.com/eclipse-che/che/issues/22932
