### ISSUE TITLE
Workspace Pod goes into a stop/start loop when the devfile includes a ConfigMap Volume Mount

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#23011]
### Describe the bug

When attempting to create a workspace with a ConfigMap embedded in the workspace which is mounted as a volume, the workspace pod goes into a stop-start loop.

__Note:__ This is not following the documentation for ConfigMaps - [https://access.redhat.com/documentation/en-us/red_hat_openshift_dev_spaces/3.14/html/user_guide/using-credentials-and-configurations-in-workspaces#mounting-configmaps](https://access.redhat.com/documentation/en-us/red_hat_openshift_dev_spaces/3.14/html/user_guide/using-credentials-and-configurations-in-workspaces#mounting-configmaps)

This method is for creating a workspace with a workspace specific ConfigMap mounted.

### Che version

7.86

### Steps to reproduce

Create a workspace from the following devfile:

```yaml
schemaVersion: 2.2.0
metadata:
  name: config-map-test
components:
- name: cm-config-volume
  openshift:
    deployByDefault: true
    inlined: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: my-configmap
      data:
        demo-txt: |
          key1=value1
          key2=value2
- name: my-container
  attributes:
    pod-overrides:
      spec:
        volumes: 
        - name: demo-config-map
          configMap:
            name: my-configmap
            items:
            - key: demo-txt
              path: demo.txt
    container-overrides:
      volumeMounts:
      - mountPath: /projects/config-map
        name: demo-config-map
  container:
    image: quay.io/cgruver0/che/dev-tools:latest
    memoryLimit: 1024Mi
    mountSources: true
```

1. You will observe that the workspace pod goes into a stop-start loop.

1. The ConfigMap is correctly created.

1. The volume is configured in the Pod.

1. It looks as though the `che-code-injector` init-container is failing.  But the pod does not go into a crash loop.

### Expected behavior

The ConfigMap is mounted at the mount point specified by the container-overrides

### Runtime

OpenShift

### Screenshots

![Screenshot 2024-06-18 at 12 53 40 PM](https://github.com/eclipse-che/che/assets/39659182/57833dcc-5643-464c-a92b-46f0f483f6b0)

### Installation method

OperatorHub

### Environment

macOS
