### ISSUE TITLE
Issues with Websockets for Che with Nginx-Ingress Controller.

### ISSUE THREAD

**Issue by Wosin** [eclipse/che#23049]
### Summary

Hey! 
I am facing an issue with Eclipse Che deployment on Vanilla k8s cluster running with Keycloak as OIDC provider using nginx-ingress controller. We have managed to pretty much configure and make everything work correctly, the only issue is the websocket connection.  

We are using the below patch to deploy che:

```
apiVersion: org.eclipse.che/v2
spec:
  devEnvironments:
     serviceAccount: default
     defaultNamespace:
       autoProvision: false
  networking:
    ingressClassName: nginx
    annotations:
      acme.cert-manager.io/http01-edit-in-place: "true"
      cert-manager.io/cluster-issuer: le-wildcard-issuer
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    auth:
      gateway:
        oAuthProxy:
         cookieExpireSeconds: 300
        deployment:
          containers:
          - name: "oauth-proxy"
            env:
            - name: OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST
              value: "true"
            - name: OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER
              value: "true"
            - name: OAUTH2_PROXY_WHITELIST_DOMAINS
              value: "[keycloak-url]"
            - name: OAUTH2_PROXY_COOKIE_REFRESH
              value: "200s"
      identityProviderURL: [keycloak-url]
      oAuthClientName: kubernetes-client
      oAuthSecret: XXXXXXXX
```

As I've mentioned everything in general works okay, but the websocket connetions to `/dashboard/api/websocket` are only working for as long as the initial oauth cookie is valid, after that they are failing with `No valid authentication in request. Initiating login.` and we see the _WebSocket connections are failing. Refer to "[Network Troubleshooting](https://www.eclipse.org/che/docs/stable/end-user-guide/troubleshooting-network-problems/)" in the user guide._ error on dashboard screen.After manual refresh everything is back to normal, again for the validity time of the cookie set in the configuration. 

Is there any documentation about setting up Che with Nginx to make sure the websocket connetions are working correctly ?

**Comment by ibuziuk** [comment]
@tolusha ptal

**Comment by ibuziuk** [comment]
@Wosin hello, could you please clarify if you followed https://eclipse.dev/che/docs/stable/administration-guide/installing-che-on-the-virtual-kubernetes-cluster/ ? if smth. is not working as expected PR to the docs should be provided to improve the installation SOP on vanilla k8s

**Comment by tolusha** [comment]
Setting `spec.networking.annotations` overrides the default ingress anotations which are:

```
"nginx.ingress.kubernetes.io/proxy-read-timeout":    "3600",
"nginx.ingress.kubernetes.io/proxy-connect-timeout": "3600",
"nginx.ingress.kubernetes.io/ssl-redirect":          "true",
"nginx.ingress.kubernetes.io/proxy-buffer-size": "16k"
"nginx.org/websocket-services": "che-gateway"
```

Could you add them as well ?

**Comment by brunnels** [comment]
I was able to resolve this I think.  I needed to set the oauth cookie expiration and then I had to add a server-snippet to get the websockets working.  I'm using authelia for oidc.

```yaml
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: eclipse-che
  namespace: eclipse-che
spec:
  components:
    cheServer:
      extraProperties:
        CHE_OIDC_USERNAME__CLAIM: email
  networking:
    annotations:
      external-dns.alpha.kubernetes.io/target: che.mydomain.dev
      kubernetes.io/ingress.class: internal
      nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/secure-backends: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.org/websocket-services: che-gateway
      nginx.ingress.kubernetes.io/server-snippets: |
       location / {
        proxysetheader Upgrade $httpupgrade;
        proxyhttpversion 1.1;
        proxysetheader X-Forwarded-Host $httphost;
        proxysetheader X-Forwarded-Proto $scheme;
        proxysetheader X-Forwarded-For $remoteaddr;
        proxysetheader Host $host;
        proxysetheader Connection "upgrade";
        proxycachebypass $httpupgrade;
        }
    auth:
      gateway:
        oAuthProxy:
          cookieExpireSeconds: 300 # needs to be shorter than the oidc token lifespan
      identityProviderURL: https://auth.mydomain.dev
      oAuthClientName: oauth2-proxy
      oAuthSecret: SUPERSECRETOIDC
    domain: che.mydomain.dev
```
