### ISSUE TITLE
HOME environment variable points to `/opt/app-root/src` in python sample

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse/che#23068]
### Describe the bug

I noticed that on the developer sandbox and on the godfooding instance HOME environment variable is set to `/opt/app-root/src`.

It brings some problems.
First, that `/opt/app-root/....` is not persisted and all the stored data are lost on workspace restart.
Seconds, it is not right ideologically, home directory should be located in `/home`, not in `/opt`.

### Che version

7.88

### Steps to reproduce

- create a workspace
- open a terminal, run
```
$ export | grep HOME
```

### Expected behavior

HOME should be set to `/home/user`

### Screenshots

![Screenshot from 2024-08-01 11-49-42](https://github.com/user-attachments/assets/75bb22ab-0001-4821-a896-56dec41d9f5d)

### Environment

Dev Sandbox (workspaces.openshift.com)

**Comment by AObuchow** [comment]
@vitaliy-guliy can you please share the devfile you used that encountered this error? I'm under the impression this is affecting tooling images other than the UDI, as I didn't reproduce the issue in the following devfile (UDI sample):

```
schemaVersion: 2.2.0
metadata:
  name: udi
  namespace: aobuchow-che-1cac83
  displayName: Universal Developer Image
  description: Universal Developer Image provides various programming languages tools and runtimes for instant coding
  icon: https://raw.githubusercontent.com/devfile/devfile-web/main/apps/landing-page/public/pwa-192x192.png
  tags:
    - Java
    - Maven
    - Scala
    - PHP
    - .NET
    - Node.js
    - Go
    - Python
    - Pip
    - ubi8
  projectType: universal
  language: Polyglot
  version: 1.0.0
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      memoryLimit: 6G
      memoryRequest: 512Mi
      cpuRequest: 1000m
      cpuLimit: 4000m
      mountSources: true
```
