### ISSUE TITLE
Devworkspace storage-type attribute temporarily removed when restarting from local devfile

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#23110]
### Describe the bug

Eclipse Che (Dev Spaces) appears to be creating a user scoped PVC when none has been requested.

### Che version

7.88

### Steps to reproduce

Create a CheCluster:

```yaml
kind: CheCluster   
metadata:              
  name: devspaces  
  namespace: devspaces
spec:                         
  components:                  
    cheServer:      
      debug: false
      logLevel: INFO
    metrics:                
      enable: true
    pluginRegistry:
      openVSXURL: https://open-vsx.org
  containerRegistry: {}      
  devEnvironments:       
    startTimeoutSeconds: 300
    secondsOfRunBeforeIdling: -1
    maxNumberOfWorkspacesPerUser: -1
    maxNumberOfRunningWorkspacesPerUser: 5
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: container-build
    disableContainerBuildCapabilities: false
    defaultComponents:
    - name: dev-tools
      container:
        image: quay.io/cgruver0/che/dev-tools:latest
        memoryLimit: 6Gi
        mountSources: true
    defaultEditor: che-incubator/che-code/latest
    defaultNamespace:
      autoProvision: true
      template: <username>-devspaces
    secondsOfInactivityBeforeIdling: 1800
    storage:
      pvcStrategy: per-workspace
      perUserStrategyPvcConfig:
        storageClass: ${STORAGE_CLASS}
      perWorkspaceStrategyPvcConfig:
        storageClass: ${STORAGE_CLASS}
  gitServices: {}
  networking: {}
```

Login as a user and create workspaces.

After an unknown amount of time, you will observe an unbound PVC for your user.

<img width="1606" alt="Screenshot 2024-08-22 at 8 22 32 AM" src="https://github.com/user-attachments/assets/935ff450-e384-4e55-88f7-7a123d634dac">

### Expected behavior

The operator will not create a per-user PVC

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

macOS

### Additional context

__Note:__  The creation of the rogue PVC does not appear to be associated with any workspace lifecycle events that I can find.

If I delete the rogue PVC, it will eventually get recreated.

**Comment by AObuchow** [comment]
@cgruver The rogue PVC is the claim-devworkspace PVC correct? It's very strange that this is getting created, especially given the fact you're using the per-workspace PVC strategy and not the per-user PVC strategy.

**Comment by cgruver** [comment]
> @cgruver The rogue PVC is the claim-devworkspace PVC correct? It's very strange that this is getting created, especially given the fact you're using the per-workspace PVC strategy and not the per-user PVC strategy.
> 

Correct.

> I wonder if this has to do with the fact you are specifying a `storageClass` for the `perUserStrategyPvcConfig` (though, that would definetly be a bug).

I tried removing the `perUserStrategyPvcConfig` entry.  It still creates that rogue PVC.

**Comment by AObuchow** [comment]
@cgruver Do you mind sharing the DevWorkspace Operator logs if possible? They should be logging if the claim-devworkspace PVC is being created.  I'm currently trying to reproduce this issue after having setup the `hostpath-csi` storage class.

**Comment by cgruver** [comment]
@AObuchow I've also seen this behavior with Rook/Ceph aka OpenShift Data Foundations.

I'll grab the logs for you.

Here's another interesting data point.  If I do not specify `perUserStrategyPvcConfig` but let it just use the default StorageClass, I do not see this behavior.

The only reason that I stumbled onto this issue is because I was running a cluster with multiple storage classes...  I first noticed it when running a cluster with both Rook/Ceph and a Qnap CSI driver.

**Comment by cgruver** [comment]
@AObuchow   Logs from `devworkspace-controller-manager`

`claim-devworkspace` is the rogue PVC that gets created.

I haven't yet found a trigger event, but there are some interesting things to point out:

1. The workspaces that it seems to be created for do not have the attribute: `controller.devfile.io/storage-type: per-workspace` set in their devfile.  This does not happen for workspaces with that attribute, as expected.
1. It only seems to happen if I have a setting for `perUserStrategyPvcConfig.storageClass`.  If I let it use the default storageClass, this does not occur.

Current CheCluster:

```yaml
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: devspaces
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
    dashboard:
      logLevel: ERROR
    devWorkspace: {}
    devfileRegistry: {}
    imagePuller:
      enable: false
      spec: {}
    metrics:
      enable: true
    pluginRegistry:
      openVSXURL: 'https://open-vsx.org'
  containerRegistry: {}
  devEnvironments:
    startTimeoutSeconds: 300
    security: {}
    secondsOfRunBeforeIdling: -1
    maxNumberOfWorkspacesPerUser: -1
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: container-build
    disableContainerBuildCapabilities: false
    defaultEditor: che-incubator/che-code/latest
    maxNumberOfRunningWorkspacesPerUser: 5
    defaultComponents:
      - container:
          image: 'quay.io/cgruver0/che/dev-tools:latest'
          memoryLimit: 6Gi
          mountSources: true
          sourceMapping: /projects
        name: dev-tools
    defaultNamespace:
      autoProvision: true
      template: <username>-devspaces
    secondsOfInactivityBeforeIdling: 1800
    storage:
      perUserStrategyPvcConfig:
        storageClass: hostpath-csi
      pvcStrategy: per-workspace
  gitServices: {}
  networking:
    auth:
      gateway:
        configLabels:
          app: che
          component: che-gateway-config
```

[devworkspace-controller-manager-cfd46bdfd-v29w9-devworkspace-controller.log](https://github.com/user-attachments/files/16752090/devworkspace-controller-manager-cfd46bdfd-v29w9-devworkspace-controller.log)
