### ISSUE TITLE
Issue on Che 7.90.0 and corporate proxy with https://registry.devfile.io

### ISSUE THREAD

**Issue by disaster37** [eclipse/che#23114]
### Describe the bug

As documented on release note of Eclipse che 7.90.0. The internal devfile registry is no more deployed and consume directly the https://registry.devfile.io.

This new enhance not working when Eclipse che is under cooporate proxy. When open Eclipse che, it stuck a long time without any error (maybee 5 minutes), then  it display error because of it can't access to https://registry.devfile.io.
I suppect that the global proxy setting is not injected on dashboard pod ``spec.components.cheServer.proxy`.

For moment, I haven't found a workaround to inject env on dashboard deployment ...

### Che version

7.90@latest

### Steps to reproduce

1. deploy eclipse che 7.90.0 with chectl under coororate proxy
2. Open Eclipse che, it stuck and then it display error 

### Expected behavior

It can access to https://registry.devfile.io. throughout the coorporate proxy

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Linux

**Comment by disaster37** [comment]
I finnaly found a way to set env on pod che-dashboard.

```yaml
apiVersion: org.eclipse.che/v2
kind: CheCluster
spec:
  components:
    dashboard:
      deployment:
        containers:
          - name: che-dashboard
            env:
              - name: "HTTP_PROXY"
                value: "http://squid.squid.svc.cluster.local:8080"
              - name: "HTTPS_PROXY"
                value: "http://squid.squid.svc.cluster.local:8080"
              - name: "NO_PROXY"
                value: "127.0.0.1,localhost,.svc.cluster.local,.svc,10.43.0.1"
```

I now get immediate error 500 instead "502 - bad gateway".

When I look Chrome devtools, it failed when it call `dashboard/api/data/resolver`. The Coorporate proxy server (Mcafee) responde with error code 500 and display on body "The SSL handshake could not be performed".
When I curl directly from the che-dahboard pod, it' work fine.

```bash
curl  https://registry.devfile.io/index
```
