### ISSUE TITLE
Cannot create personal access token under user preferences

### ISSUE THREAD

**Issue by huonguyenlt** [eclipse/che#23129]
### Describe the bug

Cannot add personal access token with provider Microsoft azure devops
Error: Token "test" was not added because it is not valid.

### Che version

7.89

### Steps to reproduce

Create PAT on azure devops
![image](https://github.com/user-attachments/assets/1925b2cb-6a00-481c-a364-65ddbaca09c6)

Add the PAT to che
![image](https://github.com/user-attachments/assets/52ba58ad-a639-4d53-be06-9a1813cc7884)

Error after add the token
![image](https://github.com/user-attachments/assets/5719c02a-6ff7-41b5-80a2-ba84fab63e7d)

### Expected behavior

Should be able to add the PAT

### Runtime

other (please specify in additional context)

### Installation method

other (please specify in additional context)

### Environment

Amazon

### Additional context

Che cluster is deployed on EKS

**Comment by tolusha** [comment]
It should definitely work for `https://dev.azure.com` If you have Azure On Prem, then it is needed to configure Eclipse Che firstly. Although, I had no chance to try it, it must be possible.
Update checluster custom resource to set the correct values:
```yaml
spec:
  components:
    cheServer:
      extraProperties:
        CHE_INTEGRATION_AZURE_DEVOPS_APPLICATION__SCOPES: "vso.code_write"
        CHE_OAUTH_AZURE_DEVOPS_AUTHURI: "https://app.vssps.visualstudio.com/oauth2/authorize"
        CHE_OAUTH_AZURE_DEVOPS_TOKENURI: "https://app.vssps.visualstudio.com/oauth2/token"
        CHE_INTEGRATION_AZURE_DEVOPS_API_ENDPOINT: "https://vssps.dev.azure.com"
        CHE_INTEGRATION_AZURE_DEVOPS_SCM_API__ENDPOINT: "https://dev.azure.com"
```
