### ISSUE TITLE
Using parent devfile, only want one project checked out - Is it possible?

### ISSUE THREAD

**Issue by isuftin** [eclipse/che#23196]
### Summary

We are trying to provide a sample workspace dashboard for our users. We want to have a workspace for the sample dashboard items with certain projects checked out using the development branch. We also want to use a parent devfile which defines a container component, a project and 1..n commands. In the child project we want to override the container component, add commands as well as specify a different project to check out.

The goal here is to give users enough of a head start so they can easily copy the devfile into their projects and change what they need.

Everything works great except in the resulting workspace, we have two projects checked out with the same code from two different branches. 

Parent devfile:

```yaml
---
schemaVersion: 2.3.0
metadata:
  generateName: universal-dev
  description: |
    Devfile for configuring a Universal Developer Image environment for
    development.

components:
  - name: udi
    container:
      image: our.internal.docker.registry/universal-developer-image:3.16

projects:
  - name: starter-workspace
    git:
      remotes:
        origin: "https://our.internal.gitlab.repo/applications/openshift/dev-files/starter-workspace.git"
      checkoutFrom:
        revision: development

commands:
  - id: some-command
    exec:
      commandLine: "do-a-thing --update"
      component: udi
      label: This does a thing
```

Child devfile:

```yaml
---
schemaVersion: 2.3.0
metadata:
  generateName: aws-dev
  description: |
    Devfile for working within AWS

parent:
  # This refers to the above parent devfile in its own repo
  uri: https://our.internal.gitlab.repo/applications/openshift/dev-files/starter-workspace/-/raw/main/devfile.yaml?ref_type=heads
  components:
    - name: udi
      container:
        image: our.internal.docker.registry/aws-developer-image:1
  projects:
    - name: starter-workspace
      git:
        remotes:
          origin: "https://our.internal.gitlab.repo/applications/openshift/dev-files/aws-developer-workspace.git"

commands:
  - id: whoami
    exec:
      commandLine: "whoami"
      component: udi
      label: do a whoami
```

So what we end up with here is two projects checked out. `starter-workspace` checked out and on the development branch (good) and then also `aws-developer-workspace` checked out to the main branch (bad). This is probably happening because by default, if a devfile doesn't specify a project, DevSpaces will check out the project/branch that includes the devfile the workspace was created from. 

If we also define `projects` in the child devfile and name it `aws-developer-workspace` but specify the development branch, DevSpaces opens a workspace with two projects, both checked out to the development branch of the `aws-developer-workspace` project. The names are `starter-workspace` and `aws-developer-workspace` Great, but we really only want one project checked out in the workspace.

I've also tried setting the `projects` parameter in the parent to an empty array with no luck.

I wonder if there's actually a way to achieve what we're going for?

This is being done on RH OpenShift DevSpaces 3.16.1 using the DevWorkspace Operator 0.31.0
