### ISSUE TITLE
Dev Workspace Controller Loop with Identical Endpoint Names on DevWorkspace

### ISSUE THREAD

**Issue by eye0fra** [eclipse/che#23231]
### Describe the bug

If I start two workspaces containing an endpoint with the same name, the dev workspace controller enters a loop. As a result, both namespaces do not start and remain stuck on "Preparing Service".

sample devfile

```yaml
schemaVersion: 2.3.0
metadata:
  name: endpoints-issue
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      memoryRequest: 1G
      memoryLimit: 4G
      cpuRequest: '1'
      cpuLimit: '2'
  - name: data
    volume:
      size: 256Mi
  - name: postgresql
    container:
      image: quay.io/fedora/postgresql-12:latest
      cpuLimit: "1"
      cpuRequest: 50m
      memoryLimit: 512Mi
      memoryRequest: 64Mi
      endpoints:
        - exposure: internal
          targetPort: 5432
          name: postgresql
          protocol: tcp
          attributes:
            discoverable: true
      env:
        - name: POSTGRESQL_USER
          value: user
        - name: POSTGRESQL_PASSWORD
          value: pass
        - name: POSTGRESQL_ROOT_PASSWORD
          value: root
        - name: POSTGRESQL_DATABASE
          value: db
      volumeMounts:
        - name: data
          path: /var/lib/pgsql/data
```

### Che version

7.93@latest

### Steps to reproduce

1. Create two workspaces with endpoints having the same name.
2. Start both workspaces.
3. Observe that the dev workspace controller goes into a loop and both namespaces remain stuck on "Preparing Service".

### Expected behavior

Both workspaces should start without any issues

### Runtime

OpenShift

### Screenshots

<img width="2004" alt="Screenshot 2024-11-04 at 15 15 26" src="https://github.com/user-attachments/assets/66938a8f-3006-4b63-9cf5-7748e6688d8a">

<img width="616" alt="Screenshot 2024-11-04 at 15 16 28" src="https://github.com/user-attachments/assets/8da86dae-4813-4c55-942f-c40f814c0e8b">

<img width="688" alt="Screenshot 2024-10-31 at 11 44 26" src="https://github.com/user-attachments/assets/77ba8f10-f9d6-4c34-ac01-942ec9705d28">

### Installation method

OperatorHub

### Environment

other (please specify in additional context)

### Additional context

Environment:
DevSpaces Version: 3.16.1
DevWorkspaces Operator Version: 0.30.2
