### ISSUE TITLE
Add ability to override base domain of workspaces endpoints to match custom Che server hostname base domain

### ISSUE THREAD

**Issue by achdmbp** [eclipse/che#23249]
### Is your enhancement related to a problem? Please describe

When configuring custom hostname for Che as described [Configuring Eclipse Che server hostname](https://eclipse.dev/che/docs/stable/administration-guide/configuring-che-hostname/). Let's say we use `che.devs.mycompany.com` as the hostname, the behavior will be:

- accessing che dashboard and IDE will use `che.devs.mycompany.com`
- however, when devs defined public endpoints in their devworkspace, the generated routes will use the default base domain. the route will be for example: `https://<user>-<workspace>-<endpoint-name>.apps.<default base domain>`

### Describe the solution you'd like

to support switching to a new cluster and keep same custom domain of che server, add ability to use same base domain of custom hostname to be used also to generate workspace endpoints

**Comment by tolusha** [comment]
@achdmbp 
Try this by updating CheCluster CR:
```
spec:
  components:
    cheServer:
      extraProperties:
        CHE_INFRA_OPENSHIFT_ROUTE_HOST_DOMAIN__SUFFIX: "<...>"
```

**Comment by achdmbp** [comment]
@tolusha thank you very much. this worked! I'm surprised this wasn't documented in the admin guide or maybe I missed it somewhere ? 

also is there a way to change the strategy to serve the endpoints via the main che gateway. for example, 

`https://<che _url>/<user>-<workspace>-<endpoint-name>`

instead of creating the endpoint as new routes. Using `https://<che _url>/<user>-<workspace>-<endpoint-name>` is much easier to point explicit DNS entry to openshift ingress router NLB. vs having to use wild card domain record to cover all endpoints

**Comment by tolusha** [comment]
@achdmbp 
Unfortunately we didn't have that in the doc. We will add.

> also is there a way to change the strategy to serve the endpoints via the main che gateway. for example,

@dkwon17

**Comment by cgruver** [comment]
> @tolusha thank you very much. this worked! I'm surprised this wasn't documented in the admin guide or maybe I missed it somewhere ?
> 
> also is there a way to change the strategy to serve the endpoints via the main che gateway. for example,
> 
> `https://<che _url>/<user>-<workspace>-<endpoint-name>`
> 
> instead of creating the endpoint as new routes. Using `https://<che _url>/<user>-<workspace>-<endpoint-name>` is much easier to point explicit DNS entry to openshift ingress router NLB. vs having to use wild card domain record to cover all endpoints

Putting this here for visibility since I don't think it is documented:

Adding the attribute: `urlRewriteSupported: true` will achieve the desired result.

__Note:__ The endpoints will now require authentication, so they will not be easily shared with others on your dev team if you are collaborating between developer of two services, or frontend & backend.


```yaml
    endpoints:
    - name: node
      targetPort: 4200
      exposure: public
      protocol: https
      attributes:
        urlRewriteSupported: true
    - name: https-quarkus
      targetPort: 8080
      exposure: public
      protocol: https
      attributes:
        urlRewriteSupported: true
```
