### ISSUE TITLE
Allow for global configuration of workspace resource requests

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#23243]
### Is your enhancement related to a problem? Please describe

An inexperienced developer can cause a cluster node to become unschedulable by creating a devfile which has extreme values for `cpuRequest` or `memoryRequest`

### Describe the solution you'd like

1. Allow for global configuration of the default `cpuRequest` & `memoryRequest` values.
2. Allow for global configuration to ignore devfile defined `cpuRequest` & `memoryRequest` entries in a devfiles.
3. If `cpuLimit` or `memoryLimit` is set in a devfile, the `cpuRequest` & `memoryRequest` should still use the default values and not be set to the requested limits.

**Comment by tolusha** [comment]
Hello, @cgruver 

It remind me Kubernetes ResoureQuotas.
Why not to use it?

**Comment by ibuziuk** [comment]
@cgruver in the recent release we introduced a new feature allowing configuring user namespaces with an OpenShift template which I believe should address this issue - https://github.com/eclipse-che/che/releases/tag/7.94.0

**Comment by cgruver** [comment]
@ibuziuk   Let me take a look at that.

I would still like to consider configurable defaults.

Plus, it feels like an anti-pattern that we set limit and requests to be the same if only one of them is specified.

I may open that as a separate issue.  IMO, it's a bug that I can override a default by setting a different parameter.

**Comment by ibuziuk** [comment]
> I would still like to consider configurable defaults.

Well, it is configurable as soon as limit ranges are applied on the namespace level, right?
The anthology would be the default flat pod network which is configurable on the kluster by applying specific network policies.

> Plus, it feels like an anti-pattern that we set limit and requests to be the same if only one of them is specified.

Well, this is a nuanced approach - CDE is guaranteed the requested resources, preventing performance degradation for more or less stable workloads

**Comment by mbenitez1607** [comment]
https://issues.redhat.com/browse/CRW-9546

**Comment by dkwon17** [comment]
With the merge of https://github.com/devfile/devworkspace-operator/pull/1545, the DevWorkspace operator introduced new field, `containerResourceCaps`:

```
kind: DevWorkspaceOperatorConfig
metadata:
  name: devworkspace-operator-config
  namespace: openshift-operators
apiVersion: controller.devfile.io/v1alpha1
config:
  workspace:
    containerResourceCaps:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "0.1"
        memory: 100Mi
```

Which sets the maximum limit and requests for cpu and memory. The fields can also be configured in the CheCluster: https://github.com/eclipse-che/che-operator/pull/2069

If the requests and limits in the devfile exceed these maximums set in the DWOC/CheCluster, the maximums will be used instead.
