### ISSUE TITLE
Update existing workspaces / CDE images accordingly if the parent devfile was updated

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#23279]
### Is your task related to a problem? Please describe

there is a situation when CDE is created from a devfile with reference to parent  e.g.

```
schemaVersion: 2.3.0
metadata:
  name: my-project-dev
parent:
  uri: https://raw.githubusercontent.com/redhat-developer-demos/cde-ollama-continue/main/devfile.yaml
```

Let's assume the situation when container image was updated in the parent devfile. New workspaces would be started with the new image, but existing would be restarted with an old one

### Describe the solution you'd like

When CDE is created based on devfile with parent reference, during the restart the component's image should be checked and updated if needed

### Additional context

I think the similar mechanism is used by dashboard to update VS Code versions for existing workspaces when Eclipse Che is udpated
