### ISSUE TITLE
Restart from local devfile doesn't work anymore

### ISSUE THREAD

**Issue by batleforc** [eclipse/che#23292]
### Describe the bug

Hi, i just made the update to the latest image and ended up being unable to use the restart from local devfile.
When I use it, the dashboard shows the screen
![image](https://github.com/user-attachments/assets/bd8b3cbf-5979-4034-a3a9-c4ad7b3c0032)

A full reinstall has already been done

### Che version

next (development version)

### Steps to reproduce

1. start a workspace based on https://github.com/batleforc/WeeboDevImage
2. Edit the devfile has follow
```yaml
schemaVersion: 2.3.0
metadata:
  name: WeeboDevImage
  language: golang
  version: 1.0.0

components:
- name: tools
  container:
    image: ghcr.io/batleforc/weebodevimage/che-golang:main
    memoryLimit: 2Gi
    mountSources: true
- name: devtool
  container:
    image: buildpack-deps:bookworm
    memoryLimit: 1Gi
    mountSources: false
    command: ['tail']
    args: ['-f', '/dev/null']
```
Use the restart from local devfile feature in vscode
3. Ends up with the following error
```yaml
    - lastTransitionTime: '2024-12-17T19:43:38Z'
      message: "Error processing devfile: failed to merge DevWorkspace parents/plugins: 1 error occurred:\n\t* Some Attributes are already defined in plugin 'unknown': version. If you want to override them, you should do it in the plugin scope.\n\n"
      reason: BadRequest
      status: 'True'
      type: FailedStart
    - lastTransitionTime: '2024-12-17T19:43:39Z'
      message: Workspace stopped due to error
      status: 'False'
      type: Started
 ```
 4. if you edit the dev workspaces object ( update done with headlamp), then no IDE will be injected inside the end object

### Expected behavior

To have the workspaces up and running

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/next

### Environment

Linux

**Comment by ibuziuk** [comment]
@RomanNikitenko @azatsarynnyy @vitaliy-guliy please, take a look?

**Comment by RomanNikitenko** [comment]
@vitaliy-guliy 
could you check if it's related to recent changes in the `che-code`: https://github.com/che-incubator/che-code/pull/465

**Comment by vitaliy-guliy** [comment]
I have checked it on our dogfooding cluster (OpenShift based) and haven't found any issues.
Will retry it right now on the minikube.

**Comment by vitaliy-guliy** [comment]
@batleforc does restart from local devfile work if you just add a container environment variable?

**Comment by batleforc** [comment]
Hi @vitaliy-guliy 
Same problem,
I've tried with the following devfile:

```yaml
schemaVersion: 2.3.0
metadata:
  name: WeeboDevImage
  language: golang
  version: 1.0.0

components:
- name: tools
  container:
    image: ghcr.io/batleforc/weebodevimage/che-golang:main
    memoryLimit: 2Gi
    mountSources: true
    env:
      - name: ENV
        value: dev-che
```

**Comment by batleforc** [comment]
![image](https://github.com/user-attachments/assets/22b62d83-f66d-4892-b3a7-4ae488547c4d)

**Comment by ibuziuk** [comment]
@vitaliy-guliy @RomanNikitenko @azatsarynnyy probably unrelated to this issue but today I have the following error on Developer Sandbox when trying to restart from the local devfile:

<img width="464" alt="Screenshot 2024-12-18 at 17 04 13" src="https://github.com/user-attachments/assets/26fc2729-84b9-419c-9a7a-c25491fe5618" />

for what it worth there are no self-signed certs on the rosa cluster afaik

**Comment by batleforc** [comment]
@ibuziuk Already had the issue in my own setup, just had to restart the full che instance to fix it

**Comment by ibuziuk** [comment]
cc: @tolusha

**Comment by batleforc** [comment]
Hi @vitaliy-guliy 
I've setup the new workspace and restarted will skipping the copying of attributes, and it perfectly works. I made the most basic change (reverting the add of the env or no change at all) and I end up with the previous error.

**Comment by vitaliy-guliy** [comment]
@batleforc it fails when copying the attributes, right? If yes, could you share both (of course, if it can be shared) '/projects/new-devfile.yaml' files, with and without attributes? I just want to understand whether the section contains some attributes, that we should not copy.

**Comment by batleforc** [comment]
@vitaliy-guliy it fails when copying the attributes :+1: and yes, there is nothing private in those manifest.

Without copying the attributes:

```
devfile:
  schemaVersion: 2.3.0
  metadata:
    name: WeeboDevImage
    language: golang
    version: 1.0.0
  components: &ref_0
    - name: tools
      container:
        image: ghcr.io/batleforc/weebodevimage/che-golang:main
        memoryLimit: 2Gi
        mountSources: true
devWorkspace:
  apiVersion: workspace.devfile.io/v1alpha2
  kind: DevWorkspace
  metadata:
    name: WeeboDevImage
    annotations:
      che.eclipse.org/devfile: |
        schemaVersion: 2.3.0
        metadata:
          name: WeeboDevImage
          language: golang
          version: 1.0.0
        components:
          - name: tools
            container:
              image: ghcr.io/batleforc/weebodevimage/che-golang:main
              memoryLimit: 2Gi
              mountSources: true
  spec:
    started: true
    routingClass: che
    template:
      components: *ref_0
      projects:
        - git:
            remotes:
              origin: https://github.com/batleforc/WeeboDevImage.git
          name: weebodevimage
    contributions:
      - name: editor
        kubernetes:
          name: che-code-WeeboDevImage
devWorkspaceTemplates:
  - apiVersion: workspace.devfile.io/v1alpha2
    kind: DevWorkspaceTemplate
    metadata:
      name: che-code-WeeboDevImage
    spec: {}
suffix: WeeboDevImage
```

While copying the attributes : 

```
devfile:
  schemaVersion: 2.3.0
  metadata:
    name: WeeboDevImage
    language: golang
    version: 1.0.0
  components: &ref_0
    - name: tools
      container:
        image: ghcr.io/batleforc/weebodevimage/che-golang:main
        memoryLimit: 2Gi
        mountSources: true
devWorkspace:
  apiVersion: workspace.devfile.io/v1alpha2
  kind: DevWorkspace
  metadata:
    name: WeeboDevImage
    annotations:
      che.eclipse.org/devfile: |
        schemaVersion: 2.3.0
        metadata:
          name: WeeboDevImage
          language: golang
          version: 1.0.0
        components:
          - name: tools
            container:
              image: ghcr.io/batleforc/weebodevimage/che-golang:main
              memoryLimit: 2Gi
              mountSources: true
  spec:
    started: true
    routingClass: che
    template:
      components: *ref_0
      projects:
        - git:
            remotes:
              origin: https://github.com/batleforc/WeeboDevImage.git
          name: weebodevimage
      attributes:
        controller.devfile.io/devworkspace-config:
          name: devworkspace-config
          namespace: eclipse-che
        controller.devfile.io/storage-type: per-user
        version: null
    contributions:
      - name: editor
        kubernetes:
          name: che-code-WeeboDevImage
devWorkspaceTemplates:
  - apiVersion: workspace.devfile.io/v1alpha2
    kind: DevWorkspaceTemplate
    metadata:
      name: che-code-WeeboDevImage
    spec: {}
suffix: WeeboDevImage
```
