### ISSUE TITLE
User Dashboard showed wrong default devfile content of workspace created from private GitHub repo using SSH URL

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#23301]
### Describe the bug

User Dashboard showed wrong default devfile content of workspace created from private GitHub repo using SSH URL.

Expected devfile yaml content: https://github.com/crw-qe/quarkus-api-example-public/blob/main/devfile.yaml

Actual devfile yaml content:
```
schemaVersion: 2.2.0
metadata:
  name: quarkus-api-example-private-d4hf
attributes:
  controller.devfile.io/bootstrap-devworkspace: true
projects:
  - git:
      remotes:
        origin: git@github.com:crw-qe/quarkus-api-example-private.git
    name: quarkus-api-example-private
components:
  - name: universal-developer-image
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
```
![Screenshot from 2025-01-05 21-53-20](https://github.com/user-attachments/assets/0125429f-dc00-4dc1-8c89-3bd065e4dd1b)

Screencast: 
[scrnli_GgaR048tsZvCNH.webm](https://github.com/user-attachments/assets/d02a0116-36bb-4945-85f8-c8f7a8369499)

DevWorkspace.yaml: 
[devworkspace-quarkus-api-example-private-d4hf.yaml.txt](https://github.com/user-attachments/files/18311526/devworkspace-quarkus-api-example-private-d4hf.yaml.txt)

### Che version

7.96@latest

### Steps to reproduce

1. Install Eclipse Che.
2. Create private repo on GitHub.com using https://github.com/crw-qe/quarkus-api-example-public
3. Make sure you have ssh key added to your account on GitHub.com and to the User Dashboard in Eclipse Che.
4. Create workspace using SSH URL.
5. Go to "_User Dashboard > Workspaces > (new workspace) > Devfile_" tab.

#### Alternative scenario
Use [SSH Url of Gogs server private repo, which che-server doesn't support](https://github.com/eclipse-che/che/issues/23277).

### Expected behavior

Devfile content displayed at the "_Dashboard > Workspaces > (new workspace) > Devfile_" tab should be the same as https://github.com/crw-qe/quarkus-api-example-private/blob/main/devfile.yaml

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

### Additional context

The error reproduced with Dev Spaces 3.17.0 on Dev Sandbox and with Eclipse Che Next on Che dogfooding instance having configured GitHub OAuth.
