### ISSUE TITLE
JetBrains editors should support running in UDI 9-based user's container

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse/che#23335]
When running a workspace with the following test Devfile:

```yaml
schemaVersion: 2.2.2
metadata:
  name: private
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi9-latest
      args: ['tail', '-f', '/dev/null']
      memoryRequest: 10Mi
      memoryLimit: 4G
      cpuRequest: 1000m
      cpuLimit: 2000m
commands:
  - id: package
    exec:
      label: "1. Package"
      component: tools
      workingDir: ${PROJECTS_ROOT}/inventory-quarkus
      commandLine: "./mvnw clean package -DskipTests=true"
      group:
        kind: build
        isDefault: true
  - id: runtests
    exec:
      label: "2. Run Tests"
      component: tools
      workingDir: ${PROJECTS_ROOT}/inventory-quarkus
      commandLine: "./mvnw test"
      group:
        kind: test
  - id: startdev
    exec:
      label: "3. Start Development mode (Hot reload + debug)"
      component: tools
      workingDir: ${PROJECTS_ROOT}/inventory-quarkus
      commandLine: "./mvnw compile quarkus:dev"
      group:
        kind: run
        isDefault: true
  - id: buildimage
    exec:
      label: "4. Build Image"
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: |
        IMAGE=image-registry.openshift-image-registry.svc:5000/openshift/quarkus-api-example
        podman build -f src/main/docker/Dockerfile.jvm -t "${IMAGE}" .
      group:
        kind: build
  - id: pushimage
    exec:
      label: "5. Push Image"
      component: tools
      commandLine: |
        # Requires `oc policy add-role-to-user registry-editor <user_name> -n openshift`
        IMAGE=image-registry.openshift-image-registry.svc:5000/openshift/quarkus-api-example
        podman login --tls-verify=false -u $(oc whoami) -p $(oc whoami -t) image-registry.openshift-image-registry.svc:5000
        podman push --tls-verify=false "${IMAGE}"
      group:
        kind: build
```

There's an error:

![Image](https://github.com/user-attachments/assets/2e8b5c43-db96-4ba5-a8de-15be373f9262)
