### ISSUE TITLE
When installing che-operator via helm, the devfile workspace CRDs are not installed

### ISSUE THREAD

**Issue by mangelajo** [eclipse/che#23388]
### Describe the bug

Installing the che-operator via helm charts fails with:

```
2025-03-18T10:38:46Z	ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "DevWorkspaceRouting.controller.devfile.io", "error": "no matches for kind \"DevWorkspaceRouting\" in version \"controller.devfile.io/v1alpha1\""}
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1
	/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:143
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext
	/che-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:235
k8s.io/apimachinery/pkg/util/wait.WaitForWithContext
	/che-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:662
k8s.io/apimachinery/pkg/util/wait.poll
	/che-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:596
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext
	/che-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:547
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1
	/che-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:136
```

The helm operator should offer an option to install those CRDs, there seems to be no helm chart to install the CRDs , that only leaves the option to hack/apply those in place.

### Che version

7.10@latest

### Steps to reproduce

1. Install che-operator:
```
  - name: eclipse-che
    needs:
      - cert-manager/cert-manager
      - dex/dex
    chart: eclipse-che/eclipse-che
    namespace: eclipse-che
    createNamespace: true
    version: 7.100.0
    set:
     - name: networking.domain
       value: che.demo.jumpstarter.dev
     - name: networking.auth.oAuthSecret
       value: eclipse-che
     - name: networking.auth.oAuthClientName
       value: k8s-client
     - name: networking.auth.identityProviderURL
       value: https://keycloak.demo.jumpstarter.dev/realms/che
```

2. the che-operator pod stays in crash loop because of the missing CRDs

### Expected behavior

The operator works, all necessary CRDs are in place.

### Runtime

Kubernetes (vanilla)

### Installation method

other (please specify in additional context)

### Environment

other (please specify in additional context)

### Eclipse Che Logs

```shell

```

### Additional context

Using helm charts from https://eclipse-che.github.io/che-operator/charts

on a vanilla OVH/Kubernetes
