### ISSUE TITLE
docs: Running at Scale section

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#23382]
### Is your task related to a problem? Please describe

Contribute "Running at Scale" section to the Administration Guide

### Describe the solution you'd like

Relevant info:

- https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/scalability_and_performance/planning-your-environment-according-to-object-maximums 

- number of Dev Workspaces per-cluster

etcd:

```
apiVersion: operators.coreos.com/v1
kind: OLMConfig
metadata:
  name: cluster
spec:
  features:
    disableCopiedCSVs: true
```
