### ISSUE TITLE
ConfigMap mounting leads to removing folders

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#23399]
### Describe the bug

I found that directories were removed  when I mounted a ConfigMap.

### Che version

7.10@latest

### Steps to reproduce

1. Create the following ConfigMap
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: test
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-configmap: 'true'
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: /checode/remote/data/configs
    controller.devfile.io/read-only: 'true'
data:
  configurations.json: |
    {
      "test-property": false
    }
```
2. Start a workspace
3. Go to terminal
4. Check `/checode/remote/data` folder contents

<img width="273" alt="Image" src="https://github.com/user-attachments/assets/b088b269-4c4d-44b1-8ca1-000902592881" />

### Expected behavior

<img width="532" alt="Image" src="https://github.com/user-attachments/assets/77752063-cb25-445a-bd65-db65d5781004" />

### Environment

I faced the problem on the dogfooding instance. 

### Additional context

The problem reproduces randomly.
Try to remove a workspace and create a new one if you don't face the problem.
